mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Capex_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>New Customer Facing Feature</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Closed__c</fullName>
        <formula>CASE(  Status__c, &quot;Tested&quot;, 1, &quot;Closed&quot;, 1, &quot;Closed-Untested&quot;, 1, &quot;Closed-U/Ftest&quot;, 1, &quot;Completed&quot;, 1, &quot;Not Reproducible&quot;, 1, &quot;Never&quot;, 1, &quot;Not a bug&quot;, 1, &quot;Duplicate&quot;, 1, &quot;Closed - Duplicate&quot; , 1, &quot;Closed - Known Bug Exists&quot;, 1, &quot;Closed - New Bug Logged&quot;, 1, &quot;Closed - No Fix - Working as Designed&quot;,1, &quot;Closed - No Fix - Feature Request&quot;,1, &quot;Closed - No Fix - Will Not Fix&quot;,1, &quot;Closed - LAP Request Approved&quot;, 1, &quot;Closed - LAP Request Denied&quot;, 1, &quot;Closed - Resolved Without Code Change&quot;, 1, &quot;Rejected&quot;, 1, &quot;Closed - Resolved With Internal Tools&quot;, 1, &quot;Closed - Defunct&quot;,1,&quot;Closed - Doc/Usability&quot;,1,&quot;Closed - Resolved with DB Script&quot;,1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Closed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/classes/ADM_CapexUtility.cls
public class ADM_CapexUtility {
    
    public static void removeAllCapexFlagsForOpenItems(List<Id> scrumTeamIds) {

        try {

            List<ADM_Work__c> workList = 
                [SELECT Id, Capex_Enabled__c,Scrum_Team__c FROM ADM_Work__c WHERE Scrum_Team__c in :scrumTeamIds AND Capex_Enabled__c = true AND Closed__c = 0 ];
            
            for ( ADM_Work__c  tempWork : workList ){
                tempWork.Capex_Enabled__c = false;
            }

            Database.update(workList);

        } catch ( Exception e ){

            String noreply_user = 'noreply@salesforce.com';
            String current_user = UserInfo.getUserEmail();
 
            List<String> emailList = new List<String>();
            emailList.add(noreply_user);
            emailList.add(current_user);

            String info = 'There was an exception with updating a work items CapEx flag : Please contact the GUS team\n';
            ADM_WorkEmail.sendSimpleSingleEmail( noreply_user, info, current_user, emailList, info+e.getMessage(), info+e.getMessage());
    
        }
    }
}