mdapi-source/original-package/unpackaged/objects/ADM_Assignment_Rule__c.object
<CustomObject>
    <description>Used to populate the Assignment Rules on ADM_Work__c records</description>
    <fields>
        <fullName>Assignee_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assignment_Rules2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If this field is empty it will be pre-populated with the Product Owner for the rule&apos;s scrum team.</inlineHelpText>
        <label>Product Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assignment_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QA_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>QA Engineer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00NT0000000lhZjMAI</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scrum_Team_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scrum Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipName>R00NT0000000lhZkMAI</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Senior_Management_POC_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Senior Management POC</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assignment_Rules4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sev_1_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This user is assigned to Investigations with Severity Level 1</inlineHelpText>
        <label>Sev 1 Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assignment_Rules6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sev_2_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This user is assigned to Investigations with a Severity Level of 2.</inlineHelpText>
        <label>Sev 2 Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assignment_Rules7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sev_3_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This user is assigned to Investigations with Severity Level 3</inlineHelpText>
        <label>Sev 3 Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assignment_Rules8</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sev_4_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This user is assigned to Investigations with Severity Level 4</inlineHelpText>
        <label>Sev 4 Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assignment_Rules9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Systest_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Performance Engineer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00NT0000000lhZlMAI</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tech_Writer_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tech Writer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00NT0000000lhZmMAI</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UE_Engineer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UE Engineer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assignment_Rules1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assignment Rule</label>
    <nameField>
        <label>Assignment Rule</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignment Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Tag_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Assignment_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment Rule</label>
        <referenceTo>ADM_Assignment_Rule__c</referenceTo>
        <relationshipLabel>Tag Assignments</relationshipLabel>
        <relationshipName>Tag_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Tag__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Tag</label>
        <referenceTo>ADM_Product_Tag__c</referenceTo>
        <relationshipLabel>Tag Assignments</relationshipLabel>
        <relationshipName>Tag_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <label>Record Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bug</fullName>
                </value>
                <value>
                    <fullName>User Story</fullName>
                </value>
                <value>
                    <fullName>Investigation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tag Assignment</label>
    <nameField>
        <displayFormat>TA-{0000}</displayFormat>
        <label>Tag Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tag Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/classes/ADM_AssignmentRuleCreateController.cls
public with sharing class ADM_AssignmentRuleCreateController {
    
    @AuraEnabled
    public static ADM_Assignment_Rule__c saveRule(Id productTagId, String recordType, ADM_Assignment_Rule__c rule) {
        System.debug('inside saveRule()');
        System.debug('inside saveRule() productTagId:' + productTagId + ' recordType:' + recordType + ' rule:' + rule);
        //in LEX insted of showing the matrix view we give a simpler form layout.  therefore we need
        //to disable old rule and insert new ones 
        
        //remove existing tag assignments for this tag, rule and record type
        List<ADM_Tag_Assignment__c> tagAssignments = [select id from ADM_Tag_Assignment__c where Record_Type__c = :recordType and Product_Tag__c = :productTagId];       
        if(tagAssignments != null && tagAssignments.size() > 0) {
            delete tagAssignments;
        }
        
        //insert new assignment rule
        ADM_Assignment_Rule__c newRule = new ADM_Assignment_Rule__c();
        newRule.Assignee_Assignment__c = rule.Assignee_Assignment__c;
        newRule.QA_Assignment__c = rule.QA_Assignment__c;
        newRule.Product_Owner__c = rule.Product_Owner__c;
        newRule.Tech_Writer_Assignment__c = rule.Tech_Writer_Assignment__c;
        newRule.UE_Engineer__c = rule.UE_Engineer__c;
        newRule.Systest_Assignment__c = rule.Systest_Assignment__c;
        newRule.Scrum_Team_Assignment__c = rule.Scrum_Team_Assignment__c;
        newRule.Sev_1_Assignee__c = rule.Sev_1_Assignee__c;
        newRule.Sev_2_Assignee__c = rule.Sev_2_Assignee__c;
        newRule.Sev_3_Assignee__c = rule.Sev_3_Assignee__c;
        newRule.Sev_4_Assignee__c = rule.Sev_4_Assignee__c;
        newRule.Senior_Management_POC_Assignment__c = rule.Senior_Management_POC_Assignment__c;
        
        insert newRule;
        
        //relate new rule to product tag with new tag assignments
        ADM_Tag_Assignment__c newTagAssignment = new ADM_Tag_Assignment__c();
        newTagAssignment.Assignment_Rule__c = newRule.id;
        newTagAssignment.Product_Tag__c = productTagId;
        newTagAssignment.Record_Type__c = recordType;
        insert newTagAssignment;
        
        
        //return new rule
        return newRule;
        
    }

}