mdapi-source/original-package/unpackaged/objects/ADM_Case__c.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Work__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipName>Work62OrgCases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>62 Org Case</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Related Case ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>62 Org Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Change_List__c.object
<CustomObject>
    <description>Perforce change lists for checking in code changes.  Related to bugs and user stories.</description>
    <fields>
        <fullName>Changelist__c</fullName>
        <description>Link back to the changelist description</description>
        <formula>IF(ISPICKVAL(Source__c, &apos;Perforce&apos;), 



HYPERLINK( &quot;https://build.soma.salesforce.com/build/Perforce/describe?change=&quot; &amp; Perforce_Changelist__c, Perforce_Changelist__c), 



IF(ISPICKVAL(Source__c, &apos;&apos;), 



HYPERLINK( &quot;https://build.soma.salesforce.com/build/Perforce/describe?change=&quot; &amp; Perforce_Changelist__c, Perforce_Changelist__c), 



IF(ISPICKVAL(Source__c, &apos;GitHub&apos;),  HYPERLINK( &quot;https://github.com/&quot; &amp; Perforce_Changelist__c, &quot;github.com/&quot; &amp; Perforce_Changelist__c),


IF(ISPICKVAL(Source__c, &apos;Stash&apos;),  

HYPERLINK( &quot;https://stash.soma.salesforce.com/&quot; &amp; Perforce_Changelist__c, &quot;stash.soma.salesforce.com/&quot; &amp; Perforce_Changelist__c),


HYPERLINK(&quot;https://git.soma.salesforce.com/&quot; &amp; Perforce_Changelist__c, &quot;git.soma.salesforce.com/&quot; &amp; Perforce_Changelist__c)

)


)



)



)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Changelist Link</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>An external ID used for syncing between instances.</description>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Perforce_Changelist__c</fullName>
        <description>Reference to Perforce Changelist number</description>
        <label>Changelist #</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipName>WorkChangeLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Change List</label>
    <nameField>
        <displayFormat>PF-{0000000}</displayFormat>
        <label>Changelist ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Perforce_Connector__c.object
<CustomObject>
    <fields>
        <fullName>Changelist__c</fullName>
        <label>Change List</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Describe__c</fullName>
        <label>Describe</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <description>CL@workId</description>
        <externalId>true</externalId>
        <inlineHelpText>CL@workId</inlineHelpText>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <label>Release</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Perforce_Connectors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work__c</fullName>
        <label>Work</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Source Control Connector</label>
    <nameField>
        <displayFormat>PC-{0000000000}</displayFormat>
        <label>Perforce Connector Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Source Control Connectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Release__c.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Released_In__c.object
<CustomObject>
    <description>Object to define the releases that a fix was deployed to.  Each Work record has a one to many relationship with releases.</description>
    <fields>
        <fullName>External_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <label>Release</label>
        <referenceTo>ADM_Release__c</referenceTo>
        <relationshipName>Release</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Work__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work ID</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipName>WorkReleasedIn</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Released In</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Released In #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Released In</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>External_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Release</label>
        <referenceTo>ADM_Release__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>ADM_Work__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A connection to the Agile Accelerator Work object used to track Bugs, Investigations and User Stories</description>
        <label>Work</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>AgileAcceleratorCases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/User.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/classes/ADM_WorkRelatedListControllerTest.cls
@isTest
public class ADM_WorkRelatedListControllerTest {

    /*

      @testcaseID a0B20000003yOApEAM

      @hierarchy GUS.BugforceToGUS.Change Lists page.Add new change list in GUS

      @userstory a0A20000001uzqH

      @expectedResults: The change list should get submitted and the change list link and description shows on the Work Item under "Change Lists" section. This section shows the Perforce link, check in user name, check in date and Comments

    */
    @isTest
    static void testChangeListLimit() {
        ADM_WorkRelatedListController wrl = new ADM_WorkRelatedListController();
        wrl.enableChangeListLimit();
        System.assertEquals(true, wrl.getChangeListLimit());
        wrl.disableChangeListLimit();
        System.assertEquals(false, wrl.getChangeListLimit());
    }

    /*

      @testcaseID a0B20000005GDvBEAW

      @hierarchy GUS.BugforceToGUS.Bugs in GUS.W-626310

      @userstory a0A20000001uzqH

      @expectedResults: The list of production cases show in descending order by case ID

    */
    @isTest
    static void test62OrgLimit() {
        ADM_WorkRelatedListController wrl = new ADM_WorkRelatedListController();
        wrl.enable62OrgCaseLimit();
        System.assertEquals(true, wrl.getSixtyTwoOrgCaseLimit());
        wrl.disable62OrgCaseLimit();
        System.assertEquals(false, wrl.getSixtyTwoOrgCaseLimit());
    }

    /*

      @testcaseID a0B20000005IJ1dEAG

      @hierarchy GUS.BugforceToGUS.Bugs in GUS.W-621041

      @userstory a0A20000001uzqH

      @expectedResults: The release stamps list shows without returning any errors

    */
    @isTest
    static void testReleaseLimit() {
        ADM_WorkRelatedListController wrl = new ADM_WorkRelatedListController();
        wrl.enableReleaseLimit();
        System.assertEquals(true, wrl.getReleaseLimit());
        wrl.disableReleaseLimit();
        System.assertEquals(false, wrl.getReleaseLimit());
    }


    @isTest
    static void testListSizes() {
        ADM_Work__c work = ADM_Work.createTestWork();
        ADM_WorkRelatedListController wrl = new ADM_WorkRelatedListController(work);

        wrl.getRelatedChangeListSize();
        System.assert(wrl.relatedChangeListSize != null);

        wrl.getRelatedReleaseListSize();
        System.assert(wrl.relatedReleaseListSize != null);

        wrl.getRelated62OrgCaseListSize();
        System.assert(wrl.related62OrgCaseListSize != null);
    }

    /*

      @testcaseID a0B20000001pXSvEAM

      @hierarchy GUS.BugforceToGUS.WorkPage.BugsCreatedInGus.Detail page

      @userstory a0A20000001uzqH

      @expectedResults: A release link shows under the "Releases" section on work detail page

    */
    @isTest
    static void testGetRelatedReleasesList() {
        ADM_Work__c work = ADM_Work.createTestWork();
        
        List<ADM_Release__c> rels = new List<ADM_Release__c>();
        List<ADM_Released_In__c> stamps = new List<ADM_Released_In__c>();
        for(Integer i=0; i < 6; i++) {
            ADM_Release__c release = new ADM_Release__c(Name='ApexTestReleaseName-' + i);
            rels.add(release);
            
        } 
        insert rels;
        
        for(Integer i=0; i < 6; i++) {
            ADM_Release__c r = rels.get(i); 
            ADM_Released_In__c stamp = new ADM_Released_In__c();
            stamp.Work__c = work.id;
            stamp.Release__c = r.id;
            stamps.add(stamp);
        } 
        insert stamps;
        
        ADM_WorkRelatedListController wrl = new ADM_WorkRelatedListController(work);
        wrl.enableReleaseLimit();
        List<ADM_Released_In__c> releases = wrl.getRelatedReleasesList();
        System.assertEquals(5, releases.size());
        wrl.disableReleaseLimit();
        List<ADM_Released_In__c> releasesNoLimit = wrl.getRelatedReleasesList();
        System.assertEquals([select count() from ADM_Released_In__c where Work__c = : wrl.getWorkID()], releasesNoLimit.size());
    }

    /*

      @testcaseID a0B20000007nSodEAE

      @hierarchy GUS.BugforceToGUS.WorkPage.BugsCreatedInGus.Detail page

      @userstory a0A20000001uzqH

      @expectedResults: When there is an amount of more than 5 changes lists, a link to go to the list appears on the work detail page

    */
    @isTest
    static void testGetRelatedChangeListWithoutLimit() {
        ADM_Work__c work = ADM_Work.createTestWork();
        ADM_WorkRelatedListController wrl = new ADM_WorkRelatedListController(work);
        ADM_ChangelistDetailAccumulator cld = new ADM_ChangelistDetailAccumulator();
        ADM_Perforce_Connector__c pc = new ADM_Perforce_Connector__c();
        ADM_Change_List__c cl;
        List<ADM_Change_List__c> cls = new List<ADM_Change_List__c>();

        String describe = '';

        wrl.disableChangeListLimit();

        for(Integer i = 0; i > 1001; i++) {
            describe = describe + '        Testing new ARS';
            describe = describe + '        https://tapp0.salesforce.com/' + wrl.getWorkID();
            describe = describe + '        @rev jhatton@';
            describe = describe + '        @revert@';

            pc.Describe__c = 'Change: 9999' + i + '\n\nClient: alwilliams-wsr\n\nStatus: pending\n\nDescription:\n' + describe;
            pc.Changelist__c = '9999' + i;
            pc.Release__c = 'ATHF';

            cl = cld.getChangelist(pc.Describe__c, pc.Changelist__c, wrl.getWorkID(), pc.Release__c, pc.User__c, '');
            cls.add(cl);
        }

        Database.insert(cls);

        List<ADM_Change_List__c> relListNoLimit = wrl.getRelatedChangeLists();
        relListNoLimit = wrl.getRelatedChangeLists();

        System.assertEquals([select count() from ADM_Change_List__c where Work__c = : wrl.getWorkID()], relListNoLimit.size());

    }

    /*

      @testcaseID a0B20000001pXSsEAM

      @hierarchy GUS.BugforceToGUS.WorkPage.BugsCreatedInGus.Detail page

      @userstory a0A20000001uzqH

      @expectedResults: The new change lists show under the "Change Lists" section

    */
    @isTest
    static void testGetRelatedChangeList() {
        ADM_Work__c work = ADM_Work.createTestWork();
        List<ADM_Change_List__c> cls = new List<ADM_Change_List__c>();
        for(Integer i =0; i<6; i++ ) {
            ADM_Change_List__c cl = new ADM_Change_List__c();
            cl.External_ID__c = work.id + '-' + i;
            cl.Perforce_Changelist__c = 'Test:' + i;
            cl.Work__c = work.id;
            cls.add(cl);
        }
        
        insert cls;
        
        ADM_WorkRelatedListController wrl = new ADM_WorkRelatedListController(work);
        wrl.enableChangeListLimit();
        List<ADM_Change_List__c> relList = wrl.getRelatedChangeLists();
        System.assertEquals(5, relList.size());
        wrl.disableChangeListLimit();
        List<ADM_Change_List__c> relListNoLimit = wrl.getRelatedChangeLists();
        System.assertEquals([select count() from ADM_Change_List__c where Work__c = : wrl.getWorkID()], relListNoLimit.size());
    }

    /*

      @testcaseID a0B20000005IIyxEAG

      @hierarchy GUS.BugforceToGUS.WorkPage.BugsCreatedInGus.Detail page

      @userstory a0A20000001uzqH

      @expectedResults: All 62 org cases are linked to the work item

    */
    @isTest
    static void testGetRelated62OrgList() {
        ADM_Work__c work = ADM_Work.createTestWork();
        ADM_WorkRelatedListController wrl = new ADM_WorkRelatedListController(work);
        wrl.enable62OrgCaseLimit();
        List<ADM_Case__c> relList = wrl.getRelated62OrgCaseList();
        System.assertEquals([select count() from ADM_Case__c where Work__c = : wrl.getWorkID()], relList.size());
        wrl.disable62OrgCaseLimit();
        List<ADM_Case__c> relListNoLimit = wrl.getRelated62OrgCaseList();
        System.assertEquals([select count() from ADM_Case__c where Work__c = : wrl.getWorkID()], relListNoLimit.size());
    }

    @isTest
    static void testErrorMessages() {
        ADM_Work__c work = ADM_Work.createTestWork();
        ADM_WorkRelatedListController wrl = new ADM_WorkRelatedListController(work);
        wrl.addDuplicateItemErrorMsg();
        wrl.addSelfReferenceErrorMsg();
        wrl.addInvalidItemErrorMsg('widget', '123abc');
        wrl.addReferenceExistsErrorMsg();
        wrl.addReferenceExistsErrorMsg('test item');
        wrl.addReferenceExistsErrorMsg('test id', 'child');
        System.assertEquals(6, wrl.getErrorMessages().size());
        wrl.clearErrorMessages();
        System.assertEquals(0, wrl.getErrorMessages().size());

    }

    @isTest
    public static void getRelatedParentWorkListSizeTest(){
        ADM_Work__c work = ADM_Work.createTestWork();
        ADM_WorkRelatedListController wrl = new ADM_WorkRelatedListController(work);
        Integer c = wrl.getRelatedParentWorkListSize();
        String s = wrl.getWorkID();
        System.assertEquals(c, 0);
        wrl.setWorkID(work.id);
        ADM_Work__c workR = wrl.getWork();
        System.assertEquals(workR.id, work.id);
        wrl.setWork(workR);
        List<String> msgs =  wrl.getFatalErrorMessages();
        System.assertEquals(msgs, null);
    }
}