mdapi-source/original-package/unpackaged/objects/ADM_Parent_Work__c.object
<CustomObject>
    <fields>
        <fullName>Child_Work__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Child Work</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipLabel>Parent Work Records</relationshipLabel>
        <relationshipName>Child_Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Duplicate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is child a duplicate of parent?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Work__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Work</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipLabel>Child Work Records</relationshipLabel>
        <relationshipName>Parent_Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Related Work</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Parent Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Works</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Priority__c</fullName>
        <inlineHelpText>For bugs, priority is automatically determined based upon the combination of Impact and Frequency.

For user stories, P0 represents the highest priority, P4 the lowest.</inlineHelpText>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>P0</fullName>
                    <color>#0B6FCE</color>
                    <label>P0</label>
                </value>
                <value>
                    <fullName>P1</fullName>
                    <color>#FF0000</color>
                    <label>P1</label>
                </value>
                <value>
                    <fullName>P2</fullName>
                    <color>#E27001</color>
                    <label>P2</label>
                </value>
                <value>
                    <fullName>P3</fullName>
                    <color>#FFFF66</color>
                    <label>P3</label>
                </value>
                <value>
                    <fullName>P4</fullName>
                    <color>#78C953</color>
                    <label>P4</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bug</fullName>
                </value>
                <value>
                    <fullName>Gack</fullName>
                </value>
                <value>
                    <fullName>Help</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Test Change</fullName>
                </value>
                <value>
                    <fullName>Test Case</fullName>
                </value>
                <value>
                    <fullName>Test Failure</fullName>
                </value>
                <value>
                    <fullName>Test Tool</fullName>
                </value>
                <value>
                    <fullName>Skunkforce</fullName>
                </value>
                <value>
                    <fullName>Bug List</fullName>
                </value>
                <value>
                    <fullName>Translation</fullName>
                </value>
                <value>
                    <fullName>Non Deterministic Test</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <recordTypes>
        <fullName>Bug</fullName>
        <active>true</active>
        <description>Used to track defects or problems</description>
        <label>Bug</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ADM_WorkTreeControllerTest.cls
@isTest
private class ADM_WorkTreeControllerTest {

/**
* @testcaseID a0B20000009gsiEEAQ
* @hierarchy GUS.BugforceToGUS.Bugs in GUS.W-785283
* @userstory a07B0000000Dfi3IAC
* @expected results When you create a child record from a bug list work record, the child is always a bug list, and doesn't seem to be editable.
*/

    static testMethod void verifyCreatingChildOfBug() {
    	Apexpages.Standardcontroller sc;
    	ADM_WorkTreeController wtc;
    	ADM_selectWorkRecordTypeExtensions selWorkExt;
    	ADM_WorkControllerExtension wce;
        ADM_Work__c work = ADM_Work.setupTestWork('Bug','P3');
        ADM_Work__c emptyWork = new ADM_Work__c();

        Test.startTest();
            work.Type__c = 'Bug List';
            work.Priority__c = 'P1';
            insert work;
        Test.stopTest();

        sc = new Apexpages.Standardcontroller(work);
        wtc = new ADM_WorkTreeController(sc);

        System.currentPageReference().getParameters().putAll(wtc.redirectToNewChildWorkRecord().getParameters());
        sc = new Apexpages.Standardcontroller(emptyWork);
        selWorkExt = new ADM_selectWorkRecordTypeExtensions(sc);
        List<RecordType> recTypes = selWorkExt.getRecordTypes();
        for(RecordType recType : recTypes) {
        	if(recType.Name.equalsIgnoreCase('bug')) {
        		selWorkExt.setRecordType(recType.Id);
        	}
        }

        System.currentPageReference().getParameters().putAll(selWorkExt.gotoWorkEdit().getParameters());
        sc = new Apexpages.Standardcontroller(emptyWork);
        wce = new ADM_WorkControllerExtension(sc);
        List<Selectoption> workTypes = wce.getWorkTypes();
        for(Selectoption workType : workTypes) {
        	if(!workType.getLabel().equalsIgnoreCase('bug list')) {
        		wce.setWorkType(workType.getValue());
        	}
        }

        System.assertNotEquals('Bug List', wce.getRecordType().Name);
    }
    
    static testMethod void testCreateNewChildWork() {
        List<ADM_Work__c> works = ADM_Work.createListOfWork(2, 'Bug');
        insert works;
        works = [select Id, Name from ADM_Work__c where Id in :works];
        
        ADM_Work__c work = works.get(0);
        ADM_Work__c work2 = works.get(1);
        
        Test.startTest();
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(work);
        ADM_WorkTreeController wtc = new ADM_WorkTreeController(stdController);
        wtc.newChildWorkName = work2.Name;
        wtc.relationshipType = 'duplicate';
        wtc.createNewChildWork();
        
        Test.stopTest();
        
        List<ADM_Parent_Work__c> relationships = [select Duplicate__c from ADM_Parent_Work__c where Parent_Work__c = :work.Id and Child_Work__c = :work2.Id];
        System.assertEquals(1, relationships.size(), 'Expected there to be one relationship created');
        System.assertEquals(true, relationships.get(0).Duplicate__c, 'Expected the duplicate value to be set to true since the relationship type was Duplicate');
        
    }
}