mdapi-source/original-package/unpackaged/objects/ADM_Build__c.object
<CustomObject>
    <label>Build</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Builds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Scrum_Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Scrum_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Analyst</fullName>
                </value>
                <value>
                    <fullName>Architect</fullName>
                </value>
                <value>
                    <fullName>BSA</fullName>
                </value>
                <value>
                    <fullName>Business Owner</fullName>
                </value>
                <value>
                    <fullName>Capacity Planner</fullName>
                </value>
                <value>
                    <fullName>Data Center Engineer</fullName>
                </value>
                <value>
                    <fullName>DBA</fullName>
                </value>
                <value>
                    <fullName>Developer</fullName>
                </value>
                <value>
                    <fullName>Dev Manager</fullName>
                </value>
                <value>
                    <fullName>Doc Editor</fullName>
                </value>
                <value>
                    <fullName>Doc Manager</fullName>
                </value>
                <value>
                    <fullName>Engineering Manager</fullName>
                </value>
                <value>
                    <fullName>Network Engineer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Performance Engineer</fullName>
                </value>
                <value>
                    <fullName>Product Owner</fullName>
                </value>
                <value>
                    <fullName>Program Manager</fullName>
                </value>
                <value>
                    <fullName>Provisioning Specialist / Asset Manager</fullName>
                </value>
                <value>
                    <fullName>QA Engineer</fullName>
                </value>
                <value>
                    <fullName>QA Manager</fullName>
                </value>
                <value>
                    <fullName>Release Engineer</fullName>
                </value>
                <value>
                    <fullName>Release Manager</fullName>
                </value>
                <value>
                    <fullName>Scrum Master</fullName>
                </value>
                <value>
                    <fullName>Security Engineer</fullName>
                </value>
                <value>
                    <fullName>Site Reliability Engineer</fullName>
                </value>
                <value>
                    <fullName>Software Engineer</fullName>
                </value>
                <value>
                    <fullName>SysAdmin</fullName>
                </value>
                <value>
                    <fullName>SysAdmin Linux</fullName>
                </value>
                <value>
                    <fullName>SysAdmin Storage</fullName>
                </value>
                <value>
                    <fullName>SysAdmin Win</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>Scrum_Team_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <displayFormat>STM-{00000}</displayFormat>
        <label>Team Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <recordTypes>
        <fullName>Internal</fullName>
        <active>true</active>
        <description>SFDC Employee</description>
        <label>Internal</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Scheduled_Build__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Scheduled Build field is a lookup to the Build object.  Enter a pre-existing build where the change will be made.</inlineHelpText>
        <label>Scheduled Build</label>
        <referenceTo>ADM_Build__c</referenceTo>
        <relationshipLabel>Work (Scheduled Build)</relationshipLabel>
        <relationshipName>Scheduled_Build</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/Custom_Report__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Report_ID__c</fullName>
        <externalId>true</externalId>
        <label>Report ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Custom Report</label>
</CustomObject>

mdapi-source/original-package/unpackaged/classes/ADM_DevelopmentCycleUtils.cls
public abstract with sharing class ADM_DevelopmentCycleUtils {
	
	public static final String SELECT_CLAUSE = 'select Id, Scheduled_Build__c, Scrum_Team__c, Scheduled_Build__r.Name, Scrum_Team__r.Name  from ADM_Work__c';
	public static final String IGNORED_BUILDS = '\'internal\',\'store\',\'eclipse\',\'prodtest\',\'l10n\',\'pollmatic\',\'lp\',\'RB\'';
	public static final String IGNORED_CUSTOMERS_COMPLETE = '\'behind perm\', \'patch approved\', \'translation\'';
	public static final String IGNORED_CUSTOMERS_PARTIAL = '\'behind perm\', \'patch approved\'';
    private String nameSpacePrefix = ADM_ConstantsSingleton.getInstance().getNameSpace();
	
	protected  List<SObject> countWorkRecordsMatchingCriteria(List<SObject> records, String q, String fieldNameWithTotal)	{
														
		
		Map<String, List<ADM_Work__c>> openRecs = new Map<String, List<ADM_Work__c>>();
		
		for(ADM_Work__c w : Database.query(q)) {
			openRecs = addWorkToMap(w, openRecs);
		}												
		
		for(SObject so: records) {  
			String buildKey = parseParentBuild((String)so.get('Build__c'));
			List<ADM_Work__c> openWork = openRecs.get(buildKey + '-' + so.get('Scrum_Team__c'));
			
			if(openWork != null && openWork.size() > 0) {
				so.put(fieldNameWithTotal, openWork.size());
			} else {
				so.put(fieldNameWithTotal, 0);
			}
		}
		
		return records;		
		
	}
	
	protected  List<SObject> countWorkRecordsMatchingCriteriaDividedByRole(List<SObject> records, String q, String fieldNameWithTotal, AggregateResult[] memberRoleCountByScrumTeam, String roleName, Map<Id, ADM_Scrum_Team__c> scrumTeamIDs)	{
														
		
		Map<String, List<ADM_Work__c>> openRecs = new Map<String, List<ADM_Work__c>>();
		
		for(ADM_Work__c w : Database.query(q)) {
			openRecs = addWorkToMap(w, openRecs);
		}												
														
		for(SObject so: records) {  
			String buildKey = parseParentBuild((String)so.get('Build__c'));
			List<ADM_Work__c> openWork = openRecs.get(buildKey + '-' + so.get('Scrum_Team__c'));
			if(openWork != null && openWork.size() > 0) {
				//divide total by number of users of specified role type (dev, qa etc)
				Integer roleCount = countMembersMatchingRoleAndScrumTeam(memberRoleCountByScrumTeam, roleName, String.valueOf(so.get('Scrum_Team__c')), scrumTeamIDs );
				Double result = 0;
				if(roleCount != 0) {
					result = openWork.size() / roleCount;	
				} else {
					result = openWork.size();
				}
				
				so.put(fieldNameWithTotal, result);
			} else {
				so.put(fieldNameWithTotal, 0);
			}
		}
		
		return records;		
		
	}
	
	
	protected  Map<String, List<ADM_Work__c>> addWorkToMap(ADM_Work__c w, Map<String, List<ADM_Work__c>> wmap) {
		//stats for patch released should be grouped with parent build
		String buildPrefix = '';
		
			
		if(w.Scheduled_Build__r.Name != null && w.Scheduled_Build__r.Name.contains('.')) {
			//must work fine for 174.1 174.2 etc but also AXM.174.1 and AXM.174.2 mentioned in AC for story W-922997
			//buildPrefix = w.Scheduled_Build__r.Name.substring(0, w.Scheduled_Build__r.Name.indexOf('.'));
			buildPrefix = parseParentBuild(w.Scheduled_Build__r.Name);
		} else {
			buildPrefix = w.Scheduled_Build__r.Name;
		}
				
		
		
		
		String key = buildPrefix + '-' + w.Scrum_Team__r.Name;
		if(wmap.containsKey(key)) {
			wmap.get(key).add(w);
		} else {
			wmap.put(key, new List<ADM_Work__c>{w});
		}
		
		return wmap;			
	}
	
	public Set<String> getDistinctStrings(List<SObject> records, String idFieldName) {
		Set<String> ids = new Set<String>();
		for(SObject s: records) {
			
			ids.add(String.valueOf(s.get(idFieldName)));
		}
		return ids;
	}
	
	public String addSingleQuotesToStringSet(Set<String> els) {
		String s = '';
		for(String e : els) {
			s = s + '\'' + String.escapeSingleQuotes(e) + '\',';
		}
		//strip trailing comma
		s = s.substring(0, s.length()-1);
		return s;
	}
	
	public String addSingleQuotesAndWildCardToStringSet(Set<String> els, String fieldName) {
		String s = '';
		for(String e : els) {
			if(s != '') {
				s = s + ' OR ';
			}
			s = s + String.escapeSingleQuotes(fieldName) + ' LIKE \'' + String.escapeSingleQuotes(e) + '%\'';
		}
		return s;
	}
	
	protected  AggregateResult[] getMemberRoleCountsGroupedByScrumTeam(Set<String> teamNames) {
		
        String sobjectTypeName = nameSpacePrefix + 'ADM_Scrum_Team_Member__c';

        String roleFieldOnScrumTeamMember = nameSpacePrefix + 'Role__c';
        
        String teamFieldOnScrumTeamMember = nameSpacePrefix + 'Scrum_Team__c';
        
        String teamForeignFieldOnScrumTeamMember = teamFieldOnScrumTeamMember.replace('__c', '__r');
		
        String soql = 'select count(Name), '+ roleFieldOnScrumTeamMember + ', ' + teamFieldOnScrumTeamMember +', '+
                                                                ' GROUPING(' + teamFieldOnScrumTeamMember +') grpTeam, GROUPING('+ roleFieldOnScrumTeamMember +') grpRole from ' + sobjectTypeName +  
                                                                ' where '+ teamForeignFieldOnScrumTeamMember +'.Name in:teamNames '+ 
                                                                'group by ROLLUP('+teamFieldOnScrumTeamMember+ ', '+ roleFieldOnScrumTeamMember + ')';
        AggregateResult[] memberRoleCountByScrumTeam = Database.query(soql);
        /*AggregateResult[] memberRoleCountByScrumTeam = [select COUNT(Name), gus__Role__c, gus__Scrum_Team__c, 
                                                                GROUPING(gus__Scrum_Team__c) grpTeam, GROUPING(gus__Role__c) grpRole  
                                                                from gus__ADM_Scrum_Team_Member__c 
                                                                where gus__Scrum_Team__r.Name in:teamNames
                                                                group by ROLLUP(gus__Scrum_Team__c, gus__Role__c)];*/
														
		return memberRoleCountByScrumTeam;												
		
	}
	
	
	protected  Integer countMembersMatchingRoleAndScrumTeam(AggregateResult[] memberRoleCountByScrumTeam, String role, String teamName, Map<Id, ADM_Scrum_Team__c> scrumTeamIDs) {
        String roleFieldOnScrumTeamMember = nameSpacePrefix + 'Role__c';
        String teamFieldOnScrumTeamMember = nameSpacePrefix + 'Scrum_Team__c';
		
		for(AggregateResult ar : memberRoleCountByScrumTeam) {
            ADM_Scrum_Team__c foundTeam = scrumTeamIDs.get(String.valueOf(ar.get(teamFieldOnScrumTeamMember)));
            if((foundTeam != null && foundTeam.Name == teamName) && (ar.get(roleFieldOnScrumTeamMember) == role) ) {
				return (Integer)ar.get('expr0');
			}
		}
		//nothing found 
		return 0;
	}
	
	private String parseParentBuild(String build) {
		String buildPrefix = '';
		try {
			buildPrefix = build.substring(0, build.indexOf('.'));
		} catch (Exception e) {
			
			buildPrefix = build;
		}
		return buildPrefix;		
	} 
	
	public static String getCustomReportIDByName(String reportName) { 
		String reportIdName = '';
		Custom_Report__c [] customReports = [select Report_ID__c from Custom_Report__c where Name = :reportName limit 1];
		if(customReports != null){
			reportIdName = customReports[0].Report_ID__c;
	}
		return reportIdName;
    }
}