mdapi-source/original-package/unpackaged/objects/ADM_Column__c.object
<CustomObject>
    <description>Used to store meta data for a team&apos;s kanban board</description>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Column__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Column</label>
        <referenceTo>ADM_Column__c</referenceTo>
        <relationshipLabel>Columns</relationshipLabel>
        <relationshipName>Columns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Columns</relationshipLabel>
        <relationshipName>Columns</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Column</label>
    <nameField>
        <label>Column Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Columns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Column_Status_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Column__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Column</label>
        <referenceTo>ADM_Column__c</referenceTo>
        <relationshipLabel>Column Status Assignments</relationshipLabel>
        <relationshipName>Column_Status_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Status__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Work Status</label>
        <referenceTo>ADM_Work_Status__c</referenceTo>
        <relationshipLabel>Column Status Assignments</relationshipLabel>
        <relationshipName>Column_Status_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Column Status Assignment</label>
    <nameField>
        <displayFormat>CSA-{000000}</displayFormat>
        <label>Column Status Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Column Status Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work_Status__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Work Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ADM_ColumnStatusAssignment.cls
public with sharing class ADM_ColumnStatusAssignment {
	
	Static final String SELECT_CLAUSE = 'select Column__c, Work_Status__c, Work_Status__r.Name ';
	Static final String FROM_CLAUSE = ' from ADM_Column_Status_Assignment__c';
	Static final String COLUMN_WHERE_CLAUSE = ' Column__c ';
	Static final String TEAM_WHERE_CLAUSE = ' Column__r.Team__c ';

	public static List<ADM_Column_Status_Assignment__c> getAssignmentsByColumns(List<String> columnIds){
		String soql = '';
		soql += SELECT_CLAUSE;
		soql += FROM_CLAUSE;
		String inClause = COM_SoqlUtils.createInClause(COLUMN_WHERE_CLAUSE, columnIds);
		soql += ' where ' + inClause + ' order by Work_Status__r.Order__c ';
		List<ADM_Column_Status_Assignment__c> columnStatusMappings = Database.query(soql);
   		return columnStatusMappings;
	}

	public static List<ADM_Column_Status_Assignment__c> getAssignmentsByColumn(String columnId){
		List<String> columnIds = new List<String>{columnId};
		List<ADM_Column_Status_Assignment__c> columnStatusMappings = getAssignmentsByColumns(columnIds);
   		return columnStatusMappings;
	}

	public static List<ADM_Column_Status_Assignment__c> getAssignmentsFromColumnStatusMapping(Set<String> workStatusIds, Set<String> currentTeamIds){
		List<ADM_Column_Status_Assignment__c> columnStatusMapping = [select Column__c, Work_Status__c, Work_Status__r.Name from ADM_Column_Status_Assignment__c where Work_Status__c in :workStatusIds 
		                                                                                      and Column__r.Team__c in :currentTeamIds order by column__r.Parent_Column__c Nulls First, column__r.level__c, column__r.position__c];
		return columnStatusMapping;
	}

	public static List<ADM_Column_Status_Assignment__c> getAssignmentsByColumns(Set<String> columnIds){
		List<ADM_Column_Status_Assignment__c> columnStatusMapping = getAssignmentsByColumns(new List<String>(columnIds));
		return columnStatusMapping;
	}


	public static List<ADM_Column_Status_Assignment__c> getAssignmentsByTeams(Set<String> teamIds){
		String soql = '';
		soql += SELECT_CLAUSE;
		soql += FROM_CLAUSE;
		String inClause = COM_SoqlUtils.createInClause(TEAM_WHERE_CLAUSE, teamIds);
		soql += ' where ' + inClause + ' order by column__r.Parent_Column__c Nulls First, column__r.level__c, column__r.position__c ';
		List<ADM_Column_Status_Assignment__c> columnStatusMappings = Database.query(soql);
   		return columnStatusMappings;
	}

}