mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Test_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Test Plan</label>
        <referenceTo>QA_Test_Plan__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/classes/QA_TPUserStoryListExtension.cls
public with sharing class QA_TPUserStoryListExtension {

    public List<ADM_Work__c> works { get; set; }
    public Id testPlanId { get; set; }

    public QA_TPUserStoryListExtension (ApexPages.StandardController stdController) {
        testPlanId = stdController.getId();
        works = ADM_Work.getAllBy('Test_Plan__c', new List<String> {testPlanId}, 0, 100, 'Id', 'ASC');
    }

    public PageReference workWizard() {
        PageReference pageRef = Page.QA_addUStoTP;
        pageRef.getParameters().put('id', testPlanId);
        pageRef.getParameters().put('retURL', '/apex/QA_TPDetails?id='+testplanId);
        return pageRef;
    }
}