mdapi-source/original-package/unpackaged/objects/ADM_Build__c.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Build</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Builds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Product_Tag__c.object
<CustomObject>
    <label>TE Activity</label>
    <nameField>
        <label>TE Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TE Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Scrum_Team__c.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Program</fullName>
                    <default>true</default>
                    <label>Program</label>
                </value>
                <value>
                    <fullName>Program of Programs</fullName>
                </value>
                <value>
                    <fullName>Portfolio</fullName>
                </value>
                <value>
                    <fullName>Workrgoup</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>External_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bug</fullName>
                </value>
                <value>
                    <fullName>Gack</fullName>
                </value>
                <value>
                    <fullName>Help</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Test Change</fullName>
                </value>
                <value>
                    <fullName>Test Case</fullName>
                </value>
                <value>
                    <fullName>Test Failure</fullName>
                </value>
                <value>
                    <fullName>Test Tool</fullName>
                </value>
                <value>
                    <fullName>Skunkforce</fullName>
                </value>
                <value>
                    <fullName>Bug List</fullName>
                </value>
                <value>
                    <fullName>Translation</fullName>
                </value>
                <value>
                    <fullName>Non Deterministic Test</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <recordTypes>
        <fullName>Bug</fullName>
        <active>true</active>
        <description>Used to track defects or problems</description>
        <label>Bug</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/User.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/classes/ADM_WorkCreatorRestServiceTest.cls
@isTest
public class ADM_WorkCreatorRestServiceTest {

    @isTest
    public static void testUserStoryCreation(){
    
        String subject = 'Test-subject' + System.currentTimeMillis();
		ADM_Scrum_Team__c team = ADM_ScrumTeam.createTestScrumTeam('TestTeam');
    	ADM_Product_Tag__c productTagForTeam = ADM_ProductTag.createAndInsertProductTagForTeam(team);
    	String type = 'user story';
    
        ADM_WorkCreatorRestService.createWork(subject, productTagForTeam.Name, 
                                                     team.Name, type, null, null, null, null, null);
              
        List<ADM_Work__c> work_list = [ SELECT Id,Subject__c,Type__c from ADM_Work__c where Subject__c LIKE :subject ];
        System.assertEquals(1, work_list.size());
        System.assertEquals('User Story', work_list.get(0).Type__c);    
        
	}
    
    
    @isTest
    public static void testUserStoryCreationWithNullProductTag(){
    
        String subject = 'Test-subject' + System.currentTimeMillis();
		ADM_Scrum_Team__c team = ADM_ScrumTeam.createTestScrumTeam('TestTeam');
    	String type = 'user story';
    
        ADM_WorkCreatorRestService.Result result = ADM_WorkCreatorRestService.createWork(subject, 'bogus-product-tag', 
                                                     team.Name, type, null, null, null, null, null);
       	
        System.assertEquals( 1, result.getErrorMessages().size(), 'The error messages count was not one'); 
        System.assert( result.getErrorMessages().get(0).containsIgnoreCase('Cannot find a Product tag with name "bogus-product-tag"'), 
                      'The error message is not what was expected');
            
	}

    public static void testBugCreation(){
        
        String subject = 'Test-bug' + System.currentTimeMillis();
		ADM_Scrum_Team__c team = ADM_ScrumTeam.createTestScrumTeam('TestTeam');
    	ADM_Product_Tag__c productTagForTeam = ADM_ProductTag.createAndInsertProductTagForTeam(team);
        String priority = 'p3';
        String type = 'bug';
    
        String test_build = 'ptest1.0' + System.currentTimeMillis();
        ADM_Build__c build = new ADM_Build__c();
        build.Name = test_build;
        build.External_ID__c = test_build;
        upsert build;
        
        ADM_WorkCreatorRestService.Result result = ADM_WorkCreatorRestService.createWork(subject, productTagForTeam.Name, 
                                                     team.Name, type, test_build, priority, null, null, null );
        
        RecordType bug_type = ADM_RecordType.getByName('Bug', 'ADM_Work__c');
        
		List<ADM_Work__c> work_list = [ SELECT Id,Subject__c,RecordTypeId from ADM_Work__c where Subject__c LIKE :subject ];
        System.assertEquals(1, work_list.size());
        System.assertEquals(bug_type.Id, work_list.get(0).RecordTypeId);    
        
	}
    
    @isTest
    public static void testBugCreationNoBuild(){
        
        String subject = 'Test-subject' + System.currentTimeMillis();
		ADM_Scrum_Team__c team = ADM_ScrumTeam.createTestScrumTeam('TestTeam');
    	ADM_Product_Tag__c productTagForTeam = ADM_ProductTag.createAndInsertProductTagForTeam(team);
        String priority = 'p3';
        String type = 'bug';
		// Make a bogus found in build
        String found_in_build = 'bogus-data' +System.currentTimeMillis();
    
        ADM_WorkCreatorRestService.Result result = ADM_WorkCreatorRestService.createWork(subject, productTagForTeam.Name, 
                                                     team.Name, type, found_in_build, priority, null, null, null);
       	
        System.assertEquals( 1, result.getErrorMessages().size(), 'The error messages count was not one'); 
        System.assert( result.getErrorMessages().get(0).containsIgnoreCase('Cannot find build with name'), 
                      'The error message is not what was expected');
        
	}
}