mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If you leave this field empty on save you will be the Assignee.</inlineHelpText>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assignee</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bug_Number__c</fullName>
        <label>Bugforce #</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Closed_By__c</fullName>
        <label>Closed By</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Closed_On__c</fullName>
        <label>Closed On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Closed__c</fullName>
        <formula>CASE(  Status__c, &quot;Tested&quot;, 1, &quot;Closed&quot;, 1, &quot;Closed-Untested&quot;, 1, &quot;Closed-U/Ftest&quot;, 1, &quot;Completed&quot;, 1, &quot;Not Reproducible&quot;, 1, &quot;Never&quot;, 1, &quot;Not a bug&quot;, 1, &quot;Duplicate&quot;, 1, &quot;Closed - Duplicate&quot; , 1, &quot;Closed - Known Bug Exists&quot;, 1, &quot;Closed - New Bug Logged&quot;, 1, &quot;Closed - No Fix - Working as Designed&quot;,1, &quot;Closed - No Fix - Feature Request&quot;,1, &quot;Closed - No Fix - Will Not Fix&quot;,1, &quot;Closed - LAP Request Approved&quot;, 1, &quot;Closed - LAP Request Denied&quot;, 1, &quot;Closed - Resolved Without Code Change&quot;, 1, &quot;Rejected&quot;, 1, &quot;Closed - Resolved With Internal Tools&quot;, 1, &quot;Closed - Defunct&quot;,1,&quot;Closed - Doc/Usability&quot;,1,&quot;Closed - Resolved with DB Script&quot;,1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Closed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Comments will be added to the Work record and included in an email to the names listed in the Email Notifications section after saving. Formatting will also be preserved when saving via in line edit.</inlineHelpText>
        <label>Comment</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email_Subscription_ID__c</fullName>
        <inlineHelpText>Enter email aliases separated by spaces. These users are sent one email if the &quot;Email on Save&quot; check box is selected when you click &quot;Save.&quot; They do not automatically receive future updates.</inlineHelpText>
        <label>To</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Major_Func_Area__c</fullName>
        <label>Major Func Area</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Area__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>.NET</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Minor_Func_Area__c</fullName>
        <label>Minor Func Area</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Perforce_Status__c</fullName>
        <label>Source Control Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open Once</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <inlineHelpText>For bugs, priority is automatically determined based upon the combination of Impact and Frequency.

For user stories, P0 represents the highest priority, P4 the lowest.</inlineHelpText>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>P0</fullName>
                    <color>#0B6FCE</color>
                    <label>P0</label>
                </value>
                <value>
                    <fullName>P1</fullName>
                    <color>#FF0000</color>
                    <label>P1</label>
                </value>
                <value>
                    <fullName>P2</fullName>
                    <color>#E27001</color>
                    <label>P2</label>
                </value>
                <value>
                    <fullName>P3</fullName>
                    <color>#FFFF66</color>
                    <label>P3</label>
                </value>
                <value>
                    <fullName>P4</fullName>
                    <color>#78C953</color>
                    <label>P4</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Area__c</fullName>
        <label>Product Area</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>API</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Child__c</fullName>
        <description>Used only by the Clients team. Dependent on the Product Area picklist.</description>
        <inlineHelpText>Used only by the Clients team. Dependent on the Product Area picklist.</inlineHelpText>
        <label>Product Child</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AXIS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If you leave it empty on save you will be the Product Owner</inlineHelpText>
        <label>Product Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Product_Owner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QA_Engineer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>QA Engineer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QA_Engineer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Regressed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Regressed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Related_URL__c</fullName>
        <label>Related URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Resolved_By__c</fullName>
        <label>Resolved By</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Resolved_On__c</fullName>
        <label>Resolved On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Resolved__c</fullName>
        <formula>CASE( Status__c, &quot;Fixed&quot;, 1, &quot;Tested&quot;, 1, &quot;Closed&quot;, 1, &quot;Completed&quot;, 1, &quot;Not Reproducible&quot;, 1, &quot;Not a bug&quot;, 1, &quot;Duplicate&quot;, 1,
&quot;Closed - Duplicate&quot;, 1, &quot;Closed - Known Bug Exists&quot;, 1, &quot;Never&quot;, 1,&quot;Closed-U/Ftest&quot;, 1, &quot;Closed-Untested&quot;, 1, &quot;QA In Progress&quot;, 1,
&quot;Closed - New Bug Logged&quot;, 1, &quot;Closed - No Fix - Working as Designed&quot;,1,
&quot;Closed - LAP Request Approved&quot;, 1, &quot;Closed - LAP Request Denied&quot;, 1, &quot;Closed - Resolved Without Code Change&quot;, 1,
&quot;Closed - No Fix - Feature Request&quot;,1, &quot;Closed - No Fix - Will Not Fix&quot;,1, &quot;Rejected&quot;, 1, &quot;Closed - Resolved With Internal Tools&quot;, 1, &quot;Closed - Defunct&quot;, 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Resolved</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scheduled_Build__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Scheduled Build field is a lookup to the Build object.  Enter a pre-existing build where the change will be made.</inlineHelpText>
        <label>Scheduled Build</label>
        <referenceTo>ADM_Build__c</referenceTo>
        <relationshipLabel>Work (Scheduled Build)</relationshipLabel>
        <relationshipName>Scheduled_Build</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scheduled_On__c</fullName>
        <description>Deprecated field from BF 1.0</description>
        <label>Scheduled On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Triaged</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Investigating</fullName>
                </value>
                <value>
                    <fullName>Ready for Review</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>QA In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Defunct</fullName>
                </value>
                <value>
                    <fullName>Closed - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Closed - Eng Internal</fullName>
                </value>
                <value>
                    <fullName>Closed - Known Bug Exists</fullName>
                </value>
                <value>
                    <fullName>Closed - New Bug Logged</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Approved</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Denied</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved With Internal Tools</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved Without Code Change</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Working as Designed</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Feature Request</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Will Not Fix</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Pending Release</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>More Info Reqd from Support</fullName>
                </value>
                <value>
                    <fullName>Never</fullName>
                </value>
                <value>
                    <fullName>Not a bug</fullName>
                </value>
                <value>
                    <fullName>Not Reproducible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Test_Engineer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Performance Engineer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>System_Test_Engineer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tech_Writer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tech Writer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Tech_Writer</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ADM_WorkPerforceStatus.cls
public class ADM_WorkPerforceStatus {
	public static String OPEN = 'Open';
	public static String OPEN_ONCE = 'Open Once';
	public static String REQUESTED = 'Requested';
	public static String P4_WORK_NOT_OPEN_ERROR = 'Please set the Status to one of the following values when opening the Source Control Status: ' + ADM_TextUtils.joinSet(ADM_Work.STATUS_VALUES_OPEN, ',') + '.';
	public static String P4_ASSIGNEE_CANNOT_UPDATE_ERROR = 'The assignee of a work record can\'t open the Source Control Status. Put some Windex on it and try again.';

	public static String getOpen() {
		return OPEN;
	}

	public static String getOpenOnce() {
		return OPEN_ONCE;
	}
	
	public static String getPerforceErrorWhenWorkOpened(ADM_Work__c newWork, ADM_Work__c oldWork) {
		if(newWork.Perforce_Status__c != oldWork.Perforce_Status__c) {
			if(!ADM_TextUtils.isBlank(newWork.Perforce_Status__c) && newWork.Perforce_Status__c.toLowerCase().contains('open')) {
	        	if(ADM_Work.STATUS_VALUES_OPEN.contains(newWork.Status__c)) {  
	        		if(newWork.Assignee__c == UserInfo.getUserId()) {
						return P4_ASSIGNEE_CANNOT_UPDATE_ERROR;        			
	        		}      		
	        	} else {
	        		return P4_WORK_NOT_OPEN_ERROR;
	        	}	        	
	        }
		}
        return '';	
	}

	// --------------------------------- isPerforceStatusUpdated Begin ------------------------------------------ \\

	public static Boolean isPerforceStatusUpdated( ADM_Work__c nw, ADM_Work__c ow ) {
		Boolean returnValue = false;
		if ( nw.Perforce_Status__c != ow.Perforce_Status__c && nw.Perforce_Status__c != null ) {							
			if ( nw.Perforce_Status__c.contains(ADM_WorkPerforceStatus.getOpen()) || nw.Perforce_Status__c.contains(ADM_WorkPerforceStatus.getOpenOnce()) ) {
				returnValue = true;
			}			
		}
		return returnValue;
	}

	static testMethod void testIsPerforceStatusUpdated (){
		ADM_Work__c w_1 = new ADM_Work__c();
		ADM_Work__c w_2 = new ADM_Work__c();
		Boolean checkValue = false;

		ADM_Work__c[] work = [
			Select a.Assignee__c, a.Bug_Number__c, a.Closed__c, a.Closed_By__c, a.Closed_On__c, a.Customer__c, a.Description__c, a.Email_Subscription_ID__c, a.External_ID__c, a.Major_Func_Area__c, a.Minor_Func_Area__c, a.Perforce_Status__c, a.Priority__c, a.Product_Area__c, a.Product_Child__c, a.Product_Owner__c, a.QA_Engineer__c, a.Regressed__c, a.Related_URL__c, a.Resolved__c, a.Resolved_By__c, a.Resolved_On__c, a.Scheduled_Build__c, a.Scheduled_On__c, a.Scrum_Team__c, a.Status__c, a.Subject__c, a.System_Test_Engineer__c, a.Tech_Writer__c, a.Type__c, a.CreatedById, a.CreatedDate, a.Id, a.LastModifiedById, a.LastModifiedDate, a.Name, a.OwnerId
			from ADM_Work__c a
			limit 2
		];

		if ( work.size() > 1 ) {
			w_1 = work[0];
			w_2 = work[1];
			if ( w_1.Perforce_Status__c != w_2.Perforce_Status__c ) {
				if ( w_1.Perforce_Status__c == ADM_WorkPerforceStatus.getOpen() || w_1.Perforce_Status__c == ADM_WorkPerforceStatus.getOpenOnce() ) {
					checkValue = true;
				}
			}
		}

		System.assertEquals( checkValue, isPerforceStatusUpdated( w_1, w_2 ) );

	}

// --------------------------------- isPerforceStatusUpdated End ------------------------------------------ \\

	//================================================RUN beginning TESTS==================================\\

	static testMethod void testGetOpen() {
		System.assertEquals( OPEN, getOpen() );
	}

	static testMethod void testGetOpenOnce() {
		System.assertEquals( OPEN_ONCE, getOpenOnce() );
	}

	//================================================RUN ending TESTS==================================\\

}