mdapi-source/original-package/unpackaged/objects/ADM_Scrum_Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/Locking_Record__c.object
<CustomObject>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Lock Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ToBe</fullName>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Unlock Override</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Locking Records</relationshipLabel>
        <relationshipName>Locking_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Locking Record</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Locking Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locking Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/classes/LockingRecordsTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class LockingRecordsTest {

/*
 @testcaseID  a1DB00000000qMn
 @userstoryID a07B0000000EV6RIAW
 @Hierarchy GUS.BugforceToGUS.SystemIntegrations.Locking Record
 @ExpectedResults Error message displayed reads: "Team has been locked out of Perforce check in's by user_name. More information can be found at the following link: link_name
 @Author = Alexis Williams
 */
    static testMethod void testGettingLockingRecordsMessage() {
        ADM_Scrum_Team__c team = ADM_ScrumTeam.createTestScrumTeam();
        LockingRecords lock = new LockingRecords(team.Id); 
        String lockedByMessage = 'Team has been locked out of main branch by ' + Userinfo.getName() + '. ';
        
        System.assertEquals('', lock.message);
        System.assertEquals(true, lock.getLocks().isEmpty());
        
        Locking_Record__c lr = new Locking_Record__c();
        lr.Status__c = 'ToBe';
        lr.Team__c = team.Id;
        lr.Start_Time__c = System.now();
        insert lr;
        
        lock.getLocks();
        
        System.assertEquals('', lock.message);
        
        Locking_Record__c lr2 = lr.clone(false, true);
        lr2.Status__c = 'Locked';
        insert lr2;
        delete lr;
        
        List<Locking_Record__c> locks = lock.getLocks();
        
        System.assert(lock.message.contains(lockedByMessage), 'Expected locked by user message');  
        System.assert((lock.lockRecord.id == lr2.id),'Expected matching lock record id');      
    }
}