mdapi-source/original-package/unpackaged/objects/ADM_Scrum_Team__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Sprint__c.object
<CustomObject>
    <customHelpPage>ADM_CreateSprintOverview</customHelpPage>
    <description>Added to support User Story for Scrumforce integration into GUS.</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scrum Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Sprints</relationshipLabel>
        <relationshipName>Sprints</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sprint</label>
        <referenceTo>ADM_Sprint__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Triaged</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Investigating</fullName>
                </value>
                <value>
                    <fullName>Ready for Review</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>QA In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Defunct</fullName>
                </value>
                <value>
                    <fullName>Closed - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Closed - Eng Internal</fullName>
                </value>
                <value>
                    <fullName>Closed - Known Bug Exists</fullName>
                </value>
                <value>
                    <fullName>Closed - New Bug Logged</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Approved</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Denied</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved With Internal Tools</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved Without Code Change</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Working as Designed</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Feature Request</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Will Not Fix</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Pending Release</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>More Info Reqd from Support</fullName>
                </value>
                <value>
                    <fullName>Never</fullName>
                </value>
                <value>
                    <fullName>Not a bug</fullName>
                </value>
                <value>
                    <fullName>Not Reproducible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Story_Points__c</fullName>
        <inlineHelpText>If you leave it empty on save it will automatically assign the value from the TE activity selected.</inlineHelpText>
        <label>Story Points</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/classes/ADM_Planner_ReleaseVisualizerTests.cls
@isTest
public with sharing class ADM_Planner_ReleaseVisualizerTests {

	static ADM_Sprint__c pastSprintA = null;
	static ADM_Sprint__c pastSprintB = null;
	static ADM_Sprint__c futureSprintA = null;
	static ADM_Sprint__c futureSprintB = null;

	public ADM_Planner_ReleaseVisualizerTests() {
	}
			
	static testMethod void testGetTeamName() {
		ADM_Scrum_Team__c team = ADM_ScrumTeam.createAndInsertScrumTeamWithRandomName();
		
		Test.startTest();
		ApexPages.currentPage().getParameters().put('teamId', team.Id);
		ADM_Planner_ReleaseVisualizerController controller = new ADM_Planner_ReleaseVisualizerController();
		String retrievedName = controller.getTeamName();
		Test.stopTest();

		System.assert(retrievedName == team.Name, 'Expected getTeamName to return test team name');
	}


	static testMethod void testGetAverageVelocity() {
		// Create a list of four work items
		Set<String> additionalFields = new Set<String>();
        additionalFields.add('Scrum_Team__c');
		List<ADM_Work__c> workItems = ADM_Work.createListOfWork(4, ADM_Work.RECORD_TYPE_NAME_USERSTORY, additionalFields);
		// All the items are assigned the same scrum team
		Id teamId = workItems[0].Scrum_Team__c;
		System.assert(teamId != null, 'Expected teamId to be non-null');

		ApexPages.currentPage().getParameters().put('teamid', teamId);
		ADM_Planner_ReleaseVisualizerController controller = new ADM_Planner_ReleaseVisualizerController();

		Test.startTest();

		createPastSprints(teamId);
		createFutureSprints(teamId); // Note: these sprints shouldn't matter or cause any exceptions

		// Assign the first two work items to past sprint 'a' and the other two to past sprint 'b'
		workItems[0].Sprint__c = pastSprintA.Id;
		workItems[0].Story_Points__c = 3;
		workItems[1].Sprint__c = pastSprintA.Id;
		workItems[1].Story_Points__c = 5;
		workItems[2].Sprint__c = pastSprintB.Id;
		workItems[2].Story_Points__c = 8;
		workItems[3].Sprint__c = pastSprintB.Id;
		workItems[3].Story_Points__c = 13;

		// Insert the work items
		insert workItems;

		// Make sure they were inserted and set the status to 'Closed'
		for (ADM_Work__c workItem : workItems) {
			System.assert(workItem.Id != null, 'Expected work Id to be non-null');
			workItem.Status__c = 'Closed';
		}

		// Update the items - this should update the sprint velocity
		update workItems;


		Test.stopTest();

		Integer avgVelocity = controller.getAverageVelocity();
		// Our expected velocity for each sprint is sprint A = 8, sprint B = 21
		// So the average velocity should be (8 + 21)/2 ~= 14
		System.assert(avgVelocity == 14, 'Expected average velocity to be 14');

	}

	static testMethod void testGetPlanningSprints() {
		ADM_Scrum_Team__c team = ADM_ScrumTeam.createAndInsertScrumTeamWithRandomName();
		ApexPages.currentPage().getParameters().put('teamid', team.Id);
		ADM_Planner_ReleaseVisualizerController controller = new ADM_Planner_ReleaseVisualizerController();

		Test.startTest();

		createPastSprints(team.Id); // Note: these sprints should not be returned
		createFutureSprints(team.Id);

		List<ADM_Sprint__c> planningSprints = controller.getPlanningSprints();

		Test.stopTest();

		System.assert(planningSprints.size() == 2, 'Expected two planning sprints');
		System.assert(planningSprints[0].Id == futureSprintA.Id, 'Expected first planning sprint to be sprint A');
		System.assert(planningSprints[1].Id == futureSprintB.Id, 'Expected second planning sprint to be sprint B');

	}

	static testMethod void testGetSprintsToBeDisplayed() {
		// Create a list of four work items
		Set<String> additionalFields = new Set<String>();
        additionalFields.add('Scrum_Team__c');
		List<ADM_Work__c> workItems = ADM_Work.createListOfWork(6, ADM_Work.RECORD_TYPE_NAME_USERSTORY, additionalFields);
		// All the items are assigned the same scrum team
		Id teamId = workItems[0].Scrum_Team__c;
		System.assert(teamId != null, 'Expected teamId to be non-null');

		ApexPages.currentPage().getParameters().put('teamid', teamId);
		ADM_Planner_ReleaseVisualizerController controller = new ADM_Planner_ReleaseVisualizerController();

		Test.startTest();

		createPastSprints(teamId);
		createFutureSprints(teamId);

		// Assign the first two work items to past sprint 'a' and the next two to past sprint 'b'
		workItems[0].Sprint__c = pastSprintA.Id;
		workItems[0].Story_Points__c = 3;
		workItems[1].Sprint__c = pastSprintA.Id;
		workItems[1].Story_Points__c = 5;
		workItems[2].Sprint__c = pastSprintB.Id;
		workItems[2].Story_Points__c = 8;
		workItems[3].Sprint__c = pastSprintB.Id;
		workItems[3].Story_Points__c = 13;

		// Assign the last two work items to future sprint 'a' and future sprint 'b', respectively
		workItems[4].Sprint__c = futureSprintA.Id;
		workItems[4].Story_Points__c = 5;
		workItems[5].Sprint__c = futureSprintB.Id;
		workItems[5].Story_Points__c = 8;


		// Insert the work items
		insert workItems;

		// Make sure they were inserted and set the status to 'Closed' for past sprints
		for (ADM_Work__c workItem : workItems) {
			System.assert(workItem.Id != null, 'Expected work Id to be non-null');
			if (workItem.Sprint__c == pastSprintA.Id || workItem.Sprint__c == pastSprintB.Id) {
				workItem.Status__c = 'Closed';
			}
		}

		// Update the items - this should update the sprint velocity
		update workItems;

		Test.stopTest();

		// Generate the custom VF component based on the data set up above
		Component.Apex.OutputPanel panel = controller.getSprintsToBeDisplayed();
		System.assert(panel != null, 'Expected the custom output panel to be non-null');

		// Unfortunately, this simple sanity check (!= null) is about the only realistic test that can
		// be done at this level for this method.  See:
		// http://salesforce.stackexchange.com/questions/16080/how-do-i-unit-test-an-apex-controller-method-for-dynamic-components
		// for a discussion of the troubles testing dynamic components.  Selenium should be able to cover the generated
		// HTML later.
	}

	private static void createPastSprints(Id teamId) {
		// Create two sprints in the past: Go back one month from the current month and set up the 'a' and 'b' sprints
		Date sprintAStart = Date.today().toStartOfMonth().addMonths(-1);
		Date sprintAEnd = Date.newInstance(sprintAStart.year(), sprintAStart.month(), sprintAStart.day()).addDays(14);
		Date sprintBStart = Date.newInstance(sprintAEnd.year(), sprintAEnd.month(), sprintAEnd.day()).addDays(1);
		Date sprintBEnd = Date.today().toStartOfMonth().addDays(-1);

		pastSprintA = createAndInsertTestSprint(sprintAStart, sprintAEnd, teamId, 'a');
		pastSprintB = createAndInsertTestSprint(sprintBStart, sprintBEnd, teamId, 'b');

		System.assert(pastSprintA.Id != null, 'Expected sprint A ID to be non-null');
		System.assert(pastSprintB.Id != null, 'Expected sprint B ID to be non-null');

	}

	private static void createFutureSprints(Id teamId) {
		// Create two sprints in the future: Go forward one month from the current month and set up the 'a' and 'b' sprints
		Date sprintAStart = Date.today().toStartOfMonth().addMonths(1);
		Date sprintAEnd = Date.newInstance(sprintAStart.year(), sprintAStart.month(), sprintAStart.day()).addDays(14);
		Date sprintBStart = Date.newInstance(sprintAEnd.year(), sprintAEnd.month(), sprintAEnd.day()).addDays(1);
		Date sprintBEnd = Date.today().toStartOfMonth().addMonths(2).addDays(-1);

		futureSprintA = createAndInsertTestSprint(sprintAStart, sprintAEnd, teamId, 'a');
		futureSprintB = createAndInsertTestSprint(sprintBStart, sprintBEnd, teamId, 'b');

		System.assert(futureSprintA.Id != null, 'Expected sprint A ID to be non-null');
		System.assert(futureSprintB.Id != null, 'Expected sprint B ID to be non-null');

	}

  private static ADM_Sprint__c createAndInsertTestSprint(Date startDate, Date endDate, Id teamId, String sprintSuffix) {    
    String sprintMonth = startDate.month().format();
    if(sprintMonth.length() == 1) {
        sprintMonth = '0' + sprintMonth;
    }
    String sprintName = startDate.year() + '.' + sprintMonth + sprintSuffix;
    ADM_Sprint__c sprint = new ADM_Sprint__c();
    sprint.Name = sprintName;
    sprint.Scrum_Team__c = teamId;
    sprint.Start_Date__c = startDate;
    sprint.End_Date__c = endDate;
    insert sprint;
    
    return sprint;
  }

}