mdapi-source/original-package/unpackaged/objects/ADM_Assignment_Rule__c.object
<CustomObject>
    <description>Used to populate the Assignment Rules on ADM_Work__c records</description>
    <fields>
        <fullName>Product_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If this field is empty it will be pre-populated with the Product Owner for the rule&apos;s scrum team.</inlineHelpText>
        <label>Product Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assignment_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scrum_Team_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scrum Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipName>R00NT0000000lhZkMAI</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assignment Rule</label>
    <nameField>
        <label>Assignment Rule</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignment Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Product_Tag__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipName>Product_Tags</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TE Activity</label>
    <nameField>
        <label>TE Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TE Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Scrum_Team__c.object
<CustomObject>
    <fields>
        <fullName>Product_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Product_Owner_For_Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Scrum_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Member_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Scrum_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Analyst</fullName>
                </value>
                <value>
                    <fullName>Architect</fullName>
                </value>
                <value>
                    <fullName>BSA</fullName>
                </value>
                <value>
                    <fullName>Business Owner</fullName>
                </value>
                <value>
                    <fullName>Capacity Planner</fullName>
                </value>
                <value>
                    <fullName>Data Center Engineer</fullName>
                </value>
                <value>
                    <fullName>DBA</fullName>
                </value>
                <value>
                    <fullName>Developer</fullName>
                </value>
                <value>
                    <fullName>Dev Manager</fullName>
                </value>
                <value>
                    <fullName>Doc Editor</fullName>
                </value>
                <value>
                    <fullName>Doc Manager</fullName>
                </value>
                <value>
                    <fullName>Engineering Manager</fullName>
                </value>
                <value>
                    <fullName>Network Engineer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Performance Engineer</fullName>
                </value>
                <value>
                    <fullName>Product Owner</fullName>
                </value>
                <value>
                    <fullName>Program Manager</fullName>
                </value>
                <value>
                    <fullName>Provisioning Specialist / Asset Manager</fullName>
                </value>
                <value>
                    <fullName>QA Engineer</fullName>
                </value>
                <value>
                    <fullName>QA Manager</fullName>
                </value>
                <value>
                    <fullName>Release Engineer</fullName>
                </value>
                <value>
                    <fullName>Release Manager</fullName>
                </value>
                <value>
                    <fullName>Scrum Master</fullName>
                </value>
                <value>
                    <fullName>Security Engineer</fullName>
                </value>
                <value>
                    <fullName>Site Reliability Engineer</fullName>
                </value>
                <value>
                    <fullName>Software Engineer</fullName>
                </value>
                <value>
                    <fullName>SysAdmin</fullName>
                </value>
                <value>
                    <fullName>SysAdmin Linux</fullName>
                </value>
                <value>
                    <fullName>SysAdmin Storage</fullName>
                </value>
                <value>
                    <fullName>SysAdmin Win</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>Scrum_Team_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <displayFormat>STM-{00000}</displayFormat>
        <label>Team Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Tag_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Assignment_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment Rule</label>
        <referenceTo>ADM_Assignment_Rule__c</referenceTo>
        <relationshipLabel>Tag Assignments</relationshipLabel>
        <relationshipName>Tag_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Tag__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Tag</label>
        <referenceTo>ADM_Product_Tag__c</referenceTo>
        <relationshipLabel>Tag Assignments</relationshipLabel>
        <relationshipName>Tag_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <label>Record Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bug</fullName>
                </value>
                <value>
                    <fullName>User Story</fullName>
                </value>
                <value>
                    <fullName>Investigation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tag Assignment</label>
    <nameField>
        <displayFormat>TA-{0000}</displayFormat>
        <label>Tag Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tag Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ADM_AssignmentRulePickerControllerTests.cls
@IsTest
private class ADM_AssignmentRulePickerControllerTests {
    
    /* Test to make sure the correct assignment rule is returned when the 
     * product tag has previously been related to an assignment rule */
    
    static testmethod void testGetRuleByRecordTypeWhenAssignmentRuleExists() {
       //setup some test data
        ADM_Assignment_Rule__c rule = ADM_AssignmentRule.createAndInsertAssignmentRule();
        System.assert(rule.id != null, 'Error setting up test data.  Assignment Rule was not inserted');
        ADM_Scrum_Team__c team = [select id, Name from ADM_Scrum_Team__c where id =:rule.Scrum_Team_Assignment__c];
        System.assert(team.id != null, 'Error setting up test data.  Scrum Team was not inserted');
        ADM_Product_Tag__c tag = ADM_ProductTag.createAndInsertProductTagForTeam(team);
        System.assert(tag.id != null, 'Error setting up test data.  Product Tag was not inserted');
        //relate the product tag and the assignment rule for Bugs
        ADM_Tag_Assignment__c bugRule = new ADM_Tag_Assignment__c();
        bugRule.record_type__c = 'Bug';
        bugRule.Product_Tag__c = tag.id;
        bugRule.Assignment_Rule__c = rule.id;
        insert bugRule;
        System.assert(bugRule.id != null, 'Error setting up test data.  Tag Assignment was not inserted');
        //call the controller and verify we get the expected results back
        List<ADM_AssignmentRulePickerController.TagAssignmentWrapper> wrappers = ADM_AssignmentRulePickerController.getRuleByRecordType(tag.id, 'Bug'); 
        System.assert(wrappers != null && wrappers.size() == 1, 'Unexpected number of tag assignments found for Product Tag:' + tag);
        //verify the product tag is connected to the expected assignment rule
        ADM_AssignmentRulePickerController.TagAssignmentWrapper wrapper = wrappers.get(0);
        System.assertEquals('Bug',wrapper.recordType);
        System.assertEquals(rule.id, wrapper.rule.id);
    }
    
    /*Test to make sure a default assignment rule is initialized for new Product Tags */
    
    static testmethod void testGetRuleByRecordTypeWhenAssignmentRuleDoesNotExist() {
       //setup test team and product tag but deliberately don't relate it to an assignment rule to re-create the conditions
       //of a brand new product tag
        ADM_Product_Tag__c tag = ADM_ProductTag.createAndInsertProductTag();
        System.assert(tag.id != null, 'Error setting up test data.  Product Tag was not inserted');
        ADM_Scrum_Team__c team = [select id, Name from ADM_Scrum_Team__c where id =:tag.Team__c];
        System.assert(team.id != null, 'Error setting up test data.  Scrum Team was not inserted');
        //add myself as product owner on new team
        ADM_Scrum_Team_Member__c member = new ADM_Scrum_Team_Member__c();
        member.Scrum_Team__c = team.id;
        member.Member_Name__c = UserInfo.getUserId();
        member.Role__c = 'Product Owner';
        insert member;
        
        //call the controller and verify we get a new assignment rule back even though we didn't create one
        List<ADM_AssignmentRulePickerController.TagAssignmentWrapper> wrappers = ADM_AssignmentRulePickerController.getRuleByRecordType(tag.id, 'Bug'); 
        System.assert(wrappers != null && wrappers.size() == 1, 'Unexpected number of tag assignments found for Product Tag:' + tag);
        
        //verify the product tag is connected to an assignment rule and the product owner has been populated
        ADM_AssignmentRulePickerController.TagAssignmentWrapper wrapper = wrappers.get(0);
        System.assertEquals('Bug',wrapper.recordType);
        System.assert(wrapper.rule.id != null);
        System.assert(wrapper.rule.Product_Owner__c != null);
        System.assertEquals(UserInfo.getUserId(), wrapper.rule.Product_Owner__c);
        
        
    }

}