mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Perforce_Status__c</fullName>
        <label>Source Control Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open Once</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <inlineHelpText>For bugs, priority is automatically determined based upon the combination of Impact and Frequency.

For user stories, P0 represents the highest priority, P4 the lowest.</inlineHelpText>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>P0</fullName>
                    <color>#0B6FCE</color>
                    <label>P0</label>
                </value>
                <value>
                    <fullName>P1</fullName>
                    <color>#FF0000</color>
                    <label>P1</label>
                </value>
                <value>
                    <fullName>P2</fullName>
                    <color>#E27001</color>
                    <label>P2</label>
                </value>
                <value>
                    <fullName>P3</fullName>
                    <color>#FFFF66</color>
                    <label>P3</label>
                </value>
                <value>
                    <fullName>P4</fullName>
                    <color>#78C953</color>
                    <label>P4</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/classes/ADM_BackboneController.cls
global with sharing class ADM_BackboneController {
	private Map<String, List<String>> workStatusValues;
	private List<String> priorities;
	private List<String> perforceStatusValues;
	
    /**
     * Gets the map of work status values grouped by the record type name
     */
	public Map<String, List<String>> getWorkStatusValues() {
		if(workStatusValues == null) {
			workStatusValues = ADM_Work.getStatusValues();
		}
		return workStatusValues;
	}
	
	/**
	 * Gets the map of work status values grouped by record type name as a JSON string
	 */
	public String getWorkStatusValuesAsJson() {
		return JSON.serialize(getWorkStatusValues());
	}
    
    /**
     * Gets the list of priorities  
     */
    public List<String> getPriorities() {
        if(this.priorities == null) {
            this.priorities = new List<String>();
            
            Schema.DescribeFieldResult fieldResult = ADM_Work__c.Priority__c.getDescribe();
            List<Schema.PicklistEntry> ples = fieldResult.getPicklistValues();
            for(Schema.Picklistentry ple : ples) {
                this.priorities.add(ple.getLabel());
            }
        }
        return this.priorities;
    }
    
    /**
     * Gets the list of priorities as a JSON string
     */
    public String getPrioritiesAsJson() {
        return JSON.serialize(getPriorities());
    }
    
    /**
     * Gets the list of Perforce status values
     */
    public List<String> getPerforceStatusValues() {
        if(this.perforceStatusValues == null) {
            this.perforceStatusValues = new List<String>();
            
            Schema.DescribeFieldResult fieldResult = ADM_Work__c.Perforce_Status__c.getDescribe();
            List<Schema.PicklistEntry> ples = fieldResult.getPicklistValues();
            for(Schema.Picklistentry ple : ples) {
                this.perforceStatusValues.add(ple.getLabel());
            }
        }
        return this.perforceStatusValues;
    }
    
    /**
     * Gets the list of Perforce status values as a JSON string
     */
    public String getPerforceStatusValuesAsJson() {
        return JSON.serialize(getPerforceStatusValues());
    }

}