mdapi-source/original-package/unpackaged/objects/ADM_Build__c.object
<CustomObject>
    <label>Build</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Builds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Product_Tag__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipName>Product_Tags</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TE Activity</label>
    <nameField>
        <label>TE Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TE Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Scrum_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Member_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Scrum_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scrum_Team_Name__c</fullName>
        <formula>Scrum_Team__r.Name</formula>
        <label>Team Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>Scrum_Team_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <displayFormat>STM-{00000}</displayFormat>
        <label>Team Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Sprint__c.object
<CustomObject>
    <customHelpPage>ADM_CreateSprintOverview</customHelpPage>
    <description>Added to support User Story for Scrumforce integration into GUS.</description>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scrum Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Sprints</relationshipLabel>
        <relationshipName>Sprints</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If you leave this field empty on save you will be the Assignee.</inlineHelpText>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assignee</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Perforce_Status__c</fullName>
        <label>Source Control Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open Once</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If you leave it empty on save you will be the Product Owner</inlineHelpText>
        <label>Product Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Product_Owner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Tag__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TE Activity</label>
        <referenceTo>ADM_Product_Tag__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Product_Tag</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QA_Engineer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>QA Engineer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QA_Engineer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scheduled_Build_Name__c</fullName>
        <formula>Scheduled_Build__r.Name</formula>
        <label>Scheduled Build Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scheduled_Build__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Scheduled Build field is a lookup to the Build object.  Enter a pre-existing build where the change will be made.</inlineHelpText>
        <label>Scheduled Build</label>
        <referenceTo>ADM_Build__c</referenceTo>
        <relationshipLabel>Work (Scheduled Build)</relationshipLabel>
        <relationshipName>Scheduled_Build</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scrum_Team_Name__c</fullName>
        <formula>Scrum_Team__r.Name</formula>
        <label>Scrum Team Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sprint_Name__c</fullName>
        <formula>Sprint__r.Name</formula>
        <label>Sprint Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sprint</label>
        <referenceTo>ADM_Sprint__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Triaged</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Investigating</fullName>
                </value>
                <value>
                    <fullName>Ready for Review</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>QA In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Defunct</fullName>
                </value>
                <value>
                    <fullName>Closed - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Closed - Eng Internal</fullName>
                </value>
                <value>
                    <fullName>Closed - Known Bug Exists</fullName>
                </value>
                <value>
                    <fullName>Closed - New Bug Logged</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Approved</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Denied</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved With Internal Tools</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved Without Code Change</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Working as Designed</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Feature Request</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Will Not Fix</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Pending Release</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>More Info Reqd from Support</fullName>
                </value>
                <value>
                    <fullName>Never</fullName>
                </value>
                <value>
                    <fullName>Not a bug</fullName>
                </value>
                <value>
                    <fullName>Not Reproducible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bug</fullName>
                </value>
                <value>
                    <fullName>Gack</fullName>
                </value>
                <value>
                    <fullName>Help</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Test Change</fullName>
                </value>
                <value>
                    <fullName>Test Case</fullName>
                </value>
                <value>
                    <fullName>Test Failure</fullName>
                </value>
                <value>
                    <fullName>Test Tool</fullName>
                </value>
                <value>
                    <fullName>Skunkforce</fullName>
                </value>
                <value>
                    <fullName>Bug List</fullName>
                </value>
                <value>
                    <fullName>Translation</fullName>
                </value>
                <value>
                    <fullName>Non Deterministic Test</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <recordTypes>
        <fullName>Bug</fullName>
        <active>true</active>
        <description>Used to track defects or problems</description>
        <label>Bug</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work_Status__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bug</fullName>
                </value>
                <value>
                    <fullName>User Story</fullName>
                </value>
                <value>
                    <fullName>Investigation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Work Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ADM_EmailWorkQuickViewController.cls
public with sharing class ADM_EmailWorkQuickViewController {
	private static String nameSpacePrefix = ADM_ConstantsSingleton.getInstance().getNameSpace();
	@AuraEnabled
    public static ADM_Work__c findWork(String workName) {
        //all fields must be readable by the current user to proceed otherwise an exception is thrown
        if (!(Schema.sObjectType.ADM_Work__c.fields.Name.isAccessible() &&
              Schema.sObjectType.ADM_Work__c.fields.Subject__c.isAccessible() &&
              Schema.sObjectType.ADM_Work__c.fields.Due_Date__c.isAccessible() &&
              Schema.sObjectType.ADM_Work__c.fields.Status__c.isAccessible() &&
              Schema.sObjectType.ADM_Work__c.fields.Assignee__c.isAccessible() &&
              Schema.sObjectType.ADM_Work__c.fields.QA_Engineer__c.isAccessible() &&
              Schema.sObjectType.ADM_Work__c.fields.Sprint__c.isAccessible() &&
              Schema.sObjectType.ADM_Work__c.fields.Sprint_Name__c.isAccessible() &&
              Schema.sObjectType.ADM_Work__c.fields.Scheduled_Build_Name__c.isAccessible() &&
              Schema.sObjectType.ADM_Work__c.fields.Scrum_Team_Name__c.isAccessible() &&
              Schema.sObjectType.ADM_Work__c.fields.Scrum_Team__c.isAccessible() &&
              Schema.sObjectType.ADM_Work__c.fields.Type__c.isAccessible() &&
              Schema.sObjectType.ADM_Work__c.fields.Product_Tag__c.isAccessible() &&
              Schema.sObjectType.User.fields.Id.isAccessible() &&
              Schema.sObjectType.User.fields.Name.isAccessible() &&
              Schema.sObjectType.ADM_Build__c.fields.Id.isAccessible() &&
              Schema.sObjectType.ADM_Sprint__c.fields.Id.isAccessible() &&
              Schema.sObjectType.ADM_Work__c.fields.Id.isAccessible()
             )){
                 throw new AuraHandledException('User cannot change that field');
             }
        return 
       	[SELECT Name, Subject__c, Due_Date__c, Status__c, Assignee__r.Name, Assignee__r.Id, QA_Engineer__r.Name, QA_Engineer__r.Id, Sprint__c, Sprint_Name__c, Sprint__r.Id,
         Scheduled_Build__r.Id,Scheduled_Build_Name__c, Scrum_Team_Name__c, Scrum_Team__c, Type__c, Product_Tag__r.Team__c, Product_Owner__r.Name,
         Id FROM ADM_Work__c Where Name=:workName LIMIT 1];     
    }
    
    @AuraEnabled
    public static List<String> getSourceControlStatuses(String workId){ 
        if(!isSourceControlStatusUpdateable()) {
			throw new AuraHandledException('Insufficient Access Permission: WorkQuickViewController.getSourceControlStatuses');
        }

        ADM_Work__c work = [SELECT Perforce_Status__c FROM ADM_Work__c WHERE Id=:workId LIMIT 1];
        Schema.sObjectType objType = work.getSObjectType(); 
        // Describe the SObject using its object type.
        Schema.DescribeSObjectResult objDescribe = objType.getDescribe();       
        // Get a map of fields for the SObject
        Map<String, Schema.SObjectField> fieldMap = objDescribe.fields.getMap();
        
        List<String> toReturn = new List<String>();
        // Get the list of picklist values for this field.
        for(Schema.PicklistEntry i : fieldMap.get(nameSpacePrefix + 'Perforce_Status__c').getDescribe().getPickListValues()) {
            toReturn.add(i.getValue());
        }
        return toReturn;
    }
    
    /*
     * Get the current source control status of the work item
     */
    @AuraEnabled
    public static String getSourceControlStatus(String workId) {
        if(!isSourceControlStatusUpdateable()) {
            throw new AuraHandledException('Insufficient Access Permission: WorkQuickViewController.getSourceControlStatus');
        }
        ADM_Work__c work = [SELECT Perforce_Status__c FROM ADM_Work__c WHERE Id=:workId LIMIT 1];
        return work.Perforce_Status__c;
    }
    
    /**
     * Get Team members of the work item's team based on the product tag 
     * for assigning the assignee and qa engineer
     */
    @AuraEnabled
    public static ADM_Scrum_Team_Member__c[] getTeamMembers(String teamId){
        if (!Schema.sObjectType.User.fields.Id.isAccessible() ||
            !Schema.sObjectType.User.fields.Name.isAccessible()){
                
        	throw new AuraHandledException('Insufficient Access Permissions: WorkQuickViewController.getTeamMembers');
        }
        return [SELECT Member_Name__r.Name, Member_Name__r.Id FROM ADM_Scrum_Team_Member__c WHERE Scrum_Team__c=:teamId];
    }
    
    /*
     * Gets the current sprint and any sprint that started last month
     */
    @AuraEnabled
    public static ADM_Sprint__c[] getSprints(String scrumTeamId) {
        if (!Schema.sObjectType.ADM_Sprint__c.fields.Name.isAccessible()){
            return new ADM_Sprint__c[]{};
        }
        Date lastMonth = Date.today().addMonths(-1);
        return [SELECT Name, Id FROM ADM_Sprint__c WHERE Scrum_Team__c = :scrumTeamId AND Start_Date__c > :lastMonth];
    }

    /*
     * Get all possible statuses based on the work type which is a comma separated list
     */
	@AuraEnabled
    public static ADM_Work_Status__c[] getWorkStatusList(String workType) {
        if (!Schema.sObjectType.ADM_Work_Status__c.fields.Name.isAccessible() || !Schema.sObjectType.ADM_Work_Status__c.fields.Type__c.isAccessible()){
            return new ADM_Work_Status__c[]{};
        }
        return [SELECT Name FROM ADM_Work_Status__c WHERE Type__c includes (:workType)];
    }
 
    /*
     * Get all builds from 208 and 210. If the user needs more options they should edit the bug in GUS
     */
    @AuraEnabled
    public static ADM_Build__c[] getBuilds() {
        if (!Schema.sObjectType.ADM_Build__c.fields.Name.isAccessible()){
            return new ADM_Build__c[]{};
        }
        return [SELECT Name, Id FROM ADM_Build__c WHERE Name LIKE '208%' OR Name = '210'];
    }
    
    /**************************************
     * 
     *           SETTER METHODS
     * 
     **************************************/
    
    @AuraEnabled
    public static void setStatus(String status, String name){
        if (!Schema.sObjectType.ADM_Work__c.fields.Status__c.isUpdateable()){
            throw new AuraHandledException('User cannot change the status field.');
        }
        try {
            ADM_Work__c work = [SELECT Status__c FROM ADM_Work__c Where Name=:name LIMIT 1];
            work.Status__c = status;
            update work;
        } catch (Exception e) {
            System.debug(e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static void setAssignee(String assigneeId, String workName) {
        try {
            if (!Schema.sObjectType.ADM_Work__c.fields.Assignee__c.isUpdateable()){
            	return;
        	}
            ADM_Work__c work = [SELECT Assignee__c FROM ADM_Work__c WHERE Name=:workName LIMIT 1];
            work.Assignee__c = assigneeId;
            update work;
        } catch (Exception e) {
            System.debug(e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static void setQAEngineer(String qaId, String workName) {
        try {
            if (!Schema.sObjectType.ADM_Work__c.fields.QA_Engineer__c.isUpdateable()){
            	return;
        	}
            ADM_Work__c work = [SELECT QA_Engineer__c FROM ADM_Work__c WHERE Name=:workName LIMIT 1];
            work.QA_Engineer__c = qaId;
            update work;
        } catch (Exception e) {
            System.debug(e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static void setSprint(String sprintId, String workName) {
        try {
            if (!Schema.sObjectType.ADM_Work__c.fields.Sprint__c.isUpdateable()){
            	throw new AuraHandledException('Sprint is not updateable');
        	}
            ADM_Work__c work = [SELECT Sprint__c FROM ADM_Work__c WHERE Name=:workName LIMIT 1];
            work.Sprint__c = sprintId;
            update work;
        } catch (Exception e) {
            System.debug(e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static void setBuild(String buildId, String workName) {
        try {
            if (!Schema.sObjectType.ADM_Work__c.fields.Scheduled_Build__c.isUpdateable()){
            	return;
        	}
            ADM_Work__c work = [SELECT Scheduled_Build__c FROM ADM_Work__c WHERE Name=:workName LIMIT 1];
            work.Scheduled_build__c = buildId;
            update work;
        } catch (Exception e) {
            System.debug(e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static void setSourceControl(String sourceControlStatus, String workName) {     
        try{
            if (!isSourceControlStatusUpdateable()){
            	throw new AuraHandledException('User cannot change ADM_Work__c.Perfoce_Status__c');
        	}
            ADM_Work__c work = [SELECT Perforce_Status__c FROM ADM_Work__c WHERE Name=:workName LIMIT 1];
            work.Perforce_Status__c = sourceControlStatus;
            update work;
        } catch(Exception e) {
            System.debug(e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    /**************************************
     * 
     *           MISC. METHODS
     * 
     **************************************/
    
    public static boolean isSourceControlStatusUpdateable() {
    	return Schema.sObjectType.ADM_Work__c.fields.Perforce_Status__c.isUpdateable();
    }
    
}