mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>ADM_Work__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A connection to the Agile Accelerator Work object used to track Bugs, Investigations and User Stories</description>
        <label>Work</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>AgileAcceleratorCases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/classes/ADM_CaseRelatedListController.cls
public class ADM_CaseRelatedListController {
   
   private ADM_ConstantsSingleton signletonConstants = ADM_ConstantsSingleton.getInstance(); 
    
   public Id workId {
        get; 
        set;
   }
    
   public String workName {
        get; 
        set;
   } 
   
   public Boolean packagedOrg{
        get{
          return signletonConstants.isPackagedOrg();
        }
        set;
   } 
    
   public List<Case> getCasesRelatedToWork() {
       List<Case> cases = new List<Case>();
       try {
          //The relationship between work and cases differs between GUS and Agile Accelerator
          
          if(packagedOrg) {
            System.debug('executing getCasesRelatedToWork() for packaged org...');
             cases = Database.query('select Id, CaseNumber, Subject, CreatedDate, LastModifiedDate, Owner.Name, Status from Case where ADM_Work__c=:workId order by CreatedDate');
          } else {
            System.debug('executing getCasesRelatedToWork() for non packaged org...');
            cases = Database.query('select Id, CaseNumber, Subject, CreatedDate, LastModifiedDate, Owner.Name, Status from Case where SM_Bug__c=:workName order by CreatedDate');
          
          }
           
           
       } catch(Exception e) {
           System.debug('Exception getting cases related to work e:' + e + ' work id:' + workId);
       } 
       
       return cases;
        
        
   } 
    
    public PageReference newCase() {
        return null;
    }

}