mdapi-source/original-package/unpackaged/objects/ADM_Case__c.object
<CustomObject>
    <fields>
        <fullName>Work__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipName>Work62OrgCases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>62 Org Case</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Related Case ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>62 Org Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Scrum_Team__c.object
<CustomObject>
    <fields>
        <fullName>Business_Hours__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Hours</label>
        <referenceTo>BusinessHours</referenceTo>
        <relationshipName>Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Program</fullName>
                    <default>true</default>
                    <label>Program</label>
                </value>
                <value>
                    <fullName>Program of Programs</fullName>
                </value>
                <value>
                    <fullName>Portfolio</fullName>
                </value>
                <value>
                    <fullName>Workrgoup</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_User_Business_Hours__c.object
<CustomObject>
    <fields>
        <fullName>Business_Hours__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Specify your working hours based on your location. This is used to improve the accuracy of SLAs of Work you own. If you don&apos;t specify a value, GUS will use the setting for your team.</inlineHelpText>
        <label>Business Hours</label>
        <referenceTo>BusinessHours</referenceTo>
        <relationshipLabel>User Business Hours</relationshipLabel>
        <relationshipName>User_Business_Hours</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Business_Hours</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Business Hours</label>
    <nameField>
        <displayFormat>UBH-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Business Hours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If you leave this field empty on save you will be the Assignee.</inlineHelpText>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assignee</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CS_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field defaults to the Investigation creator if the creator is in support (otherwise it defaults to blank). It can also be populated/overridden manually.</description>
        <inlineHelpText>This field defaults to the Investigation creator if the creator is in support (otherwise it defaults to blank). It can also be populated/overridden manually.</inlineHelpText>
        <label>Support Contact</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Work4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Details_and_Steps_to_Reproduce__c</fullName>
        <inlineHelpText>Text contents of this field will be sent in initial record creation only</inlineHelpText>
        <label>Details and Steps to Reproduce</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Impact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Impact</label>
        <referenceTo>ADM_Impact__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <inlineHelpText>For bugs, priority is automatically determined based upon the combination of Impact and Frequency.

For user stories, P0 represents the highest priority, P4 the lowest.</inlineHelpText>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>P0</fullName>
                    <color>#0B6FCE</color>
                    <label>P0</label>
                </value>
                <value>
                    <fullName>P1</fullName>
                    <color>#FF0000</color>
                    <label>P1</label>
                </value>
                <value>
                    <fullName>P2</fullName>
                    <color>#E27001</color>
                    <label>P2</label>
                </value>
                <value>
                    <fullName>P3</fullName>
                    <color>#FFFF66</color>
                    <label>P3</label>
                </value>
                <value>
                    <fullName>P4</fullName>
                    <color>#78C953</color>
                    <label>P4</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Tag__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TE Activity</label>
        <referenceTo>ADM_Product_Tag__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Product_Tag</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Severity_Level__c</fullName>
        <label>Severity Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <color>#000099</color>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <color>#990000</color>
                    <label>2</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <color>#FF6600</color>
                    <label>3</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <color>#F3D904</color>
                    <label>4</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Triaged</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Investigating</fullName>
                </value>
                <value>
                    <fullName>Ready for Review</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>QA In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Defunct</fullName>
                </value>
                <value>
                    <fullName>Closed - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Closed - Eng Internal</fullName>
                </value>
                <value>
                    <fullName>Closed - Known Bug Exists</fullName>
                </value>
                <value>
                    <fullName>Closed - New Bug Logged</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Approved</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Denied</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved With Internal Tools</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved Without Code Change</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Working as Designed</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Feature Request</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Will Not Fix</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Pending Release</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>More Info Reqd from Support</fullName>
                </value>
                <value>
                    <fullName>Never</fullName>
                </value>
                <value>
                    <fullName>Not a bug</fullName>
                </value>
                <value>
                    <fullName>Not Reproducible</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bug</fullName>
                </value>
                <value>
                    <fullName>Gack</fullName>
                </value>
                <value>
                    <fullName>Help</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Test Change</fullName>
                </value>
                <value>
                    <fullName>Test Case</fullName>
                </value>
                <value>
                    <fullName>Test Failure</fullName>
                </value>
                <value>
                    <fullName>Test Tool</fullName>
                </value>
                <value>
                    <fullName>Skunkforce</fullName>
                </value>
                <value>
                    <fullName>Bug List</fullName>
                </value>
                <value>
                    <fullName>Translation</fullName>
                </value>
                <value>
                    <fullName>Non Deterministic Test</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <recordTypes>
        <fullName>Bug</fullName>
        <active>true</active>
        <description>Used to track defects or problems</description>
        <label>Bug</label>
    </recordTypes>
    <recordTypes>
        <fullName>Investigation</fullName>
        <active>true</active>
        <description>Used to request R&amp;D triage/diagnosis support for a customer support escalation</description>
        <label>Investigation</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ADM_WorkSLATestData.cls
/** This class contains utils for creating test data for SLA Violations tests in other classes.
    It doesn't contain any actual test methods itself.
   */

@isTest
public class ADM_WorkSLATestData {

    // Current SLA settings https://sites.google.com/a/salesforce.com/support-technology-escalations/
    public static final Long MIN_IN_MILLISEC = 60 * 1000L;
    public static final Long HOUR_IN_MILLISEC = 60 * MIN_IN_MILLISEC;   
    
    public static final Long ACK_TIME_SEV1 = 7 * MIN_IN_MILLISEC;
    public static final Long ACK_TIME_SEV2 = 4 * HOUR_IN_MILLISEC;
    public static final Long ACK_TIME_SEV3 = 8 * HOUR_IN_MILLISEC;
    
    public static final Long UPDATE_TIME_SEV1 = 1 * HOUR_IN_MILLISEC;
    public static final Long UPDATE_TIME_SEV2 = 8 * HOUR_IN_MILLISEC;
    public static final Long UPDATE_TIME_SEV3 = 16 * HOUR_IN_MILLISEC;
    
    public static final String WORK_STATUS_NEW = 'New';
    public static final String WORK_STATUS_ACKNOWLEDGED = 'Acknowledged';
    public static final String WORK_STATUS_INVESTIGATING = 'Investigating';
    public static final String WORK_STATUS_MOREINFOREQUIREDFROMSUPPORT = 'More Info Reqd from Support';
    public static final String WORK_STATUS_REJECTED = 'Rejected';
    public static final String WORK_STATUS_WAD = 'Closed - No Fix - Working as Designed';
    public static final String WORK_STATUS_DEFUNCT = 'Closed - Defunct';
    public static final String WORK_STATUS_NEWBUGLOGGED = 'Closed - New Bug Logged';
        
    
    public static final String SEV1 = '1';
    public static final String SEV2 = '2';
    public static final String SEV3 = '3';
    public static final String SEV4 = '4';
    
    public static final String USER_PROFILE_APIONLY = 'GUS API ONLY CRUD BY PERM SET';
    public static final String USER_PROFILE_SUPPORT = 'GUS Customer Support User';
    public static final String USER_PROFILE_STANDARDUSER = 'GUS User';
    
    public static final String INVESTIGATION_DEFAULT_STATUS = WORK_STATUS_NEW;
    public static final String INVESTIGATION_DEFAULT_SEV_LEVEL = SEV3;
    
    public static final Map<String, Long> ACK_TIME_MAP = new Map<String, Long>();
    static {
        ACK_TIME_MAP.put(SEV1, ACK_TIME_SEV1);
        ACK_TIME_MAP.put(SEV2, ACK_TIME_SEV2);
        ACK_TIME_MAP.put(SEV3, ACK_TIME_SEV3);
    }
    
    private static final Map<String, Long> UPDATE_TIME_MAP = new Map<String, Long>();
    static {
        UPDATE_TIME_MAP.put(SEV1, UPDATE_TIME_SEV1);
        UPDATE_TIME_MAP.put(SEV2, UPDATE_TIME_SEV2);
        UPDATE_TIME_MAP.put(SEV3, UPDATE_TIME_SEV3);
    }
    private static BusinessHours defaultBusinessHours;
    private static BusinessHours nonDefaultBusinessHours;
    
    private static ADM_Product_Tag__c productTag;
    private static ADM_Impact__c impact;
    private static ADM_Priority__c priority;
    private static ADM_Build__c build;
    private static Map<String,RecordType> recordTypesMap = new Map<String,RecordType>();
    private static User apiOnlyUser;
    private static User standardUser;
    private static User supportUser;
    private static User businessHoursUser;


    public static void setupTestData() {
        BusinessHours nonDefaultBhs = ADM_WorkSLATestData.getNonDefaultBusinessHours();
        boolean hasNonDefaultBHs = (nonDefaultBhs!=null);  // does org have a second business hours defined?

        //System.debug('nonDefaultBhs.Id='+nonDefaultBhs.Id);
        //System.debug('defaultBhs.Id='+ADM_WorkSLATestData.getDefaultBusinessHours().Id);

        ADM_Scrum_Team__c teamWithDefaultBHS = ADM_WorkSLATestData.createTeamWithBHS(ADM_WorkSLATestData.TEAMNAME_WITH_DEFAULT_BUSINESS_HOURS, ADM_WorkSLATestData.getDefaultBusinessHours().Id, false);
        ADM_Scrum_Team__c teamWithoutBHS = ADM_WorkSLATestData.createTeamWithBHS(ADM_WorkSLATestData.TEAMNAME_WITHOUT_BUSINESS_HOURS, null, false);
        List<ADM_Scrum_Team__c> teamsToInsert = new List<ADM_Scrum_Team__c> {
                teamWithDefaultBHS,
                teamWithoutBHS
            };

        ADM_Scrum_Team__c teamWithNonDefaultBHS = null;
        if (hasNonDefaultBHs) {
            teamWithNonDefaultBHS = ADM_WorkSLATestData.createTeamWithBHS(ADM_WorkSLATestData.TEAMNAME_WITH_NONDEFAULT_BUSINESS_HOURS, nonDefaultBhs.Id, false);
            teamsToInsert.add(teamWithNonDefaultBHS);
        }
        insert teamsToInsert;
        
        for (ADM_Scrum_Team__c t : teamsToInsert) {
            ADM_ProductTag.createAndInsertProductTagForTeam(t);
        }
        ADM_Build.createTestBuild('Test' + String.valueOf(Math.random()));
        insert new ADM_Impact__c(Name=String.valueOf(Math.random()));
        insert new ADM_Priority__c(Name='priority');
        
        User userWithBusinessHours = createUser('businesshours', 'TestUser', null, USER_PROFILE_STANDARDUSER);
        
        insert new List<User> {
            userWithBusinessHours,
            createUser('standard', 'TestUser', null, USER_PROFILE_STANDARDUSER),
            createUser('support', 'TestUser', null, USER_PROFILE_SUPPORT),
            createUser('apionly', 'TestUser', null, USER_PROFILE_APIONLY)
        };
        
        if(userWithBusinessHours != null && nonDefaultBhs != null) {
            insert new ADM_User_Business_Hours__c(User__c = userWithBusinessHours.Id, Business_Hours__c = nonDefaultBhs.Id); // ADM_WorkSLATestData.getDefaultBusinessHours().Id);  
        }
            
    }
    
    public static BusinessHours getDefaultBusinessHours() {
        if (defaultBusinessHours==null) defaultBusinessHours = [SELECT Id, Name, IsDefault FROM BusinessHours WHERE IsDefault = true];
        return defaultBusinessHours;
    }
    
    public static BusinessHours getNonDefaultBusinessHours() {
        if (nonDefaultBusinessHours==null) {
            List<BusinessHours> hours = [SELECT Id, Name, IsDefault FROM BusinessHours WHERE IsDefault = false AND Name LIKE 'Europe/Ireland%' LIMIT 1];
            if(hours != null && hours.size() > 0) {
                nonDefaultBusinessHours = hours.get(0);
            }
        }
        return nonDefaultBusinessHours;
    }

    public static ADM_Impact__c getImpact() {
        if (impact==null) impact = [SELECT Id FROM ADM_Impact__c LIMIT 1];
        return impact;
    }
    
    public static ADM_Priority__c getPriority() {
        if (priority==null) priority = [SELECT Id FROM ADM_Priority__c LIMIT 1];
        return priority;
    }

    public static ADM_Product_Tag__c getProductTag() {
        if (productTag==null) productTag = [SELECT Id FROM ADM_Product_Tag__c LIMIT 1];
        return productTag;
    }
    
    public static ADM_Build__c getBuild() {
        if (build==null) build = [SELECT Id FROM ADM_Build__c LIMIT 1];
        return build;
    }
    
    public static RecordType getRecordTypeFor(String recordTypeName) {
        RecordType recordType = recordTypesMap.get(recordTypeName);
        if (recordType==null && !recordTypesMap.containsKey(recordTypeName)) {
            recordType = [SELECT Id, Name FROM RecordType WHERE Name = :recordTypeName ];
            recordTypesMap.put(recordTypeName, recordType);
        }
        return recordType;
    }
    
    public static User getStandardUser() {
        if (standardUser==null) loadUsers();
        return standardUser;
    }
    
    public static User getBusinessHoursUser() {
        if (businessHoursUser==null) loadUsers();
        return businessHoursUser;
    }
    
    public static User getSupportUser() {
        if (supportUser==null) loadUsers();
        return supportUser;
    }
    
    public static User getAPIOnlyUser() {
        if (apiOnlyUser==null) loadUsers();
        return apiOnlyUser;
    }
    
    private static void loadUsers() {
        List<User> testUsers = [SELECT Id,Name,Firstname,Lastname,Email,ProfileId
                                FROM User
                                WHERE lastname = 'TestUser'
                                  AND (firstname = 'standard'
                                       OR firstname = 'support'
                                       OR firstname = 'apionly'
                                       OR firstname = 'businesshours')];
        for (User u : testUsers) {
            if (u.firstname == 'standard') {
                standardUser = u;
            } else if (u.firstname == 'support') {
                supportUser = u;
            } else if (u.firstname == 'apionly') {
                apiOnlyUser = u;
            } else if (u.firstname == 'businesshours') {
                businessHoursUser = u;
            }
        }
    }
    
    /**
    * Create an Investigation with proper severty level
    * @param severityLevel The severity level of the investigation
    * @return New investigation
    */
    public static ADM_Work__c createInvestigationWithSevLevel(String severityLevel){
        return createMockInvestigation(severityLevel, null, null, null);
    }
    
    public static ADM_Work__c createMockInvestigation(String severityLevel, String status, Id teamId, DateTime slaDueTime) {
        
        ADM_Work__c investigation =  new ADM_Work__c();
        
        //investigation.Type__c = ADM_Work.RECORD_TYPE_NAME_INVESTIGATION;
        investigation.RecordType = getRecordTypeFor(ADM_Work.RECORD_TYPE_NAME_INVESTIGATION);
        investigation.RecordTypeId = getRecordTypeFor(ADM_Work.RECORD_TYPE_NAME_INVESTIGATION).Id;
        investigation.Status__c = status;
        investigation.Scrum_Team__c = teamId;
        investigation.Severity_Level__c = severityLevel;
        investigation.Due_Date__c = slaDueTime;
        
        return investigation;
    }
    
    public static ADM_Work__c createInvestigation(String severityLevel, String status, Id teamId, DateTime slaDueTime, Boolean doInsert){
        
        ADM_Work__c investigation =  new ADM_Work__c();
       
        investigation.CS_Contact__c = Userinfo.getUserId();
        investigation.Details_and_Steps_to_Reproduce__c = 'details and steps to reproduce';
        //investigation.Type__c = ADM_Work.RECORD_TYPE_NAME_INVESTIGATION;
        investigation.RecordType = getRecordTypeFor(ADM_Work.RECORD_TYPE_NAME_INVESTIGATION);
        investigation.RecordTypeId = getRecordTypeFor(ADM_Work.RECORD_TYPE_NAME_INVESTIGATION).Id;
        investigation.Assignee__c = getStandardUser().Id;
        investigation.CS_Contact__c = getSupportUser().Id;
        investigation.Severity_Level__c = severityLevel;
        investigation.Subject__c = 'Test ADM_WorkSLAMonitoringHelper';
        investigation.Scrum_Team__c = teamId;
        
        investigation.Priority__c = getPriority().Id;
        investigation.Product_Tag__c = getProductTag().Id;
        investigation.Found_in_Build__c = getBuild().Id;
        investigation.Impact__c = getImpact().Id;
        
        
        if(status == null){
            investigation.Status__c = INVESTIGATION_DEFAULT_STATUS;
        } else {
            investigation.Status__c = status;
        }
        
        if(severityLevel == null){
            investigation.Severity_Level__c = INVESTIGATION_DEFAULT_SEV_LEVEL;
        } else {
            investigation.Severity_Level__c = severityLevel;
        }
        
        if(doInsert == true){
            insert investigation;
        }
        
        // set this ater insert -- do not save this SLA Due Time to the DB
        investigation.Due_Date__c = slaDueTime;
        
        return investigation;
    }
    
    public static ADM_Case__c createCaseForWork(Id workId) {
        ADM_Case__c org62case = new ADM_Case__c();
        org62case.Work__c = workId;
        //org62case.Case_ID__c = generateRandomString(100);
        //org62case.Account_Id__c = generateRandomString(50);
        //org62case.External_ID__c = System.now().getTime().format();
        
        return org62Case;
    }
    
    public static String generateRandomString(Integer len) {
        final String chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz';
        String randStr = '';
        while (randStr.length() < len) {
           Integer idx = Math.mod(Math.abs(Crypto.getRandomInteger()), chars.length());
           randStr += chars.substring(idx, idx+1);
        }
        return randStr; 
    }
    
    
    public static ADM_Scrum_Team__c createTeamWithBHS(String name, Id bhsId, Boolean doInsert){
        ADM_Scrum_Team__c team = new ADM_Scrum_Team__c();
        team.Name = name;
        team.Cloud__c = 'Chatter';
        team.Team_Home_Page__c = 'salesforce.com';
        team.recordtypeid = getRecordTypeFor(ADM_ScrumTeam.RECORD_TYPE_NAME_SCRUM_TEAM).id; // getScrumTeamRecordType().id; 
        team.Active__c = true;
        team.Business_Hours__c = bhsId;
        if(doInsert == true){
            insert team;
        }
        return team;
    }
    
    private static RecordType scrumTeamRecordType;
    private static RecordType getScrumTeamRecordType() {
         if (scrumTeamRecordType==null) scrumTeamRecordType = [select id from RecordType where name =:ADM_ScrumTeam.RECORD_TYPE_NAME_SCRUM_TEAM LIMIT 1];
         return scrumTeamRecordType;
    }
    
    
    /**
    * Return a test user for given profile
    * 
    * @param profileName the profile name of the test user
    */    
    public static User setupUserwithProfile(String profileName, String userName){
        return createUser('standard', 'testing', userName, profileName);
    }
    
    public static User createUser(String firstname, String lastname, String username, String profileName) {
        List<Profile> profiles = [SELECT Id FROM Profile WHERE Name= :profileName];
        Profile p = null;
        if(profiles != null && profiles.size() > 0 ) {
            p = profiles.get(0);   
        } else {
            //prefrered profile not available.  Only profile guarenteed to exist is sys admin
            p = [SELECT Id FROM Profile WHERE Name= 'System Administrator'];
        }   
        String email = (username==null) ? (firstname + lastname + '@company.com') : username;
        
        return new User(FirstName=firstname,
                        LastName=lastname,
                        Username=email,
                        Email=email,
                        Alias=(firstname + lastname).substring(0,7),
                        CommunityNickname=(firstname + lastname).substring(0,7),
                        ProfileId=p.Id,
                        LocaleSidKey='en_US',
                        LanguageLocaleKey='en_US',
                        TimeZoneSidKey='America/Los_Angeles',
                        EmailEncodingKey='UTF-8');
    }
    
    private static TeamsWithBusinessHours teamsWithBH;
    
    public static TeamsWithBusinessHours getTeamsWithBusinessHours() {
        if (teamsWithBH==null) teamsWithBH = new TeamsWithBusinessHours();
        return teamsWithBH;
    }
    
    public final static String TEAMNAME_WITH_DEFAULT_BUSINESS_HOURS = 'TeamWithDefaultBHS';
    public final static String TEAMNAME_WITHOUT_BUSINESS_HOURS = 'TeamWithoutBHS';
    public final static String TEAMNAME_WITH_NONDEFAULT_BUSINESS_HOURS = 'TeamWithNonDefaultBHS';
    
        
    public class TeamsWithBusinessHours {
        public ADM_Scrum_Team__c teamWithDefaultBHS;
        public ADM_Scrum_Team__c teamWithoutBHS;
        public ADM_Scrum_Team__c teamWithNonDefaultBHS;
        
        public Set<Id> teamIds = new Set<Id>();
        
        private TeamsWithBusinessHours() {
            List<ADM_Scrum_Team__c> teamsWithBHs = [SELECT Id, Name, Business_Hours__c
                                             FROM ADM_Scrum_Team__c
                                             WHERE Name = :TEAMNAME_WITH_DEFAULT_BUSINESS_HOURS
                                                OR Name = :TEAMNAME_WITHOUT_BUSINESS_HOURS
                                                OR Name = :TEAMNAME_WITH_NONDEFAULT_BUSINESS_HOURS];
            
            for (ADM_Scrum_Team__c t : teamsWithBHs) {
                if (TEAMNAME_WITH_DEFAULT_BUSINESS_HOURS.equals(t.name)) {
                    teamWithDefaultBHS = t;
                } else if (TEAMNAME_WITHOUT_BUSINESS_HOURS.equals(t.name)) {
                    teamWithoutBHS = t;
                } else if (TEAMNAME_WITH_NONDEFAULT_BUSINESS_HOURS.equals(t.name)) {
                    teamWithNonDefaultBHS = t;
                }
            }
            
            teamIds.add(teamWithDefaultBHS.Id);
            teamIds.add(teamWithoutBHS.Id);
            if (teamWithNonDefaultBHS!=null) {
                teamIds.add(teamWithNonDefaultBHS.Id);
            }
        }
        
    }
}