mdapi-source/original-package/unpackaged/objects/ADM_Cloud__c.object
<CustomObject>
    <label>Cloud</label>
    <nameField>
        <label>Cloud Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clouds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Scrum_Team__c.object
<CustomObject>
    <fields>
        <fullName>Cloud__c</fullName>
        <label>Department</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Analytics</fullName>
                </value>
                <value>
                    <fullName>Capacity</fullName>
                </value>
                <value>
                    <fullName>Core</fullName>
                </value>
                <value>
                    <fullName>Core Infrastructure</fullName>
                </value>
                <value>
                    <fullName>Data Center Automation</fullName>
                </value>
                <value>
                    <fullName>Industry</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Matrix</fullName>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                </value>
                <value>
                    <fullName>Network and Systems Platform</fullName>
                </value>
                <value>
                    <fullName>Path-To-Production</fullName>
                </value>
                <value>
                    <fullName>Platform</fullName>
                </value>
                <value>
                    <fullName>Production Support</fullName>
                </value>
                <value>
                    <fullName>Productivity</fullName>
                </value>
                <value>
                    <fullName>Programmatic UI</fullName>
                </value>
                <value>
                    <fullName>R&amp;D App Delivery</fullName>
                </value>
                <value>
                    <fullName>Reliability</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Security</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Shared Services</fullName>
                </value>
                <value>
                    <fullName>Trust</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ADM_ApproversCloudOrTeam.cls
public class ADM_ApproversCloudOrTeam {
    /*
     * Takes a list of form: <user ID>:<cloud__c ID>:<scrum_team__c ID> 
     * and returns a list of form: <user ID>:<cloud__c Name> Cloud OR <user ID>:<scrum_team__c Name> Team
     * If both Cloud and Team IDs are given, only Cloud is used.
     */
    @InvocableMethod
    public static List<List<String>> ADM_ApproversCloudOrTeam(List<List<String>> cloudTeamList) {
        Map<Id, ADM_Cloud__c> clouds = new Map<Id, ADM_Cloud__c>();
        Map<Id, ADM_Scrum_Team__c> teams = new Map<Id, ADM_Scrum_Team__c>();
        List<List<String>> returnList = new List<List<String>>();
		
        for (List<String> aCloudTeamList : cloudTeamList) {
        
            for (String key : aCloudTeamList) {
                String cloudId = key.substringAfter(':').substringBefore(':');
                String teamId = key.substringAfterLast(':');
                if (cloudId != null && cloudId.length() > 0) {
                    clouds.put((Id)cloudId, null);
                } else if (teamId != null && teamId.length() > 0) {
                    teams.put((Id)teamId, null);                
                }
                /* DEBUG OFF */ System.Debug('ADM_ApproversCloudOrTeam: cloudId=' + cloudId + ' teamId=' + teamId); /* DEBUG */
            }
        }
        if (clouds.size() > 0) {
            try {
                clouds = new Map<Id, ADM_Cloud__c>([SELECT Id, Name from ADM_Cloud__c where Id =: clouds.keySet()]);
            } catch (Exception e) {
                System.Debug('ADM_ApproversCloudOrTeam: Exception accessing Cloud records: ' + e);
            }
        }
        if (teams.size() > 0) {
            try {
                teams = new Map<Id, ADM_Scrum_Team__c>([SELECT Id, Name from ADM_Scrum_Team__c where Id =: teams.keySet()]);
            } catch (Exception e) {
                System.Debug('ADM_ApproversCloudOrTeam: Exception accessing Team records: ' + e);
            }
        }
        for (List<String> aCloudTeamList : cloudTeamList) {
        
            List<String> aReturnList = new List<String>();
            for (String key : aCloudTeamList) {
                ID userId = key.substringBefore(':');			// userId will always be a valid ID
                String cloudId = key.substringAfter(':').substringBefore(':');
                if (cloudId != null && cloudId.length() > 0) {
                    ADM_Cloud__c cloud = clouds.get(cloudId);
                    if (cloud != null) {
                        aReturnList.add(userId + ':' + cloud.Name + ' Cloud');
                    }
                } else {
                    String teamId = key.substringAfterLast(':');
                    if (teamId != null && teamId.length() > 0) {
                        ADM_Scrum_Team__c team = teams.get(teamId);
                        if (team != null) {
                            aReturnList.add(userId + ':' + team.Name + ' Team');
                        }
                    }  
                }
            }
            returnList.add(aReturnList);
        }
    	return returnList;
    }
}