mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>DateTime</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <recordTypes>
        <fullName>Investigation</fullName>
        <active>true</active>
        <description>Used to request R&amp;D triage/diagnosis support for a customer support escalation</description>
        <label>Investigation</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/classes/ADM_Investigation_Ack_ControllerTest.cls
@IsTest
public class ADM_Investigation_Ack_ControllerTest {

    @isTest
    static void testGetSLADueTimeDiff() {
        
        ADM_Work__c work = ADM_Work.createTestWork('Investigation');
       
        // padding all times by 30 sec to prevent failed assertions due to clock timing
        
        Test.startTest();
        work.Due_Date__c = null;
        System.assertEquals('', ADM_Investigation_Ack_Controller.getSLADueTimeDiff( work ));
        
        work.Due_Date__c = System.now().addSeconds(1*60 + 30);
        System.assertEquals('Due in 1 minute ', ADM_Investigation_Ack_Controller.getSLADueTimeDiff(work));
        
        work.Due_Date__c = System.now().addSeconds(5*60 + 30);
        System.assertEquals('Due in 5 minutes ', ADM_Investigation_Ack_Controller.getSLADueTimeDiff(work));
        
        work.Due_Date__c = System.now().addSeconds(1*3600 + 30);
        System.assertEquals('Due in 1 hour ', ADM_Investigation_Ack_Controller.getSLADueTimeDiff(work));
        
        work.Due_Date__c = System.now().addSeconds(4*3600 + 30);
        System.assertEquals('Due in 4 hours ', ADM_Investigation_Ack_Controller.getSLADueTimeDiff(work));
        
        work.Due_Date__c = System.now().addSeconds(1*24*3600 + 30);
        System.assertEquals('Due in 1 day ', ADM_Investigation_Ack_Controller.getSLADueTimeDiff(work));
        
        work.Due_Date__c = System.now().addSeconds(4*24*3600 + 30);
        System.assertEquals('Due in 4 days ', ADM_Investigation_Ack_Controller.getSLADueTimeDiff(work));
        
        work.Due_Date__c = System.now().addSeconds(10*3600 + 29*60 + 30);
        System.assertEquals('Due in 10 hours 29 minutes ', ADM_Investigation_Ack_Controller.getSLADueTimeDiff(work));
        
        work.Due_Date__c = System.now().addSeconds(2*24*3600 + 10*3600 + 29*60 + 30);
        System.assertEquals('Due in 2 days 10 hours 29 minutes ', ADM_Investigation_Ack_Controller.getSLADueTimeDiff(work));
        
        work.Due_Date__c = System.now().addSeconds(-(9*60 + 30));
        System.assertEquals('Overdue by 9 minutes ', ADM_Investigation_Ack_Controller.getSLADueTimeDiff(work));
    }
    
}