mdapi-source/original-package/unpackaged/objects/ADM_Build__c.object
<CustomObject>
    <label>Build</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Builds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Deleted_Task__c.object
<CustomObject>
    <description>Due to a lack of &quot;deletion&quot; events in the streaming API, we have to store the deleted tasks so subscribers can be notified.</description>
    <fields>
        <fullName>Task__c</fullName>
        <description>ID of the task. This is not a relationship field because the task will have been deleted by the time this record is created.</description>
        <label>Task</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work__c</fullName>
        <description>ID of the work item. This is not a relationship field because the work record may be deleted by the time this value is needed.</description>
        <label>Work</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Deleted Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deleted Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Sprint__c.object
<CustomObject>
    <customHelpPage>ADM_CreateSprintOverview</customHelpPage>
    <description>Added to support User Story for Scrumforce integration into GUS.</description>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scrum Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Sprints</relationshipLabel>
        <relationshipName>Sprints</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Theme__c.object
<CustomObject>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Optional relationship with a scrum team so teams can organize their themes</description>
        <label>Scrum Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipName>Themes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Theme</label>
    <nameField>
        <label>Theme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Themes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If you leave this field empty on save you will be the Assignee.</inlineHelpText>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assignee</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Closed__c</fullName>
        <formula>CASE(  Status__c, &quot;Tested&quot;, 1, &quot;Closed&quot;, 1, &quot;Closed-Untested&quot;, 1, &quot;Closed-U/Ftest&quot;, 1, &quot;Completed&quot;, 1, &quot;Not Reproducible&quot;, 1, &quot;Never&quot;, 1, &quot;Not a bug&quot;, 1, &quot;Duplicate&quot;, 1, &quot;Closed - Duplicate&quot; , 1, &quot;Closed - Known Bug Exists&quot;, 1, &quot;Closed - New Bug Logged&quot;, 1, &quot;Closed - No Fix - Working as Designed&quot;,1, &quot;Closed - No Fix - Feature Request&quot;,1, &quot;Closed - No Fix - Will Not Fix&quot;,1, &quot;Closed - LAP Request Approved&quot;, 1, &quot;Closed - LAP Request Denied&quot;, 1, &quot;Closed - Resolved Without Code Change&quot;, 1, &quot;Rejected&quot;, 1, &quot;Closed - Resolved With Internal Tools&quot;, 1, &quot;Closed - Defunct&quot;,1,&quot;Closed - Doc/Usability&quot;,1,&quot;Closed - Resolved with DB Script&quot;,1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Closed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Priority_Rank__c</fullName>
        <label>Backlog Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <inlineHelpText>For bugs, priority is automatically determined based upon the combination of Impact and Frequency.

For user stories, P0 represents the highest priority, P4 the lowest.</inlineHelpText>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>P0</fullName>
                    <color>#0B6FCE</color>
                    <label>P0</label>
                </value>
                <value>
                    <fullName>P1</fullName>
                    <color>#FF0000</color>
                    <label>P1</label>
                </value>
                <value>
                    <fullName>P2</fullName>
                    <color>#E27001</color>
                    <label>P2</label>
                </value>
                <value>
                    <fullName>P3</fullName>
                    <color>#FFFF66</color>
                    <label>P3</label>
                </value>
                <value>
                    <fullName>P4</fullName>
                    <color>#78C953</color>
                    <label>P4</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Scheduled_Build__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Scheduled Build field is a lookup to the Build object.  Enter a pre-existing build where the change will be made.</inlineHelpText>
        <label>Scheduled Build</label>
        <referenceTo>ADM_Build__c</referenceTo>
        <relationshipLabel>Work (Scheduled Build)</relationshipLabel>
        <relationshipName>Scheduled_Build</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sprint</label>
        <referenceTo>ADM_Sprint__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Triaged</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Investigating</fullName>
                </value>
                <value>
                    <fullName>Ready for Review</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>QA In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Defunct</fullName>
                </value>
                <value>
                    <fullName>Closed - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Closed - Eng Internal</fullName>
                </value>
                <value>
                    <fullName>Closed - Known Bug Exists</fullName>
                </value>
                <value>
                    <fullName>Closed - New Bug Logged</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Approved</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Denied</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved With Internal Tools</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved Without Code Change</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Working as Designed</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Feature Request</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Will Not Fix</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Pending Release</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>More Info Reqd from Support</fullName>
                </value>
                <value>
                    <fullName>Never</fullName>
                </value>
                <value>
                    <fullName>Not a bug</fullName>
                </value>
                <value>
                    <fullName>Not Reproducible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Story_Points__c</fullName>
        <inlineHelpText>If you leave it empty on save it will automatically assign the value from the TE activity selected.</inlineHelpText>
        <label>Story Points</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Theme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Theme-Deprecated</label>
        <referenceTo>ADM_Theme__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Use_Prioritizer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to determine whether or not a work record should be shown on the Work Prioritizer page</description>
        <inlineHelpText>Used to determine whether or not a work record should be shown on the Work Prioritizer page</inlineHelpText>
        <label>Include in Prioritize View</label>
        <type>Checkbox</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/COM_SoqlUtilsTest.cls
@isTest
private class COM_SoqlUtilsTest {
    static Map<String, String> expectedSOQLMap = new Map<String,String>();
	static{
		if((ADM_ConstantsSingleton.getInstance()).isPackagedOrg()){
			expectedSOQLMap.put('expectedSqlWithCustomFields','select Id, Subject__c, Status__c, Story_Points__c, Theme__c, Scheduled_Build__c, Assignee__c, Scrum_Team__c, Sprint__c, LastModifiedDate from ADM_Work__c' );
			expectedSOQLMap.put('expectedSqlWithNoCustomFields','select Id, Name, LastModifiedDate from User' );
			expectedSOQLMap.put('expectedSqlWithRelationship','select id, Name, Subject__c, Status__c, Priority__c, Theme__r.Name, Scheduled_Build__r.Name, Sprint__r.Name, Sprint__c, Closed__c, Use_Prioritizer__c, RecordType.name from ADM_Work__c where Scrum_Team__c = :sprint.Scrum_Team__c and Sprint__c != :sprintID and Closed__c = 0 and Use_Prioritizer__c = true and RecordType.Name !=:ADM_Work.TEMPLATE_RECORD_TYPE_NAME order by Priority_Rank__c, Id  nulls first limit 1000' );
			expectedSOQLMap.put('expecteSqlWithCustomFieldAndObjectNameContainingSameField', 'select Id, Name, Work__c, Task__c, LastModifiedDate from ADM_Deleted_Task__c');
		}
	}
	
	@isTest static void testMakeQualifiedQuery() {
		String sqlWithCustomFields = 'select Id, Subject__c, Status__c, Story_Points__c, Theme__c, Scheduled_Build__c, Assignee__c, Scrum_Team__c, Sprint__c, LastModifiedDate from ADM_Work__c';
		String actualSql = COM_SoqlUtils.makeQualifiedQuery(sqlWithCustomFields);
		String expectedSql = getExpectedSOQL('expectedSqlWithCustomFields');

		if(null == expectedSql){ // If this is null then this org is not a packaged or No NameSpace exist in this org
			expectedSql = sqlWithCustomFields;
		}

		System.assertEquals(expectedSql,actualSql,'Converted soql didn\'t match expected soql');

		String sqlWithNoCustomFields = 'select Id, Name, LastModifiedDate from User';
		actualSql = COM_SoqlUtils.makeQualifiedQuery(sqlWithNoCustomFields);
		expectedSql = getExpectedSOQL('expectedSqlWithNoCustomFields');

		if(null == expectedSql){ // If this is null then this org is not a packaged or No NameSpace exist in this org
			expectedSql = sqlWithNoCustomFields;
		}

		System.assertEquals(expectedSql,actualSql,'Converted soql didn\'t match expected soql');

		String sqlWithRelationship = 'select id, Name, Subject__c, Status__c, Priority__c, Theme__r.Name, Scheduled_Build__r.Name, Sprint__r.Name, Sprint__c, Closed__c, Use_Prioritizer__c, RecordType.name from ADM_Work__c where Scrum_Team__c = :sprint.Scrum_Team__c and Sprint__c != :sprintID and Closed__c = 0 and Use_Prioritizer__c = true and RecordType.Name !=:ADM_Work.TEMPLATE_RECORD_TYPE_NAME order by Priority_Rank__c, Id  nulls first limit 1000';
		actualSql = COM_SoqlUtils.makeQualifiedQuery(sqlWithRelationship);
		
		expectedSql = getExpectedSOQL('expectedSqlWithRelationship');

		if(null == expectedSql){ // If this is null then this org is not a packaged or No NameSpace exist in this org
			expectedSql = sqlWithRelationship;
		}

		System.assertEquals(expectedSql,actualSql,'Converted soql didn\'t match expected soql');

		String sqlWithCustomFieldAndObjectNameContainingSameField = 'select Id, Name, Work__c, Task__c, LastModifiedDate from ADM_Deleted_Task__c';
		actualSql = COM_SoqlUtils.makeQualifiedQuery(sqlWithCustomFieldAndObjectNameContainingSameField);
		
		expectedSql = getExpectedSOQL('expecteSqlWithCustomFieldAndObjectNameContainingSameField');

		if(null == expectedSql){ // If this is null then this org is not a packaged or No NameSpace exist in this org
			expectedSql = sqlWithCustomFieldAndObjectNameContainingSameField;
		}

		System.assertEquals(expectedSql,actualSql,'Converted soql didn\'t match expected soql');
	}

	private static String getExpectedSOQL(String expectedQueryName){
		return expectedSOQLMap.get(expectedQueryName);
	}
	
}