mdapi-source/original-package/unpackaged/objects/ADM_Work_Status__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bug</fullName>
                </value>
                <value>
                    <fullName>User Story</fullName>
                </value>
                <value>
                    <fullName>Investigation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Work Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ADM_WorkStatusTest.cls
@isTest
public with sharing class ADM_WorkStatusTest {
	@isTest
	public static void testCreateOrUpdateAllWorkStatusrecords(){
		List<ADM_Work_Status__c> workStatusItems = [Select id from ADM_Work_Status__c ];
		delete workStatusItems;
		workStatusItems = [Select id from ADM_Work_Status__c ];
		System.assertEquals(0,workStatusItems.size(),'Initiall all work statuses are deleted.');
		Set<String> allStatuses = new Set<String>();
		allStatuses.addAll(ADM_Work.STATUS_VALUES_INVESTIGATION);
		allStatuses.addAll(ADM_Work.STATUS_VALUES_BUG);
		allStatuses.addAll(ADM_Work.STATUS_VALUES_USERSTORY);
		Integer totalRecordsExpected = allStatuses.size();
		ADM_WorkStatus.createOrUpdateAllWorkStatusRecords();
		workStatusItems = [Select id, Name, Type__c, Order__c from ADM_Work_Status__c order by Order__c];
		System.assertEquals(totalRecordsExpected,workStatusItems.size(),'Expected the total number to be equal to sum of statuses for the 3 work record types');
		ADM_Work_Status__c newStatus = [Select id, Name, Type__c, Order__c from ADM_Work_Status__c where Name = 'New' limit 1];
		System.assert(newStatus.Type__c.contains('Bug'));
		System.assert(newStatus.Type__c.contains('User Story'));
		System.assert(newStatus.Type__c.contains('Investigation'));
	}
}