mdapi-source/original-package/unpackaged/objects/ADM_Build__c.object
<CustomObject>
    <label>Build</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Builds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Scrum_Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Team_Release__c.object
<CustomObject>
    <description>Keep track of which teams are part of a release.</description>
    <fields>
        <fullName>Build__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Build</label>
        <referenceTo>ADM_Build__c</referenceTo>
        <relationshipLabel>Team Builds</relationshipLabel>
        <relationshipName>Team_Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scrum Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipName>Release_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team Release</label>
    <nameField>
        <displayFormat>RT-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/Release_Reports__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Release Reports</label>
</CustomObject>

force-app/main/default/classes/ADM_TeamReleaseExtension.cls
public with sharing class ADM_TeamReleaseExtension {
   
    public String reportResultsDebug { get; set; }
        
    // Controller extension used to help generate the release burndown charts on the team release detail page.
    @TestVisible
    private final ADM_Team_Release__c teamRelease;
    Release_Reports__c releaseReportsCustomSetting;
    
    public ADM_TeamReleaseExtension(ApexPages.StandardController stdController) {
        releaseReportsCustomSetting = Release_Reports__c.getInstance(UserInfo.getProfileId());
        this.teamRelease = [select id, Build__c, Build__r.name, Scrum_Team__r.name from ADM_Team_Release__c where id=:stdController.getRecord().ID limit 1];
        //Uncomment for debugging
        /* Reports.ReportDescribeResult descRes = Reports.ReportManager.describeReport('00Oo0000001wtxL');
        reportResultsDebug = JSON.serializePretty(descRes.getReportMetaData().getDetailColumns());
        //Reports.ReportResults results = Reports.ReportManager.runReport('00Oo0000001wtxJ');
        //reportResultsDebug = JSON.serializePretty(results); */
    }
    
    public String getPackageNameSpace() {
       ADM_ConstantsSingleton constants = ADM_ConstantsSingleton.getInstance();
       String namespace = constants.getNameSpace();
        if(namespace != null && namespace != '') {
            return namespace;
        } else {
            return '';
        }
         
    }
   
    public String getTeamReleaseId15() {
        String idString = teamRelease.ID;
        return ADM_TextUtils.oldSchoolSalesforceID(idString);
    }

    public String getBuildID15() {
        String idString = teamRelease.Build__c;
       return ADM_TextUtils.oldSchoolSalesforceID(idString);
    }
     
    public String getScrumTeamName() {
        return teamRelease.Scrum_Team__r.name;
    }
    
    public String getBuildName() {
        return teamRelease.Build__r.name;
    }
   
}