mdapi-source/original-package/unpackaged/objects/ADM_Change_List__c.object
<CustomObject>
    <description>Perforce change lists for checking in code changes.  Related to bugs and user stories.</description>
    <fields>
        <fullName>Changelist__c</fullName>
        <description>Link back to the changelist description</description>
        <formula>IF(ISPICKVAL(Source__c, &apos;Perforce&apos;), 



HYPERLINK( &quot;https://build.soma.salesforce.com/build/Perforce/describe?change=&quot; &amp; Perforce_Changelist__c, Perforce_Changelist__c), 



IF(ISPICKVAL(Source__c, &apos;&apos;), 



HYPERLINK( &quot;https://build.soma.salesforce.com/build/Perforce/describe?change=&quot; &amp; Perforce_Changelist__c, Perforce_Changelist__c), 



IF(ISPICKVAL(Source__c, &apos;GitHub&apos;),  HYPERLINK( &quot;https://github.com/&quot; &amp; Perforce_Changelist__c, &quot;github.com/&quot; &amp; Perforce_Changelist__c),


IF(ISPICKVAL(Source__c, &apos;Stash&apos;),  

HYPERLINK( &quot;https://stash.soma.salesforce.com/&quot; &amp; Perforce_Changelist__c, &quot;stash.soma.salesforce.com/&quot; &amp; Perforce_Changelist__c),


HYPERLINK(&quot;https://git.soma.salesforce.com/&quot; &amp; Perforce_Changelist__c, &quot;git.soma.salesforce.com/&quot; &amp; Perforce_Changelist__c)

)


)



)



)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Changelist Link</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipName>WorkChangeLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Change List</label>
    <nameField>
        <displayFormat>PF-{0000000}</displayFormat>
        <label>Changelist ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Perforce_Connector__c.object
<CustomObject>
    <fields>
        <fullName>Changelist__c</fullName>
        <label>Change List</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Describe__c</fullName>
        <label>Describe</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <label>Release</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work__c</fullName>
        <label>Work</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Source Control Connector</label>
    <nameField>
        <displayFormat>PC-{0000000000}</displayFormat>
        <label>Perforce Connector Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Source Control Connectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Release__c.object
<CustomObject>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Released_In__c.object
<CustomObject>
    <description>Object to define the releases that a fix was deployed to.  Each Work record has a one to many relationship with releases.</description>
    <fields>
        <fullName>Release__c</fullName>
        <label>Release</label>
        <referenceTo>ADM_Release__c</referenceTo>
        <relationshipName>Release</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Work__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work ID</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipName>WorkReleasedIn</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Released In</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Released In #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Released In</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Release</label>
        <referenceTo>ADM_Release__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/classes/ADM_PerforceConnectorCleanupTest.cls
@IsTest
public class ADM_PerforceConnectorCleanupTest {
	testMethod static void testTriggerInsert() {/*		         
        ADM_ChangelistDetailAccumulator cld = new ADM_ChangelistDetailAccumulator();
        ADM_ReleasedInDetailAccumulator rida = new ADM_ReleasedInDetailAccumulator();
        ADM_ReleaseDetailAccumulator rda = new ADM_ReleaseDetailAccumulator();
        */
        
        ADM_Perforce_Connector__c pc = new ADM_Perforce_Connector__c();
        List<ADM_Perforce_Connector__c> pcs = new List<ADM_Perforce_Connector__c>();
        ADM_Work__c work = ADM_Work.createTestWork();
        /*ADM_Release__c release = new ADM_Release__c(Name = System.now() + 'ATHF');        
        ADM_Released_In__c releasedIn;        
        List<ADM_Change_List__c> cls = new List<ADM_Change_List__c>();
        List<ADM_Release__c> releases = new List<ADM_Release__c>();
        List<ADM_Released_In__c> releasedIns = new List<ADM_Released_In__c>();        
		
		upsert release;		
		releases.add(release);
		*/
        String describe = '';
        describe = describe + '        Testing new ARS';
        describe = describe + '        https://tapp0.salesforce.com/' + work.Id;
        describe = describe + '        @rev jhatton@';
        describe = describe + '        @revert@';
        
        pc.Describe__c = 'Change: 921073\n\nDate:   2009/02/25 10:35:33\n\nClient: alwilliams-wsr\n\nUser:   alexis.williams\n\nStatus: pending\n\nDescription:\n' + describe;
        pc.Changelist__c = '921073';
        pc.Release__c = 'ATHF';     
        pc.Work__c = work.Id;   
        pcs.add(pc);
        /*cls.add(cld.getChangelist(pc.Describe__c, pc.Changelist__c, work.Id, pc.Release__c));
        releasedIns = rida.getReleasedIns(cls, rda.getReleaseMap(releases));*/
        
        
        Test.startTest();
        try{
        	Database.insert(pc);
        } catch (System.Nullpointerexception e) {
        	
        }        
        Test.stopTest();
	}
}