mdapi-source/original-package/unpackaged/objects/ADM_Build__c.object
<CustomObject>
    <label>Build</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Builds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Scrum_Team__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Product_Owner_For_Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Sprint__c.object
<CustomObject>
    <customHelpPage>ADM_CreateSprintOverview</customHelpPage>
    <description>Added to support User Story for Scrumforce integration into GUS.</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scrum Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Sprints</relationshipLabel>
        <relationshipName>Sprints</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Workdays__c</fullName>
        <label>Total Workdays</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Task__c.object
<CustomObject>
    <description>Created to import task data from SF</description>
    <fields>
        <fullName>Actual_Hours__c</fullName>
        <label>Actual Hours</label>
        <precision>5</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Completed_On__c</fullName>
        <label>Completed On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Hours_Remaining__c</fullName>
        <label>Hours Remaining</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Starting_Hours__c</fullName>
        <label>Starting Hours</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Waiting on someone else</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Work__c</fullName>
        <label>Work</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Theme__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Optional relationship with a scrum team so teams can organize their themes</description>
        <label>Scrum Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipName>Themes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Theme</label>
    <nameField>
        <label>Theme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Themes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Theme_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Theme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Theme</label>
        <referenceTo>ADM_Theme__c</referenceTo>
        <relationshipLabel>Theme Assignments</relationshipLabel>
        <relationshipName>Theme_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipLabel>Theme Assignments</relationshipLabel>
        <relationshipName>Theme_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Theme Assignment</label>
    <nameField>
        <displayFormat>THA-{0000}</displayFormat>
        <label>Theme Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Theme Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Closed_On__c</fullName>
        <label>Closed On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Epic__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Epic</label>
        <referenceTo>ADM_Epic__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority_Rank__c</fullName>
        <label>Backlog Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If you leave it empty on save you will be the Product Owner</inlineHelpText>
        <label>Product Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Product_Owner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QA_Engineer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>QA Engineer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QA_Engineer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scheduled_Build__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Scheduled Build field is a lookup to the Build object.  Enter a pre-existing build where the change will be made.</inlineHelpText>
        <label>Scheduled Build</label>
        <referenceTo>ADM_Build__c</referenceTo>
        <relationshipLabel>Work (Scheduled Build)</relationshipLabel>
        <relationshipName>Scheduled_Build</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sprint</label>
        <referenceTo>ADM_Sprint__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Triaged</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Investigating</fullName>
                </value>
                <value>
                    <fullName>Ready for Review</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>QA In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Defunct</fullName>
                </value>
                <value>
                    <fullName>Closed - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Closed - Eng Internal</fullName>
                </value>
                <value>
                    <fullName>Closed - Known Bug Exists</fullName>
                </value>
                <value>
                    <fullName>Closed - New Bug Logged</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Approved</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Denied</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved With Internal Tools</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved Without Code Change</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Working as Designed</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Feature Request</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Will Not Fix</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Pending Release</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>More Info Reqd from Support</fullName>
                </value>
                <value>
                    <fullName>Never</fullName>
                </value>
                <value>
                    <fullName>Not a bug</fullName>
                </value>
                <value>
                    <fullName>Not Reproducible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Story_Points__c</fullName>
        <inlineHelpText>If you leave it empty on save it will automatically assign the value from the TE activity selected.</inlineHelpText>
        <label>Story Points</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Theme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Theme-Deprecated</label>
        <referenceTo>ADM_Theme__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Use_Prioritizer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to determine whether or not a work record should be shown on the Work Prioritizer page</description>
        <inlineHelpText>Used to determine whether or not a work record should be shown on the Work Prioritizer page</inlineHelpText>
        <label>Include in Prioritize View</label>
        <type>Checkbox</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <recordTypes>
        <fullName>Bug</fullName>
        <active>true</active>
        <description>Used to track defects or problems</description>
        <label>Bug</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/classes/ADM_BacklogUtilityTest.cls
@isTest
private class ADM_BacklogUtilityTest {
    
    @isTest static void testGetMasterBacklog() {
        Set<String> additionalFields = new Set<String>();
        additionalFields.add('Epic__c');
        additionalFields.add('Scheduled_Build__c');
        List<ADM_Work__c> works = ADM_Work.createListOfWork(10, 'Bug', additionalFields);
        for(ADM_Work__c work : works) {
           work.Status__c = 'New';
           work.Use_Prioritizer__c = true;
           work.Priority_Rank__c = 1;
        }
        upsert works;
        
        //get the team of the work items
        works = [select Scrum_Team__c from ADM_Work__c where Id in :works];
        //Id teamId = getTeamId(works);
        
        Test.startTest();
        ADM_BacklogController.QueryParameters parameters = new ADM_BacklogController.QueryParameters();
        parameters.teamId = getTeamId(works);
        ADM_BacklogController.BackLogManagerResponse response = ADM_BacklogUtility.getPanelWorkItemsByType(parameters, 'backlog', false, 10, 0);
        Test.stopTest();
        
        System.assertEquals(10, response.numberOfRecords, 'Expected the number of records to be 10');
        System.assertEquals(10, response.records.size(), 'Expected all of the work items to be returned');
    }

    @isTest static void testGetBackburnerPanel() {
        Set<String> additionalFields = new Set<String>();
        additionalFields.add('Sprint__c');
        additionalFields.add('QA_Engineer__c');
        additionalFields.add('Product_Owner__c');
        List<ADM_Work__c> works = ADM_Work.createListOfWork(10, 'Bug', additionalFields);
        for(ADM_Work__c work : works) {
            work.Status__c = 'New';
            work.Use_Prioritizer__c = true;
            work.Priority_Rank__c = null;
        }
        upsert works;
        
        //get the team of the work items
        works = [select Scrum_Team__c from ADM_Work__c where Id in :works];

        ADM_BacklogController.QueryParameters parameters = new ADM_BacklogController.QueryParameters();
        parameters.teamId = getTeamId(works);
        
        ADM_BacklogController.BackLogManagerResponse response = ADM_BacklogUtility.getPanelWorkItemsByType(parameters, 'backburner', false, 10, 0);
        
        System.assertEquals(10, response.numberOfRecords, 'Expected the number of records to be 10');
        System.assertEquals(10, response.records.size(), 'Expected getBackburner to return all of the work items');
    }

    @isTest static void testGetFeatureBacklog() {
        List<ADM_Work__c> works = ADM_Work.createListOfWork(10, 'User Story');
        for(ADM_Work__c work : works) {
            work.Status__c = 'New';
            work.Use_Prioritizer__c = true;
            work.Priority_Rank__c = 1;
        }
        upsert works;
        
        //get the team of the work items
        works = [select Scrum_Team__c from ADM_Work__c where Id in :works];

        ADM_BacklogController.QueryParameters parameters = new ADM_BacklogController.QueryParameters();
        parameters.teamId = getTeamId(works);
        
        ADM_BacklogController.BackLogManagerResponse response = ADM_BacklogUtility.getPanelWorkItemsByType(parameters, 'featureBacklog', false, 10, 0);
        
        System.assertEquals(10, response.numberOfRecords, 'Expected the number of records to be 10');
        System.assertEquals(10, response.records.size(), 'Expected getBackburner to return all of the work items');
    }

    @isTest static void testGetTrustBacklog() {
        ADM_Theme__c trustTheme = ensureTrustTheme();
        
        List<ADM_Work__c> works = ADM_Work.createListOfWork(10, 'Bug');
        for(ADM_Work__c work : works) {
           work.Status__c = 'New';
           work.Use_Prioritizer__c = true;
           work.Priority_Rank__c = 1;
        }
        upsert works;
        works = [select Scrum_Team__c from ADM_Work__c where Id in :works];
        
        //create theme assignments for each work item relating to the theme
        List<ADM_Theme_Assignment__c> themeAssignments = new List<ADM_Theme_Assignment__c>();
        for(ADM_Work__c work : works) {
           ADM_Theme_Assignment__c themeAssignment = new ADM_Theme_Assignment__c();
           themeAssignment.Work__c = work.id;
           themeAssignment.Theme__c = trustTheme.id;
           themeAssignments.add(themeAssignment);
        }
        insert themeAssignments;
        
        //get the team of the work items

        ADM_BacklogController.QueryParameters parameters = new ADM_BacklogController.QueryParameters();
        parameters.teamId = getTeamId(works);
        
        Test.startTest();
        ADM_BacklogController.BackLogManagerResponse response = ADM_BacklogUtility.getPanelWorkItemsByType(parameters, 'trustBacklog', false, 10, 0);
        Test.stopTest();
        
        System.assertEquals(10, response.numberOfRecords, 'Expected the number of records to be 10');
        System.assertEquals(10, response.records.size(), 'Expected getTrustBacklog to return all of the work items');
    
    }

   /* @isTest static void testGetThemeBacklog() {
        ADM_Theme__c theme = new ADM_Theme__c();
        theme.Name = 'Test Theme';
        theme.Active__c = true;
        insert theme;
        
        List<ADM_Work__c> works = ADM_Work.createListOfWork(10, 'Bug');
        for(ADM_Work__c work : works) {
           work.Status__c = 'New';
           work.Use_Prioritizer__c = true;
           work.Priority_Rank__c = 1;
        }
        upsert works;
        
        List<ADM_Theme_Assignment__c> taList = new List<ADM_Theme_Assignment__c>();
        for(ADM_Work__c work : works) {
           //relate the themes to work records
           ADM_Theme_Assignment__c ta = new ADM_Theme_Assignment__c();
           ta.Work__c = work.id;
           ta.Theme__c = theme.id;
           taList.add(ta);
        }
        insert taList;
        
        //get the team of the work items
        works = [select Scrum_Team__c from ADM_Work__c where Id in :works];
        Id teamId = getTeamId(works);
        
        Test.startTest();
        ADM_BacklogController.BackLogManagerResponse response = ADM_BacklogUtility.getPanelWorkItemsByType(teamId, 'themeBacklog', false, 10, 0);
        Test.stopTest();
        
        System.assertEquals(10, response.numberOfRecords, 'Expected the number of records to be 10');
        System.assertEquals(10, response.records.size(), 'Expected getThemeBacklog to return all of the work items');
    
    }

    @isTest static void testGetScheduledBuildBacklog() {
        ADM_Build__c build = new ADM_Build__c();
        build.Name = 'Test Build';
        insert build;
        
        List<ADM_Work__c> works = ADM_Work.createListOfWork(10, 'Bug');
        for(ADM_Work__c work : works) {
           work.Status__c = 'New';
           work.Scheduled_Build__c = build.Id;
        }
        upsert works;
        
        //get the team of the work items
        works = [select Scrum_Team__c from ADM_Work__c where Id in :works];
        Id teamId = getTeamId(works);
        
        Test.startTest();
        ADM_BacklogController.BackLogManagerResponse response = ADM_BacklogUtility.getPanelWorkItemsByType(teamId, 'themeBacklog', false, 10, 0);
        Test.stopTest();
        
        System.assertEquals(10, response.numberOfRecords, 'Expected the number of records to be 10');
        System.assertEquals(10, response.records.size(), 'Expected getScheduledBuildBacklog to return all of the work items');
    
    }*/

    @isTest static void testGetDefaultBackLogColumns() {
        
        List<ADM_BacklogController.BackLogColumn> backlog_list = ADM_BacklogUtility.getDefaultBackLogColumns();
        System.assert( backlog_list.size() > 0 );
                
        // Let's assert a few items from the default list, not the entire set
        for ( ADM_BacklogController.BackLogColumn backlog_item : backlog_list  ){
            
            if ( backlog_item.value == 'work.Name' ){
                System.assert( backlog_item.showLabel == true );
                System.assert( backlog_item.required == true );
                System.assert( backlog_item.sortable == true );                
            }
            if ( backlog_item.value == 'work.Subject' ){
                System.assert( backlog_item.showLabel == true );
                System.assert( backlog_item.required == true );
                System.assert( backlog_item.sortable == true );
            }
            if ( backlog_item.value == 'work.Sprint__c' ){
                System.assert( backlog_item.showLabel == true );
                System.assert( backlog_item.required == true );
                System.assert( backlog_item.sortable == true );
            }
        }
    }

    @isTest static void testGetSprintChart() {

        ADM_Scrum_Team__c team = ADM_ScrumTeam.createTestScrumTeam();
        ADM_Sprint__c sprint = ADM_Sprint.createTestSprintForTeam(team);
        sprint.Start_Date__c = System.today();
        sprint.End_Date__c = System.today() + 15;
        sprint.Total_Workdays__c=12; 
        
        update sprint;
        
        ADM_Work__c story = ADM_Work.createTestWork('User Story');
        story.Sprint__c = sprint.Id;
        story.Story_Points__c = 3;
        // The fake the Sprint created above is pushed out 60 to 75 days (beginning and end)
        // So we'll leave the Closed Status__c commented out so the trtigger doesn't
        // override the pushing out the Closed date by 65 days
        // story.Status__c = 'Closed';
        story.Closed_On__c = Date.today().addDays(6);
        update story;
        
        List<ADM_Sprint__c> sprint_list = new List<ADM_Sprint__c>();
        sprint_list.add(sprint);
            
        new ADM_SprintBurnDownUtils().createSprintBurnDownIdeal( sprint_list );
        //List<ADM_Work__c> deets = [SELECT Closed_On__c, Status__c, Sprint__c from ADM_Work__c WHERE Sprint__c =:sprint.Id];

        ADM_Chart chart = ADM_BacklogUtility.getSprintChart( (String)sprint.Id );

        System.assertEquals('Day', chart.getXAxis().getTitle() );
        System.assertEquals('Story Points', chart.getYAxis().getTitle() );
        System.assertEquals('Burn Down', chart.title );        
        
        List<ADM_Chart.Series> series_list = chart.getSeriesList();
        System.assertEquals( 2 , series_list.size(), 'Expected only two series data points.');
       
        Boolean found_ideal = false;
        Boolean found_real = false;
        List<Object> ideal_objects = new List<Object>();
 		List<Object> real_objects = new List<Object>();

        for ( ADM_Chart.Series series_item : series_list ){
            if ( series_item.name == 'Real Burndown' ){
            	found_real = true;   
				real_objects = series_item.data;
            }
            if ( series_item.name == 'Ideal Burndown' ){
                found_ideal = true;
                ideal_objects = series_item.data;
            }
        }
        
        System.assert(found_ideal, 'The ideal series data was not available');
        System.assert(found_real, 'The real series data was not available');
        
        System.assert( 0 < real_objects.size() , 'The real object series list had zero entries.');
        System.assert( 0 < ideal_objects.size() , 'The ideal object series list had zero entries.');
        
        Boolean ideal_had_a_positive = false;
        Boolean real_had_a_positive = false;
        
        for ( Object o : ideal_objects ){
            if ( o instanceof Double ){
                Double d = (Double) o;
                System.assert( 0.0 <= d , 'The ideal series data wasn\'t a positive number ' + d);
                if ( 0.0 < d ) ideal_had_a_positive = true;
            }
        }

        for ( Object o : real_objects ){
            if ( o instanceof Double ){
                Double d = (Double) o;
                System.assert( 0.0 <= d , 'The real series data wasn\'t a positive number ' + d);
                if ( 0.0 < d ) real_had_a_positive = true;
            }
        }

        System.assert( ideal_had_a_positive , 'The ideal series data did not have a single positive number');
        System.assert( real_had_a_positive , 'The real series data did not have a single positive number');
        
    }

    @isTest static void testGetTaskHoursSprintChart() {
        ADM_Scrum_Team__c team = ADM_ScrumTeam.createTestScrumTeam();
        ADM_Sprint__c sprint = ADM_Sprint.createTestSprintForTeam(team);
        sprint.Start_Date__c = System.today();
        sprint.End_Date__c = System.today() + 15;
        sprint.Total_Workdays__c=12; 
        
        update sprint;
       
        ADM_Work__c story = ADM_Work.createTestWork('User Story');
        story.Sprint__c = sprint.Id;
        story.Story_Points__c = 3;
        story.Closed_On__c = Date.today().addDays(6);
        update story;

        ADM_Task__c task = new ADM_Task__c(Subject__c = 'Task1', Assigned_To__c = UserInfo.getUserId(), Actual_Hours__c = 10, Hours_Remaining__c = 10, Starting_Hours__c = 10, Work__c = story.id, Completed_On__c=Date.today().addDays(6));
        insert task;
       
        List<ADM_Sprint__c> sprint_list = new List<ADM_Sprint__c>();
        sprint_list.add(sprint);
            
        new ADM_SprintBurnDownUtils().createSprintBurnDownIdeal( sprint_list );

        ADM_Chart chart = ADM_BacklogUtility.getSprintChart( (String)sprint.Id, 'Task Hours');

        System.assertEquals('Day', chart.getXAxis().getTitle() );
        System.assertEquals('Task Hours', chart.getYAxis().getTitle() );
        System.assertEquals('Burn Down', chart.title );        
        
        List<ADM_Chart.Series> series_list = chart.getSeriesList();
        System.assertEquals( 2 , series_list.size(), 'Expected only two series data points.');
       
        Boolean found_ideal = false;
        Boolean found_real = false;
        List<Object> ideal_objects = new List<Object>();
        List<Object> real_objects = new List<Object>();

        for ( ADM_Chart.Series series_item : series_list ){
            if ( series_item.name == 'Real Burndown' ){
                found_real = true;   
                real_objects = series_item.data;
            }
            if ( series_item.name == 'Ideal Burndown' ){
                found_ideal = true;
                ideal_objects = series_item.data;
            }
        }
        
        System.assert(found_ideal, 'The ideal series data was not available');
        System.assert(found_real, 'The real series data was not available');
        
        System.assert( 0 < real_objects.size() , 'The real object series list had zero entries.');
        System.assert( 0 < ideal_objects.size() , 'The ideal object series list had zero entries.');
        
        Boolean ideal_had_a_positive = false;
        Boolean real_had_a_positive = false;
        
        for ( Object o : ideal_objects ){
            if ( o instanceof Double ){
                Double d = (Double) o;
                System.assert( 0.0 <= d , 'The ideal series data wasn\'t a positive number ' + d);
                if ( 0.0 < d ) ideal_had_a_positive = true;
            }
        }

        for ( Object o : real_objects ){
            if ( o instanceof Double ){
                Double d = (Double) o;
                System.assert( 0.0 <= d , 'The real series data wasn\'t a positive number ' + d);
                if ( 0.0 < d ) real_had_a_positive = true;
            }
        }

        System.assert( ideal_had_a_positive , 'The ideal series data did not have a single positive number');
        System.assert( real_had_a_positive , 'The real series data did not have a single positive number');
        
    }

    @isTest
    static void testBackLogControllerThrowsExceptionOnNullInput() {
        
        ADM_BacklogController.QueryParameters params = new ADM_BacklogController.QueryParameters();
        params.sprintId = '';
        
        ADM_BacklogUtility.SprintBacklogPanel panel = 
            new ADM_BacklogUtility.SprintBacklogPanel();        
        
        try {
            // Since we're only checking the params object, the other inputs can be bogus (i.e. nulls)
            panel.getWorkItems(params, null, 10, 10);
            System.assert(false,'An exception should be thrown here.');
        } catch (Exception e) {
            System.assertEquals('No sprintId was found in parameters.', e.getMessage());
        }
        
    }

    private static Id getTeamId(List<ADM_Work__c> works) {
        Id teamId = (works == null || works.isEmpty()) ? null : works.get(0).Scrum_Team__c;
        if(teamId == null) {
            throw new ADM_ApplicationException('Scrum_Team__c is null');
        }
        return teamId;
    }   

    private static ADM_Theme__c ensureTrustTheme() {
        ADM_Theme__c trustTheme = new ADM_Theme__c();
        trustTheme.Name = 'Trust';
        insert trustTheme;
        return trustTheme;
    }
}