mdapi-source/original-package/unpackaged/objects/ADM_Product_Tag__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipName>Product_Tags</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TE Activity</label>
    <nameField>
        <label>TE Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TE Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Scrum_Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Sprint__c.object
<CustomObject>
    <customHelpPage>ADM_CreateSprintOverview</customHelpPage>
    <description>Added to support User Story for Scrumforce integration into GUS.</description>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scrum Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Sprints</relationshipLabel>
        <relationshipName>Sprints</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Team_Release__c.object
<CustomObject>
    <description>Keep track of which teams are part of a release.</description>
    <fields>
        <fullName>Build__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Build</label>
        <referenceTo>ADM_Build__c</referenceTo>
        <relationshipLabel>Team Builds</relationshipLabel>
        <relationshipName>Team_Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scrum Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipName>Release_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team Release</label>
    <nameField>
        <displayFormat>RT-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Product_Tag__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TE Activity</label>
        <referenceTo>ADM_Product_Tag__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Product_Tag</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scheduled_Build__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Scheduled Build field is a lookup to the Build object.  Enter a pre-existing build where the change will be made.</inlineHelpText>
        <label>Scheduled Build</label>
        <referenceTo>ADM_Build__c</referenceTo>
        <relationshipLabel>Work (Scheduled Build)</relationshipLabel>
        <relationshipName>Scheduled_Build</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sprint</label>
        <referenceTo>ADM_Sprint__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/classes/ADM_TeamReleaseExtensionTest.cls
@IsTest
public class ADM_TeamReleaseExtensionTest {
    
    @IsTest
    static void testADM_TeamReleaseExtension() {

        Test.startTest();

        ADM_Sprint__c sprint = ADM_ReleaseBurndownUtils.createTestClosedSprint();
        List<ADM_Work__c> works = [select id, Product_Tag__c, Scheduled_Build__c, Scrum_Team__c from ADM_Work__c where Sprint__c =:sprint.id];
        String build = works[0].Scheduled_Build__c;
        ADM_Work__c work = works[0];
        
        //update the team of the Product Tag autocreated in setupTestWork() to match the team used on the team release record.  
        ADM_Product_Tag__c tag = [select id, Name from ADM_Product_Tag__c where id =:work.Product_Tag__c];
        tag.Team__c = sprint.Scrum_Team__c;
        update tag;
        //ensure scrum team is populated
        work.Scrum_Team__c = sprint.Scrum_Team__c;
        update work;
        
        //process release burn down
        ADM_ReleaseBurndownUtils.updateReleaseBurndownsBulk(new Set<Id>{sprint.id});
    
        Test.stopTest();
    
        //assert team release was created       
        List<ADM_Team_Release__c> teamReleases = [select id, Scrum_Team__c, Scrum_Team__r.Name, Build__c from ADM_Team_Release__c where Build__c = :build];
        
        System.assert(teamReleases != null);
        System.assertEquals(1, teamReleases.size(), 'Found unexpeted # of team releases for build:' + build);
        
        ADM_Team_Release__c tRelease = teamReleases[0];

        ApexPages.StandardController stdController = new ApexPages.StandardController(tRelease);
        ADM_TeamReleaseExtension controller = new ADM_TeamReleaseExtension(stdController);
        String releaseID = tRelease.id;
        String buildID = tRelease.Build__c;
        String scrumTeamID = tRelease.Scrum_Team__c;
        
        System.assert(controller != null);
        System.assertEquals(releaseID.substring(0, 15), controller.getTeamReleaseId15());
        System.assertEquals(buildID.substring(0, 15), controller.getBuildID15());
        System.assertEquals(tRelease.Scrum_Team__r.Name, controller.getScrumTeamName());

    }
   
}