mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>DateTime</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/classes/ADM_EmailSLACounterControllerTest.cls
@isTest
public class ADM_EmailSLACounterControllerTest {
    /*
     * DEPRECATED
     * 
	static testMethod void findWorkTest(){
         ADM_Work__c w1;
         ADM_Work__c w2;
            
         try{
         	DateTime expectedDateTime = DateTime.newInstance(2016, 12, 12,1,33,0);
            w1 = new ADM_Work__c();
            w1.Due_Date__c = expectedDateTime;
            w2 = new ADM_Work__c();
            w2.Due_Date__c = DateTime.now();
                        
            insert w1;
            insert w2;
            
            //Test here
            ADM_Work__c foundWork = ADM_EmailSLACounterController.findWork(w1.Name);
            System.assertEquals(expectedDateTime,foundWork.Due_Date__c,  'Search did not return the correct work item');
            
            //get rid of it
            delete w1;
            delete w2;
        }catch(Exception e){
            System.debug(e.getMessage());
        }
         
    }
*/
}