mdapi-source/original-package/unpackaged/objects/ADM_Scrum_Team__c.object
<CustomObject>
    <fields>
        <fullName>Capex_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This team can mark User Stories and Tasks as Capital Expenditures</description>
        <inlineHelpText>This team can mark User Stories and Tasks as Capital Expenditures</inlineHelpText>
        <label>Capitalizable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Sprint__c.object
<CustomObject>
    <customHelpPage>ADM_CreateSprintOverview</customHelpPage>
    <description>Added to support User Story for Scrumforce integration into GUS.</description>
    <fields>
        <fullName>Completed_Story_Points__c</fullName>
        <label>Velocity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Days_Remaining__c</fullName>
        <formula>IF( TODAY() &lt; Start_Date__c, &apos;NOT STARTED&apos;, IF( End_Date__c &gt;= TODAY(), TEXT( ROUND(End_Date__c - TODAY(), 0) + 1 ), &apos;CLOSED&apos; ) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days Remaining</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scrum Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Sprints</relationshipLabel>
        <relationshipName>Sprints</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Theme__c.object
<CustomObject>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Optional relationship with a scrum team so teams can organize their themes</description>
        <label>Scrum Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipName>Themes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Theme</label>
    <nameField>
        <label>Theme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Themes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If you leave this field empty on save you will be the Assignee.</inlineHelpText>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assignee</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Capex_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>New Customer Facing Feature</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Closed__c</fullName>
        <formula>CASE(  Status__c, &quot;Tested&quot;, 1, &quot;Closed&quot;, 1, &quot;Closed-Untested&quot;, 1, &quot;Closed-U/Ftest&quot;, 1, &quot;Completed&quot;, 1, &quot;Not Reproducible&quot;, 1, &quot;Never&quot;, 1, &quot;Not a bug&quot;, 1, &quot;Duplicate&quot;, 1, &quot;Closed - Duplicate&quot; , 1, &quot;Closed - Known Bug Exists&quot;, 1, &quot;Closed - New Bug Logged&quot;, 1, &quot;Closed - No Fix - Working as Designed&quot;,1, &quot;Closed - No Fix - Feature Request&quot;,1, &quot;Closed - No Fix - Will Not Fix&quot;,1, &quot;Closed - LAP Request Approved&quot;, 1, &quot;Closed - LAP Request Denied&quot;, 1, &quot;Closed - Resolved Without Code Change&quot;, 1, &quot;Rejected&quot;, 1, &quot;Closed - Resolved With Internal Tools&quot;, 1, &quot;Closed - Defunct&quot;,1,&quot;Closed - Doc/Usability&quot;,1,&quot;Closed - Resolved with DB Script&quot;,1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Closed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Created_By_import__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User imported from bugforce that created the original bug.</description>
        <label>Created By (import)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority_Rank__c</fullName>
        <label>Backlog Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>QA_Engineer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>QA Engineer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QA_Engineer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <formula>$RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type of Record(Deprecated)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scheduled_Build__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Scheduled Build field is a lookup to the Build object.  Enter a pre-existing build where the change will be made.</inlineHelpText>
        <label>Scheduled Build</label>
        <referenceTo>ADM_Build__c</referenceTo>
        <relationshipLabel>Work (Scheduled Build)</relationshipLabel>
        <relationshipName>Scheduled_Build</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sprint_Rank__c</fullName>
        <label>Rank of this work item in a sprint</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sprint</label>
        <referenceTo>ADM_Sprint__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Triaged</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Investigating</fullName>
                </value>
                <value>
                    <fullName>Ready for Review</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>QA In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Defunct</fullName>
                </value>
                <value>
                    <fullName>Closed - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Closed - Eng Internal</fullName>
                </value>
                <value>
                    <fullName>Closed - Known Bug Exists</fullName>
                </value>
                <value>
                    <fullName>Closed - New Bug Logged</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Approved</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Denied</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved With Internal Tools</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved Without Code Change</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Working as Designed</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Feature Request</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Will Not Fix</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Pending Release</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>More Info Reqd from Support</fullName>
                </value>
                <value>
                    <fullName>Never</fullName>
                </value>
                <value>
                    <fullName>Not a bug</fullName>
                </value>
                <value>
                    <fullName>Not Reproducible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Story_Points__c</fullName>
        <inlineHelpText>If you leave it empty on save it will automatically assign the value from the TE activity selected.</inlineHelpText>
        <label>Story Points</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Theme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Theme-Deprecated</label>
        <referenceTo>ADM_Theme__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work_Commitment__c.object
<CustomObject>
    <description>Work items committed to in a sprint</description>
    <fields>
        <fullName>Committed_Story_Points__c</fullName>
        <description>Number of story points assigned to work item when it was committed to in this sprint</description>
        <inlineHelpText>Number of story points assigned to work item when it was committed to in this sprint</inlineHelpText>
        <label>Committed Story Points</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sprint</label>
        <referenceTo>ADM_Sprint__c</referenceTo>
        <relationshipLabel>Work Commitments</relationshipLabel>
        <relationshipName>Work_Commitments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipLabel>Work Commitments</relationshipLabel>
        <relationshipName>Work_Commitments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work Commitment</label>
    <nameField>
        <displayFormat>WC-{0000000}</displayFormat>
        <label>Work Commitment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Commitments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ADM_ScopeChangeController.cls
public with sharing class ADM_ScopeChangeController {
    
    @AuraEnabled
    public static String getScopeChangeJSON(Id sprintId) {
        return JSON.serialize(getScopeChange(sprintId));
    }

    private static ScopeChange getScopeChange(Id sprintId) {
        Map<Id, ADM_Work__c> currentWorkInSprint = new Map<Id, ADM_Work__c>(ADM_Work.getWorksBySprint(sprintId));
        ADM_Work_Commitment__c[] commitments = [SELECT Committed_Story_Points__c, Work__c, Work__r.Assignee__c, Work__r.Assignee__r.Name, Work__r.Id, Work__r.Name, Work__r.Subject__c, Work__r.Status__c, Work__r.Story_Points__c, Work__r.Record_Type__c FROM ADM_Work_Commitment__c WHERE Sprint__c = :sprintId];
        ScopeChangeItem[] committedWork = new List<ScopeChangeItem>();
        ScopeChangeItem[] removedWork = new List<ScopeChangeItem>();
        Decimal committedWorkTotalPoints = 0;
        Decimal committedWorkCurrentPoints = 0;
        Decimal removedWorkTotalPoints = 0;
        Decimal removedWorkCurrentPoints = 0;
        Decimal addedWorkCurrentPoints = 0;

        for (ADM_Work_Commitment__c workCommitment : commitments) {
            ScopeChangeItem workItem = new ScopeChangeItem();
            Decimal committedStoryPoints = (workCommitment.Committed_Story_Points__c != null ? workCommitment.Committed_Story_Points__c : 0);
            
            if (workCommitment.Work__r.Story_Points__c == null) {
                workCommitment.Work__r.Story_Points__c = 0;
            }

            Decimal workStoryPoints = workCommitment.Work__r.Story_Points__c;
            
            workItem.work = workCommitment.Work__r;
            workItem.committedStoryPoints = committedStoryPoints;
            
            if (workStoryPoints != committedStoryPoints) {
                workItem.pointsDiffCssClass = 'adm-text-color_orange';
            }
            
            if (currentWorkInSprint.containsKey(workCommitment.Work__r.Id)) {
                committedWork.add(workItem);
                currentWorkInSprint.remove(workCommitment.Work__r.Id);
                committedWorkTotalPoints += committedStoryPoints;
                committedWorkCurrentPoints += workStoryPoints;
            } else {
                removedWork.add(workItem);
                currentWorkInSprint.remove(workCommitment.Work__r.Id);
                removedWorkTotalPoints += committedStoryPoints;
                removedWorkCurrentPoints += workStoryPoints;
            }
        }

        for (ADM_Work__c work : currentWorkInSprint.values()) {
            addedWorkCurrentPoints += (work.Story_Points__c != null ? work.Story_Points__c : 0);
        }

        ScopeChange scopeChange = new ScopeChange();

        scopeChange.committedWork.addAll(committedWork);
        scopeChange.addedWork.addAll(currentWorkInSprint.values());
        scopeChange.removedWork.addAll(removedWork);
        scopeChange.committedPoints = committedWorkTotalPoints;
        scopeChange.currentCommittedPoints = (committedWorkCurrentPoints != null ? committedWorkCurrentPoints : 0);
        scopeChange.removedPoints = removedWorkTotalPoints;
        scopeChange.currentRemovedPoints = (removedWorkCurrentPoints != null ? removedWorkCurrentPoints : 0);
        scopeChange.currentAddedPoints = addedWorkCurrentPoints;
        scopeChange.sprintData = getSprintData(sprintId);
        scopeChange.sprintCommitment = getSprintWorkCommitment(sprintId);
        
        return scopeChange;
    }
    

    private static ADM_SprintVirtualWallController.SprintData getSprintData(Id sprintId) {
        return ADM_SprintVirtualWallController.getSprintData(sprintId);
    }

    @AuraEnabled
    public static String getSprintJSON(Id sprintId) {
        return JSON.serialize(getSprintData(sprintId));
    }

    @AuraEnabled
    public static String setSprintWorkCommitment(String sprintId, Boolean defOfReady) {
        Integer existingCommitmentCount = [SELECT Count() FROM ADM_Work_Commitment__c WHERE Sprint__c = :sprintId];

        if (existingCommitmentCount == 0) {
            ADM_Work__c[] works = [SELECT Id, Name, Subject__c , Closed__c, Assignee__r.Id, Assignee__r.FirstName, Assignee__r.LastName, Assignee__r.Name, Assignee__r.SmallPhotoUrl, QA_Engineer__r.FirstName, QA_Engineer__r.Id, QA_Engineer__r.LastName, QA_Engineer__r.Name, QA_Engineer__r.SmallPhotoUrl, LastModifiedDate, LastModifiedById, Status__c, Sprint__c, Sprint__r.Start_Date__c, Sprint__r.End_Date__c, RecordType.Name, Theme__r.Name, Scheduled_Build__r.Name, Story_Points__c, Sprint_Rank__c, Capex_Enabled__c FROM ADM_Work__c WHERE Sprint__r.Id = :sprintId ORDER BY Sprint_Rank__c ASC NULLS LAST, Priority_Rank__c ASC NULLS LAST, CreatedDate ASC];
            ADM_Sprint__c sprint = [SELECT Id,Name,Scrum_Team__c,Completed_Story_Points__c,Days_Remaining__c,Definition_of_Ready_Met__c,Scrum_Team__r.Name,Scrum_Team__r.Story_Point_Scale__c,Scrum_Team__r.Capex_Enabled__c,Start_Date__c,End_Date__c FROM ADM_Sprint__c WHERE Id =: sprintId];
            ADM_Work_Commitment__c[] commitments = new List<ADM_Work_Commitment__c>();
            Decimal totalStoryPoints = 0;
            Integer workItemCount = 0;

            for (ADM_Work__c work : works) {
                ADM_Work_Commitment__c workCommitment = new ADM_Work_Commitment__c();

                workCommitment.Work__c = work.Id;
                workCommitment.Sprint__c = sprint.Id;
                workCommitment.Committed_Story_Points__c = work.Story_Points__c;

                totalStoryPoints += (work.Story_Points__c != null ? work.Story_Points__c : 0);
                workItemCount++;

                commitments.add(workCommitment);
            }
            
            if (sprint.Definition_of_Ready_Met__c != defOfReady) {
                sprint.Definition_of_Ready_Met__c = defOfReady;
            }

            sprint.Committed_Points__c = totalStoryPoints;
            sprint.Committed_Items__c = workItemCount;

            update sprint;

            Set<Id> sprintIds = new Set<Id>{sprint.Id};
            ADM_SprintBurnDownUtils.asyncCalculateVelocity(sprintIds);

            SprintCommitment sprintCommitment = new SprintCommitment();

            sprintCommitment.storyPoints = totalStoryPoints;
            sprintCommitment.numOfItems = workItemCount;

            insert commitments;

            return JSON.serialize(sprintCommitment);
        } else {
            throw new AuraHandledException(Label.ADM_Commitment_Exists_On_Sprint);
        }
    }

    public static Map<Id, ADM_Work_Commitment__c> getSprintWorkCommitmentMap(String sprintId) {
        Map<Id, ADM_Work_Commitment__c> commitmentMap = new Map<ID, ADM_Work_Commitment__c>([SELECT Committed_Story_Points__c, Work__r.RecordTypeId FROM ADM_Work_Commitment__c WHERE Sprint__c = :sprintId]);

        return commitmentMap;
    }

    public static SprintCommitment getSprintWorkCommitment(String sprintId) {
        List<ADM_Work_Commitment__c> commitments = getSprintWorkCommitmentMap(sprintId).values();
        List<ADM_Work__c> committedWork = new List<ADM_Work__c>();
        Decimal totalStoryPoints = 0;
        Integer workItemCount = 0;

        for (ADM_Work_Commitment__c workCommitment : commitments) {
            committedWork.add(workCommitment.Work__r);

            workItemCount++;

            totalStoryPoints += (workCommitment.Committed_Story_Points__c != null ? workCommitment.Committed_Story_Points__c : 0);
        }

        SprintCommitment commitment = new SprintCommitment();

        commitment.committedWork = committedWork;
        commitment.storyPoints = totalStoryPoints;
        commitment.numOfItems = workItemCount;

        return commitment;
    }

    public static List<Id> getWorkIdsCommittedToInSprint(String sprintId) {
        List<ADM_Work_Commitment__c> commitments = getSprintWorkCommitmentMap(sprintId).values();
        List<Id> commitmentWorkIds = new List<Id>();

        for (ADM_Work_Commitment__c workCommitment : commitments) {
            commitmentWorkIds.add(workCommitment.Work__c);
        }

        return commitmentWorkIds;
    }
    
    @AuraEnabled
    public static String getSprintWorkCommitmentJSON(String sprintId) {
        return JSON.serialize(getSprintWorkCommitment(sprintId));
    }

    public class ScopeChange {
        public ScopeChangeItem[] committedWork;
        public ADM_Work__c[] addedWork;
        public ScopeChangeItem[] removedWork;
        public Decimal committedPoints;
        public Decimal currentCommittedPoints;
        public Decimal removedPoints;
        public Decimal currentRemovedPoints;
        public Decimal currentAddedPoints;
        public ADM_SprintVirtualWallController.SprintData sprintData;
        public SprintCommitment sprintCommitment;

        public ScopeChange() {
            this.committedWork = new List<ScopeChangeItem>();
            this.addedWork = new List<ADM_Work__c>();
            this.removedWork = new List<ScopeChangeItem>();
        }
    }

    public class ScopeChangeItem {
        public ADM_Work__c work;
        public Decimal committedStoryPoints;
        public String pointsDiffCssClass;

        public ScopeChangeItem() {}
    }

    public class SprintCommitment {
        public Decimal storyPoints;
        public Integer numOfItems;
        public List<ADM_Work__c> committedWork;

        public SprintCommitment() {}
    }
}