mdapi-source/original-package/unpackaged/objects/ADM_Color__c.object
<CustomObject>
    <fields>
        <fullName>Color__c</fullName>
        <label>Color</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Color</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Color__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Color</label>
        <referenceTo>ADM_Color__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <recordTypes>
        <fullName>Bug</fullName>
        <active>true</active>
        <description>Used to track defects or problems</description>
        <label>Bug</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ADM_ColorTriggerTest.cls
@isTest
private class ADM_ColorTriggerTest {
	private 
	@isTest static void TestColorDeactivationRemovesColorFromWorkCard() {
		ADM_Work__c bug = ADM_Work.createTestBug();
		ADM_Color__c testColor = ADM_Color.createColor('Test', '#000000', bug.Scrum_Team__c, 1);

		insert testColor;

		bug.Color__c = testColor.Id;
		update bug;

		ADM_Work__c bugAfterUpdate = [Select Color__c from ADM_Work__c where id = :bug.Id];
		System.assert(null != bugAfterUpdate.Color__c);
		
		Database.delete(testColor);//Deleting color should remove it's reference from work objects.


		bugAfterUpdate = [Select Color__c from ADM_Work__c where id = :bug.Id];

		System.assertEquals(null, bugAfterUpdate.Color__c, 'Expected color__c reference to be deleted as color ' + testColor.Name + ' was deactivated');
	}
	
	
	
}