mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Comments will be added to the Work record and included in an email to the names listed in the Email Notifications section after saving. Formatting will also be preserved when saving via in line edit.</inlineHelpText>
        <label>Comment</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email_On_Save__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box to send an email to the users in the To: field when you save this record.</inlineHelpText>
        <label>Email On Save</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email_Subscription_ID__c</fullName>
        <inlineHelpText>Enter email aliases separated by spaces. These users are sent one email if the &quot;Email on Save&quot; check box is selected when you click &quot;Save.&quot; They do not automatically receive future updates.</inlineHelpText>
        <label>To</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Found_in_Build__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Found In Build field is a lookup to the Build object.  Enter the build where the bug was introduced.</inlineHelpText>
        <label>Found in Build</label>
        <referenceTo>ADM_Build__c</referenceTo>
        <relationshipLabel>Work (Found in Build)</relationshipLabel>
        <relationshipName>Found_in_Build</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Minor_Func_Area__c</fullName>
        <label>Minor Func Area</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_ID__c</fullName>
        <inlineHelpText>Add the GUS Work ID of any parent work item.  Separate multiple work IDs with commas.  View and edit the relationship via the related list.</inlineHelpText>
        <label>Add Parent ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority_Rank__c</fullName>
        <label>Backlog Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <inlineHelpText>For bugs, priority is automatically determined based upon the combination of Impact and Frequency.

For user stories, P0 represents the highest priority, P4 the lowest.</inlineHelpText>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>P0</fullName>
                    <color>#0B6FCE</color>
                    <label>P0</label>
                </value>
                <value>
                    <fullName>P1</fullName>
                    <color>#FF0000</color>
                    <label>P1</label>
                </value>
                <value>
                    <fullName>P2</fullName>
                    <color>#E27001</color>
                    <label>P2</label>
                </value>
                <value>
                    <fullName>P3</fullName>
                    <color>#FFFF66</color>
                    <label>P3</label>
                </value>
                <value>
                    <fullName>P4</fullName>
                    <color>#78C953</color>
                    <label>P4</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Related_URL__c</fullName>
        <label>Related URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scheduled_Build__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Scheduled Build field is a lookup to the Build object.  Enter a pre-existing build where the change will be made.</inlineHelpText>
        <label>Scheduled Build</label>
        <referenceTo>ADM_Build__c</referenceTo>
        <relationshipLabel>Work (Scheduled Build)</relationshipLabel>
        <relationshipName>Scheduled_Build</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sprint</label>
        <referenceTo>ADM_Sprint__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Triaged</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Investigating</fullName>
                </value>
                <value>
                    <fullName>Ready for Review</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>QA In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Defunct</fullName>
                </value>
                <value>
                    <fullName>Closed - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Closed - Eng Internal</fullName>
                </value>
                <value>
                    <fullName>Closed - Known Bug Exists</fullName>
                </value>
                <value>
                    <fullName>Closed - New Bug Logged</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Approved</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Denied</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved With Internal Tools</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved Without Code Change</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Working as Designed</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Feature Request</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Will Not Fix</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Pending Release</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>More Info Reqd from Support</fullName>
                </value>
                <value>
                    <fullName>Never</fullName>
                </value>
                <value>
                    <fullName>Not a bug</fullName>
                </value>
                <value>
                    <fullName>Not Reproducible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscribe_to_Work__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Subscribe to Work</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bug</fullName>
                </value>
                <value>
                    <fullName>Gack</fullName>
                </value>
                <value>
                    <fullName>Help</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Test Change</fullName>
                </value>
                <value>
                    <fullName>Test Case</fullName>
                </value>
                <value>
                    <fullName>Test Failure</fullName>
                </value>
                <value>
                    <fullName>Test Tool</fullName>
                </value>
                <value>
                    <fullName>Skunkforce</fullName>
                </value>
                <value>
                    <fullName>Bug List</fullName>
                </value>
                <value>
                    <fullName>Translation</fullName>
                </value>
                <value>
                    <fullName>Non Deterministic Test</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ftest__c</fullName>
        <inlineHelpText>Document the name of the automated test to prevent this bug happenning again.</inlineHelpText>
        <label>test</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <recordTypes>
        <fullName>Bug</fullName>
        <active>true</active>
        <description>Used to track defects or problems</description>
        <label>Bug</label>
    </recordTypes>
    <recordTypes>
        <fullName>Investigation</fullName>
        <active>true</active>
        <description>Used to request R&amp;D triage/diagnosis support for a customer support escalation</description>
        <label>Investigation</label>
    </recordTypes>
    <recordTypes>
        <fullName>Template</fullName>
        <active>true</active>
        <description>Used to store common values which can then be applied to new Bugs</description>
        <label>Template</label>
    </recordTypes>
    <recordTypes>
        <fullName>ToDo</fullName>
        <active>true</active>
        <description>Used to track a unit of work that does not need to have anything checked into Source Control nor does it need to have auto assignment rules applied</description>
        <label>ToDo</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ADM_WorkEditControllerTests.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class ADM_WorkEditControllerTests {
	
	private static ADM_WorkEditController getWorkEditController(ADM_Work__c work) {		
        Apexpages.Standardcontroller controller = new Apexpages.Standardcontroller(work);
        ADM_WorkEditController eController = new ADM_WorkEditController(controller);
        return eController;
	}

/*
* @testcaseID a1DB00000000l6w
* @userstoryID a07B0000000EAFe
* @Hierarchy GUS.BugforcetoGUS.Work.Bug Performance.New Page from URL
* @ExpecteResults The URL gets rendered correctly with no exceptions and all fields stated in the URL are filled in. Also the template shown in that of a Bug and the user gets the following error message: An error occurred getting the record type with the value provided over the URL, , resulting in the following error: List has no rows for assignment to SObject
* @Author: Alexis Williams
*/
    static testMethod void gotoEditDefaultPage() {        
        ADM_Work__c work = new ADM_Work__c();
        ADM_WorkEditController controller = getWorkEditController(work);
        System.assertEquals(true, controller.gotoEditPage().getUrl().contains('adm_workeditbug'));                        
    }

/*
* @testcaseID a1DB00000000l72
* @userstoryID a07B0000000EAFe
* @Hierarchy GUS.BugforcetoGUS.Work.User Story Performance.New Page
* @ExpecteResults The New user story page works normally when saving the user story
* @Author: Alexis Williams
*/
    static testMethod void gotoEditUserStoryPage() {        
        ADM_Work__c work = ADM_Work.createTestWork(ADM_Work.RECORD_TYPE_NAME_USERSTORY);
        ADM_WorkEditController controller = getWorkEditController(work);
        System.assertEquals(true, controller.gotoEditPage().getUrl().contains('adm_workedituserstory'));                        
    }

/*
* @testcaseID a1DB00000000l6r
* @userstoryID a07B0000000EAFe
* @Hierarchy GUS.BugforcetoGUS.Work.Bug Performance.New Page
* @ExpecteResults The New bug page works normally when saving the bug
* @Author: Alexis Williams
*/
    static testMethod void gotoEditBugPage() {        
        ADM_Work__c work = ADM_Work.createTestWork(ADM_Work.BUG_RECORD_TYPE_NAME);
        ADM_WorkEditController controller = getWorkEditController(work);
        System.assertEquals(true, controller.gotoEditPage().getUrl().contains('adm_workeditbug'));                        
    }

/*
* @testcaseID a1DB00000000l78
* @userstoryID a07B0000000EAFe
* @Hierarchy GUS.BugforcetoGUS.Work.ToDo Performance.New Page
* @ExpecteResults The New todo page works normally when saving 
* @Author: Alexis Williams
*/
    static testMethod void gotoEditTodoPage() {        
        ADM_Work__c work = ADM_Work.createTestWork(ADM_Work.RECORD_TYPE_NAME_TODO);
        ADM_WorkEditController controller = getWorkEditController(work);
        System.assertEquals(true, controller.gotoEditPage().getUrl().contains('adm_workedittodo'));                        
    }

/*
* @testcaseID a1DB00000000l79
* @userstoryID a07B0000000EAFe
* @Hierarchy GUS.BugforcetoGUS.Work.Investigation Performance.New Page
* @ExpecteResults The assignees from assignment rule derived from PA/MFA/Sev selection are added instantenously
* @Author: Alexis Williams
*/
    static testMethod void gotoEditInvestigationPage() {        
        ADM_Work__c work = ADM_Work.createTestWork(ADM_Work.RECORD_TYPE_NAME_INVESTIGATION);
        ADM_WorkEditController controller = getWorkEditController(work);
        System.assertEquals(true, controller.gotoEditPage().getUrl().contains('adm_workeditinvestigation'));                        
    }

/*
* @testcaseID a1DB00000000l77
* @userstoryID a07B0000000EAFe
* @Hierarchy GUS.BugforcetoGUS.Work.Template Performance.New Page
* @ExpecteResults All fields are cloned from template to a bug layout
* @Author: Alexis Williams
*/
    static testMethod void gotoEditTemplatePage() {        
        ADM_Work__c work = ADM_Work.createTestWork(ADM_Work.TEMPLATE_RECORD_TYPE_NAME);
        ADM_WorkEditController controller = getWorkEditController(work);
        System.assertEquals(true, controller.gotoEditPage().getUrl().contains('adm_workedittemplate'));                        
    }

/*
* @testcaseID a1DB00000000l7F
* @userstoryID a07B0000000EAFe
* @Hierarchy GUS.BugforcetoGUS.Work.Bug Performance.New Page from URL
* @ExpecteResults The URL gets rendered correctly with no exceptions and all fields stated in the URL are filled in
* @Author: Alexis Williams
*/
    static testMethod void testProperlyEscapingURLValues() {
        String testSubject = 'Lorrem Ipsum -+=?.,|}{%%&**ab[c]|^tt_(9)-@#<>';
        String encoded = EncodingUtil.urlEncode(testSubject, 'UTF-8');
        System.currentPageReference().getParameters().put('Subject__c', testSubject);        
        System.currentPageReference().getParameters().put('Description__c', testSubject);        
        System.currentPageReference().getParameters().put('Status__c', testSubject);        
        System.currentPageReference().getParameters().put('Type__c', testSubject);        
        System.currentPageReference().getParameters().put('Minor_Func_Area__c', testSubject);        
        System.currentPageReference().getParameters().put('Priority__c', testSubject);        
        System.currentPageReference().getParameters().put('Email_Subscription_ID__c', testSubject);        
        System.currentPageReference().getParameters().put('Related_URL__c', testSubject);        
        System.currentPageReference().getParameters().put('ftest__c', testSubject);        
        System.currentPageReference().getParameters().put('Subscribe_to_Work__c', '1');       
        System.currentPageReference().getParameters().put('Priority_Rank__c', testSubject); 
        System.currentPageReference().getParameters().put('Sprint__c', testSubject); 
        System.currentPageReference().getParameters().put('Scrum_Team__c', testSubject); 
        System.currentPageReference().getParameters().put('Email_On_Save__c', '1');
        System.currentPageReference().getParameters().put('Customer__c', testSubject);
        System.currentPageReference().getParameters().put('Parent_ID__c', testSubject);
        System.currentPageReference().getParameters().put('Scheduled_Build__c', testSubject);
        System.currentPageReference().getParameters().put('Found_In_Build__c', testSubject);
        System.currentPageReference().getParameters().put('Priority_Rank__c', testSubject);
        
        ADM_Work__c work = ADM_Work.createTestWork(ADM_Work.TEMPLATE_RECORD_TYPE_NAME);
        ADM_WorkEditController controller = getWorkEditController(work);
        
        System.assertEquals(encoded,controller.params.get('Subject__c'));
        System.assertEquals(encoded,controller.params.get('Description__c'));
        System.assertEquals(encoded,controller.params.get('Status__c'));
        System.assertEquals(encoded,controller.params.get('Type__c'));
        System.assertEquals(encoded,controller.params.get('Minor_Func_Area__c'));
        System.assertEquals(encoded,controller.params.get('Priority__c'));
        System.assertEquals(encoded,controller.params.get('Email_Subscription_ID__c'));
        System.assertEquals(encoded,controller.params.get('Related_URL__c'));
        System.assertEquals(encoded,controller.params.get('ftest__c'));
        System.assertEquals('1',controller.params.get('Subscribe_to_Work__c'));
        System.assertEquals(encoded,controller.params.get('Priority_Rank__c'));
        System.assertEquals(encoded,controller.params.get('Sprint__c'));
        System.assertEquals(encoded,controller.params.get('Scrum_Team__c'));
        System.assertEquals(encoded,controller.params.get('Scrum_Team__c'));
        System.assertEquals('1',controller.params.get('Email_On_Save__c'));
        System.assertEquals(encoded,controller.params.get('Customer__c'));
        System.assertEquals(encoded,controller.params.get('Parent_ID__c'));
        System.assertEquals(encoded,controller.params.get('Scheduled_Build__c'));
        System.assertEquals(encoded,controller.params.get('Found_In_Build__c'));
        System.assertEquals(encoded,controller.params.get('Priority_Rank__c'));
    }
}