mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>CS_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field defaults to the Investigation creator if the creator is in support (otherwise it defaults to blank). It can also be populated/overridden manually.</description>
        <inlineHelpText>This field defaults to the Investigation creator if the creator is in support (otherwise it defaults to blank). It can also be populated/overridden manually.</inlineHelpText>
        <label>Support Contact</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Work4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Triaged</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Investigating</fullName>
                </value>
                <value>
                    <fullName>Ready for Review</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>QA In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Defunct</fullName>
                </value>
                <value>
                    <fullName>Closed - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Closed - Eng Internal</fullName>
                </value>
                <value>
                    <fullName>Closed - Known Bug Exists</fullName>
                </value>
                <value>
                    <fullName>Closed - New Bug Logged</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Approved</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Denied</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved With Internal Tools</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved Without Code Change</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Working as Designed</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Feature Request</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Will Not Fix</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Pending Release</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>More Info Reqd from Support</fullName>
                </value>
                <value>
                    <fullName>Never</fullName>
                </value>
                <value>
                    <fullName>Not a bug</fullName>
                </value>
                <value>
                    <fullName>Not Reproducible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <recordTypes>
        <fullName>Investigation</fullName>
        <active>true</active>
        <description>Used to request R&amp;D triage/diagnosis support for a customer support escalation</description>
        <label>Investigation</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ADM_InvestigationExtension.cls
global with sharing class ADM_InvestigationExtension extends ADM_WorkCommonExtension {
    ADM_Work__C work;
    Id profileId;
    String profileName; 
    public ADM_InvestigationExtension(ApexPages.StandardController stdController) {
        super(stdController);
        work = getSelectedWork();
        setProfileName();
    }

    public Pagereference doSaveInvestigationAndNew(){      
        if(profileName.equalsIgnoreCase('gus customer support user') && getIsNew() == true && ADM_TextUtils.isBlank(work.CS_Contact__c)) {
            setCSContactDefault(work);
        }
        return doSaveAndNew();
     }

    public Pagereference doSaveInvestigationAndDetail(){
        if(profileName.equalsIgnoreCase('gus customer support user') && getIsNew() == true && ADM_TextUtils.isBlank(work.CS_Contact__c)) {
            setCSContactDefault(work);
        }
        return doSaveAndDetail();
    }

    private void setCSContactDefault(ADM_Work__c work){
        work.CS_Contact__c = UserInfo.getUserId();
    }

    public PageReference doClone() {
        PageReference pr;
        boolean isSFXPagePreferred = ADM_ConstantsSingleton.getInstance().getUserLightningExperiencePreferred();
        if(isSFXPagePreferred){
            pr = Page.ADM_InvestigationEditSds;           
        }
        else{
             pr = Page.ADM_InvestigationEdit;
        }
        pr.setRedirect(true);
        pr.getParameters().put('id', getSelectedWork().Id);
        pr.getParameters().put('clone','1');
        pr.getParameters().put('retURL','/' + getSelectedWork().Id);
        return pr;
    }

    private void setProfileName(){
        profileId = UserInfo.getProfileId();
        profileName = [Select Name from Profile where Id =: profileId limit 1 ].Name;
    }

    protected override void setDefaultValues(ADM_Work__c work) {
        super.setDefaultValues(work); 
        //set the default properties for an Investigation
        try{
            setProfileName();
            if(this.profileName.equalsIgnoreCase('gus customer support user') && getIsNew() == true){
                work.CS_Contact__c = Userinfo.getUserId();
            }
        }
        catch(Exception e){
            System.debug('Exception fetching profile Id and Name and setting Support Contact for Investigation : '+ e);
        }
    }
    
    /** Investigation SLA Monitoring - Returns true if SLA Due Time is in the past */
    public Boolean getIsSLAOverdue() {
        return work.Due_Date__c!=null && (System.now().getTime() > work.Due_Date__c.getTime());
    }
    
    /** Investigation SLA Monitoring - Returns the field label to display for the time remaining until SLA is violated */
    public String getSLACountdownLabel() {
        String msg = '';
        try{
            if (work.Due_Date__c != null) {
            
                if (work.Status__c == 'New') {
                    msg = 'Acknowledgement Due';
                } else if (work.Status__c == 'More Info Reqd from Support') {
                    msg = 'Update Due From Support';
                } else {
                    msg = 'Update Due From T&P';
                }
            }
        }
        catch(Exception e){
            System.debug('iSLA Exception in getting SLA count down label for Investigation : ' + e);
        }
        
        return msg;
    }
    
    public String getSLACountdownLabelStyle() {
        String style = '';
        try{
            if (work.Due_Date__c != null) {
                Long diffHours = (work.Due_Date__c.getTime() - System.now().getTime()) / (60 * 60 * 1000);
                if (diffHours < 1) {
                    style = 'color:red';
                }
            }
        }
        catch(Exception e){
            System.debug('iSLA Exception in getting SLA count down label style for Investigation : ' + e);
        }
        
        return style;
    }
    
    public String getSLACountdownStyle() {
        String style = '';
        try{
            if (work.Due_Date__c != null) {
                Long diffHours = (work.Due_Date__c.getTime() - System.now().getTime()) / (60 * 60 * 1000);
                if (diffHours < 1) {
                    style = 'color:red';
                } else if (diffHours < 4) {
                    style = 'color:darkorange';
                } else {
                    style = 'color:green';
                }
            }
        }
        catch(Exception e){
            System.debug('iSLA Exception in getting SLA count down style for Investigation : ' + e);
        }
        
        return style;
    }
    
    /** Investigation SLA Monitoring - Returns the diff between now and the SLA Due Time (absolute value) */
    public String getSLADueTimeDiff() {
        String msg = '';
        try {
            if (work.Due_Date__c != null) {
                Long diffMilliseconds = Math.abs(work.Due_Date__c.getTime() - System.now().getTime());
                Long diffMinutes = diffMilliseconds / (60 * 1000);
                
                Long minutesPart = Math.mod(diffMinutes, 60);
                Long hoursPart = Math.mod(diffMinutes/60, 24);
                Long daysPart = diffMinutes / (24 * 60);
            
                if (getIsSLAOverdue()) {
                    msg = 'Overdue by ';
                } else {
                    msg = 'In ';
                }
            
                if (daysPart > 0) {
                    msg += daysPart;
                    msg += (daysPart > 1) ? ' Days ' : ' Day ';
                }
                if (hoursPart > 0) {
                    msg += hoursPart;
                    msg += (hoursPart > 1) ? ' Hours ' : ' Hour ';
                }
                if (minutesPart > 0) {
                    msg += minutesPart;
                    msg += (minutesPart > 1) ? ' Minutes ' : ' Minute ';
                }
            }
        }
        catch(Exception e){
            System.debug('iSLA Exception in getting SLA due time diff for Investigation : ' + e);
        }
               
        return msg;
    }
}