mdapi-source/original-package/unpackaged/objects/ADM_Comment__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Comment</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Preserve_Formatting__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to decide if we are going to surround our comment body with a &quot;PRE&quot; tag</description>
        <label>Preserve Formatting</label>
        <type>Checkbox</type>
    </fields>
    <label>Comment</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000}</displayFormat>
        <label>Story Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Comments will be added to the Work record and included in an email to the names listed in the Email Notifications section after saving. Formatting will also be preserved when saving via in line edit.</inlineHelpText>
        <label>Comment</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Preserve_Formatting__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Preserve Formatting</label>
        <type>Checkbox</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ADM_WorkCommentsControllerTests.cls
@isTest
private class ADM_WorkCommentsControllerTests{

	static testMethod void testGetComments() {
        ADM_WorkCommentsController controller = new ADM_WorkCommentsController();
        ADM_Work__c work = ADM_Work.createTestBug();
        controller.work = work;
        work.Description__c = 'test';
        work.Preserve_Formatting__c = true;
        Test.startTest();
        update work;
        Test.stopTest();
        ADM_Comment__c[] comments = controller.getComments();
        ADM_Comment__c comment = comments[0];
        System.assertEquals(1, comments.size());
        System.assert(comment.Body__c.contains('test'));
        
	}

}