mdapi-source/original-package/unpackaged/objects/ADM_Scrum_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Member_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Scrum_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Analyst</fullName>
                </value>
                <value>
                    <fullName>Architect</fullName>
                </value>
                <value>
                    <fullName>BSA</fullName>
                </value>
                <value>
                    <fullName>Business Owner</fullName>
                </value>
                <value>
                    <fullName>Capacity Planner</fullName>
                </value>
                <value>
                    <fullName>Data Center Engineer</fullName>
                </value>
                <value>
                    <fullName>DBA</fullName>
                </value>
                <value>
                    <fullName>Developer</fullName>
                </value>
                <value>
                    <fullName>Dev Manager</fullName>
                </value>
                <value>
                    <fullName>Doc Editor</fullName>
                </value>
                <value>
                    <fullName>Doc Manager</fullName>
                </value>
                <value>
                    <fullName>Engineering Manager</fullName>
                </value>
                <value>
                    <fullName>Network Engineer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Performance Engineer</fullName>
                </value>
                <value>
                    <fullName>Product Owner</fullName>
                </value>
                <value>
                    <fullName>Program Manager</fullName>
                </value>
                <value>
                    <fullName>Provisioning Specialist / Asset Manager</fullName>
                </value>
                <value>
                    <fullName>QA Engineer</fullName>
                </value>
                <value>
                    <fullName>QA Manager</fullName>
                </value>
                <value>
                    <fullName>Release Engineer</fullName>
                </value>
                <value>
                    <fullName>Release Manager</fullName>
                </value>
                <value>
                    <fullName>Scrum Master</fullName>
                </value>
                <value>
                    <fullName>Security Engineer</fullName>
                </value>
                <value>
                    <fullName>Site Reliability Engineer</fullName>
                </value>
                <value>
                    <fullName>Software Engineer</fullName>
                </value>
                <value>
                    <fullName>SysAdmin</fullName>
                </value>
                <value>
                    <fullName>SysAdmin Linux</fullName>
                </value>
                <value>
                    <fullName>SysAdmin Storage</fullName>
                </value>
                <value>
                    <fullName>SysAdmin Win</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>Scrum_Team_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <displayFormat>STM-{00000}</displayFormat>
        <label>Team Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Team_Dependency__c.object
<CustomObject>
    <description>Used to track dependencies between teams for a given  release</description>
    <fields>
        <fullName>Deliver_By__c</fullName>
        <inlineHelpText>If the deliverable is needed by a specific date, indicate that in this field.</inlineHelpText>
        <label>Needed by (date)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deliverable__c</fullName>
        <description>Short description of the work that is needed from the other team.</description>
        <inlineHelpText>Short description (255 chars max) of the work that is needed from the other team. More detailed description can be added to the Notes field.</inlineHelpText>
        <label>Deliverable</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dependency_Status__c</fullName>
        <inlineHelpText>The status of this dependency.

Prioritized = Deliverable has a user story and is prioritized on the backlog.

Committed = Team is confident the work can be done in the needed timeframe and PO committed to maintaining the priority of the deliverable.</inlineHelpText>
        <label>Dependency Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>More Info Needed</fullName>
                </value>
                <value>
                    <fullName>Prioritized</fullName>
                </value>
                <value>
                    <fullName>Committed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Never</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dependent_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The team that is dependent on another team to provide the deliverable.</description>
        <inlineHelpText>The team that is dependent on another team to provide the deliverable.</inlineHelpText>
        <label>Team With Dependency</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Team With Dependency you selected is not active.</errorMessage>
            <filterItems>
                <field>ADM_Scrum_Team__c.Active__c</field>
                <operation>notEqual</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Dependencies we have on other teams</relationshipLabel>
        <relationshipName>Our_Dependencies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The team that will provide the deliverable to fulfill this dependency.</description>
        <inlineHelpText>The team that will provide the deliverable to fulfill this dependency.</inlineHelpText>
        <label>Team Providing Deliverable</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Team Providing Deliverable you selected is not active.</errorMessage>
            <filterItems>
                <field>ADM_Scrum_Team__c.Active__c</field>
                <operation>notEqual</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Dependencies other teams have on us</relationshipLabel>
        <relationshipName>Dependencies_on_us</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The record representing the work to satisfy the deliverable of this dependency.</description>
        <inlineHelpText>The record representing the work to satisfy the deliverable of this dependency.</inlineHelpText>
        <label>Work For Deliverable</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipLabel>Team Dependencies on this work</relationshipLabel>
        <relationshipName>Team_Dependencies_On_Story</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Build__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The build in which you would like the deliverable completed.</description>
        <inlineHelpText>The build in which you would like the deliverable completed. If the deliverable is not associated with a specific build, enter the major product release corresponding to the season in which this deliverable is needed (e.g. 162 - Winter &apos;10).</inlineHelpText>
        <label>Target Build</label>
        <referenceTo>ADM_Build__c</referenceTo>
        <relationshipLabel>Team Dependencies</relationshipLabel>
        <relationshipName>Team_Dependencies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team Dependency</label>
    <nameField>
        <displayFormat>TD-{0000000}</displayFormat>
        <label>Team Dependency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Dependencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Triaged</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Investigating</fullName>
                </value>
                <value>
                    <fullName>Ready for Review</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>QA In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Defunct</fullName>
                </value>
                <value>
                    <fullName>Closed - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Closed - Eng Internal</fullName>
                </value>
                <value>
                    <fullName>Closed - Known Bug Exists</fullName>
                </value>
                <value>
                    <fullName>Closed - New Bug Logged</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Approved</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Denied</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved With Internal Tools</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved Without Code Change</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Working as Designed</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Feature Request</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Will Not Fix</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Pending Release</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>More Info Reqd from Support</fullName>
                </value>
                <value>
                    <fullName>Never</fullName>
                </value>
                <value>
                    <fullName>Not a bug</fullName>
                </value>
                <value>
                    <fullName>Not Reproducible</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_Build__c</fullName>
        <label>Target Build</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ADM_TeamDependencyUtils.cls
public with sharing class ADM_TeamDependencyUtils {
    public static final Map<String, ADM_FieldWrapper> TEAM_DEPENDENCY_MAP = new Map<String, ADM_FieldWrapper>{'Provider_User_Story__c' => new ADM_FieldWrapper('Provider User Story'), 'Deliver_By__c' => new ADM_FieldWrapper('Needed By Date'), 'Dependency_Status__c' => new ADM_FieldWrapper('Dependency Status'),'Target_Build__c' => new ADM_FieldWrapper('Target Build')};    
    
    public static List<String> getSObjectChange(SObject elOld, SObject elNew, String elFieldName, String elFieldLabel, List<String> changes) {
        String fieldValueOld;
        String fieldValueNew;
        Map<String,String> changeTypes = new Map<String,String>();
        String messageAdded;
        String messageRemoved;
        String messageChanged;
        
        if(elOld != null && elNew != null) {
            fieldValueOld = String.valueOf(elOld.get(elFieldName));
            fieldValueNew = String.valueOf(elNew.get(elFieldName));
            
            
            try{
                Id idOld = fieldValueOld;
                Id idNew = fieldValueNew;
                changeTypes.put('messageAdded', elFieldLabel + ' has been added');
                changeTypes.put('messageRemoved', elFieldLabel + ' has been removed');
                changeTypes.put('messageChanged', elFieldLabel + ' has been changed');
            } catch(System.Exception e) {
                try{
                    fieldValueOld = date.valueOf(fieldValueOld).format();
                } catch(System.Exception ex) {
                    System.debug(ex);
                }
                
                try{
                    fieldValueNew = date.valueOf(fieldValueNew).format();
                } catch(System.Exception ex) {
                    System.debug(ex);
                }   
                
                changeTypes.put('messageAdded',elFieldLabel + ', ' + fieldValueNew + ', added');
                changeTypes.put('messageRemoved',elFieldLabel + ', ' + fieldValueOld + ', removed');
                changeTypes.put('messageChanged',elFieldLabel + ' changed from ' + fieldValueOld + ' to ' + fieldValueNew); 
            }
                
            if(fieldValueNew != fieldValueOld) {
                if(fieldValueNew == null && fieldValueOld != null) {
                    changes.add(changeTypes.get('messageRemoved'));
                } else if(fieldValueNew != null && fieldValueOld == null) {
                    changes.add(changeTypes.get('messageAdded'));
                } else {
                    changes.add(changeTypes.get('messageChanged'));
                }
            }
        }
        return changes;
    }
    public static void asyncSendUserStoryUpdateMessage(Set<Id> workUpdatedSprintOrBuild) {
        List<Set<String>> listOfEmailAddySets = new List<Set<String>>();
        List<String> listOfPlainMessages = new List<String>();
        List<String> listOfHtmlMessages = new List<String>();
        ADM_TextUtils textUtils = new ADM_TextUtils();
        User currentUser = [Select Email,Name from User where id = :UserInfo.getUserId() limit 1];
        
        if(!workUpdatedSprintOrBuild.isEmpty()) {
            ADM_Team_Dependency__c[] effectedTeamDependencies = [
                select id, provider_user_story__c, dependent_team__r.name,dependent_team__r.id, provider_team__r.name,provider_team__r.id, deliverable__c 
                from ADM_Team_Dependency__c 
                where provider_user_story__c in :workUpdatedSprintOrBuild and dependency_status__c not in ('Completed','Deferred','Never')];
            Set<Id> scrumTeamIds = new Set<Id>();
            for(ADM_Team_Dependency__c td:effectedTeamDependencies) {
                scrumTeamIds.add(td.dependent_team__r.id);
                scrumTeamIds.add(td.provider_team__r.id); 
            }
            
            ADM_Scrum_Team_Member__c[] peopleToEmail = [
                select member_name__r.email, scrum_team__c 
                from ADM_Scrum_Team_Member__c 
                where scrum_team__c in :scrumTeamIds and role__c in ('Product Owner', 'Scrum Master', 'Program Manager')];
            
            for (ADM_Team_Dependency__c td : effectedTeamDependencies) {
                Set<String> emailAddySet = new Set<String>();
                for(ADM_Scrum_Team_Member__c stm:peopleToEmail) {
                    if (stm.Scrum_Team__c == td.dependent_team__r.id || stm.scrum_team__c == td.provider_team__r.id)
                        emailAddySet.add(stm.member_name__r.email); 
                }
                listOfEmailAddySets.add(emailAddySet);
                
                String htmlMessage = 'The scheduled sprint or release has changed for the <a href=' + ADM_WorkUtils.GUS_URL + '/'+
                    td.provider_user_story__c+'> user story </a> to satisfy the <a href=' + ADM_WorkUtils.GUS_URL + '/'+
                    td.Id+'> the dependency</a> of the ' + 
                    textUtils.escapeHTML(td.dependent_team__r.name + ' team on the ' + td.provider_team__r.name + ' team to deliver "' + td.deliverable__c) + '".<p>';
                listOfHtmlMessages.add(htmlMessage);
                
                String plainMessage = 'The scheduled sprint or release has changed for this user story (' + ADM_WorkUtils.GUS_URL + '/'+
                    td.provider_user_story__c+') to satisfy this dependency (' + ADM_WorkUtils.GUS_URL + '/'+
                    td.Id+') of the '+td.dependent_team__r.name+' team on the '+ td.provider_team__r.name + 
                    ' team to deliver '+ td.deliverable__c + '.';
                listOfPlainMessages.add(plainMessage);
            }
            
            
            
            
            
            
            
            ADM_WorkEmail.sendSimpleBulkEmailForTeamDependency(currentUser.Email, 'Dependency User Story modified', currentUser.Name,listOfEmailAddySets,listOfPlainMessages,listOfHtmlMessages);
        }
    }

    public static void updateTeamDependenciesBasedOnWorkStatus(Map<String,ADM_Work__c> workIdToObjectMap){
        try {
            List<ADM_Team_Dependency__c> teamDependenciesToUpdate = new List<ADM_Team_Dependency__c>();
            if(workIdToObjectMap != null && !workIdToObjectMap.isEmpty()){
                ADM_Team_Dependency__c[] deps = [select id, dependency_status__c, Provider_User_Story__c from ADM_Team_Dependency__c where provider_user_story__c in :workIdToObjectMap.keySet()];
                System.debug(' found '+deps);
                for(ADM_Team_Dependency__c tdIter: deps){
                    ADM_Work__c workFromMap = workIdToObjectMap.get(tdIter.Provider_User_Story__c);
                    if(workFromMap.Status__c == 'Never'){
                        tdIter.Dependency_Status__c = 'Never';
                    }
                    else if(workFromMap.Closed__c == 1){
                        tdIter.Dependency_Status__c = 'Completed';
                    }
                    else if(workFromMap.Closed__c == 0){
                        tdIter.Dependency_Status__c = 'New';
                    }
                    teamDependenciesToUpdate.add(tdIter);
                }

                if(teamDependenciesToUpdate.size() > 0){
                    update teamDependenciesToUpdate;
                }
            }
        }
        catch(Exception e) {
            System.debug(e);    
        }


    }
    
   public static void closeTeamDependencies(Set<Id> closedUserStories) {
        try {
            if(!closedUserStories.isEmpty()) {
                ADM_Team_Dependency__c[] deps = [select id, dependency_status__c from ADM_Team_Dependency__c where provider_user_story__c in :closedUserStories];
                for(ADM_Team_Dependency__c d:deps) {
                    d.dependency_status__c = 'Completed';   
                }
                update deps;
            }
        } catch(Exception e) {
            System.debug(e);    
        }
    }

    public static void openTeamDependencies(Set<Id> openedUserStories) {
        try {
            if(!openedUserStories.isEmpty()) {
                ADM_Team_Dependency__c[] deps = [select id, dependency_status__c from ADM_Team_Dependency__c where provider_user_story__c in :openedUserStories];
                for(ADM_Team_Dependency__c d:deps) {
                    d.dependency_status__c = 'New'; 
                }
                update deps;
            }
        } catch(Exception e) {
            System.debug(e);    
        }           
    }

}