mdapi-source/original-package/unpackaged/objects/ADM_Build__c.object
<CustomObject>
    <label>Build</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Builds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Release__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Deployed - Other Issues</fullName>
                </value>
                <value>
                    <fullName>Deployed Successfully</fullName>
                </value>
                <value>
                    <fullName>Deployment in Progress</fullName>
                </value>
                <value>
                    <fullName>Deployment Introduced Regression</fullName>
                </value>
                <value>
                    <fullName>In Development</fullName>
                    <default>true</default>
                    <label>In Development</label>
                </value>
                <value>
                    <fullName>Partial Deployment - Halted</fullName>
                </value>
                <value>
                    <fullName>Partial Deployment - Superseded</fullName>
                </value>
                <value>
                    <fullName>Partial Rollback</fullName>
                </value>
                <value>
                    <fullName>Ready for Deployment</fullName>
                </value>
                <value>
                    <fullName>Redeployed After Rollback</fullName>
                </value>
                <value>
                    <fullName>Rollback</fullName>
                </value>
                <value>
                    <fullName>Deployed - Exceeded Release Window</fullName>
                </value>
                <value>
                    <fullName>Deployed - Date Changed</fullName>
                </value>
                <value>
                    <fullName>Canceled or Never Released</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Released_In__c.object
<CustomObject>
    <description>Object to define the releases that a fix was deployed to.  Each Work record has a one to many relationship with releases.</description>
    <fields>
        <fullName>Release__c</fullName>
        <label>Release</label>
        <referenceTo>ADM_Release__c</referenceTo>
        <relationshipName>Release</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reverted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reverted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stamped_On__c</fullName>
        <description>Date/time that the release stamp was stamped.</description>
        <label>Stamped On</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work ID</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipName>WorkReleasedIn</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Released In</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Released In #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Released In</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Priority__c</fullName>
        <inlineHelpText>For bugs, priority is automatically determined based upon the combination of Impact and Frequency.

For user stories, P0 represents the highest priority, P4 the lowest.</inlineHelpText>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>P0</fullName>
                    <color>#0B6FCE</color>
                    <label>P0</label>
                </value>
                <value>
                    <fullName>P1</fullName>
                    <color>#FF0000</color>
                    <label>P1</label>
                </value>
                <value>
                    <fullName>P2</fullName>
                    <color>#E27001</color>
                    <label>P2</label>
                </value>
                <value>
                    <fullName>P3</fullName>
                    <color>#FFFF66</color>
                    <label>P3</label>
                </value>
                <value>
                    <fullName>P4</fullName>
                    <color>#78C953</color>
                    <label>P4</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Release</label>
        <referenceTo>ADM_Release__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scheduled_Build__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Scheduled Build field is a lookup to the Build object.  Enter a pre-existing build where the change will be made.</inlineHelpText>
        <label>Scheduled Build</label>
        <referenceTo>ADM_Build__c</referenceTo>
        <relationshipLabel>Work (Scheduled Build)</relationshipLabel>
        <relationshipName>Scheduled_Build</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Triaged</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Investigating</fullName>
                </value>
                <value>
                    <fullName>Ready for Review</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>QA In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Defunct</fullName>
                </value>
                <value>
                    <fullName>Closed - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Closed - Eng Internal</fullName>
                </value>
                <value>
                    <fullName>Closed - Known Bug Exists</fullName>
                </value>
                <value>
                    <fullName>Closed - New Bug Logged</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Approved</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Denied</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved With Internal Tools</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved Without Code Change</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Working as Designed</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Feature Request</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Will Not Fix</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Pending Release</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>More Info Reqd from Support</fullName>
                </value>
                <value>
                    <fullName>Never</fullName>
                </value>
                <value>
                    <fullName>Not a bug</fullName>
                </value>
                <value>
                    <fullName>Not Reproducible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <recordTypes>
        <fullName>Bug</fullName>
        <active>true</active>
        <description>Used to track defects or problems</description>
        <label>Bug</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/classes/ADM_SetStandardControllerHelper.cls
public with sharing class ADM_SetStandardControllerHelper {
    List<String> selectedRecordTypes;
    List<String> selectedPriorities;
    List<String> selectedStatuses;
    List<String> selectedScheduledBuilds;
    String releaseId;
    public String query { get; set;}
    public String queryOriginal { get; set; }

    public ADM_SetStandardControllerHelper(String releaseId, List<String> selectedRecordTypes, List<String> selectedPriorities, List<String> selectedStatuses, List<String> selectedScheduledBuilds) {
       this.releaseId = releaseId;
       this.selectedPriorities = selectedPriorities;
       this.selectedRecordTypes = selectedRecordTypes;
       this.selectedScheduledBuilds = selectedScheduledBuilds;
       this.selectedStatuses = selectedStatuses;

       String FIELD_NAMES = 'Work__r.RecordType.Name, Work__r.Id, Work__r.Subject__c, Work__r.Priority__c, Work__r.Status__c, Work__r.Scheduled_Build__c, Work__r.Scheduled_Build__r.Name, Work__r.Name, Work__c, CreatedDate, Reverted__c, Release__r.Name, Release__c, Stamped_On__c';
       String TABLE = 'ADM_Released_In__c';
       String WHERE_CLAUSE = ' where Release__c = \'' + String.escapeSingleQuotes(releaseId) + '\'';
       String ORDER_BY = 'order by Work__r.Name, CreatedDate';
       String query = '';

       this.queryOriginal = 'select ' + FIELD_NAMES + ' from ' + TABLE + WHERE_CLAUSE + ORDER_BY + ' limit 10000';

       WHERE_CLAUSE += arrayToString('Work__r.RecordType.Name', selectedRecordTypes);
       WHERE_CLAUSE += arrayToString('Work__r.Priority__c', selectedPriorities);
       WHERE_CLAUSE += arrayToString('Work__r.Status__c', selectedStatuses);
       WHERE_CLAUSE += arrayToString('Work__r.Scheduled_Build__r.Name', selectedScheduledBuilds);

       this.query = 'select ' + FIELD_NAMES + ' from ' + TABLE + WHERE_CLAUSE + ORDER_BY + ' limit 10000';
    }

    public Apexpages.Standardsetcontroller getSetController() {
        return getSetController(20);
    }

    public Apexpages.Standardsetcontroller getSetController(Integer i) {
        Apexpages.Standardsetcontroller setCon = new ApexPages.StandardSetController(Database.getQueryLocator(query));
        setCon.setPageSize(i);
        return setCon;
    }

    private String arrayToString(String column, List<String> els) {
        String returnVar = '';

        for(String el : els){
            returnVar = returnVar + '\'' + String.escapeSingleQuotes(el.trim()) + '\''  + ',';
        }
        
        if(returnVar.endsWith(',')) {
            returnVar = returnVar.substring(0, returnVar.length() - 1);
        }

        if(returnVar.length() > 0) {
            returnVar = ' and ' + column + ' in ('+ returnVar + ')';
        }

        return returnVar;
    }
    
    static testMethod void testQuery() {
    	ADM_Release__c release = new ADM_Release__c();
        release.Name = 'Test Release';
        insert release;
        
        List<String> recordTypes = new List<String>{'Bug'};
        List<String> priorities = new List<String>{'P0'};
        List<String> statuses = new List<String>{'New'};
        List<String> scheduledBuilds = new List<String>{'Test Build'};
    	
    	ADM_SetStandardControllerHelper helper = new ADM_SetStandardControllerHelper(release.Id, recordTypes, priorities, statuses, scheduledBuilds);
    	
    	System.assert(helper.query != null, 'Expected the query property to not be null');
        System.assert(helper.queryOriginal != null, 'Expected the queryOriginal property to not be null');
        System.assert(helper.getSetController() != null, 'Expected the getSetController method to not return null');
    }
}