mdapi-source/original-package/unpackaged/objects/ADM_Column__c.object
<CustomObject>
    <description>Used to store meta data for a team&apos;s kanban board</description>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Columns</relationshipLabel>
        <relationshipName>Columns</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Column</label>
    <nameField>
        <label>Column Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Columns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Column_History__c.object
<CustomObject>
    <fields>
        <fullName>Column__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Column</label>
        <referenceTo>ADM_Column__c</referenceTo>
        <relationshipLabel>Column History</relationshipLabel>
        <relationshipName>Column_History</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time_Entered__c</fullName>
        <defaultValue>Now()</defaultValue>
        <description>The timestamp for when a work record enters a column</description>
        <label>Time Entered</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Time_Left__c</fullName>
        <description>The time stamp for when a work record left a column (and be empty if the work record is still present).</description>
        <label>Time Left</label>
        <type>DateTime</type>
    </fields>
    <label>Column History</label>
    <nameField>
        <displayFormat>CH-{0000000000}</displayFormat>
        <label>Column History ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Column History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Product_Tag__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipName>Product_Tags</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TE Activity</label>
    <nameField>
        <label>TE Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TE Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Scrum_Team__c.object
<CustomObject>
    <fields>
        <fullName>Kanban__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Kanban</label>
        <type>Checkbox</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Column__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Column</label>
        <referenceTo>ADM_Column__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Tag__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TE Activity</label>
        <referenceTo>ADM_Product_Tag__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Product_Tag</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ADM_ColumnHistoryTest.cls
@isTest
public with sharing class ADM_ColumnHistoryTest {

    static testMethod void testColumnHistoryIsNullAfterUpdatingProductTag() {

        // Create a test team and make sure kanban is enabled
        ADM_Scrum_Team__c team = ADM_ScrumTeam.createTestScrumTeam();
        team.Kanban__c = true;
        update team;

        // Create a test user story 
        ADM_Work__c story = ADM_Work.createTestWork('User Story');

        // Grab a Kanban column and update the story with a column
        List<ADM_Column__c> columns = [select id, Name from ADM_Column__c where Team__c =:team.id];
        ADM_Column__c column1 = columns[2];
        story.Column__c = column1.id;
        String column_id = column1.id;
        update story;

        // Kanban column should be non null
        System.assert( story.Column__c  != null );

        List<String> workIds = new List<String> { story.Id };
        List<ADM_Column_History__c> column_history = ADM_ColumnHistory.getColumnHistoryRecordsForListOfWorkIds( workIds );
        
        System.assert( column_history.size() == 1 , 'There are no column history entries');
        for ( ADM_Column_History__c history : column_history ){
            System.assert( history.Time_Entered__c != null, 'The time entered field for the history column was not populated.');
            System.assert( history.Time_Left__c == null , 'The time left field for the history column populated, but supposed to be null.');
            System.assert( history.Column__c != null , 'The column ID field for the history column was not populated.');            
        }

        // Now let's reassign to a different team, by updating the product tag
        ADM_Product_Tag__c productTag = ADM_ProductTag.createAndInsertProductTag();
        story.Product_Tag__c = productTag.Id;
        update story;

        List<ADM_Column_History__c> column_history_after_update = ADM_ColumnHistory.getColumnHistoryRecordsForListOfWorkIds( workIds );

        System.assert( column_history_after_update.size() == 1 , 'There are no column history entries');
        for ( ADM_Column_History__c history : column_history_after_update ){
            System.assert( history.Time_Left__c != null, 'The time left field for the history column was populated, but supposed to be null.');
        }

        // Retrive the the work item from the data 
        List<ADM_Work__c> story_list = [select id, Name,Column__c from ADM_Work__c where Id =:story.id];

        System.assertEquals( null, story_list[0].Column__c, ' The work items kanban column was not set '
                            + ' to null after changing the work item\'s product tag' );
                
    }

    static testMethod void testItemsCreatedOnKanbanBoardHaveAHistoryColumn() {
           
        // Create a test team and make sure kanban is enabled
        ADM_Scrum_Team__c team = ADM_ScrumTeam.createTestScrumTeam();
        team.Kanban__c = true;
        update team;
        
        // Grab the newly created columns
        List<ADM_Column__c> columns = [select id, Name from ADM_Column__c where Team__c =:team.id];
        System.assert( columns.size() > 0 );
        
        
        // Create a story object, but don't insert until we add a column to it
        ADM_Work__c story = ADM_Work.setupTestWork('User Story');        
        story.Column__c = columns.get(0).Id;
        insert story;
        List<Id> lists = new List<Id>();
        lists.add(story.Id);
        
        // Query and assert
        List<ADM_Column_History__c> columnHistoryRecords = ADM_ColumnHistory.getColumnHistoryRecordsForListOfWorkIds(lists);
        System.assertEquals( 1 , columnHistoryRecords.size() );
        
    }

}