mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Priority_Rank__c</fullName>
        <label>Backlog Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Use_Prioritizer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to determine whether or not a work record should be shown on the Work Prioritizer page</description>
        <inlineHelpText>Used to determine whether or not a work record should be shown on the Work Prioritizer page</inlineHelpText>
        <label>Include in Prioritize View</label>
        <type>Checkbox</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/classes/ADM_PlannerBacklogListControllerTests.cls
@isTest
public with sharing class ADM_PlannerBacklogListControllerTests {

	static testMethod void testGetBacklogItems() {

		Test.startTest();

		// Create a list of test work items
		List<ADM_Work__c> workItems = ADM_Work.createListOfWork(4, ADM_Work.RECORD_TYPE_NAME_USERSTORY);

		integer rank = 1;

		// Make sure the backlog rank is set and use prioritizer flag is on
		for (ADM_Work__c item : workItems) {
			item.Priority_Rank__c = rank++;
			item.Use_Prioritizer__c = true;
		}

		// Insert the test records
		Database.SaveResult[] dsr = Database.insert(workItems, true);

		for (Database.SaveResult sr : dsr) {
			System.assert(sr.isSuccess(), 'Unexpected error writing test work: ' + sr.getErrors());
		}

		// Pull the scrum team ID from the inserted records -- safe to use first one
		// as the createListOfWork() method sets them all to the same scrum team
		List<ADM_Work__c> firstItem = [select Scrum_Team__c from ADM_Work__c where Id = :workItems.get(0).Id limit 1];
		Id scrumTeamId = firstItem.get(0).Scrum_Team__c;

		ADM_PlannerBacklogListController controller = new ADM_PlannerBacklogListController();
		controller.setScrumTeamId(scrumTeamId);

		List<ADM_Work__c> backlogItems = controller.getBacklogItems;

		Test.stopTest();

		System.assert(backlogItems.size() > 0, 'Expected backlogItems size to be > 0');

		System.assert(backlogItems.size() == workItems.size(), 'Expected workItems and backlogItems to have the same number of items');

		Set<Id> expectedIds = new Set<Id>();
		Set<Id> actualIds = new Set<Id>();

		// Create sets of the expected IDs and the actual Ids, and make sure the actual
		// set contains the expected set
		for (ADM_Work__c item : workItems) {
			expectedIds.add(item.Id);
		}

		for (ADM_Work__c item : backlogItems) {
			actualIds.add(item.Id);
		}

		System.assert(actualIds.containsAll(expectedIds));

	}
}