mdapi-source/original-package/unpackaged/objects/ADM_Acceptance_Criterion__c.object
<CustomObject>
    <fields>
        <fullName>Work__c</fullName>
        <label>Work</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipLabel>Acceptance Criteria</relationshipLabel>
        <relationshipName>Acceptance_Criteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Acceptance Criterion</label>
    <nameField>
        <label>Acceptance Criterion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Acceptance Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Case__c.object
<CustomObject>
    <fields>
        <fullName>Work__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipName>Work62OrgCases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>62 Org Case</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Related Case ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>62 Org Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Change_List__c.object
<CustomObject>
    <description>Perforce change lists for checking in code changes.  Related to bugs and user stories.</description>
    <fields>
        <fullName>Work__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipName>WorkChangeLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Change List</label>
    <nameField>
        <displayFormat>PF-{0000000}</displayFormat>
        <label>Changelist ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Comment__c.object
<CustomObject>
    <fields>
        <fullName>Posted_to_Chatter__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field tracks if the comment has been posted to chatter. This field is used to tell if we need to display legacy comments, for more info see dependent story: W-1756310</description>
        <label>Posted to Chatter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Work__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipLabel>Comments</relationshipLabel>
        <relationshipName>Comment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Comment</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000}</displayFormat>
        <label>Story Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Investigation_Exception__c.object
<CustomObject>
    <fields>
        <fullName>Investigation__c</fullName>
        <label>Investigation</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipName>Investigation_Exceptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person who created the exception. Value entered automatically upon saving the record.</description>
        <inlineHelpText>Person who created the exception. Value entered automatically upon saving the record.</inlineHelpText>
        <label>Requestor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Investigation_Exceptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Exception Request</label>
    <nameField>
        <displayFormat>IE-{00000}</displayFormat>
        <label>Investigation Exception Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Parent_Work__c.object
<CustomObject>
    <fields>
        <fullName>Child_Work__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Child Work</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipLabel>Parent Work Records</relationshipLabel>
        <relationshipName>Child_Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Work__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Work</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipLabel>Child Work Records</relationshipLabel>
        <relationshipName>Parent_Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Related Work</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Parent Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Works</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Released_In__c.object
<CustomObject>
    <description>Object to define the releases that a fix was deployed to.  Each Work record has a one to many relationship with releases.</description>
    <fields>
        <fullName>Work__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work ID</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipName>WorkReleasedIn</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Released In</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Released In #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Released In</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Task__c.object
<CustomObject>
    <description>Created to import task data from SF</description>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work__c</fullName>
        <label>Work</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Team_Dependency__c.object
<CustomObject>
    <description>Used to track dependencies between teams for a given  release</description>
    <fields>
        <fullName>Dependent_User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The work that is dependent on the completion of the specified deliverable.</description>
        <inlineHelpText>The work that is dependent on the completion of  the specified deliverable.</inlineHelpText>
        <label>Work With Dependency</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipLabel>Team Dependencies needed for this work</relationshipLabel>
        <relationshipName>Team_Dependencies_For_Story</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The record representing the work to satisfy the deliverable of this dependency.</description>
        <inlineHelpText>The record representing the work to satisfy the deliverable of this dependency.</inlineHelpText>
        <label>Work For Deliverable</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipLabel>Team Dependencies on this work</relationshipLabel>
        <relationshipName>Team_Dependencies_On_Story</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team Dependency</label>
    <nameField>
        <displayFormat>TD-{0000000}</displayFormat>
        <label>Team Dependency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Dependencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Theme_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Work__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipLabel>Theme Assignments</relationshipLabel>
        <relationshipName>Theme_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Theme Assignment</label>
    <nameField>
        <displayFormat>THA-{0000}</displayFormat>
        <label>Theme Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Theme Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>ADM_Work__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A connection to the Agile Accelerator Work object used to track Bugs, Investigations and User Stories</description>
        <label>Work</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>AgileAcceleratorCases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/eRelease_Request__c.object
<CustomObject>
    <fields>
        <fullName>Bug_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup from eRelease to Bugs</description>
        <inlineHelpText>Specify the Bug (Work record) that needs to be fixed by the requested eRelease. If there are multiple bugs, file multiple eRelease Requests.</inlineHelpText>
        <label>Bug ID</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipLabel>eRelease Requests</relationshipLabel>
        <relationshipName>eRelease_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Who_is_verifying_fix_in_prod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Specify who will be verifying the bug in production following the deployment of this fix.</inlineHelpText>
        <label>Who is verifying fix in prod?</label>
        <referenceTo>User</referenceTo>
        <relationshipName>eRelease_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>eRelease Request</label>
    <nameField>
        <displayFormat>ERR-{00000}</displayFormat>
        <label>eRelease Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eRelease Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/SLA_Violation__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Investigation Assignee at the time the SLA Violation was logged</description>
        <inlineHelpText>Investigation Assignee, or Support Contact, at the time the SLA violation occurred</inlineHelpText>
        <label>SLA Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SLA_Violations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work__c</fullName>
        <label>Work</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ADM_Work__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Investigation</value>
            </filterItems>
            <infoMessage>Related Work record must be an Investigation</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipLabel>SLA Violations</relationshipLabel>
        <relationshipName>SLA_Violations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SLA Violation</label>
    <nameField>
        <displayFormat>SLA-{000000}</displayFormat>
        <label>SLA Violation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SLA Violations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ADM_WorkTabPanelExtension.cls
public with sharing class ADM_WorkTabPanelExtension{
    private Boolean showComments = true;
    private transient Boolean tabPanelViewPreference = null;
    public Boolean hasGrandChildren {get;set;}
    ADM_ConstantsSingleton signletonConstants = ADM_ConstantsSingleton.getInstance();

    
    Map<String, Integer> relatedListRecordCount {get;set;} 
    public ADM_WorkTabPanelExtension(ApexPages.StandardController controller) {
         
        //Don't proceed if work id is not present
            
        ID workid = controller.getId();
        String workKeyPrefix = ADM_Work__c.sObjectType.getDescribe().getKeyPrefix();
        if(workid == null || !((String) workid).startsWith(workKeyPrefix)) {
            throw new ADM_ApplicationException('Expected a valid Work Id in the URL');
        }
        try {
           
            relatedListRecordCount = new Map<String, Integer>();
            setRelatedListRecordCount(workid);
            if (!ADM_TextUtils.isBlank(workid)) {
                Integer commentCount = [select count() from ADM_Comment__c where Posted_to_Chatter__c != True and Work__c =:workid limit 1];
                    if (commentCount > 0) {
                        showComments = true;
                        return;
                    }
            }
            
        } catch(System.Exception e) {
             System.debug('Unexpected exception fetching old comments for tab panel:' + e + ', line ' + e.getLineNumber());
        }
        showComments = false;
    }

    public Boolean packagedOrg{
        get{
          return signletonConstants.isPackagedOrg();
        }
        set;
       
    }

    public void setRelatedListRecordCount(Id workid){    
        
        List<ADM_Parent_Work__c> relatedWorkList = new List<ADM_Parent_Work__c> ();
        hasGrandChildren = false;
        ADM_Work__c work = [SELECT id, name, (select id from ADM_Work__c.WorkChangeLists__r),(select id from ADM_Work__c.eRelease_Requests__r),
        (select id from ADM_Work__c.Theme_Assignments__r),(select id from ADM_Work__c.workReleasedIn__r),(select id from ADM_Work__c.Acceptance_Criteria__r),
        (select id from ADM_Work__c.Work62OrgCases__r),(select id from ADM_Work__c.Tasks__r),(select id from Attachments),
        (select id from Investigation_Exceptions__r),(select id from Notes), (select id from Team_Dependencies_On_Story__r),
        (select id from Team_Dependencies_For_Story__r),(select id from SLA_Violations__r)  from ADM_Work__c  where id =: workid];
        
        //Added the query seperately because there are some records without parent and child ids in production
        Integer relatedRecordsCount = [select count() from ADM_Parent_Work__c where Child_Work__c != '' and Parent_Work__c != '' and (Child_Work__c =: workid or Parent_Work__c =: workid)];
        //Query child work records to check for grandchildren
        relatedWorkList = [Select Child_Work__c from ADM_Parent_Work__c where Child_Work__c != '' and Parent_Work__c != '' and Parent_Work__c =: workid];
        
        //Get workids and add them to a list
        List<Id> parentWorkIds = new List<Id>();
        for(ADM_Parent_Work__c parentWork :relatedWorkList){
            parentWorkIds.add(parentWork.Child_Work__c);
        }
        //Check if these work records are parent work of other work items
        List<ADM_Parent_Work__c> grandChildren = [Select id from ADM_Parent_Work__c where Parent_Work__c in : parentWorkIds];
        //if size is greater than 0 then they have other child records.
        if(grandChildren.size() > 0)
            hasGrandChildren = true;
        Integer googleDocCount = 0;
        //we can't assume the org has Google Apps turned on
        try{
            String query = 'select count() from GoogleDoc where parentId =: workid';
            
            googleDocCount = Database.countQuery(query);
        } catch(Exception e){
            System.debug('Exception getting Google Docs, most likely Google Apps is not enabled e: ' + e + ', line '+ e.getLineNumber());
        }
        
        //seperately calculate case count because it differs based on the package
        Integer relatedCaseCount = 0;
        try {
          //The relationship between work and cases differs between GUS and Agile Accelerator
          List<Case> cases = new List<Case>();
          if(packagedOrg) {
             String workRecordID = work.id; 
             cases = Database.query('select Id from Case where ADM_Work__c=:workRecordID order by CreatedDate');
          } else {
            String workName = work.Name;
            System.debug('work from standard controller:' + work);  
            cases = Database.query('select Id from Case where SM_Bug__c=:workName');
          }
          relatedCaseCount = cases.size() + work.Work62OrgCases__r.size(); 
          System.debug('relatedCaseCount:' + relatedCaseCount); 
       } catch(Exception e) {
           System.debug('setRelatedListRecordCount() Exception calculating case count e:' + e);
       } 
        
        relatedListRecordCount.put('themes',work.Theme_Assignments__r.size());
        relatedListRecordCount.put('attachments',work.Attachments.size()+work.Notes.size()+googleDocCount);
        relatedListRecordCount.put('exceptionRequests',work.Investigation_Exceptions__r.size());
        relatedListRecordCount.put('tasks',work.Tasks__r.size());
        relatedListRecordCount.put('workChangeLists',work.WorkChangeLists__r.size());
        relatedListRecordCount.put('workReleasedIn',work.workReleasedIn__r.size());
        relatedListRecordCount.put('eRelease_Requests',work.eRelease_Requests__r.size());
        relatedListRecordCount.put('sla_Violations',work.SLA_Violations__r.size());
        relatedListRecordCount.put('acceptanceCriterion',work.Acceptance_Criteria__r.size()); 
        relatedListRecordCount.put('related',relatedRecordsCount);   
        relatedListRecordCount.put('teamDependencies',work.Team_Dependencies_On_Story__r.size()+work.Team_Dependencies_For_Story__r.size());
        relatedListRecordCount.put('workAllCases',relatedCaseCount); 
        System.debug('relatedListRecordCount:' + relatedListRecordCount);
       
    }

    public Map<String, Integer> getRelatedListRecordCount(){
        return relatedListRecordCount;
    }
    
    public Boolean getOldCommentsTab() {
        return showComments;
    }

    // Indicates how to show the tab panel
    public Boolean getTabPanelViewPreference() {
        try {
            if(this.tabPanelViewPreference == null) {
                ADM_User_Preferences__c preferences = ADM_User_Preferences__c.getInstance(UserInfo.getUserId());
                this.tabPanelViewPreference = preferences.TabPanelViewPreference__c;
            }
            return this.tabPanelViewPreference;
        } catch(Exception exc) {
            System.debug(Logginglevel.WARN, 'Exception occurred while retrieving User Preferences. Returning false. ' + exc.getMessage());
            return false;
        }
    }

    @RemoteAction
    public static void setTabPanelViewPreference(Boolean toggleValue) {
        ADM_User_Preferences__c preferences = ADM_User_Preferences__c.getInstance(UserInfo.getUserId());
        preferences.TabPanelViewPreference__c = toggleValue;
        upsert preferences;
    }
}