mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If you leave this field empty on save you will be the Assignee.</inlineHelpText>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assignee</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Perforce_Status__c</fullName>
        <label>Source Control Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open Once</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Scheduled_Build__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Scheduled Build field is a lookup to the Build object.  Enter a pre-existing build where the change will be made.</inlineHelpText>
        <label>Scheduled Build</label>
        <referenceTo>ADM_Build__c</referenceTo>
        <relationshipLabel>Work (Scheduled Build)</relationshipLabel>
        <relationshipName>Scheduled_Build</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bug</fullName>
                </value>
                <value>
                    <fullName>Gack</fullName>
                </value>
                <value>
                    <fullName>Help</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Test Change</fullName>
                </value>
                <value>
                    <fullName>Test Case</fullName>
                </value>
                <value>
                    <fullName>Test Failure</fullName>
                </value>
                <value>
                    <fullName>Test Tool</fullName>
                </value>
                <value>
                    <fullName>Skunkforce</fullName>
                </value>
                <value>
                    <fullName>Bug List</fullName>
                </value>
                <value>
                    <fullName>Translation</fullName>
                </value>
                <value>
                    <fullName>Non Deterministic Test</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <recordTypes>
        <fullName>Bug</fullName>
        <active>true</active>
        <description>Used to track defects or problems</description>
        <label>Bug</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/classes/ADM_BeforeInsertOrUpdate.cls
public with sharing class ADM_BeforeInsertOrUpdate {
    
    public static void clearPerforceStatusOnChanges(ADM_Work__c[] worksNew, ADM_Work__c[] worksOld) {
        Boolean hasChange = false;
        
        for(Integer i = 0; i < worksNew.size(); i++) {
            hasChange = false;
            ADM_Work__c newWork = worksNew[i];
            ADM_Work__c oldWork = worksOld[i];
            
            if(oldWork.Perforce_Status__c == newWork.Perforce_Status__c) { 
                if(newWork.Scheduled_Build__c != oldWork.Scheduled_Build__c) {
                    hasChange = true;
                }
                if(newWork.Assignee__c != oldWork.Assignee__c) {
                    hasChange = true;
                }
            }
            
            if(hasChange) newWork.Perforce_Status__c = null;
        }
    }
    
    public static void setDefaultValues(ADM_Work__c[] works, Map<Id,RecordType> workRecordTypesById) {
        //any values that you would like defaulted at the trigger level are set here.  Note: please make sure the value
        //makes sense for records created from all origins (Salesforce Classic, LEX, API, S1)
        for(ADM_Work__c work : works) {
            String recordTypeName = workRecordTypesById.get(work.RecordTypeId).Name;
            if(recordTypeName != null) {
                //if this is a Bug and the Bug Type picklist has not been populated assume its a generic bug vs Test Chanage etc
                if(recordTypeName == 'Bug' && (work.Type__c == null || work.Type__c.trim() == '')) {
                    work.Type__c = 'Bug';
                } 
            }
        }
    }
}