mdapi-source/original-package/unpackaged/objects/ADM_Color__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Colors</relationshipLabel>
        <relationshipName>Colors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Color</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Product_Tag__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipName>Product_Tags</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TE Activity</label>
    <nameField>
        <label>TE Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TE Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Scrum_Team__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Definition_of_Done_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Definition of Done Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Definition_of_Done__c</fullName>
        <label>Definition of Done</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Definition_of_Ready_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Definition of Ready Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Definition_of_Ready__c</fullName>
        <label>Definition of Ready</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Product_Tag__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TE Activity</label>
        <referenceTo>ADM_Product_Tag__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Product_Tag</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Triaged</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Investigating</fullName>
                </value>
                <value>
                    <fullName>Ready for Review</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>QA In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Defunct</fullName>
                </value>
                <value>
                    <fullName>Closed - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Closed - Eng Internal</fullName>
                </value>
                <value>
                    <fullName>Closed - Known Bug Exists</fullName>
                </value>
                <value>
                    <fullName>Closed - New Bug Logged</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Approved</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Denied</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved With Internal Tools</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved Without Code Change</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Working as Designed</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Feature Request</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Will Not Fix</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Pending Release</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>More Info Reqd from Support</fullName>
                </value>
                <value>
                    <fullName>Never</fullName>
                </value>
                <value>
                    <fullName>Not a bug</fullName>
                </value>
                <value>
                    <fullName>Not Reproducible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <recordTypes>
        <fullName>Bug</fullName>
        <active>true</active>
        <description>Used to track defects or problems</description>
        <label>Bug</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>ADM_Work__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A connection to the Agile Accelerator Work object used to track Bugs, Investigations and User Stories</description>
        <label>Work</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>AgileAcceleratorCases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/Headcount__c.object
<CustomObject>
    <description>Prototype for T&amp;P Headcount Management functionality to be integrated into GUS</description>
    <fields>
        <fullName>Backfill_Date__c</fullName>
        <description>If an employee is being backfilled, enter the expected date of departure.</description>
        <label>Backfill Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <inlineHelpText>Effective quarter to hire headcount.  Only Finance can move headcount from quarter to quarter.</inlineHelpText>
        <label>Effective Date</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FY12-Q4</fullName>
                </value>
                <value>
                    <fullName>FY13-Q1</fullName>
                    <default>true</default>
                    <label>FY13-Q1</label>
                </value>
                <value>
                    <fullName>FY13-Q2</fullName>
                </value>
                <value>
                    <fullName>FY13-Q3</fullName>
                </value>
                <value>
                    <fullName>FY13-Q4</fullName>
                </value>
                <value>
                    <fullName>FY14-Q1</fullName>
                </value>
                <value>
                    <fullName>FY14-Q2</fullName>
                </value>
                <value>
                    <fullName>FY14-Q3</fullName>
                </value>
                <value>
                    <fullName>FY14-Q4</fullName>
                </value>
                <value>
                    <fullName>FY15-Q1</fullName>
                </value>
                <value>
                    <fullName>FY15-Q2</fullName>
                </value>
                <value>
                    <fullName>FY15-Q3</fullName>
                </value>
                <value>
                    <fullName>FY15-Q4</fullName>
                </value>
                <value>
                    <fullName>FY16-Q1</fullName>
                </value>
                <value>
                    <fullName>FY16-Q2</fullName>
                </value>
                <value>
                    <fullName>FY16-Q3</fullName>
                </value>
                <value>
                    <fullName>FY16-Q4</fullName>
                </value>
                <value>
                    <fullName>FY17-Q1</fullName>
                </value>
                <value>
                    <fullName>FY17-Q2</fullName>
                </value>
                <value>
                    <fullName>FY17-Q3</fullName>
                </value>
                <value>
                    <fullName>FY17-Q4</fullName>
                </value>
                <value>
                    <fullName>FY18-Q1</fullName>
                </value>
                <value>
                    <fullName>FY18-Q2</fullName>
                </value>
                <value>
                    <fullName>FY18-Q3</fullName>
                </value>
                <value>
                    <fullName>FY18-Q4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Headcount_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of employee filling the position (lookup to User)</inlineHelpText>
        <label>Employee Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Headcounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hiring_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Hiring Manager for headcount</description>
        <label>Hiring Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Headcount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Open - New = New position added by Finance
Open - Backfill = Existing position available for Backfill
Offer - In Progress = Offer extended to candidate
Offer - Accepted = Offer accepted by candidate
Filled = Position filled by an employee</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open - New</fullName>
                    <default>true</default>
                    <label>Open - New</label>
                </value>
                <value>
                    <fullName>Open - Backfill</fullName>
                </value>
                <value>
                    <fullName>Offer In Progress</fullName>
                </value>
                <value>
                    <fullName>Offer Accepted</fullName>
                </value>
                <value>
                    <fullName>Filled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Scrum Team assigned to the position.</inlineHelpText>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipName>Headcount</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Position</label>
    <nameField>
        <displayFormat>H-{00000}</displayFormat>
        <label>Position #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Roster</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ADM_ScrumTeamTriggerTest.cls
@isTest
public with sharing class ADM_ScrumTeamTriggerTest { 
	
	/*
	@testcaseID a1DB00000000rsg
	@userstoryID  a0790000000DL4iAAG
	@hierarchy GUS.ScrumforceToGUS.ScrumTeams.Team Information.Deactivate Scrum Team
	@expected results An error message occurs when deactivating scrum team: Review all error messages below to correct your data. There are X open records assigned to this team. Please close or re-assign these records before de-activating the team.
	@author: jhatton
	*/
	
	static testMethod void testScrumTeamCannotBeDeactivatedWithOpenWorkAssigned() {
		
		ADM_Scrum_Team__c team = ADM_ScrumTeam.createTestScrumTeam();
		List <ADM_Work__c> works = ADM_Work.createListOfWork(3, 'Bug');
		//update the team of the Product Tag autocreated in setupTestWork() to match the team used on the team release record.  
		ADM_Product_Tag__c tag = [select id, Name from ADM_Product_Tag__c where id =:works.get(0).Product_Tag__c];
		tag.Team__c = team.id;
		update tag;
		//now make sure all of the work uses the same tag as tag and team are tightly coupled
		for(ADM_Work__c work : works) {
			work.Product_Tag__c = tag.id;
			work.Status__c = 'New';
		}
		
		insert works;
		//now try to deactivate the team
		try {
			team.Active__c = false;
			Database.update(team);
			System.assert(false, 'Test should have thrown a exception before it reached here');
		} catch (DmlException e) { 
            System.assert(e.getMessage().contains('There are ' + works.size() + ' open records assigned to this team.  Please close or re-assign these records before de-activating the team.'), e.getMessage());
        }
		
		
	}


	static testMethod void testScrumTeamDefinitionOfDoneCheckBox() {
		ADM_Scrum_Team__c team = ADM_ScrumTeam.createTestScrumTeam();
		List<ADM_Scrum_Team__c> teams = [select id, Definition_of_Done__c,Definition_of_Done_Check__c from ADM_Scrum_Team__c where id =:team.id];
		System.assertEquals(ADM_TextUtils.isBlank(teams.get(0).Definition_of_Done__c),true);
		System.assertEquals(teams.get(0).Definition_of_Done_Check__c,false);
		team.Definition_of_Done__c = 'test text';
		update team;
		List<ADM_Scrum_Team__c> teams1 = [select id, Definition_of_Done__c,Definition_of_Done_Check__c from ADM_Scrum_Team__c where id =:team.id];
		System.assertEquals(teams1.get(0).Definition_of_Done_Check__c,true);
		ADM_Scrum_Team__c teamNew = teams1.get(0);
		teamNew.Definition_of_Done__c = '';
		update teamNew;
		List<ADM_Scrum_Team__c> teams2 = [select id, Definition_of_Done__c,Definition_of_Done_Check__c from ADM_Scrum_Team__c where id =:teamNew.id];
		System.assertEquals(teams2.get(0).Definition_of_Done_Check__c,false);

	}

	static testMethod void testScrumTeamDefinitionOfReadyCheckBox() {
		ADM_Scrum_Team__c team = ADM_ScrumTeam.createTestScrumTeam();
		List<ADM_Scrum_Team__c> teams = [select id, Definition_of_Ready__c,Definition_of_Ready_Check__c from ADM_Scrum_Team__c where id =:team.id];
		System.assertEquals(ADM_TextUtils.isBlank(teams.get(0).Definition_of_Ready__c),true);
		System.assertEquals(teams.get(0).Definition_of_Ready_Check__c,false);
		team.Definition_of_Ready__c = 'test text';
		update team;
		List<ADM_Scrum_Team__c> teams1 = [select id, Definition_of_Ready__c,Definition_of_Ready_Check__c from ADM_Scrum_Team__c where id =:team.id];
		System.assertEquals(teams1.get(0).Definition_of_Ready_Check__c,true);

	}
	
	/*
	@testcaseID a1DB00000000rsj
	@userstoryID  a0790000000DL4iAAG
	@hierarchy GUS.ScrumforceToGUS.ScrumTeams.Team Information.Deactivate Scrum Team
	@expected results User is able to deactivate scrum team without any warnings
	@author: jhatton
	*/
	
	static testMethod void testScrumTeamCanBeDeactivatedWithClosedWorkAssigned() {
		
		ADM_Scrum_Team__c team = ADM_ScrumTeam.createTestScrumTeam();
		List <ADM_Work__c> works = ADM_Work.createListOfWork(3, 'Bug');
		//insert the work
		for(ADM_Work__c w : works) {
			w.Status__c = 'Closed';
			w.Scrum_Team__c = team.id;
		}
		insert works;
		//now try to deactivate the team
		try {
			team.Active__c = false;
			Database.update(team);
			System.assert(true, 'Test should have passed validation');
		} catch (DmlException e) { 
            System.assert(false, 'Did not expect this error as work assigned to team being deactivated is closed:' + e.getMessage());
        }
		
		
	}
	
	/* 
	@testcaseID a1DB00000001TE3
	@userstoryID  a07B0000000LIaaIAG
	@hierarchy GUS.ScrumforceToGUS.Position.Select Cloud
	@author James Hatton
	@exected results Applicable Headcount records have their Cloud updated when Scrum Team changes
	*/
	
	static testMethod void testHeadcountCloudIsUpdatedWhenScrumTeamCloudChanges() {
		//setup a test team
		ADM_Scrum_Team__c team = ADM_ScrumTeam.createTestScrumTeam();
		
		//setup a test headcount record
        Headcount__c hc = new Headcount__c();
        User u1 = ADM_WorkUser.createTestUserWithRandomName();
        User u2 = ADM_WorkUser.createTestUserWithRandomName();
        hc.Hiring_Manager__c = u1.id;
        hc.Headcount_Name__c = u2.id;
        hc.Status__c = 'Filled';
        hc.Backfill_Date__c = System.today() +1;
        hc.Effective_Date__c = QuarterPeriod.getCurrentFiscalQuarterName();
        hc.Team__c = team.id;
        insert hc;	
		//now change the cloud on team
		team.Cloud__c = 'Data.com';
		update team;
		//verfiy Headcount was updated
		Headcount__c updatedHC = [select id, Cloud__c, Team__c from Headcount__c where id = : hc.id];
		System.assertEquals('Data.com', updatedHC.Cloud__c);
	}	

	/* Verify that New Kanban teams have default colors assigned to them */

	static testMethod void testDefaultColorCreatedForNewKanbanTeam() {
		ADM_Scrum_Team__c team = ADM_ScrumTeam.createTestScrumTeam();
		 List <ADM_Color__c> color = [select id, Name from ADM_Color__c where Team__c =:team.id];
         System.assertEquals( 0,color.size(),'Non Kanban team should not have any colors assigned');
		 team.Kanban__c = true;
		 update team;
		 List <ADM_Color__c> defaultColor = [select id, Name from ADM_Color__c where Team__c =:team.id];
         System.assertEquals(6,defaultColor.size(), 'Kanban team should have default colors assigned');

	}

  /*
				If a different Team used the team name in the past then that attempt should be denied
  */
	static testMethod void testDenyTeamNameUpdateToNamePreviouslyUsedByADifferentTeam() {
		 ADM_Scrum_Team__c firstTeam = ADM_ScrumTeam.createAndInsertScrumTeamWithRandomName();
		 String teamNameBeforeChange = firstTeam.Name;
		 firstTeam.Name = 'StarWars!543@3';
		 update firstTeam;

		 ADM_Scrum_Team__c secondTeam = ADM_ScrumTeam.createAndInsertScrumTeamWithRandomName();
		 secondTeam.Name = teamNameBeforeChange;
		 try{
		 	update secondTeam;
            System.assert(false,' Expected DML Exception because secondTeam used team name used by firstTeam');

		 }
		 catch(DMLException exp){
            System.assert(exp.getMessage().containsIgnoreCase('Team Name "'+teamNameBeforeChange+'" was used by StarWars!543@3 Team in the past, please select a different Name'), exp.getMessage());
		 }

	}

	/*
				If a different Team used the team name in the past then that attempt should be denied - Team Name should not be allowed even with different Case.
	*/
	static testMethod void testTeamNameWithDifferentCaseIsDeniedIfUsedByDifferentTeam() {
		 ADM_Scrum_Team__c firstTeam = ADM_ScrumTeam.createAndInsertScrumTeamWithRandomName();
		 String teamNameBeforeChange = firstTeam.Name;
		 firstTeam.Name = 'StarWars!543@3';
		 update firstTeam;
		
		 ADM_Scrum_Team__c secondTeam = ADM_ScrumTeam.createAndInsertScrumTeamWithRandomName();
         String teamNameLowerCase = teamNameBeforeChange.toLowerCase();
         System.assertNotEquals(teamNameBeforeChange, teamNameLowerCase, 'Expected Previous Team names to be of different cases');
         secondTeam.Name = teamNameLowerCase;
		 try{
		 	update secondTeam;
            System.assert(false,' Expected DML Exception because secondTeam used team name used by firstTeam');
            
		 }
		 catch(DMLException exp){
            System.assert(exp.getMessage().containsIgnoreCase('Team Name "'+teamNameBeforeChange+'" was used by StarWars!543@3 Team in the past, please select a different Name'), exp.getMessage());
		 }

	}

	 static testMethod void testDenyNewTeamWithNamePreviouslyUsedByADifferentTeam() {
		 ADM_Scrum_Team__c firstTeam = ADM_ScrumTeam.createTestScrumTeam();
		 String teamNameBeforeChange = firstTeam.Name;
		 firstTeam.Name = 'StarWars!543@3';
		 update firstTeam;
		 
		 try{
		 ADM_Scrum_Team__c secondTeam = ADM_ScrumTeam.createTestScrumTeam();
		 
            System.assert(false,' Expected DML Exception because secondTeam used team name used by firstTeam');
            
		 }
		 catch(DMLException exp){
            System.assert(exp.getMessage().containsIgnoreCase('Team Name "'+teamNameBeforeChange+'" was used by StarWars!543@3 Team in the past, please select a different Name'), exp.getMessage());
		 }
		 

		

	}

	static testMethod void testAllowTeamToUsePastNames() {
		 ADM_Scrum_Team__c firstTeam = ADM_ScrumTeam.createTestScrumTeam();
		 String teamNameBeforeChange = firstTeam.Name;
		 firstTeam.Name = 'StarWars!543@3';
		 update firstTeam;
		 ADM_Scrum_Team__c teamQueried = [Select Name from ADM_Scrum_Team__c where id =:firstTeam.Id];
		 System.assertEquals('StarWars!543@3', teamQueried.Name, ' Expected team Name to be updated to StarWars!543@3');
		 firstTeam.Name = teamNameBeforeChange;
		 update firstTeam;
		 teamQueried = [Select Name from ADM_Scrum_Team__c where id =:firstTeam.Id];
		  System.assertEquals(teamNameBeforeChange, teamQueried.Name, ' Expected team Name to be updated to '+ teamNameBeforeChange);

		

	}


}