mdapi-source/original-package/unpackaged/objects/ADM_Scrum_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Allocation__c</fullName>
        <label>Allocation (%)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Member_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Scrum_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>Scrum_Team_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <displayFormat>STM-{00000}</displayFormat>
        <label>Team Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Time_Off_Log__c.object
<CustomObject>
    <fields>
        <fullName>Allocation__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>Percentage of time allocated to the PTOn project between the PTOn Start date and End date.</inlineHelpText>
        <label>Allocation %</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox gets checked once a PTon request has been approved by the requestee&apos;s manager.</description>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Describe your PTOn project or Out of Office in this field.</inlineHelpText>
        <label>Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Time_Off_Log</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Out Of Office Log</label>
    <nameField>
        <displayFormat>PTO-{0000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Out Of Office Logs</pluralLabel>
    <recordTypes>
        <fullName>PTOn</fullName>
        <active>true</active>
        <description>PTOn (Paid Time ON) time spent working on a project external to the Scrum Team.</description>
        <label>PTOn (Paid Time On)</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/classes/ADM_ScrumTeamMembersOutOfOffice.cls
public with sharing class ADM_ScrumTeamMembersOutOfOffice {

    public ADM_ScrumTeamMembersOutOfOffice(ApexPages.StandardController controller) {
        
    }
    
    public ADM_ScrumTeamMembersOutOfOffice() {
        
    }
    
    private String scrumTeamId { 
    	get {
    		if(scrumTeamId == null) scrumTeamId = System.currentPageReference().getParameters().get('id');
    		return scrumTeamId;
    	}
    	set;
    }
    
    
    
    public List<ADM_Time_Off_Log__c> teamMembersOutOfOffice {
    	get {
    		teamMembersOutOfOffice = findTeamMembersOutOfOfficeInformation(scrumTeamId);
    		if(teamMembersOutOfOffice.isEmpty()) Apexpages.addMessage(new Apexpages.Message(ApexPages.severity.INFO,'No scrum team members have any upcoming time off scheduled.'));
    		return teamMembersOutOfOffice;
    	}
    	set;
    }
    
    @AuraEnabled
    public static List<ADM_Time_Off_Log__c>  getTeamMembersOutOfOfficeList(String recordId) {
      List<ADM_Time_Off_Log__c> timeOffLogs = findTeamMembersOutOfOfficeInformation(recordId);
      return timeOffLogs;
        
    }
    
    
    private static List<ADM_Time_Off_Log__c> findTeamMembersOutOfOfficeInformation(String teamId){
        List<ADM_Time_Off_Log__c> oooLogs = new List<ADM_Time_Off_Log__c>();
        List<Id> teamMemberIds = new List<Id>();
        for (ADM_Scrum_Team_Member__c teamMemberId : [select Member_Name__c from ADM_Scrum_Team_Member__c where Scrum_Team__c = : teamId]) {
            teamMemberIds.add(teamMemberId.Member_Name__c);
        }
        oooLogs = [
            select RecordType.Name, Id,User__r.Name, User__r.Id, Start_Date__c, End_Date__c, Allocation__c, Description__c, Approved__c 
            from ADM_Time_Off_Log__c 
            where User__r.Id in : teamMemberIds    		 
            and End_Date__c >= : System.today()
            and (RecordType.Name = 'Out of Office' or (RecordType.Name = 'PTOn (Paid Time On)' and Approved__c = true))
            and User__r.Id != null
            order by Start_Date__c asc];
        
        return oooLogs;
    }
    
}