mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Email_Subscription_ID__c</fullName>
        <inlineHelpText>Enter email aliases separated by spaces. These users are sent one email if the &quot;Email on Save&quot; check box is selected when you click &quot;Save.&quot; They do not automatically receive future updates.</inlineHelpText>
        <label>To</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/classes/ADM_CreateSubscriberActionTest.cls
@isTest
public class ADM_CreateSubscriberActionTest {

	@isTest    
	static void testBeforeInsertOrUpdate() {	
		ADM_Work__c work = ADM_Work.setupTestWork(ADM_Work.BUG_RECORD_TYPE_NAME);
		User u = ADM_WorkUser.createTestUser();
		work.Email_Subscription_ID__c = u.Username;
		Boolean emailSubscribersAreValid = ADM_CreateSubscriberAction.beforeInsertOrUpdate(new List<ADM_Work__c>{work}); 
		
		System.assertEquals(true, emailSubscribersAreValid);
		System.assertEquals(false, ApexPages.hasMessages());
		
		//repeat test with invalid email subscription
		work.Email_Subscription_ID__c = 'sfdfadsfdsf';
		emailSubscribersAreValid = ADM_CreateSubscriberAction.beforeInsertOrUpdate(new List<ADM_Work__c>{work});  
		System.assertEquals(false, emailSubscribersAreValid);
		System.assertEquals(true, ApexPages.hasMessages());

	}

}