mdapi-source/original-package/unpackaged/objects/ADM_Product_Tag__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipName>Product_Tags</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TE Activity</label>
    <nameField>
        <label>TE Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TE Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Sprint__c.object
<CustomObject>
    <customHelpPage>ADM_CreateSprintOverview</customHelpPage>
    <description>Added to support User Story for Scrumforce integration into GUS.</description>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scrum Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Sprints</relationshipLabel>
        <relationshipName>Sprints</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Closed__c</fullName>
        <formula>CASE(  Status__c, &quot;Tested&quot;, 1, &quot;Closed&quot;, 1, &quot;Closed-Untested&quot;, 1, &quot;Closed-U/Ftest&quot;, 1, &quot;Completed&quot;, 1, &quot;Not Reproducible&quot;, 1, &quot;Never&quot;, 1, &quot;Not a bug&quot;, 1, &quot;Duplicate&quot;, 1, &quot;Closed - Duplicate&quot; , 1, &quot;Closed - Known Bug Exists&quot;, 1, &quot;Closed - New Bug Logged&quot;, 1, &quot;Closed - No Fix - Working as Designed&quot;,1, &quot;Closed - No Fix - Feature Request&quot;,1, &quot;Closed - No Fix - Will Not Fix&quot;,1, &quot;Closed - LAP Request Approved&quot;, 1, &quot;Closed - LAP Request Denied&quot;, 1, &quot;Closed - Resolved Without Code Change&quot;, 1, &quot;Rejected&quot;, 1, &quot;Closed - Resolved With Internal Tools&quot;, 1, &quot;Closed - Defunct&quot;,1,&quot;Closed - Doc/Usability&quot;,1,&quot;Closed - Resolved with DB Script&quot;,1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Closed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <inlineHelpText>For bugs, priority is automatically determined based upon the combination of Impact and Frequency.

For user stories, P0 represents the highest priority, P4 the lowest.</inlineHelpText>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>P0</fullName>
                    <color>#0B6FCE</color>
                    <label>P0</label>
                </value>
                <value>
                    <fullName>P1</fullName>
                    <color>#FF0000</color>
                    <label>P1</label>
                </value>
                <value>
                    <fullName>P2</fullName>
                    <color>#E27001</color>
                    <label>P2</label>
                </value>
                <value>
                    <fullName>P3</fullName>
                    <color>#FFFF66</color>
                    <label>P3</label>
                </value>
                <value>
                    <fullName>P4</fullName>
                    <color>#78C953</color>
                    <label>P4</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Tag__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TE Activity</label>
        <referenceTo>ADM_Product_Tag__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Product_Tag</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sprint</label>
        <referenceTo>ADM_Sprint__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Use_Prioritizer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to determine whether or not a work record should be shown on the Work Prioritizer page</description>
        <inlineHelpText>Used to determine whether or not a work record should be shown on the Work Prioritizer page</inlineHelpText>
        <label>Include in Prioritize View</label>
        <type>Checkbox</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/classes/ADM_AddWorkToSprintControllerTest.cls
@isTest
public class ADM_AddWorkToSprintControllerTest {

    
    /* 
	  @testcaseID a0B20000006aebaEAA
	  @hierarchy GUS.ScrumforceToGUS.Sprint.Detail page.Sprint Backlog
	  @userstory a0A20000007rUNO
	  @expectedResults: Ensure work items that are closed do not show on Add work to Sprint page
	*/    
   @isTest
   static void testSuiteAddWorkToSprint() {
        ADM_Work__c story = ADM_Work.setupTestWork(ADM_Work.RECORD_TYPE_NAME_USERSTORY);
        ADM_Sprint__c sprint = ADM_Sprint.createTestSprint();
        ADM_Product_Tag__c tag = [select id, Team__c from ADM_Product_Tag__c where id =:story.Product_Tag__c];
        tag.Team__c = sprint.Scrum_Team__c;
        update tag; 
        
        System.currentPageReference().getParameters().put('sprintID', sprint.id);
        story.Priority__c = 'P1';
        Test.startTest();
            insert story; 
        
            List<ADM_Work__c> works = new List<ADM_Work__c>();
    
            works.add(story);
    	
            ADM_AddWorkToSprintController controller = new ADM_AddWorkToSprintController();
            System.assert(controller != null);
            List<ADM_WorkWrapper> work = controller.getWork();
        	
        	//on page loads the default work list is displayed
        	System.assert(work != null);
        
        	//should be 1 works records in our original list.  Limited to testing with small size due to test method gov limits
        	System.assertEquals(1, work.size());
        	//verify on load that none of the works items are selected - the checked boolean meta data shows this
        	for(ADM_WorkWrapper ww : work) {
        		System.assertEquals(false, ww.checked);
        		System.assert(ww.work != null);
        		System.assert(ww.work.Subject__c != null);
        		System.assert(ww.work.Closed__c == 0);
        		System.assert(ww.work.Sprint__c != sprint.id);
        		System.assert(ww.work.Use_Prioritizer__c == true);
        		System.assert(ww.work.RecordType.Name != ADM_Work.TEMPLATE_RECORD_TYPE_NAME);
        		//check the box to select the work item for subsequent test
        		if(ww.work.id == story.id) ww.checked = true;
        	} 
        	//verify the sprint ID is in scope
        	System.assertEquals(sprint.id, controller.getSprintID());
        	
        	//select a work record to add to the sprint
        	controller.addToSprint();
        Test.stopTest();

    	//verify success message is returned
    	System.assert(ApexPages.getMessages() != null);
    	System.assertEquals('Work item(s) have been successfuly added to the sprint.', ApexPages.getMessages().get(0).getDetail());

    	//verify story was updated with sprint
    	System.assertEquals(sprint.id, [select Sprint__c from ADM_Work__c where id =:story.id].Sprint__c);
        	
    	//repeat but deliberately forget to select a work record and assert a nice error message is returned
    	for(ADM_WorkWrapper ww : controller.workList) {
    		 ww.checked = false;
    	} 

    	//attempt to add "nothing" to the sprint
    	controller.addToSprint();
    	//verify nice error message is returned
    	System.assert(ApexPages.getMessages() != null);
    	System.assertEquals('No Work item(s) have been selected.', ApexPages.getMessages().get(1).getDetail());
    } 
      
}