mdapi-source/original-package/unpackaged/objects/ADM_Application__c.object
<CustomObject>
    <description>Application lists resources associated with the release and management of any system that is released (has Releases).</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Release_Event_Template__c.object
<CustomObject>
    <description>Release Event Templates represent events such as deployments which take place as part of a Release.</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Enter the Application to which this Release Event Item applies</inlineHelpText>
        <label>Application</label>
        <referenceTo>ADM_Application__c</referenceTo>
        <relationshipLabel>Release Event Templates</relationshipLabel>
        <relationshipName>Release_Event_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Base_Event__c</fullName>
        <description>This field indicates whether the Release Event is a &quot;Base&quot; event, that is, the event happens at the time indicated by the Release record&apos;s Scheduled Release Date.</description>
        <formula>IF(Day_Offset__c = 0 &amp;&amp;  Event_Duration__c = 0 &amp;&amp; ISBLANK(Start_Time__c) &amp;&amp; 
Minute_Offset__c =0 &amp;&amp;  Hour_Offset__c = 0, &quot;BASE EVENT&quot;, &quot;&quot;)</formula>
        <label>Base Event</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Day_Offset__c</fullName>
        <inlineHelpText>Number of days from the Scheduled Release Date that the Release Event is to occur.</inlineHelpText>
        <label>Day Offset</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event_Duration__c</fullName>
        <inlineHelpText>Enter the duration in minutes of this Release Event. Setting this value to zero when Day Offset, Hour Offset and Minute Offset are all zero creates Release Events with a Duration equal to the Release&apos;s Planned Duration.</inlineHelpText>
        <label>Event Duration</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event_Template_Name__c</fullName>
        <description>Name of the Release Event Template</description>
        <inlineHelpText>Enter a name for the Release Event Template</inlineHelpText>
        <label>Event Template Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hour_Offset__c</fullName>
        <inlineHelpText>Number of hours that this event item is offset from the Scheduled Release Date. Note: Either Start Time or Hour and Minute Offset can be used.</inlineHelpText>
        <label>Hour Offset</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minute_Offset__c</fullName>
        <inlineHelpText>Number of minutes that this event item is offset from the Scheduled Release Date. Note: Either Start Time or Hour and Minute Offset can be used.</inlineHelpText>
        <label>Minute Offset</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Notify_Customers__c</fullName>
        <inlineHelpText>Release Events that are customer facing may be communicated to customers through the Trust site or other means</inlineHelpText>
        <label>Customer facing?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Release_Type__c</fullName>
        <inlineHelpText>Select the types of Release which employ this Release Event Item</inlineHelpText>
        <label>Release Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>eRelease</fullName>
                </value>
                <value>
                    <fullName>Patch</fullName>
                </value>
                <value>
                    <fullName>Major</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <inlineHelpText>Enter the time of day when the Release Event would occur. Format is HH:MM AM/PM (12 hour). Note: Either Start Time or Hour and Minute Offset can be used.</inlineHelpText>
        <label>Start Time</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>Release Event Template</label>
    <nameField>
        <displayFormat>RET-{000000}</displayFormat>
        <label>Release Event Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Release Event Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/classes/ADM_Application_TriggerTest.cls
/**
 *	Test that ADM_Application__c records cannot be created with duplicate names
 */
/*
 * Added tests in support of Release Event Templates
 *
 *    @testcaseID ADM_ReleaseTriggerTest
 *    @userstory W-2076536 https://gus.my.salesforce.com/a07B0000000dKy6 
 *    @author: snahm
 *
 */ 
@isTest
private class ADM_Application_TriggerTest {

	static final String TEST_APPLICATION_NAME = 'Test Application 123';
	static final String TEST_APPLICATION_TYPE = 'Testing Type';

/*
@testcaseID a1DB00000002xGB
@userstory a07B0000000cluE
@Hierarchy GUS.Application.Applications with duplicate names cannot be created
@Expected Results  An error that an Application with that same name has already been created is generated
 * @author snahm
 */
    static testMethod void createApplicationWithDuplicateNames() {

    	// Test 1: Create Application with identical name
        ADM_Application__c app1 = ADM_Application.createTestApplication(TEST_APPLICATION_NAME, TEST_APPLICATION_TYPE);
        //attempt to create a new app with the same name
        ADM_Application__c app2;
        try {
			app2 = ADM_Application.createTestApplication(TEST_APPLICATION_NAME, TEST_APPLICATION_TYPE);
            System.assert(false, 'createApplicationWithDuplicateNames: Test 1 should have thrown a DML exception before it reached here');
        } catch (System.Dmlexception e) {
            System.assertEquals(true, e.getMessage().contains('duplicates value on record with id:'), '->' + e.getMessage());
        }

        // Test 2: repeat with different case
        try {
            app2 = ADM_Application.createTestApplication(TEST_APPLICATION_NAME.toUpperCase(), TEST_APPLICATION_TYPE);
            System.assert(false, 'createApplicationWithDuplicateNames: Test 2 should have thrown a DML exception before it reached here');
        } catch (System.DmlException e) {
            System.assert(e.getMessage().contains('duplicates value on record with id:'), e.getMessage());
        }

		final String TEST_APPLICATION_NOSPACE = 'MyTestApplicationName123';
		final String TEST_APPLICATION_SPACE   = 'My Test Application Name 123';
		
        // Test 3: repeat but set up two apps.  The original with no spaces and then attempt to insert a duplicate, identical except for white space
        ADM_Application__c appNoSpaces = ADM_Application.createTestApplication(TEST_APPLICATION_NOSPACE, TEST_APPLICATION_TYPE);
        try {
        	ADM_Application__c appWithSpaces = ADM_Application.createTestApplication(TEST_APPLICATION_SPACE, TEST_APPLICATION_TYPE);
            System.assert(false, 'createApplicationWithDuplicateNames: Test 3 should have thrown a DML exception before it reached here');
        } catch (System.DmlException e) {
            System.assert(e.getMessage().contains('duplicates value on record with id:'), e.getMessage());
        }

        // Test 4: Test that updating an Application to an existing app name will not work
        try {
        	app1.Name = appNoSpaces.Name;
        	update(app1);
            System.assert(false, 'createApplicationWithDuplicateNames: Test 4 should have thrown a DML exception before it reached here');
        } catch (System.DmlException e) {
            System.assert(e.getMessage().contains('duplicates value on record with id:'), e.getMessage());
        }
    }
    
/**
 * testBaseTemplateWhenNoneExist 
 * When an Application is created or updated, Base Release Event Templates will be 
 * created if no Base Release Event Templates already exist. 
 * 1) Create Application with no Base Release Events Templates 
 * 2) Check that a Base Release Event Template is created that covers all release 
 * types. 
 * 
 * @testcaseID a1DB0000000304g
 * @userStory W-2076536 
 * @hierarchy GUS.Releases page.Release Events 
 * @priority High 
 * @expectedResults Base Release Event Template is created when none already exists on 
 * Create or Update of an Application record. 
 * @author snahm
 */
    static testMethod void testBaseTemplateWhenNoneExist() {

        ADM_Application__c app1 = ADM_Application.createTestApplication(TEST_APPLICATION_NAME, TEST_APPLICATION_TYPE);

		// A Base Release Event Template should have been created
		List<ADM_Release_Event_Template__c> retList = [select Name, Base_Event__c, Notify_Customers__c, Day_Offset__c, Event_Duration__c,
			Event_Template_Name__c, Hour_Offset__c, Minute_Offset__c, Release_Type__c, Start_Time__c
			from ADM_Release_Event_Template__c where Application__c =: app1.Id];
		
		System.assert(retList.size() == 1, 
			'testBaseTemplateWhenNoneExist: Wrong number of Release Event Templates found after creation of Application. Expected 1 but got ' + retList.size());

		ADM_Release_Event_Template__c ret = retList[0];
		System.assert(ADM_ReleaseEventTemplate.isBaseEventTemplate(ret),
			'testBaseTemplateWhenNoneExist: Base offset values for Release Event Template created after creation of Application should all be zero but are not. Values are: Day_Offset__c=' + ret.Day_Offset__c + 
			' Event_Duration__c=' + ret.Event_Duration__c + ' Minute_Offset__c=' + ret.Minute_Offset__c + ' Hour_Offset__c=' + ret.Hour_Offset__c);

		Set<String> releaseTypeSet = new Set<String> {		// Check that the Base Event covers all release types
				ADM_ReleaseEventTemplate.RELEASE_TYPE_MAJOR,
				ADM_ReleaseEventTemplate.RELEASE_TYPE_PATCH,
				ADM_ReleaseEventTemplate.RELEASE_TYPE_ERELEASE,
				ADM_ReleaseEventTemplate.RELEASE_TYPE_OTHER 
		};
		for (String releaseType : releaseTypeSet) {
			if (ret.Release_Type__c != null && ret.Release_Type__c.contains(releaseType)) {
				releaseTypeSet.remove(releaseType);
			}
		}

		System.assert(releaseTypeSet.isEmpty(), 'testBaseTemplateWhenNoneExist: Created Base Event Template should cover all Release Types, but does not cover: '
			+ releaseTypeSet);

		// Delete the release event item and make sure it is recreated on update of the Application record
		
		Database.delete(ret);
		Database.update(app1);
		
		retList = [select Name, Base_Event__c, Notify_Customers__c, Day_Offset__c, Event_Duration__c,
			Event_Template_Name__c, Hour_Offset__c, Minute_Offset__c, Release_Type__c, Start_Time__c
			from ADM_Release_Event_Template__c where Application__c =: app1.Id];
		
		System.assert(retList.size() == 1, 
			'testBaseTemplateWhenNoneExist: Wrong number of Release Event Templates found after update of Application. Expected 1 but got ' + retList.size());

		ret = retList[0];
		System.assert(ADM_ReleaseEventTemplate.isBaseEventTemplate(ret),
			'testBaseTemplateWhenNoneExist: Base offset values for Release Event Template created after update of Application should all be zero but are not. Values are: Day_Offset__c=' + ret.Day_Offset__c + 
			' Event_Duration__c=' + ret.Event_Duration__c + ' Minute_Offset__c=' + ret.Minute_Offset__c + ' Hour_Offset__c=' + ret.Hour_Offset__c);
     
     
    }
    
 /**
  * testBaseTemplateForSomeReleaseTypes
  * If an Application has a Base Release Event Template for certain Release Types, but 
  * not for other Release Types, then a Base Release Event Template will be created for 
  * the other Release Types. 
  * 
  * @testcaseID a1DB0000000304h
  * @userStory W-2076536 
  * @hierarchy GUS.Releases page.Release Events 
  * @priority High 
  * @expectedResults A Base Release Event Template for the Release Types not already 
  * covered by an existing Release Event Template will be created for Application 
  * Create and Update.
  * @author snahm
  */
	static testMethod void testBaseTemplateForSomeReleaseTypes() {

        ADM_Application__c app1 = ADM_Application.createTestApplication(TEST_APPLICATION_NAME, TEST_APPLICATION_TYPE);
		ADM_Release_Event_Template__c retBase = [select Name, Base_Event__c, Notify_Customers__c, Day_Offset__c, Event_Duration__c,
			Event_Template_Name__c, Hour_Offset__c, Minute_Offset__c, Release_Type__c, Start_Time__c
			from ADM_Release_Event_Template__c where Application__c =: app1.Id];

		// Update the generated Base Release Event Template to cover just Patches
		retBase.Release_Type__c = ADM_ReleaseEventTemplate.RELEASE_TYPE_PATCH;
		Database.update(retBase);

		// Update Application to cause generation of Base Release Event Templates for the non-covered Release Types
		Database.update(app1);
		
		List<ADM_Release_Event_Template__c> retList = [select Name, Base_Event__c, Notify_Customers__c, Day_Offset__c, Event_Duration__c,
			Event_Template_Name__c, Hour_Offset__c, Minute_Offset__c, Release_Type__c, Start_Time__c
			from ADM_Release_Event_Template__c where Application__c =: app1.Id];

		// Should now have two Release Event Templates: one created when Application was created and now covering only Patch releases
		// and one created after recent update of Application, covering the other Release Types		
		System.assert(retList.size() == 2, 
			'testBaseTemplateForSomeReleaseTypes: Wrong number of Release Event Templates found after creation of Application. Expected 2 but got ' + retList.size());

		for (ADM_Release_Event_Template__c retB : retList) {
			// Both will be Base Release Event Templates
			System.assert(ADM_ReleaseEventTemplate.isBaseEventTemplate(retB),
				'testBaseTemplateForSomeReleaseTypes: Base offset values for Release Event Template created after creation of Application should ' +
				'all be zero but are not. Values are: Day_Offset__c=' + retB.Day_Offset__c + ' Event_Duration__c=' + retB.Event_Duration__c + 
				' Minute_Offset__c=' + retB.Minute_Offset__c + ' Hour_Offset__c=' + retB.Hour_Offset__c);
			if (!retB.Release_Type__c.contains(ADM_ReleaseEventTemplate.RELEASE_TYPE_PATCH)) {
				// Should cover all Release Types by Patch
				Set<String> releaseTypeSet = new Set<String> {
						ADM_ReleaseEventTemplate.RELEASE_TYPE_MAJOR,
						ADM_ReleaseEventTemplate.RELEASE_TYPE_ERELEASE,
						ADM_ReleaseEventTemplate.RELEASE_TYPE_OTHER 
				};
				for (String releaseType : releaseTypeSet) {
					if (retB.Release_Type__c != null && retB.Release_Type__c.contains(releaseType)) {
						releaseTypeSet.remove(releaseType);
					}
				}
		
				System.assert(releaseTypeSet.isEmpty(), 'testBaseTemplateForSomeReleaseTypes: Base Release Event Template should cover ' +
					'all Release Types except ' + ADM_ReleaseEventTemplate.RELEASE_TYPE_PATCH + ', but does not cover: ' + releaseTypeSet);
			}
		}
    }   
}