mdapi-source/original-package/unpackaged/objects/ADM_Assignment_Rule__c.object
<CustomObject>
    <description>Used to populate the Assignment Rules on ADM_Work__c records</description>
    <fields>
        <fullName>Assignee_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assignment_Rules2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If this field is empty it will be pre-populated with the Product Owner for the rule&apos;s scrum team.</inlineHelpText>
        <label>Product Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assignment_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QA_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>QA Engineer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00NT0000000lhZjMAI</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UE_Engineer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UE Engineer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assignment_Rules1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assignment Rule</label>
    <nameField>
        <label>Assignment Rule</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignment Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Product_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If you leave it empty on save you will be the Product Owner</inlineHelpText>
        <label>Product Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Product_Owner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UE_Engineer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UE Engineer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Work1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ADM_WorkControllerExtensionTestUserStory.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class ADM_WorkControllerExtensionTestUserStory {

	
	/*
	@testcaseID: a1DB00000000t3N
      	@hierarchy: GUS.ScrumforceToGUS.Work Page.User Story.Edit Page
      	@userstory: a07B0000000Eih7IAC
      	@expectedResults: Assignees should not be populated on User Story if the user doesn't select both PA and MFA first.
      	@author Alexis Williams
    */

    static testMethod void testAjaxAssignmentsErrors(){
        ADM_Work__c work = new ADM_Work__c();
        ADM_Assignment_Rule__c rule = new ADM_Assignment_Rule__c();
		String name = String.valueOf(Math.random());
        String assignee;
        String qa;
        String ue;
        
        System.currentPageReference().getParameters().put('recordTypeLogicalName', ADM_Work.BUG_RECORD_TYPE_NAME);
        Apexpages.Standardcontroller controller = new Apexpages.Standardcontroller(work);
        ADM_WorkControllerExtension ext = new ADM_WorkControllerExtension(controller);
				
		rule.Product_Owner__c = Userinfo.getUserId();
		rule.Assignee_Assignment__c = Userinfo.getUserId();
		rule.QA_Assignment__c = Userinfo.getUserId();
		rule.UE_Engineer__c = Userinfo.getUserId();
        
        ext.getAutoAssignedWork();
        
        assignee = ext.getAssignee();
        qa = ext.getQa();
        ue = ext.getUe();
        
        System.assertEquals('', assignee);
        System.assertEquals('', qa);
        System.assertEquals('', ue);
        
        ext.setProductArea(name);
        ext.setMajorFunctionalArea(name);
        
        ext.getAutoAssignedWork();
        
        assignee = ext.getAssignee();
        qa = ext.getQa();
        ue = ext.getUe();
        
        System.assertEquals(ext.getAssignee(), assignee);
        System.assertEquals(ext.getAssignee(), qa);
        System.assertEquals(ext.getAssignee(), ue);
    }
}