mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>DateTime</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ADM_EmailSLACounterController.cls
public with sharing class ADM_EmailSLACounterController {
    /*
     * DEPRECATED
     * See ADM_EmailWorkQuickViewController
     * 
    @AuraEnabled
    public static ADM_Work__c findWork(String workName) {
        if (!Schema.SObjectType.ADM_Work__c.fields.Due_Date__c.isAccessible()){
            return null;
        }
        return [SELECT Due_Date__c FROM ADM_Work__c Where Name=:workName LIMIT 1];
    }
	*/
}