mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Closed__c</fullName>
        <formula>CASE(  Status__c, &quot;Tested&quot;, 1, &quot;Closed&quot;, 1, &quot;Closed-Untested&quot;, 1, &quot;Closed-U/Ftest&quot;, 1, &quot;Completed&quot;, 1, &quot;Not Reproducible&quot;, 1, &quot;Never&quot;, 1, &quot;Not a bug&quot;, 1, &quot;Duplicate&quot;, 1, &quot;Closed - Duplicate&quot; , 1, &quot;Closed - Known Bug Exists&quot;, 1, &quot;Closed - New Bug Logged&quot;, 1, &quot;Closed - No Fix - Working as Designed&quot;,1, &quot;Closed - No Fix - Feature Request&quot;,1, &quot;Closed - No Fix - Will Not Fix&quot;,1, &quot;Closed - LAP Request Approved&quot;, 1, &quot;Closed - LAP Request Denied&quot;, 1, &quot;Closed - Resolved Without Code Change&quot;, 1, &quot;Rejected&quot;, 1, &quot;Closed - Resolved With Internal Tools&quot;, 1, &quot;Closed - Defunct&quot;,1,&quot;Closed - Doc/Usability&quot;,1,&quot;Closed - Resolved with DB Script&quot;,1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Closed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/classes/ADM_WorkUnsubscriber.cls
public class ADM_WorkUnsubscriber implements Schedulable {
   public void execute(SchedulableContext SC) {
      deleteEntitySubscriptionForWorks();
   }
   
     
  private void deleteEntitySubscriptionForWorks(){
    
    /*

      Querying records that are last modified between 180 - 90 days and those whose status is closed__c = 1

    */
    if(Test.isRunningTest()){
      //No last modified check for test methods...as data can be created only in tests and lastModified date check is irrelevant
      List<ADM_Work__c> testWorkRecords = [Select id from ADM_Work__c where closed__c = 1 order by lastModifiedDate   ];
      deleteEntitySubscriptionForWorks(testWorkRecords);
    }
    else{
      for( List<ADM_Work__c> oldWorkRecords: [Select id from ADM_Work__c where lastModifiedDate != LAST_N_DAYS:90 AND lastModifiedDate = LAST_N_DAYS:180 AND closed__c = 1 order by lastModifiedDate  ]){
          deleteEntitySubscriptionForWorks(oldWorkRecords);

          
         
           //1 queries expected for Entity Subscription
          if(Limits.getQueries() + 1 >= Limits.getLimitQueries()){
              break;
          }
    
          //If total queried rows are closer to allowed limit stopping the execution
          if(Limits.getQueryRows() + 200 >= Limits.getLimitQueryRows()){
              break;
          }
          
           //If total dml rows are closer to allowed limit stopping the execution
          if(Limits.getDmlRows() + 200 >= Limits.getLimitDmlRows()){
              break;
          }
          
           //If DML statements so far is closer to allowed dml statements stopping the execution
          if(Limits.getDmlStatements() + 1 >= Limits.getLimitDmlStatements()){
              break;
          }
          
           //If script statment inside the loop is closer to limit stopping the execution
          if(Limits.getScriptStatements() + 200 >= Limits.getLimitScriptStatements()){
              break;
          }
      }
    }
    
   }

   private void deleteEntitySubscriptionForWorks(ADM_Work__c [] works){
        Set<Id> workIds = new Set<Id>();
        for(ADM_Work__c work: works){
          workids.add(work.Id);
        }

        if(workIds.size() > 0){
          EntitySubscription[] entitySubsToBeDeleted = ADM_EntitySubscriptionUtils.getAllBy(workIds, new Set<Id>());
          ADM_EntitySubscriptionUtils.deleteEntitySubscriptions(entitySubsToBeDeleted); 
        }        
    }
   
   
}