mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Number_of_Change_Lists__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Change Lists</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <inlineHelpText>For bugs, priority is automatically determined based upon the combination of Impact and Frequency.

For user stories, P0 represents the highest priority, P4 the lowest.</inlineHelpText>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>P0</fullName>
                    <color>#0B6FCE</color>
                    <label>P0</label>
                </value>
                <value>
                    <fullName>P1</fullName>
                    <color>#FF0000</color>
                    <label>P1</label>
                </value>
                <value>
                    <fullName>P2</fullName>
                    <color>#E27001</color>
                    <label>P2</label>
                </value>
                <value>
                    <fullName>P3</fullName>
                    <color>#FFFF66</color>
                    <label>P3</label>
                </value>
                <value>
                    <fullName>P4</fullName>
                    <color>#78C953</color>
                    <label>P4</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resolution__c</fullName>
        <inlineHelpText>App Bug Fix - TF caught a product bug&lt;br&gt;
TC: Due to app changes - Test changed b/c app behavior changed&lt;br&gt;
TC: Test issue only - Test needed fixing&lt;br&gt;
More: search Google Sites for &quot;test resolution&quot;</inlineHelpText>
        <label>Test Resolution</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>App Bug Fix</fullName>
                </value>
                <value>
                    <fullName>Test Change: Due to app changes</fullName>
                </value>
                <value>
                    <fullName>Test Change: Test issue only</fullName>
                </value>
                <value>
                    <fullName>Test Removed/Disabled</fullName>
                </value>
                <value>
                    <fullName>Duplicate Test Failure</fullName>
                </value>
                <value>
                    <fullName>Not Reproducible: Autobuild environment issue</fullName>
                </value>
                <value>
                    <fullName>Not Reproducible: SauceLabs issue</fullName>
                </value>
                <value>
                    <fullName>Not Reproducible: Broken By Another Team</fullName>
                </value>
                <value>
                    <fullName>Not Reproducible: Unknown</fullName>
                </value>
                <value>
                    <fullName>Not Reproducible: Other (please specify in Chatter feed)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Triaged</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Investigating</fullName>
                </value>
                <value>
                    <fullName>Ready for Review</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>QA In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Defunct</fullName>
                </value>
                <value>
                    <fullName>Closed - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Closed - Eng Internal</fullName>
                </value>
                <value>
                    <fullName>Closed - Known Bug Exists</fullName>
                </value>
                <value>
                    <fullName>Closed - New Bug Logged</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Approved</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Denied</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved With Internal Tools</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved Without Code Change</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Working as Designed</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Feature Request</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Will Not Fix</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Pending Release</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>More Info Reqd from Support</fullName>
                </value>
                <value>
                    <fullName>Never</fullName>
                </value>
                <value>
                    <fullName>Not a bug</fullName>
                </value>
                <value>
                    <fullName>Not Reproducible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bug</fullName>
                </value>
                <value>
                    <fullName>Gack</fullName>
                </value>
                <value>
                    <fullName>Help</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Test Change</fullName>
                </value>
                <value>
                    <fullName>Test Case</fullName>
                </value>
                <value>
                    <fullName>Test Failure</fullName>
                </value>
                <value>
                    <fullName>Test Tool</fullName>
                </value>
                <value>
                    <fullName>Skunkforce</fullName>
                </value>
                <value>
                    <fullName>Bug List</fullName>
                </value>
                <value>
                    <fullName>Translation</fullName>
                </value>
                <value>
                    <fullName>Non Deterministic Test</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <recordTypes>
        <fullName>Bug</fullName>
        <active>true</active>
        <description>Used to track defects or problems</description>
        <label>Bug</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ADM_WorkRecordBugTests.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class ADM_WorkRecordBugTests {
    public static String testFailure {
        get {
            if(testFailure == null) {
                testFailure = 'Test Failure';
            }
            return testFailure;
        }
        set;
    }
    
    public static String errorMessage {
        get {
            if(errorMessage == null) {
                errorMessage = 'Please enter a test when closing a bug';
            }
            return errorMessage;
        }
        set;
    }
    
    public static ADM_errorUtils errorUtils {
        get {
            if(errorUtils == null) {
                errorUtils = new ADM_errorUtils();
            }
            return errorUtils;
        }
        set;
    }
   
    /**
    *@testcaseID a0B20000008yHGiEAM
    *@hierarchy GUS.BugforceToGUS.WorkPage.BugsCreatedInGus.Edit and New page
    *@userstory a0790000000DGk6AAG
    *@expectedResults  Bug is saved with no errors
*/
    /**
    *@testcaseID a0B20000008yHGjEAM
    *@hierarchy GUS.BugforceToGUS.WorkPage.BugsCreatedInGus.Edit and New page
    *@userstory a0790000000DGk6AAG
    *@expectedResults  Bug is saved with no errors
*/
    /**
    *@testcaseID a0B20000008yHGkEAM
    *@hierarchy GUS.BugforceToGUS.WorkPage.BugsCreatedInGus.Edit and New page
    *@userstory a0790000000DGk6AAG
    *@expectedResults  Bug is saved with no errors
*/
    testMethod static void setP3BugToClosedWithChangelist(){
        Map<Id,RecordType> workRecordTypesById = new Map<Id,RecordType>(ADM_RecordType.getAll());
        ADM_Work__c work = ADM_Work.setupTestWork('Bug','P3');
        
        Test.startTest();
            work.Status__c = 'Closed';
            work.Number_of_Change_Lists__c = 200;
            insert work;
        Test.stopTest();
    }
    
    /**
    *@testcaseID a0B20000008xe3mEAA
    *@hierarchy GUS.BugforceToGUS.WorkPage.BugsCreatedInGus.Edit and New page
    *@userstory a0790000000DGk6AAG
    *@expectedResults  Bug is saved with no errors
*/
    /**
    *@testcaseID a0B20000008xe3rEAA
    *@hierarchy GUS.BugforceToGUS.WorkPage.BugsCreatedInGus.Edit and New page
    *@userstory a0790000000DGk6AAG
    *@expectedResults  Bug is saved with no errors
*/
    /**
    *@testcaseID a0B20000008xe41EAA
    *@hierarchy GUS.BugforceToGUS.WorkPage.BugsCreatedInGus.Edit and New page
    *@userstory a0790000000DGk6AAG
    *@expectedResults  Bug is saved with no errors
*/

    testMethod static void setP1BugToClosedWithChangelist(){
        Map<Id,RecordType> workRecordTypesById = new Map<Id,RecordType>(ADM_RecordType.getAll());
        ADM_Work__c work = ADM_Work.setupTestWork('Bug','P1');
        
        Test.startTest();
            work.Status__c = 'Closed';
            work.Number_of_Change_Lists__c = 200;
            try {
                insert work;
            } catch(System.DmlException e) {
                System.assertEquals(errorMessage, errorUtils.getErrorMessage(e));
            }
        Test.stopTest();
    }
    
     /**
    *@testcaseID a0B20000008xe3tEAA
    *@hierarchy GUS.BugforceToGUS.WorkPage.BugsCreatedInGus.Edit and New page
    *@userstory a0790000000DGk6AAG
    *@expectedResults  Bug is saved with no errors
*/   
     /**
    *@testcaseID a0B20000008xe43EAA
    *@hierarchy GUS.BugforceToGUS.WorkPage.BugsCreatedInGus.Edit and New page
    *@userstory a0790000000DGk6AAG
    *@expectedResults  Bug is saved with no errors
*/ 
     /**
    *@testcaseID a0B20000008xe4rEAA
    *@hierarchy GUS.BugforceToGUS.WorkPage.BugsCreatedInGus.Edit and New page
    *@userstory a0790000000DGk6AAG
    *@expectedResults  Bug is saved with no errors
*/ 
    testMethod static void setP3BugToClosedWithChangelistAndCases(){
        Map<Id,RecordType> workRecordTypesById = new Map<Id,RecordType>(ADM_RecordType.getAll());
        ADM_Work__c work = ADM_Work.setupTestWork('Bug','P3');
        
        Test.startTest();
            work.Status__c = 'Closed';
            work.Number_of_Change_Lists__c = 200;
           
            try {
                insert work;
            } catch(System.DmlException e) {
                System.assertEquals(errorMessage, errorUtils.getErrorMessage(e));
            }
        Test.stopTest();
    }
    
        /**
    *@testcaseID a0B20000008xe89EAA
    *@hierarchy GUS.BugforceToGUS.WorkPage.BugsCreatedInGus.Edit and New page
    *@userstory a0790000000DGk6AAG
    *@expectedResults  Test Failure is saved with no errors
*/
    
        /**
    *@testcaseID a0B20000008xe8CEAQ
    *@hierarchy GUS.BugforceToGUS.WorkPage.BugsCreatedInGus.Edit and New page
    *@userstory a0790000000DGk6AAG
    *@expectedResults  Test Failure is saved with no errors
*/
    
        /**
    *@testcaseID a0B20000008xe8FEAQ
    *@hierarchy GUS.BugforceToGUS.WorkPage.BugsCreatedInGus.Edit and New page
    *@userstory a0790000000DGk6AAG
    *@expectedResults  Test Failure is saved with no errors
*/
    testMethod static void setP3TestFailureToClosedWithChangelist(){
        Map<Id,RecordType> workRecordTypesById = new Map<Id,RecordType>(ADM_RecordType.getAll());
        ADM_Work__c work = ADM_Work.setupTestWork('Bug','P3', testFailure);
        
        Test.startTest();
            work.Type__c = testFailure;
            work.Status__c = 'Closed';
            work.Priority__c = 'P3';
            work.Resolution__c = 'App Change';
            work.Number_of_Change_Lists__c = 200;
            insert work;
        Test.stopTest();
    }
    
        /**
    *@testcaseID a0B20000008xe8AEAQ
    *@hierarchy GUS.BugforceToGUS.WorkPage.BugsCreatedInGus.Edit and New page
    *@userstory a0790000000DGk6AAG
    *@expectedResults  Test Failure is saved with no errors
*/
        /**
    *@testcaseID a0B20000008xe8AEAQ
    *@hierarchy GUS.BugforceToGUS.WorkPage.BugsCreatedInGus.Edit and New page
    *@userstory a0790000000DGk6AAG
    *@expectedResults  Test Failure is saved with no errors
*/
        /**
    *@testcaseID a0B20000008xe8DEAQ
    *@hierarchy GUS.BugforceToGUS.WorkPage.BugsCreatedInGus.Edit and New page
    *@userstory a0790000000DGk6AAG
    *@expectedResults  Test Failure is saved with no errors
*/
    testMethod static void setP1TestFailureToClosedWithChangelist(){
        Map<Id,RecordType> workRecordTypesById = new Map<Id,RecordType>(ADM_RecordType.getAll());
        ADM_Work__c work = ADM_Work.setupTestWork('Bug','P1', testFailure);
        
        Test.startTest();
            work.Status__c = 'Closed';
            work.Number_of_Change_Lists__c = 200;
            work.Resolution__c = 'App Change';
            work.Type__c = testFailure;
            work.Priority__c = 'P1';
            try {
                insert work;
            } catch(System.DmlException e) {
                System.assertEquals(errorMessage, errorUtils.getErrorMessage(e));
            }
        Test.stopTest();
    }
    
        /**
    *@testcaseID a0B20000008yHFzEAM
    *@hierarchy GUS.BugforceToGUS.WorkPage.BugsCreatedInGus.Edit and New page
    *@userstory a0790000000DGk6AAG
    *@expectedResults  Test Failure is saved with no errors
*/
        /**
    *@testcaseID a0B20000008yHG0EAM
    *@hierarchy GUS.BugforceToGUS.WorkPage.BugsCreatedInGus.Edit and New page
    *@userstory a0790000000DGk6AAG
    *@expectedResults  Test Failure is saved with no errors
*/
        /**
    *@testcaseID a0B20000008yHG1EAM
    *@hierarchy GUS.BugforceToGUS.WorkPage.BugsCreatedInGus.Edit and New page
    *@userstory a0790000000DGk6AAG
    *@expectedResults  Test Failure is saved with no errors
*/
    testMethod static void setP3TestFailureToClosedWithChangelistAndCases(){
        Map<Id,RecordType> workRecordTypesById = new Map<Id,RecordType>(ADM_RecordType.getAll());
        ADM_Work__c work = ADM_Work.setupTestWork('Bug','P3', testFailure);
        
        Test.startTest();
            work.Status__c = 'Closed';
            work.Number_of_Change_Lists__c = 200;
            work.Resolution__c = 'App Change';
            work.Type__c = testFailure;
            work.Priority__c = 'P3';
            try {
                insert work;
            } catch(System.DmlException e) {
                System.assertEquals(errorMessage, errorUtils.getErrorMessage(e));
            }
        Test.stopTest();
    }
}