mdapi-source/original-package/unpackaged/objects/ADM_Assignment_Rule__c.object
<CustomObject>
    <description>Used to populate the Assignment Rules on ADM_Work__c records</description>
    <fields>
        <fullName>Assignee_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assignment_Rules2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If this field is empty it will be pre-populated with the Product Owner for the rule&apos;s scrum team.</inlineHelpText>
        <label>Product Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assignment_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QA_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>QA Engineer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00NT0000000lhZjMAI</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scrum_Team_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scrum Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipName>R00NT0000000lhZkMAI</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Systest_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Performance Engineer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00NT0000000lhZlMAI</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tech_Writer_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tech Writer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00NT0000000lhZmMAI</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UE_Engineer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UE Engineer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assignment_Rules1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assignment Rule</label>
    <nameField>
        <label>Assignment Rule</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignment Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Product_Tag__c.object
<CustomObject>
    <label>TE Activity</label>
    <nameField>
        <label>TE Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TE Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Tag_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Assignment_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment Rule</label>
        <referenceTo>ADM_Assignment_Rule__c</referenceTo>
        <relationshipLabel>Tag Assignments</relationshipLabel>
        <relationshipName>Tag_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Tag__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Tag</label>
        <referenceTo>ADM_Product_Tag__c</referenceTo>
        <relationshipLabel>Tag Assignments</relationshipLabel>
        <relationshipName>Tag_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <label>Record Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bug</fullName>
                </value>
                <value>
                    <fullName>User Story</fullName>
                </value>
                <value>
                    <fullName>Investigation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tag Assignment</label>
    <nameField>
        <displayFormat>TA-{0000}</displayFormat>
        <label>Tag Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tag Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If you leave this field empty on save you will be the Assignee.</inlineHelpText>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assignee</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If you leave it empty on save you will be the Product Owner</inlineHelpText>
        <label>Product Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Product_Owner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Tag__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TE Activity</label>
        <referenceTo>ADM_Product_Tag__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Product_Tag</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QA_Engineer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>QA Engineer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QA_Engineer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <formula>$RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type of Record(Deprecated)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_RD_Mgr_Review__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Request Senior Mgr Review</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Senior_Management_POC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The person who gets engaged when an escalation of the current investigation occurs</description>
        <inlineHelpText>The person who gets engaged when an escalation of the current investigation occurs</inlineHelpText>
        <label>Senior Management POC</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Work5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Severity_Level__c</fullName>
        <label>Severity Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <color>#000099</color>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <color>#990000</color>
                    <label>2</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <color>#FF6600</color>
                    <label>3</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <color>#F3D904</color>
                    <label>4</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>System_Test_Engineer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Performance Engineer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>System_Test_Engineer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tech_Writer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tech Writer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Tech_Writer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bug</fullName>
                </value>
                <value>
                    <fullName>Gack</fullName>
                </value>
                <value>
                    <fullName>Help</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Test Change</fullName>
                </value>
                <value>
                    <fullName>Test Case</fullName>
                </value>
                <value>
                    <fullName>Test Failure</fullName>
                </value>
                <value>
                    <fullName>Test Tool</fullName>
                </value>
                <value>
                    <fullName>Skunkforce</fullName>
                </value>
                <value>
                    <fullName>Bug List</fullName>
                </value>
                <value>
                    <fullName>Translation</fullName>
                </value>
                <value>
                    <fullName>Non Deterministic Test</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UE_Engineer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UE Engineer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Work1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <recordTypes>
        <fullName>Bug</fullName>
        <active>true</active>
        <description>Used to track defects or problems</description>
        <label>Bug</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ADM_AutoAssignWorkActionTests.cls
@isTest
public with sharing class ADM_AutoAssignWorkActionTests {
	
	/**
	 * Given a tag with an assignment,
	 * if a bug is created with an empty assignment and linked to the 
	 * product tag
	 * then the action should set the work properties
	 * @author jared.pearson@
	 */
	/*
	@testcaseID a1DB00000001Wnq
	@hierarchy GUS.ScrumforceToGUS.Work Page.Product Tags.Work Page
	@userstory a07B0000000Lbao
	@Expected results Given a tag with an assignment, if a bug is created with an empty assignment and linked to the product tag then the action should set the work properties
	*/
	public static testMethod void testActionWithBug() {
		//create the product tag
		ADM_Product_Tag__c productTag = ADM_ProductTag.createAndInsertProductTag();
		
		//create the assignment rule
		ADM_Assignment_Rule__c assignmentRule = ADM_AssignmentRule.createAndInsertAssignmentRule();
        
        //create the tag assignment
        ADM_Tag_Assignment__c tagAssignment = new ADM_Tag_Assignment__c();
        tagAssignment.Assignment_Rule__c = assignmentRule.Id;
        tagAssignment.Product_Tag__c = productTag.Id;
        tagAssignment.Record_Type__c = ADM_Work.BUG_RECORD_TYPE_NAME;
        insert tagAssignment;
		
		//create the work
		ADM_Work__c work1 = ADM_Work.setupTestWork(ADM_Work.BUG_RECORD_TYPE_NAME);
		work1.Product_Tag__c = productTag.Id;
		work1.Assignee__c = null;
		work1.Tech_Writer__c = null;
		work1.QA_Engineer__c = null;
		work1.UE_Engineer__c = null;
		work1.Scrum_Team__c = null;
		work1.Product_Owner__c = null;
		work1.System_Test_Engineer__c = null;
		work1.Senior_Management_POC__c = null;
		insert work1;
		
		List<ADM_Work__c> works = new List<ADM_Work__c>{work1};
		
		ADM_AutoAssignWorkAction.applyAutoAssignmentRules(works);
		
		System.assertEquals(assignmentRule.Assignee_Assignment__c, work1.Assignee__c);
		System.assertEquals(assignmentRule.Product_Owner__c, work1.Product_Owner__c);
		System.assertEquals(assignmentRule.QA_Assignment__c, work1.QA_Engineer__c);
		System.assertEquals(assignmentRule.UE_Engineer__c, work1.UE_Engineer__c);
		System.assertEquals(assignmentRule.Systest_Assignment__c, work1.System_Test_Engineer__c);
		System.assertEquals(assignmentRule.Scrum_Team_Assignment__c, work1.Scrum_Team__c);
		System.assertEquals(null, work1.Senior_Management_POC__c, 'The senior management field should be null because request manager review is not checked');
	}
	
	/**
	 * Given a tag with an assignment,
	 * if a work record is created with an assignment and linked to the 
	 * product tag
	 * then the action should not replace the existing assignee
	 * @author jared.pearson@
	 */
	/*
	@testcaseID a1DB00000001Wnv
	@hierarchy GUS.ScrumforceToGUS.Work Page.Product Tags.Work Page
	@userstory a07B0000000Lbao
	@Expected results Given a tag with an assignment, if a work record is created with an assignment and linked to the product tag then the action should not replace the existing assignee
	*/
	public static testMethod void testActionShouldNotReplaceExisting() {
		
		//create the product tag
		ADM_Product_Tag__c productTag = ADM_ProductTag.createAndInsertProductTag();
		
		//create the assignment rule
		ADM_Assignment_Rule__c assignmentRule = ADM_AssignmentRule.createAndInsertAssignmentRule();
        
        //create the tag assignment
        ADM_Tag_Assignment__c tagAssignment = new ADM_Tag_Assignment__c();
        tagAssignment.Assignment_Rule__c = assignmentRule.Id;
        tagAssignment.Product_Tag__c = productTag.Id;
        tagAssignment.Record_Type__c = ADM_Work.BUG_RECORD_TYPE_NAME;
        insert tagAssignment;
		
		//create the work
		User assignee = ADM_WorkUser.createTestUser();
		ADM_Work__c work1 = ADM_Work.setupTestWork(ADM_Work.BUG_RECORD_TYPE_NAME);
		work1.Assignee__c = assignee.Id;
		work1.Product_Tag__c = productTag.Id;
		insert work1;
		
		List<ADM_Work__c> works = new List<ADM_Work__c>{work1};
		
		ADM_AutoAssignWorkAction.applyAutoAssignmentRules(works);
		
		System.assertEquals(assignee.Id, work1.Assignee__c, 'The assignee should not be replaced');
	}
	
	
	
	
	
	/**
	 * @author jared.pearson@
	 */
	/*
	@testcaseID a1DB00000001Wo1
	@hierarchy GUS.ScrumforceToGUS.Work Page.Product Tags.Work Page
	@userstory a07B0000000Lbao
	@Expected results Tech writer from assignment rule is added to both assignee and tech writer fields on help bugs
	*/
	public static testMethod void testActionOnHelpAssignToTechWriter() {
		
		//create the product tag
		ADM_Product_Tag__c productTag = ADM_ProductTag.createAndInsertProductTag();
		
		//create the assignment rule
		ADM_Assignment_Rule__c assignmentRule = ADM_AssignmentRule.createAndInsertAssignmentRule();
        
        //create the tag assignment
        ADM_Tag_Assignment__c tagAssignment = new ADM_Tag_Assignment__c();
        tagAssignment.Assignment_Rule__c = assignmentRule.Id;
        tagAssignment.Product_Tag__c = productTag.Id;
        tagAssignment.Record_Type__c = ADM_Work.BUG_RECORD_TYPE_NAME;
        insert tagAssignment;
		
		//create the work
		ADM_Work__c work1 = ADM_Work.setupTestWork(ADM_Work.BUG_RECORD_TYPE_NAME);
		work1.Assignee__c = null;
		work1.Product_Tag__c = productTag.Id;
		work1.Type__c = 'Help';
		
		List<ADM_Work__c> works = new List<ADM_Work__c>{work1};
		
		ADM_AutoAssignWorkAction.applyAutoAssignmentRules(works);
		
		System.assertEquals(assignmentRule.Tech_Writer_Assignment__c, work1.Assignee__c, 'The assignee should be the tech writer');
		System.assertEquals(assignmentRule.Tech_Writer_Assignment__c, work1.Tech_Writer__c, 'The tech writer should be the tech writer');
	}
	
	/**
	 * @author jared.pearson@
	 */
	/*
	@testcaseID a1DB00000001WoA
	@hierarchy GUS.ScrumforceToGUS.Work Page.Product Tags.Work Page
	@userstory a07B0000000Lbao
	@Expected results When creating a user story, tech writer is automatically added to the user story on create
	*/
	public static testMethod void testActionOnUserStoryAssignToTechWriter() {
		
		//create the product tag
		ADM_Product_Tag__c productTag = ADM_ProductTag.createAndInsertProductTag();
		
		//create the assignment rule
		ADM_Assignment_Rule__c assignmentRule = ADM_AssignmentRule.createAndInsertAssignmentRule();
        
        //create the tag assignment
        ADM_Tag_Assignment__c tagAssignment = new ADM_Tag_Assignment__c();
        tagAssignment.Assignment_Rule__c = assignmentRule.Id;
        tagAssignment.Product_Tag__c = productTag.Id;
        tagAssignment.Record_Type__c = ADM_Work.RECORD_TYPE_NAME_USERSTORY;
        insert tagAssignment;
		
		//create the work
		ADM_Work__c work1 = ADM_Work.setupTestWork(ADM_Work.RECORD_TYPE_NAME_USERSTORY);
		work1.Tech_Writer__c = null;
		work1.Product_Tag__c = productTag.Id;
		
		List<ADM_Work__c> works = new List<ADM_Work__c>{work1};
		
		ADM_AutoAssignWorkAction.applyAutoAssignmentRules(works);
		
		System.assertEquals(assignmentRule.Tech_Writer_Assignment__c, work1.Tech_Writer__c, 'The tech writer in the assignment rule should be applied the tech writer');
	}
	
    /**
     * Given a tag with an assignment,
     * if a bug is created with an empty assignment and linked to the 
     * product tag
     * then the action should set the work properties
     * @author jared.pearson@
     */
	/*
	@testcaseID a1DB00000001WoF
	@hierarchy GUS.ScrumforceToGUS.Work Page.Product Tags.Work Page
	@userstory a07B0000000Lbao
	@Expected results Given a tag with an assignment, if a bug is created with an empty assignment and linked to the  product tag then the action should set the work properties
	*/
    public static testMethod void testGetAssignmentsWithBug() {
        //create the product tag
        ADM_Product_Tag__c productTag = ADM_ProductTag.createAndInsertProductTag();
        
        //create the assignment rule
        ADM_Assignment_Rule__c assignmentRule = ADM_AssignmentRule.createAndInsertAssignmentRule();
        
        //create the tag assignment
        ADM_Tag_Assignment__c tagAssignment = new ADM_Tag_Assignment__c();
        tagAssignment.Assignment_Rule__c = assignmentRule.Id;
        tagAssignment.Product_Tag__c = productTag.Id;
        tagAssignment.Record_Type__c = ADM_Work.BUG_RECORD_TYPE_NAME;
        insert tagAssignment;
        
        //create the work
        ADM_Work__c work1 = ADM_Work.setupTestWork(ADM_Work.BUG_RECORD_TYPE_NAME);
        work1.Product_Tag__c = productTag.Id;
        work1.Assignee__c = null;
        work1.Tech_Writer__c = null;
        work1.QA_Engineer__c = null;
        work1.UE_Engineer__c = null;
        work1.Scrum_Team__c = null;
        work1.Product_Owner__c = null;
        work1.System_Test_Engineer__c = null;
        work1.Senior_Management_POC__c = null;
        insert work1;
        
        boolean isInvestigation = false;
        boolean isHelpType = false;
        RecordType recordType = [select id, Name from RecordType where Name =:ADM_Work.BUG_RECORD_TYPE_NAME limit 1];
        
        Test.startTest();
        ADM_AutoAssignWorkAction action = ADM_AutoAssignWorkAction.createActionForTags(new List<ADM_Product_Tag__c>{productTag});
        ADM_AutoAssignWorkAction.Assignment assignment = action.getAssignments(productTag, isInvestigation, isHelpType, work1.Request_RD_Mgr_Review__c, recordType, work1.Severity_Level__c);
        Test.stopTest();
        
        System.assertEquals(assignmentRule.Assignee_Assignment__c, assignment.Assignee.Id, 'Expected Assignee to match assignment rule');
        System.assertEquals(assignmentRule.Product_Owner__c, assignment.Product_Owner.Id, 'Expected Product Owner to match assignment rule');
        System.assertEquals(assignmentRule.QA_Assignment__c, assignment.QA_Engineer.Id, 'Expected QA Engineer to match assignment rule');
        System.assertEquals(assignmentRule.UE_Engineer__c, assignment.UE_Engineer.Id, 'Expected UE Engineer to match assignment rule');
        System.assertEquals(assignmentRule.Systest_Assignment__c, assignment.System_Test_Engineer.Id, 'Expected System Test Engineer to match assignment rule');
        System.assertEquals(null, assignment.Senior_Management_POC, 'The senior management field should be null because request manager review is not checked');
    }
    
	@IsTest
	private static User createOscUser() {
		return ADM_WorkUser.createTestOSCUser();
	}
}