mdapi-source/original-package/unpackaged/objects/ADM_User_Preferences__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Stores user preferences for the GUS application.</description>
    <fields>
        <fullName>LaneScrolling__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean value to set User&apos;s preference on Kanban Lane scrolling</description>
        <label>LaneScrolling</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ShowColoredSubjects__c</fullName>
        <defaultValue>false</defaultValue>
        <description>User Kanban Preference -  show colored subjects on the work card</description>
        <label>ShowColoredSubjects</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ShowNumberOfDaysInColumn__c</fullName>
        <defaultValue>true</defaultValue>
        <description>User Kanban Preference for showing number of days on Work card</description>
        <label>ShowNumberOfDaysInColumn</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ShowNumberOfPosts__c</fullName>
        <defaultValue>true</defaultValue>
        <description>User Kanban Preference -  show number of feed posts on work card</description>
        <label>ShowNumberOfPosts</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ShowNumberOfTasks__c</fullName>
        <defaultValue>true</defaultValue>
        <description>User Kanban Preference - to show number of Tasks</description>
        <label>ShowNumberOfTasks</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ShowPriority__c</fullName>
        <defaultValue>true</defaultValue>
        <description>User Kanban Preference  - Show Priority field on the Work card</description>
        <label>ShowPriority</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ShowQE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>User Kanban Preference -  show QE on Work Card</description>
        <label>ShowQE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ShowRecordTypeIcon__c</fullName>
        <defaultValue>true</defaultValue>
        <description>User Kanban Preference - Show RecordTypeIcon on work card</description>
        <label>ShowRecordTypeIcon</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ShowScheduledBuild__c</fullName>
        <defaultValue>true</defaultValue>
        <description>User Kanban Preference -  show Scheduled build on work card</description>
        <label>ShowScheduledBuild</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ShowStoryPoints__c</fullName>
        <defaultValue>true</defaultValue>
        <description>User Kanban Preference - show Story Points on the work card</description>
        <label>ShowStoryPoints</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ShowWorkID__c</fullName>
        <defaultValue>true</defaultValue>
        <description>User Kanban Preference - show Work Id on the work card</description>
        <label>ShowWorkID</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UseColorCoding__c</fullName>
        <defaultValue>true</defaultValue>
        <description>User Kanban Preference</description>
        <label>UseColorCoding</label>
        <type>Checkbox</type>
    </fields>
    <label>User Preferences</label>
</CustomObject>

force-app/main/default/classes/ADM_User.cls
public with sharing class ADM_User {
	public static boolean getUserLaneScrollingPreference(){
        ADM_User_Preferences__c userPreference = getCurrentUserPreference();
        return userPreference.LaneScrolling__c;
    }

    public static void setUserLaneScrollingPreference(boolean value){
        ADM_User_Preferences__c userPreference = getCurrentUserPreference();
        userPreference.LaneScrolling__c = value;
        upsert userPreference;
    }

    public static void saveKanbanWorkCardPreferences(ADM_KanbanPreferences kanbanPreferences){
    	ADM_User_Preferences__c userPreference = getCurrentUserPreference();
    	userPreference.UseColorCoding__c = kanbanPreferences.getUseColorCoding();
		userPreference.ShowNumberOfDaysInColumn__c = kanbanPreferences.getShowNumberOfDaysInColumn();
		userPreference.ShowNumberOfTasks__c = kanbanPreferences.getShowNumberOfTasks();
		userPreference.ShowNumberOfPosts__c = kanbanPreferences.getShowNumberOfPosts();
		userPreference.ShowPriority__c = kanbanPreferences.getShowPriority();
		userPreference.ShowScheduledBuild__c = kanbanPreferences.getShowScheduledBuild();
		userPreference.ShowStoryPoints__c = kanbanPreferences.getShowStoryPoints();
		userPreference.ShowColoredSubjects__c = kanbanPreferences.getShowColoredSubjects();
		userPreference.ShowWorkID__c = kanbanPreferences.getShowWorkID();
		userPreference.ShowRecordTypeIcon__c = kanbanPreferences.getShowRecordTypeIcon();
		userPreference.ShowQE__c = kanbanPreferences.getShowQE();

		upsert userPreference;
    }

    public static void setKanbanWorkCardPreferences(ADM_KanbanPreferences kanbanPreferences){
    	ADM_User_Preferences__c userPreference = getCurrentUserPreference();
    	kanbanPreferences.setUseColorCoding(userPreference.UseColorCoding__c);
		kanbanPreferences.setShowNumberOfDaysInColumn(userPreference.ShowNumberOfDaysInColumn__c);
		kanbanPreferences.setShowNumberOfTasks(userPreference.ShowNumberOfTasks__c);
		kanbanPreferences.setShowNumberOfPosts(userPreference.ShowNumberOfPosts__c);
		kanbanPreferences.setShowPriority(userPreference.ShowPriority__c);
		kanbanPreferences.setShowScheduledBuild(userPreference.ShowScheduledBuild__c);
		kanbanPreferences.setShowStoryPoints(userPreference.ShowStoryPoints__c);
		kanbanPreferences.setShowColoredSubjects(userPreference.ShowColoredSubjects__c);
		kanbanPreferences.setShowWorkID(userPreference.ShowWorkID__c);
		kanbanPreferences.setShowRecordTypeIcon(userPreference.ShowRecordTypeIcon__c); 
		kanbanPreferences.setShowQE(userPreference.ShowQE__c); 
    }

    public static ADM_User_Preferences__c getCurrentUserPreference(){
    	return ADM_User_Preferences__c.getInstance(UserInfo.getUserId());
    }

    public static boolean isCurrenUserSysAdmin(){
    	Profile profile = [SELECT Name From Profile WHERE Id = :UserInfo.getProfileId()];
        if ( profile.Name == 'System Administrator' ) {
        	return true;
        }
        else{
        	return false;
        }
    }
    // Roster record cloud update privilege only available for Roster_TPM and Roster_Finance group members
    public static boolean currentUserHasRosterCloudChangePrivilege(){
        Set<String> assigneeIds = getPermsetAssignees();
        return assigneeIds.contains(UserInfo.getUserId());
    }
    
    private static Set<String> getPermsetAssignees(){
        Set<String> assigneeIds = new Set<String>();
        if(Test.isRunningTest()){
            assigneeIds.add(UserInfo.getUserId());//Adding current user as Permset might not be added when running test
        }
        else{
        List<PermissionSetAssignment> permSetAssignees = [select AssigneeId from PermissionSetAssignment where permissionsetid in
                                                         (select id  from permissionset where name in ('Cloud_Technical_Program_Manager', 'Headcount_Finance'))];
            
        for(PermissionSetAssignment assignee: permSetAssignees){
            assigneeIds.add(assignee.AssigneeId);
        } 
        }
        
        return assigneeIds;
        
    }
}