mdapi-source/original-package/unpackaged/objects/ADM_Deleted_Task__c.object
<CustomObject>
    <description>Due to a lack of &quot;deletion&quot; events in the streaming API, we have to store the deleted tasks so subscribers can be notified.</description>
    <fields>
        <fullName>Task__c</fullName>
        <description>ID of the task. This is not a relationship field because the task will have been deleted by the time this record is created.</description>
        <label>Task</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work__c</fullName>
        <description>ID of the work item. This is not a relationship field because the work record may be deleted by the time this value is needed.</description>
        <label>Work</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Deleted Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deleted Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/classes/ADM_SprintDetailExtension.cls
public with sharing class ADM_SprintDetailExtension {
    
    public ADM_SprintDetailExtension(ApexPages.StandardController stdController) {
    }
    
    /**
     * Ensure the push topics used by the page are created
     */
    public void ensurePushTopics() {
        ADM_Work.ensureWorkUpdatesPushTopic();
        ADM_Task.ensureTaskUpdatesPushTopic();
        ensureDeletedTaskUpdatesPushTopic();
        ADM_Sprint.ensureSprintUpdatesPushTopic();
        ADM_Work.ensureWorkHistoryPushTopic();
    }
    
    private static void ensureDeletedTaskUpdatesPushTopic() {
        String name = 'DeletedTaskUpdates';
        String query = 'select Id, Name, Work__c, Task__c, LastModifiedDate from ADM_Deleted_Task__c';
        query = COM_SoqlUtils.convertToQualifiedQuery(query);
        ADM_PushTopic.ensurePushTopic(name, query, 25, 'All', 'All');
    }
    
    public Boolean getCurrentUserLightningDesktopPreference() {
        return ADM_ConstantsSingleton.getInstance().getUserLightningExperiencePreferred();
    }

}