mdapi-source/original-package/unpackaged/objects/ADM_Product_Tag__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipName>Product_Tags</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TE Activity</label>
    <nameField>
        <label>TE Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TE Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Scrum_Team__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Program</fullName>
                    <default>true</default>
                    <label>Program</label>
                </value>
                <value>
                    <fullName>Program of Programs</fullName>
                </value>
                <value>
                    <fullName>Portfolio</fullName>
                </value>
                <value>
                    <fullName>Workrgoup</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Sprint__c.object
<CustomObject>
    <customHelpPage>ADM_CreateSprintOverview</customHelpPage>
    <description>Added to support User Story for Scrumforce integration into GUS.</description>
    <fields>
        <fullName>Completed_Story_Points__c</fullName>
        <label>Velocity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scrum Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Sprints</relationshipLabel>
        <relationshipName>Sprints</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Found_in_Build__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Found In Build field is a lookup to the Build object.  Enter the build where the bug was introduced.</inlineHelpText>
        <label>Found in Build</label>
        <referenceTo>ADM_Build__c</referenceTo>
        <relationshipLabel>Work (Found in Build)</relationshipLabel>
        <relationshipName>Found_in_Build</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Frequency reflects how often the target user will encounter the issue.</inlineHelpText>
        <label>Frequency</label>
        <referenceTo>ADM_Frequency__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Impact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Impact</label>
        <referenceTo>ADM_Impact__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority_Rank__c</fullName>
        <label>Backlog Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Tag__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TE Activity</label>
        <referenceTo>ADM_Product_Tag__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Product_Tag</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scheduled_Build__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Scheduled Build field is a lookup to the Build object.  Enter a pre-existing build where the change will be made.</inlineHelpText>
        <label>Scheduled Build</label>
        <referenceTo>ADM_Build__c</referenceTo>
        <relationshipLabel>Work (Scheduled Build)</relationshipLabel>
        <relationshipName>Scheduled_Build</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sprint</label>
        <referenceTo>ADM_Sprint__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Triaged</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Investigating</fullName>
                </value>
                <value>
                    <fullName>Ready for Review</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>QA In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Defunct</fullName>
                </value>
                <value>
                    <fullName>Closed - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Closed - Eng Internal</fullName>
                </value>
                <value>
                    <fullName>Closed - Known Bug Exists</fullName>
                </value>
                <value>
                    <fullName>Closed - New Bug Logged</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Approved</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Denied</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved With Internal Tools</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved Without Code Change</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Working as Designed</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Feature Request</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Will Not Fix</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Pending Release</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>More Info Reqd from Support</fullName>
                </value>
                <value>
                    <fullName>Never</fullName>
                </value>
                <value>
                    <fullName>Not a bug</fullName>
                </value>
                <value>
                    <fullName>Not Reproducible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bug</fullName>
                </value>
                <value>
                    <fullName>Gack</fullName>
                </value>
                <value>
                    <fullName>Help</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Test Change</fullName>
                </value>
                <value>
                    <fullName>Test Case</fullName>
                </value>
                <value>
                    <fullName>Test Failure</fullName>
                </value>
                <value>
                    <fullName>Test Tool</fullName>
                </value>
                <value>
                    <fullName>Skunkforce</fullName>
                </value>
                <value>
                    <fullName>Bug List</fullName>
                </value>
                <value>
                    <fullName>Translation</fullName>
                </value>
                <value>
                    <fullName>Non Deterministic Test</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Use_Prioritizer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to determine whether or not a work record should be shown on the Work Prioritizer page</description>
        <inlineHelpText>Used to determine whether or not a work record should be shown on the Work Prioritizer page</inlineHelpText>
        <label>Include in Prioritize View</label>
        <type>Checkbox</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <recordTypes>
        <fullName>Bug</fullName>
        <active>true</active>
        <description>Used to track defects or problems</description>
        <label>Bug</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ADM_PriorExtTestRemoting.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class ADM_PriorExtTestRemoting {
    private static String lorem = 'lorem ipsum dolor sit amet';

    @IsTest
    private static ADM_PriorExt setupPrioritizer() {
        List<ADM_Work__c> recs = new List<ADM_Work__c>();
        List<ADM_Sprint__c> sprints = new List<ADM_Sprint__c>();
        ADM_Work__c work = ADM_Work.createTestWork('Bug');
        ADM_Scrum_Team__c team = ADM_ScrumTeam.createTestScrumTeam(); 
        ADM_Product_Tag__c tag = [select id, Team__c from ADM_Product_Tag__c where id =:work.Product_Tag__c];
        tag.Team__c = team.id;
        update tag;
        work.Product_Tag__c = tag.id;
        update work;
        work = [select id, Subject__c, Status__c, Use_Prioritizer__c, Found_In_Build__c, Scheduled_Build__c, Type__c, Impact__c, Frequency__c, Scrum_Team__c, Sprint__c, Product_Tag__c from ADM_Work__c where id=:work.id];
        System.assertEquals(work.Scrum_Team__c, team.id);
        
        ADM_Sprint__c sprint;
        
        
        
        for(Integer i = 0; i < 3; i++) {
            ADM_Work__c w = work.clone(false, false);
            w.Use_Prioritizer__c = true;
            w.Priority_Rank__c = null;
            recs.add(w);
        }
        
        //repeat but add a priority rank
        for(Integer j = 1; j < 2; j++) {
            ADM_Work__c w = work.clone(false, false);
            w.Use_Prioritizer__c = true;
            w.Priority_Rank__c = j;
            recs.add(w);
        }
        
        insert recs;
        
        
        String sprintName = '';
        List<String> alpha = new List<String>{'a','b','c','d','e','f','g','h','i','j','k'};
        
        for(Integer i = 0; i < 7; i++) {
            sprint = new ADM_Sprint__c();
            
            if(i == 6) {
                sprint.Start_Date__c = Date.today().addDays(-1);
                sprint.End_Date__c = Date.today();
            } else {
                sprint.Start_Date__c = Date.today().addDays(-100 - i - 1);
                sprint.End_Date__c = Date.today().addDays(-100 - i);
                sprint.Completed_Story_Points__c = i;   
            }
            
            sprintName = String.valueOf(sprint.Start_Date__c.month());
            
            if(sprintName.length() == 1) {
                sprintName = '0' + sprintName;
            }
            
            sprintName = sprint.Start_Date__c.year() + '.' + sprintName;
            
            if(i == 6) {
                sprintName += alpha.get(0);
            } else {
                sprintName += alpha.get(i);
            }
            
            sprintName += '-' + team.Name;
            sprint.Name = sprintName;
            sprint.Scrum_Team__c = team.Id;
            
            sprints.add(sprint);                
        }
        
        insert sprints; 
        
        System.debug('-->' + work.Scrum_Team__c);
        
        System.currentPageReference().getParameters().put('scrumteamId', team.id);
        Apexpages.Standardcontroller ctrl = new Apexpages.Standardcontroller(work);
        ADM_PriorExt ext = new ADM_PriorExt(ctrl);
        
        System.assertEquals(work.Scrum_Team__c, ext.teamId);
        
        return ext;     
    }
    
    /*
    @testcaseID a1DB000000018or
    @userstoryID a07B0000000Eq0GIAS
    @hierarchy GUS.ScrumforceToGUS.ScrumTeams.Prioritizer.In-Row Edit Bug
    @Expected Results Error message is generated that Sprint is invalid. Other changes made on the details view are not lost
    @ Author: Alexis Williams 
    */
 
     /*
    @testcaseID a1DB000000018os
    @userstoryID a07B0000000Eq0GIAS
    @hierarchy GUS.ScrumforceToGUS.ScrumTeams.Prioritizer.In-Row Edit Bug
    @Expected Results Error message is generated that Theme is invalid. Other changes made on the details view are not lost
    @ Author: Alexis Williams 
    */

     /*
    @testcaseID a1DB000000018ox
    @userstoryID a07B0000000Eq0GIAS
    @hierarchy GUS.ScrumforceToGUS.ScrumTeams.Prioritizer.In-Row Edit Bug
    @Expected Results The Subject saves normally
    @ Author: Alexis Williams 
    */


     /*
    @testcaseID a1DB000000018p2
    @userstoryID a07B0000000Eq0GIAS
    @hierarchy GUS.ScrumforceToGUS.ScrumTeams.Prioritizer.In-Row Edit User Story
    @Expected Results User can save changes when in-row editing a user story in the Prioritizer
    @ Author: Alexis Williams 
    */


    /*
    @testcaseID a1DB000000018ow
    @userstoryID a07B0000000Eq0GIAS
    @hierarchy GUS.ScrumforceToGUS.ScrumTeams.Prioritizer.In-Row Edit Bug
    @Expected Results Error is generated
    @ Author: Alexis Williams 
    */
    static testMethod void testUpdateWorkVals() {
        ADM_PriorExt ext = setupPrioritizer();
        ADM_Work__c work = ext.backlogRecs.get(0);
        ADM_DmlResult result;
        String workId, subject, details, status;
        
        //#1 Call method without any valid values       
        result = ADM_PriorExt.updateWorkVals(workId, subject, details, status);
        System.assertEquals(null, result);
        
        //#2 Call without any valid subject, details, or status & a valid workId
        result = ADM_PriorExt.updateWorkVals(work.Id, subject, details, status);
        System.assertEquals(null, result);
        
        //#3 Call with valid subject only
        subject = 'Test';
        result = ADM_PriorExt.updateWorkVals(workId, subject, details, status);
        System.assertEquals(null, result);
        
        //#4 Call with valid details only
        details = 'Test';
        subject = null;
        result = ADM_PriorExt.updateWorkVals(workId, subject, details, status);
        System.assertEquals(null, result);
        
        //#5 Call with valid status only
        details = null;
        status = 'New';
        subject = null;     
        result = ADM_PriorExt.updateWorkVals(workId, subject, details, status);
        System.assertEquals(null, result); 
    }
    
 

    

    
   
    
}