mdapi-source/original-package/unpackaged/objects/ADM_Build__c.object
<CustomObject>
    <label>Build</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Builds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Product_Tag__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipName>Product_Tags</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TE Activity</label>
    <nameField>
        <label>TE Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TE Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Scrum_Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Details__c</fullName>
        <inlineHelpText>User type (As a...) Goal (I want to...) Reason (so that...) Additional Details</inlineHelpText>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Details_and_Steps_to_Reproduce__c</fullName>
        <inlineHelpText>Text contents of this field will be sent in initial record creation only</inlineHelpText>
        <label>Details and Steps to Reproduce</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Found_in_Build__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Found In Build field is a lookup to the Build object.  Enter the build where the bug was introduced.</inlineHelpText>
        <label>Found in Build</label>
        <referenceTo>ADM_Build__c</referenceTo>
        <relationshipLabel>Work (Found in Build)</relationshipLabel>
        <relationshipName>Found_in_Build</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <inlineHelpText>For bugs, priority is automatically determined based upon the combination of Impact and Frequency.

For user stories, P0 represents the highest priority, P4 the lowest.</inlineHelpText>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>P0</fullName>
                    <color>#0B6FCE</color>
                    <label>P0</label>
                </value>
                <value>
                    <fullName>P1</fullName>
                    <color>#FF0000</color>
                    <label>P1</label>
                </value>
                <value>
                    <fullName>P2</fullName>
                    <color>#E27001</color>
                    <label>P2</label>
                </value>
                <value>
                    <fullName>P3</fullName>
                    <color>#FFFF66</color>
                    <label>P3</label>
                </value>
                <value>
                    <fullName>P4</fullName>
                    <color>#78C953</color>
                    <label>P4</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Tag__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TE Activity</label>
        <referenceTo>ADM_Product_Tag__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Product_Tag</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <recordTypes>
        <fullName>Bug</fullName>
        <active>true</active>
        <description>Used to track defects or problems</description>
        <label>Bug</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/classes/ADM_WorkCreatorRestService.cls
@RestResource(urlMapping='/CreateWork/*')
global with sharing class ADM_WorkCreatorRestService{

    static Set<String> fieldsToCheck = new Set<String>{'Subject__c', 'Product_Tag__c', 'Found_in_Build__c', 'Priority__c', 'Details_and_steps_to_Reproduce__c',
                                            'Details__c' };
    static boolean arefieldsAccessibleOnWorkObject = true;
    static boolean arefieldsCreatableOnWorkObject = true;
    static boolean isPtagObjectQueryable = true;
    static boolean isBuildObjectQueryable = true;

    @HttpPost  
    global static ADM_WorkCreatorRestService.Result createWork(String subject, String ptag, String team,String type, String finBuild, String priority, String description, String details, String image) {
        Result result = new Result();
        if(validateUserPerm()){
            ADM_Work__c work = new ADM_Work__c();
            work.Subject__c = subject;
            RecordType rType = ADM_RecordType.getByName(type, 'ADM_Work__c');
            if(rType != null){
               work.RecordTypeId = rType.Id;
               String soqlPTag= 'select id, name from adm_product_tag__c where name=:ptag and team__c in (select id from ADM_Scrum_Team__c where name = :team) limit 1' ;
               List<ADM_Product_Tag__c> ptags =  Database.query(soqlPTag );
               if(ptags != null && ptags.size() >0){
                work.Product_Tag__c = ptags[0].Id;
               }
               else{
                 result.getErrorMessages().add('Cannot find a Product tag with name "' + ptag.escapeHTML4() + '" which belongs to team "'+ team.escapeHTML4() +'"') ;
               }
               if(rType.Name.equalsIgnoreCase('bug')){
                    String fBuildsoql= 'select id, name from adm_Build__c where name=:finBuild limit 1' ;
                    List<ADM_Build__c> builds = Database.query(fBuildsoql);
                    
                    if (builds.size() > 0){
                    work.Found_in_Build__c = builds[0].Id;
                    }
                    else{
                            result.getErrorMessages().add( 'Cannot find build with name "' + finBuild.escapeHTML4() + '"');
                    }
                    work.Priority__c = priority;
                    work.Details_and_steps_to_Reproduce__c = details;
                    
                }
                else{
                    work.Details__c = description;
                    work.RecordTypeId = [Select id from RecordType where name = 'User Story'].Id;
                }
                
                if(result.getErrorMessages().size() == 0){
                    insert work;
                    result.setId(work.id);
                }
 
                if ( ( work.Id != null ) && (image != null ) &&  ( image.length() > 0 )){
                    Attachment attachment = new Attachment();
                    attachment.ContentType = 'image/jpg';
                    attachment.Name = 'screen-capture.jpg';
                    attachment.ParentId = work.Id;                   
                    attachment.Body = EncodingUtil.base64Decode(image);
                    insert attachment;
                } 
            }
        }
        else{
            result.getErrorMessages().add('User has insufficient access');
        }
        
        
        return (result);  
    }

    private static boolean validateUserPerm(){
        arefieldsAccessibleOnWorkObject = ADM_SchemaManager.areFieldsAccessible('ADM_Work__c', fieldsToCheck);
        arefieldsCreatableOnWorkObject = ADM_SchemaManager.areFieldsCreateable('ADM_Work__c', fieldsToCheck);
        isPtagObjectQueryable = ADM_SchemaManager.isObjectQueryable('ADM_Product_Tag__c');
        isBuildObjectQueryable = ADM_SchemaManager.isObjectQueryable('ADM_Build__c');

        return (arefieldsAccessibleOnWorkObject && arefieldsCreatableOnWorkObject && isPtagObjectQueryable && isBuildObjectQueryable);

    }
    
    
    global class Result{
        String id;
        List<String> errorMessages = new List<String>();
        global void setId(String id){
            this.id = id;
        }

        global List<String> getErrorMessages(){
            return this.errorMessages;
        }
    }

}