mdapi-source/original-package/unpackaged/objects/ADM_Release__c.object
<CustomObject>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Released_In__c.object
<CustomObject>
    <description>Object to define the releases that a fix was deployed to.  Each Work record has a one to many relationship with releases.</description>
    <fields>
        <fullName>Release__c</fullName>
        <label>Release</label>
        <referenceTo>ADM_Release__c</referenceTo>
        <relationshipName>Release</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reverted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reverted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Work__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work ID</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipName>WorkReleasedIn</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Released In</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Released In #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Released In</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ADM_StampBatch.cls
public class ADM_StampBatch  implements Database.Batchable<Sobject>{
    String releaseFrom;
    String releaseTo;
    String query;
    ADM_Release__c relFrom = new ADM_Release__c();
    ADM_Release__c relTo = new ADM_Release__c();

    public ADM_StampBatch(String releaseFrom, String releaseTo, String query) {
      this.releaseFrom = releaseFrom;
      this.releaseTo = releaseTo;
      this.query = query;
      List<ADM_Release__c> releases = ADM_Release.getAllBy('Id', new Set<String>{releaseFrom, releaseTo});
      for(ADM_Release__c release : releases) {
        if(release.Id == releaseFrom) {
            relFrom = release;
        } else if(release.Id == releaseTo) {
            relTo = release;
        }
      }
    }

    public Database.Querylocator start(Database.BatchableContext BC) {
      return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<Sobject> scope) {
      List<ADM_Released_In__c> stamps = new List<ADM_Released_In__c>();
      List<ADM_Released_In__c> stamps2 = new List<ADM_Released_In__c>();
      stamps2 = [select Work__c from ADM_Released_In__c where Release__c = : releaseTo];
      Map<String,ADM_Released_In__c> stamps2map = new Map<String,ADM_Released_In__c>();
      for(ADM_Released_In__c stamp2 : stamps2) {
        stamps2map.put(stamp2.Work__c, stamp2);
      }

      for(Sobject s : scope) {
         ADM_Released_In__c stamp = new ADM_Released_In__c();
         String workId = String.valueOf(s.get('Work__c'));
         if(!stamps2map.containsKey(workId)) {
           stamp.Work__c = workId;
           stamp.Release__c = releaseTo;
           stamp.Reverted__c = Boolean.valueOf(s.get('Reverted__c'));
           stamps.add(stamp);
         }
      }
      if(stamps.isEmpty()) {
      } else {
        Database.insert(stamps,false);
      }
    }

    public void finish(Database.BatchableContext BC) {
        Messaging.Singleemailmessage mail = new Messaging.Singleemailmessage();
        User user = ADM_WorkUser.get(Userinfo.getUserId());
        mail.setToAddresses(new String[] {user.Email});
        mail.setReplyTo(user.Email);
        mail.setSenderDisplayName('Release Stamp Batch');
        mail.setSubject('Completed copying release stamps from release, ' + relFrom.Name  + ', to release, ' + relTo.Name + '.');
        mail.setPlainTextBody(mail.getSubject());
        Messaging.sendEmail(new Messaging.Singleemailmessage[] {mail});
    }
}