mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Closed_On__c</fullName>
        <label>Closed On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Product_Tag__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TE Activity</label>
        <referenceTo>ADM_Product_Tag__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Product_Tag</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Triaged</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Investigating</fullName>
                </value>
                <value>
                    <fullName>Ready for Review</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>QA In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Defunct</fullName>
                </value>
                <value>
                    <fullName>Closed - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Closed - Eng Internal</fullName>
                </value>
                <value>
                    <fullName>Closed - Known Bug Exists</fullName>
                </value>
                <value>
                    <fullName>Closed - New Bug Logged</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Approved</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Denied</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved With Internal Tools</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved Without Code Change</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Working as Designed</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Feature Request</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Will Not Fix</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Pending Release</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>More Info Reqd from Support</fullName>
                </value>
                <value>
                    <fullName>Never</fullName>
                </value>
                <value>
                    <fullName>Not a bug</fullName>
                </value>
                <value>
                    <fullName>Not Reproducible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <recordTypes>
        <fullName>Bug</fullName>
        <active>true</active>
        <description>Used to track defects or problems</description>
        <label>Bug</label>
    </recordTypes>
    <recordTypes>
        <fullName>Investigation</fullName>
        <active>true</active>
        <description>Used to request R&amp;D triage/diagnosis support for a customer support escalation</description>
        <label>Investigation</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ADM_ThroughputChartTest.cls
@isTest
private class ADM_ThroughputChartTest {
	
	@isTest static void testGetThroughputChartForTeamAndGivenNumberOfWeeks() {
		List<ADM_Work__c> listOfWorks = new List<ADM_Work__c>();
		ADM_Work__c bug1 = ADM_Work.setupTestWork('Bug');
		listOfWorks.add(bug1);

		ADM_Work__c us1 = ADM_Work.setupTestWork('User Story');
		us1.Product_Tag__c = bug1.Product_Tag__c;
		us1.Scrum_Team__c = bug1.Scrum_Team__c;
		listOfWorks.add(us1);


		
		ADM_Work__c inv1 = ADM_Work.setupTestWork('Investigation');
		inv1.Product_Tag__c = bug1.Product_Tag__c;
		inv1.Scrum_Team__c = bug1.Scrum_Team__c;
		listOfWorks.add(inv1);

		insert listOfWorks;


		ADM_ThroughputChart.initializeThroughputData();
		
		listOfWorks = new List<ADM_Work__c>();
		bug1.Status__c='Closed';
		listOfWorks.add(bug1);
		us1.Status__c = 'Closed';
		listOfWorks.add(us1);
		inv1.Status__c = 'Closed - Defunct';
		listOfWorks.add(inv1);
		update listOfWorks;

		listOfWorks = new List<ADM_Work__c>();
		DateTime startofLastWeek = ADM_ThroughputChart.findStartOfPreviousWeek(Datetime.now());
		Datetime newDate = startofLastWeek.addDays(1);
		bug1.Closed_On__c = newDate;
		listOfWorks.add(bug1);
		us1.Closed_On__c = newDate.addDays(-5);
		listOfWorks.add(us1);
		inv1.Closed_On__c = newDate.addDays(-14);
		listOfWorks.add(inv1);
		update listOfWorks;

		ADM_Chart chart = ADM_ThroughputChart.getThroughputChartForTeamAndGivenNumberOfWeeks(12,bug1.Scrum_Team__c);

		System.assertEquals('Number of Work Items Closed',chart.getYAxis().getTitle());
		System.assertEquals('',chart.getXAxis().getTitle());
		System.assertEquals(12,chart.getXAxis().getCategories().size());
		System.assertEquals(startofLastWeek.addDays(6).format('M/d/YYYY'),chart.getXAxis().getCategories().get(11));

		System.assertEquals(3,chart.getSeriesList().size());

		for (ADM_Chart.Series series : chart.getSeriesList()){
			if(series.name == 'User Stories'){
				System.assertEquals(1,series.data.get(10));
			}
			if(series.name == 'Bugs'){
				System.assertEquals(1,series.data.get(11));
			}
			if(series.name == 'Investigations'){
				System.assertEquals(1,series.data.get(9));
			}
		}


	}
	
}