mdapi-source/original-package/unpackaged/objects/ADM_Sprint__c.object
<CustomObject>
    <customHelpPage>ADM_CreateSprintOverview</customHelpPage>
    <description>Added to support User Story for Scrumforce integration into GUS.</description>
    <fields>
        <fullName>Completed_Story_Points__c</fullName>
        <label>Velocity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Days_Remaining__c</fullName>
        <formula>IF( TODAY() &lt; Start_Date__c, &apos;NOT STARTED&apos;, IF( End_Date__c &gt;= TODAY(), TEXT( ROUND(End_Date__c - TODAY(), 0) + 1 ), &apos;CLOSED&apos; ) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days Remaining</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hours_in_a_work_day__c</fullName>
        <defaultValue>6</defaultValue>
        <label>Hours in a work day</label>
        <precision>3</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scrum Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Sprints</relationshipLabel>
        <relationshipName>Sprints</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sprint</label>
        <referenceTo>ADM_Sprint__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Story_Points__c</fullName>
        <inlineHelpText>If you leave it empty on save it will automatically assign the value from the TE activity selected.</inlineHelpText>
        <label>Story Points</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/classes/ADM_SprintChartsController.cls
global with sharing class ADM_SprintChartsController {
	public ADM_SprintChartsController() {}
	private static Integer DEFAULT_SPRINTS = 6;
	private static Integer MAX_SPRINTS = 10; 
	private static Integer TOTAL_SPRINTS = 0;
	
	public String m_teamId { get; set; }
	public String m_sprintId { get; set; }
	
	public static transient String numSprints;
	
	public String getNumSprints() {
		return numSprints;
	}
	
	public void setNumSprints(String s) {
		numSprints = s;
	}
    
    public static ADM_Cookie cookie;
    
    public ADM_Cookie getCookie() {
    	return cookie;
    }
    
    public List<ADM_Sprint__c> sprints { 
        get {
        	if(sprints == null) {
	            sprints = new List<ADM_Sprint__c>();	                
	            if(m_teamId != null) {
					sprints = getMySprints(String.valueOf(m_teamId + ',' + 6));
	            }
        	}
            return sprints;
        } 
        set; 
    }
	
	private static List<AggregateResult> getAggregateResults(String sprintId) {
		List<AggregateResult> results = new List<AggregateResult>();				
		for(AggregateResult result : [select Sprint__c, SUM(Story_Points__c) summ from ADM_Work__c where Sprint__c = :sprintId group by Sprint__c]) {
			results.add(result);
		}
		return results;				
	}
	
	private static List<ADM_Sprint__c> getMySprints(String teamIdAndNumSprints) {
		String teamId;
		Integer num;
		Integer breakPt;
		Integer maxNum = 10;
		
		List<String> results = teamIdAndNumSprints.split(',');
        List<ADM_Sprint__c> sprintResults = new List<ADM_Sprint__c>();
        List<ADM_Sprint__c> sprints2Return = new List<ADM_Sprint__c>();
        
        if(results.size() == 2) {
        	teamId = results.get(0);
        	num = Integer.valueOf(results.get(1));
        	
        	sprintResults = [select a.Hours_in_a_work_day__c, a.Name, a.Start_Date__c, a.End_Date__c, a.Days_Remaining__c, a.Completed_Story_Points__c from ADM_Sprint__c a where a.Completed_Story_Points__c != null and a.Scrum_Team__c = :teamId and a.Days_Remaining__c like 'CLOSED%' order by a.End_Date__c desc limit 10];
        	
        	TOTAL_SPRINTS = sprintResults.size();
        	
        	if(num > TOTAL_SPRINTS || num < 2) {
        		breakPt = DEFAULT_SPRINTS;        		
        	} else {
        		breakPt = num;
        	}
        	
	        for(ADM_Sprint__c sprintResult : sprintResults) {
	            sprints2Return.add(sprintResult);
	            if(sprints2Return.size() == breakPt) break;
	        }
	        
	        numSprints = teamId + ',' + sprints2Return.size();
	        cookie = new ADM_Cookie('s2v' + teamId, teamId + ',' + sprints2Return.size());
        }     
           
        return sprints2Return;
	}
	
	@RemoteAction 
	global static Integer getTotalSprints(String teamId) {
		Integer counter = [select count() from ADM_Sprint__c a where a.Completed_Story_Points__c != null and a.Scrum_Team__c = :teamId and a.Days_Remaining__c like 'CLOSED%' limit 10];
		return counter;
	}
	
	@RemoteAction
	global static List<ADM_Sprint__c> getCurrSprints(String teamId) {
		List<ADM_Sprint__c> results = getMySprints(teamId);
		return results;	
	}
	
	@RemoteAction 
	global static String getCurrSprintPoints(String sprintId) {
		List<AggregateResult> results = getAggregateResults(sprintId);		
		String currSprintPoints = '0'; 
		
		for(AggregateResult result : results) {
			currSprintPoints = String.valueOf(result.get('summ'));
		}
		
		if(currSprintPoints == null) currSprintPoints = '0';
		
		return currSprintPoints;			
	}
	
	public List<Selectoption> getNumAvailSprints() {
        List<Selectoption> options = new List<Selectoption>();

        for(Integer i = 2; i <= TOTAL_SPRINTS; i++) {
            options.add(new SelectOption(String.valueOf(m_teamId + ',' + i), String.valueOf(i)));
            if(i == TOTAL_SPRINTS) break;
        }

        return options;
    }
}