mdapi-source/original-package/unpackaged/objects/ADM_Build__c.object
<CustomObject>
    <label>Build</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Builds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Scrum_Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Age_With_Scrum_Team__c</fullName>
        <description>Age with Scrum Team is the difference between now and the last time the Scrum Team field was modified. This calculation excludes weekends.</description>
        <formula>IF(ISNULL(Scrum_Team_Last_Modified__c), null,
CASE(MOD( TODAY() - DATE(1985,6,24),7),
0 , CASE( MOD( TODAY() - DATEVALUE(Scrum_Team_Last_Modified__c) ,7),1,0,2,0,3,1,4,2,5,3,6,4,0),
1 , CASE( MOD( TODAY() - DATEVALUE(Scrum_Team_Last_Modified__c) ,7),1,1,2,1,3,1,4,2,5,3,6,4,0),
2 , CASE( MOD( TODAY() - DATEVALUE(Scrum_Team_Last_Modified__c) ,7),1,1,2,2,3,2,4,2,5,3,6,4,0),
3 , CASE( MOD( TODAY() - DATEVALUE(Scrum_Team_Last_Modified__c) ,7),1,1,2,2,3,3,4,3,5,3,6,4,0),
4 , CASE( MOD( TODAY() - DATEVALUE(Scrum_Team_Last_Modified__c) ,7),1,1,2,2,3,3,4,4,5,4,6,4,0),
5 , CASE( MOD( TODAY() - DATEVALUE(Scrum_Team_Last_Modified__c) ,7),1,0,2,1,3,2,4,3,5,4,6,0,0),
6 , CASE( MOD( TODAY() - DATEVALUE(Scrum_Team_Last_Modified__c) ,7),1,0,2,0,3,1,4,2,5,3,6,4,0),
999)
+
(FLOOR(( TODAY() - DATEVALUE(Scrum_Team_Last_Modified__c) )/7)*5)
)</formula>
        <inlineHelpText>Age with Scrum Team is the difference between now and the last time the Scrum Team field was modified. This calculation excludes weekends.</inlineHelpText>
        <label>Age With Scrum Team</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Age__c</fullName>
        <description>Age is the difference between now and when the record was created if the record has not been resolved; otherwise, age is the difference between now and when the record was resolved. The age is removed once the record is closed.</description>
        <formula>IF(
    ISNULL(Resolved_On__c), (NOW() - Created_On_import__c),
    IF(
        ISNULL(Closed_On__c), (NOW() - Resolved_On__c), null
    )
)</formula>
        <inlineHelpText>Age is the difference between now and when the record was created if the record has not been resolved; otherwise, age is the difference between now and when the record was resolved. The age is removed once the record is closed.</inlineHelpText>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Created_On_import__c</fullName>
        <description>Data/time imported from the original bug from bugforce.</description>
        <label>Created On (import)</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Found_in_Build__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Found In Build field is a lookup to the Build object.  Enter the build where the bug was introduced.</inlineHelpText>
        <label>Found in Build</label>
        <referenceTo>ADM_Build__c</referenceTo>
        <relationshipLabel>Work (Found in Build)</relationshipLabel>
        <relationshipName>Found_in_Build</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scrum_Team_Last_Modified__c</fullName>
        <defaultValue>Now()</defaultValue>
        <description>Stores the last time the Scrum Team field was modified</description>
        <inlineHelpText>Stores the last time the Scrum Team field was modified</inlineHelpText>
        <label>Scrum Team Last Modified</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Triaged</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Investigating</fullName>
                </value>
                <value>
                    <fullName>Ready for Review</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>QA In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Defunct</fullName>
                </value>
                <value>
                    <fullName>Closed - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Closed - Eng Internal</fullName>
                </value>
                <value>
                    <fullName>Closed - Known Bug Exists</fullName>
                </value>
                <value>
                    <fullName>Closed - New Bug Logged</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Approved</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Denied</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved With Internal Tools</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved Without Code Change</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Working as Designed</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Feature Request</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Will Not Fix</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Pending Release</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>More Info Reqd from Support</fullName>
                </value>
                <value>
                    <fullName>Never</fullName>
                </value>
                <value>
                    <fullName>Not a bug</fullName>
                </value>
                <value>
                    <fullName>Not Reproducible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Age_When_Closed__c</fullName>
        <formula>IF(ISBLANK(Closed_On__c), 0, IF( Created_On_Date__c &gt; DATEVALUE(Closed_On__c), 0, DATEVALUE(Closed_On__c) - Created_On_Date__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Age When Closed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <recordTypes>
        <fullName>Bug</fullName>
        <active>true</active>
        <description>Used to track defects or problems</description>
        <label>Bug</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ADM_AgeOfWorkTests.cls
@IsTest
public with sharing class ADM_AgeOfWorkTests {



	/*  

	  @testcaseID a0B20000007m1cREAQ

	  @hierarchy GUS.BugforceToGUS.Work Page.BugsCreatedInGus.Bug Age

	  @userstory TO BE ADDED

	  @expectedResults: Scrum Team Last Modified field is updated 
	  
	  @author jhatton

	*/ 
	
	/* 

	  @testcaseID a0B20000007m1qFEAQ

	  @hierarchy GUS.BugforceToGUS.Work Page.BugsCreatedInGus.Bug Age

	  @userstory TO BE ADDED

	  @expectedResults: Verify that age of scrum team defaults to the last scrum team when changing  to different scrum teams for bugs
	  
	  @author jhatton

	*/ 
	
	/* 

	  @testcaseID a0B20000007m0ZzEAI

	  @hierarchy GUS.BugforceToGUS.Work Page.BugsCreatedInGus.Bug Age

	  @userstory TO BE ADDED

	  @expectedResults: Verify age with scrum team resets to zero when changing scrum teams on a bug from the UI
	  
	  @author jhatton

	*/ 
	
	static testMethod void testScrumTeamLastModifiedIsUpdatedWhenScrumTeamChanges() {
		ADM_Work__c work = ADM_Work.createTestWork();
		ADM_Scrum_Team__c team = ADM_ScrumTeam.createTestScrumTeam('New Team Name Test');
		work.Scrum_Team__c = team.id;
		update work;
		work = [select id, Scrum_Team_Last_Modified__c, Age_With_Scrum_Team__c from ADM_Work__c where id = :work.id];
		System.assert(work.Scrum_Team_Last_Modified__c != null);
		System.assertEquals(0, work.Age_With_Scrum_Team__c);
		
	}  
	
	/* 

	  @testcaseID a0B20000007m0a5EAA

	  @hierarchy GUS.BugforceToGUS.Work Page.BugsCreatedInGus.Bug Age

	  @userstory TO BE ADDED

	  @expectedResults: age with scrum team resets to zero when deleting scrum teams on a bug
	  
	  @author jhatton

	*/ 
	
	static testMethod void testScrumTeamLastModifiedIsUpdatedWhenScrumTeamIsRemoved() {
		ADM_Work__c work = ADM_Work.createTestWork();
		work.Scrum_Team__c = null;
		update work;
		work = [select id, Scrum_Team_Last_Modified__c, Age_With_Scrum_Team__c from ADM_Work__c where id = :work.id];
		System.assert(work.Scrum_Team_Last_Modified__c != null);
		System.assertEquals(0, work.Age_With_Scrum_Team__c);
		
	} 
	
	/* 

	  @testcaseID a0B20000007m1qGEAQ

	  @hierarchy GUS.BugforceToGUS.Work Page.BugsCreatedInGus.Bug Age

	  @userstory TO BE ADDED

	  @expectedResults: Verify that age of scrum team defaults to the last scrum team when changing  to different scrum teams for user stories
	  
	  @author jhatton

	*/ 
	
	/* 

	  @testcaseID a0B20000007m0a4EAA

	  @hierarchy GUS.BugforceToGUS.Work Page.BugsCreatedInGus.Bug Age

	  @userstory TO BE ADDED

	  @expectedResults: Scrum Team Last Modified field is updated 
	  
	  @author jhatton

	*/ 
	
	/* 

	  @testcaseID a0B20000007m0aJEAQ

	  @hierarchy GUS.BugforceToGUS.Work Page.BugsCreatedInGus.Bug Age

	  @userstory TO BE ADDED

	  @expectedResults: Verify that changing the name of a scrum team doesn't affect the bug age 
	  
	  @author jhatton

	*/
	
	static testMethod void testScrumTeamLastModifiedIsUpdatedWhenScrumTeamChangesForUserStory() {
		ADM_Work__c work = ADM_Work.createTestWork('User Story');
		ADM_Scrum_Team__c team = ADM_ScrumTeam.createTestScrumTeam('New Team Name Test');
		work.Scrum_Team__c = team.id;
		update work;
		work = [select id, Scrum_Team_Last_Modified__c, Age_With_Scrum_Team__c from ADM_Work__c where id = :work.id];
		System.assert(work.Scrum_Team_Last_Modified__c != null);
		System.assertEquals(0, work.Age_With_Scrum_Team__c);
		
	} 
	
	/* 

	  @testcaseID a0B20000007m1hbEAA

	  @hierarchy GUS.BugforceToGUS.Work Page.BugsCreatedInGus.Bug Age

	  @userstory TO BE ADDED

	  @expectedResults: Verify new user stories in open status show an actual bug age
	  
	  @author jhatton

	*/ 
	
	/* 

	  @testcaseID a0B20000003xGsBEAU

	  @hierarchy GUS.BugforceToGUS.Work Page.BugsCreatedInGus.Bug Age

	  @userstory TO BE ADDED

	  @expectedResults: Verify new work in open status show an actual bug age
	  
	  @author jhatton

	*/ 
	
	static testMethod void testAgeForUserStory() {
		ADM_Work__c work = ADM_Work.createTestWork('User Story');
		
		work = [select id, Age__c from ADM_Work__c where id = :work.id];
		System.assert(work.Age__c != null);
		System.assertEquals(0, work.Age__c); //expect 0 as its less then 1 day old
		
	}
	
	/* 

	  @testcaseID a0B20000007m1f1EAA

	  @hierarchy GUS.BugforceToGUS.Work Page.BugsCreatedInGus.Bug Age

	  @userstory TO BE ADDED

	  @expectedResults: Verify age doesn't change when changing record types
	  
	  @author jhatton

	*/ 
	
	static testMethod void testAgeRemainsTheSameWhenChangingFromBugToUserStory() {
		ADM_Work__c work = ADM_Work.createTestWork('Bug');
		ADM_Scrum_Team__c team = ADM_ScrumTeam.createTestScrumTeam('New Team Name Test');
		work.Scrum_Team__c = team.id;
		update work;
		work = [select id, Age__c from ADM_Work__c where id = :work.id];
		System.assert(work.Age__c != null);
		System.assertEquals(0, work.Age__c); //expect 0 as its less then 1 day old
		work.RecordTypeId = [ Select Id from RecordType r Where Name = 'User Story'].Id;
		update work;
		work = [select id, Age__c from ADM_Work__c where id = :work.id];
		System.assert(work.Age__c != null);
		System.assertEquals(0, work.Age__c); //expect 0 as its less then 1 day old
		
	}  
	
	/* 

	  @testcaseID a0B20000007m20uEAA

	  @hierarchy GUS.BugforceToGUS.Work Page.BugsCreatedInGus.Bug Age

	  @userstory TO BE ADDED

	  @expectedResults: Scrum Team Last Modified field is not updated when scrum team remains constant 
	  
	  @author jhatton

	*/ 
	
	static testMethod void testScrumTeamLastModifiedIsNotUpdatedIfScrumTeamRemainsTheSame() {
		ADM_Work__c work = ADM_Work.createTestWork();
		ADM_Scrum_Team__c team = ADM_ScrumTeam.createTestScrumTeam('New Team Name Test');
		work.Scrum_Team__c = team.id;
		update work;
		work = [select id, Scrum_Team_Last_Modified__c, Age_With_Scrum_Team__c from ADM_Work__c where id = :work.id];
		Datetime lastMod = work.Scrum_Team_Last_Modified__c;
		work.Subject__c = '123';
		update work;
		work = [select id, Scrum_Team_Last_Modified__c, Age_With_Scrum_Team__c from ADM_Work__c where id = :work.id];
		System.assert(work.Scrum_Team_Last_Modified__c != null);
		System.assertEquals(0, work.Age_With_Scrum_Team__c);
		//verfiy original time stamp remains as the last edit did not effect the scrum team
		System.assertEquals(lastMod, work.Scrum_Team_Last_Modified__c);
	} 
	
	/* 
	  @testcaseID a1DB00000000qm9
	  @hierarchy GUS.BugforceToGUS.Work Page.BugsCreatedInGus.Bug Age
	  @userstory a07B0000000Dd2mIAC
	  @expectedResults:  Total age when closed is 0 when item is open
	  @author alexis williams
	*/ 

	/* 
	  @testcaseID a1DB00000000qmE
	  @hierarchy GUS.BugforceToGUS.Work Page.BugsCreatedInGus.Bug Age
	  @userstory a07B0000000Dd2mIAC
	  @expectedResults:  Total age when closed is 0 when item is closed the same day
	  @author alexis williams
	*/ 

	/* 
	  @testcaseID a1DB00000000qmE
	  @hierarchy GUS.BugforceToGUS.Work Page.BugsCreatedInGus.Bug Age
	  @userstory a07B0000000Dd2mIAC
	  @expectedResults: Total age when closed is 0 when item is closed the same day	 
	  @author alexis williams
	*/ 

	/* 
	  @testcaseID a1DB00000000qmF
	  @hierarchy GUS.BugforceToGUS.Work Page.BugsCreatedInGus.Bug Age
	  @userstory a07B0000000Dd2mIAC
	  @expectedResults: Total age when closed is 0 when the created on import date is less than the closed date 
	  @author alexis williams
	*/ 
	static testMethod void testTotalAgeWhenClosed() {		
		ADM_Work__c work = ADM_Work.createTestWork();
		ADM_Build__c build = ADM_Build.createTestBuild();
		Test.startTest();
			//#1 Test to make sure the total age when closed is 0 becuase this is open
			work = [Select w.Total_Age_When_Closed__c From ADM_Work__c w Where w.Id =: work.Id];
			System.assertEquals(0, work.Total_Age_When_Closed__c);
			work.Status__c = 'Closed';
			work.Found_in_Build__c = build.Id;
			update work;
			//#2 Test to make sure the total age when closed is 0 becuase this was closed the same day
			work = [Select w.Total_Age_When_Closed__c From ADM_Work__c w Where w.Id =: work.Id];
			System.assertEquals(0, work.Total_Age_When_Closed__c);
			work.Created_On_import__c = System.now().addDays(-1);
			update work;		
			//#3 Test to make sure the total age when closed is 1 because it was "opened a day ago" according to the created on import date
			work = [Select w.Total_Age_When_Closed__c From ADM_Work__c w Where w.Id =: work.Id];
			System.assertEquals(1, work.Total_Age_When_Closed__c);
			work.Created_On_import__c = System.now().addDays(1);
			update work;		
			//#4 Test to make sure the total age when closed is 0 becuase the created on import date is less than the closed date which does not make sense
			work = [Select w.Total_Age_When_Closed__c From ADM_Work__c w Where w.Id =: work.Id];
		Test.stopTest();
		System.assertEquals(0, work.Total_Age_When_Closed__c);						
	}


}