mdapi-source/original-package/unpackaged/objects/ADM_Product_Tag__c.object
<CustomObject>
    <label>TE Activity</label>
    <nameField>
        <label>TE Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TE Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Tag_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Assignment_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment Rule</label>
        <referenceTo>ADM_Assignment_Rule__c</referenceTo>
        <relationshipLabel>Tag Assignments</relationshipLabel>
        <relationshipName>Tag_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Tag__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Tag</label>
        <referenceTo>ADM_Product_Tag__c</referenceTo>
        <relationshipLabel>Tag Assignments</relationshipLabel>
        <relationshipName>Tag_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <label>Record Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bug</fullName>
                </value>
                <value>
                    <fullName>User Story</fullName>
                </value>
                <value>
                    <fullName>Investigation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tag Assignment</label>
    <nameField>
        <displayFormat>TA-{0000}</displayFormat>
        <label>Tag Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tag Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ADM_TagAssignment.cls
public with sharing class ADM_TagAssignment {
    
    /**
     * Gets a list of all Tag Assignments that are associated to the specified 
     * product tag IDs. 
     */
    public static List<ADM_Tag_Assignment__c> getAllWhereProductTagIdEquals(List<String> tagIds) {
        List<ADM_Tag_Assignment__c> assignments = [select Id, Name, Assignment_Rule__c, Product_Tag__c, Record_Type__c from ADM_Tag_Assignment__c where Product_Tag__c in :tagIds];
        return assignments;
    }
    
    public static ADM_Tag_Assignment__c createAndInsertTagAssignment(ADM_Product_Tag__c tag, RecordType rType){
        ADM_Tag_Assignment__c tagAsgnmt = new ADM_Tag_Assignment__c();
        tagAsgnmt.Product_Tag__c = tag.id;
        tagAsgnmt.Record_Type__c = rType.Name;
        
        insert tagAsgnmt;
        return tagAsgnmt;
    }
    
}