mdapi-source/original-package/unpackaged/objects/ADM_Feature_Freeze_Status__c.object
<CustomObject>
    <fields>
        <fullName>Build__c</fullName>
        <formula>Team_Release__r.Build__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Build</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Bugs_to_Fix_max_1_Dev__c</fullName>
        <description>Total Number of Bugs to Fix (maximum 1 per Full-Time Developer)</description>
        <inlineHelpText>Total Number of Bugs to Fix (maximum 1 per Full-Time Developer)</inlineHelpText>
        <label>Number of Bugs to Fix (max 1/Dev)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Bugs_to_Verify_max_1_QE__c</fullName>
        <description>Total Number of Fixed Bugs to Verify (maximum 1 per Full-Time QE)</description>
        <inlineHelpText>Total Number of Fixed Bugs to Verify (maximum 1 per Full-Time QE)</inlineHelpText>
        <label>Number of Bugs to Verify (max 1/QE)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Open_User_Stories_0__c</fullName>
        <description>Number of Open User Stories – excluding “Release Sprint Theme” stories (0)</description>
        <inlineHelpText>Number of Open User Stories – excluding “Release Sprint Theme” stories (0)</inlineHelpText>
        <label>Number of Open User Stories (0)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <formula>Team_Release__r.Scrum_Team__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Scrum Team</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team_Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Release</label>
        <referenceTo>ADM_Team_Release__c</referenceTo>
        <relationshipName>R00NT0000000txY2MAI</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Signoff_Status__c</fullName>
        <label>Team Signoff Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes / meets criteria</fullName>
                </value>
                <value>
                    <fullName>Yes / does not meet criteria</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Freeze Team Status</label>
    <nameField>
        <displayFormat>FS-{0000000}</displayFormat>
        <label>Freeze Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Freeze Team Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Product_Tag__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipName>Product_Tags</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TE Activity</label>
    <nameField>
        <label>TE Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TE Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Scrum_Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Sprint__c.object
<CustomObject>
    <customHelpPage>ADM_CreateSprintOverview</customHelpPage>
    <description>Added to support User Story for Scrumforce integration into GUS.</description>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scrum Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Sprints</relationshipLabel>
        <relationshipName>Sprints</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Team_Release__c.object
<CustomObject>
    <description>Keep track of which teams are part of a release.</description>
    <fields>
        <fullName>Build__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Build</label>
        <referenceTo>ADM_Build__c</referenceTo>
        <relationshipLabel>Team Builds</relationshipLabel>
        <relationshipName>Team_Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scrum Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipName>Release_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team Release</label>
    <nameField>
        <displayFormat>RT-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Found_in_Build__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Found In Build field is a lookup to the Build object.  Enter the build where the bug was introduced.</inlineHelpText>
        <label>Found in Build</label>
        <referenceTo>ADM_Build__c</referenceTo>
        <relationshipLabel>Work (Found in Build)</relationshipLabel>
        <relationshipName>Found_in_Build</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <inlineHelpText>For bugs, priority is automatically determined based upon the combination of Impact and Frequency.

For user stories, P0 represents the highest priority, P4 the lowest.</inlineHelpText>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>P0</fullName>
                    <color>#0B6FCE</color>
                    <label>P0</label>
                </value>
                <value>
                    <fullName>P1</fullName>
                    <color>#FF0000</color>
                    <label>P1</label>
                </value>
                <value>
                    <fullName>P2</fullName>
                    <color>#E27001</color>
                    <label>P2</label>
                </value>
                <value>
                    <fullName>P3</fullName>
                    <color>#FFFF66</color>
                    <label>P3</label>
                </value>
                <value>
                    <fullName>P4</fullName>
                    <color>#78C953</color>
                    <label>P4</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Tag__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TE Activity</label>
        <referenceTo>ADM_Product_Tag__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Product_Tag</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QA_Engineer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>QA Engineer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QA_Engineer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scheduled_Build__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Scheduled Build field is a lookup to the Build object.  Enter a pre-existing build where the change will be made.</inlineHelpText>
        <label>Scheduled Build</label>
        <referenceTo>ADM_Build__c</referenceTo>
        <relationshipLabel>Work (Scheduled Build)</relationshipLabel>
        <relationshipName>Scheduled_Build</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sprint</label>
        <referenceTo>ADM_Sprint__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Triaged</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Investigating</fullName>
                </value>
                <value>
                    <fullName>Ready for Review</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>QA In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Defunct</fullName>
                </value>
                <value>
                    <fullName>Closed - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Closed - Eng Internal</fullName>
                </value>
                <value>
                    <fullName>Closed - Known Bug Exists</fullName>
                </value>
                <value>
                    <fullName>Closed - New Bug Logged</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Approved</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Denied</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved With Internal Tools</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved Without Code Change</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Working as Designed</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Feature Request</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Will Not Fix</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Pending Release</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>More Info Reqd from Support</fullName>
                </value>
                <value>
                    <fullName>Never</fullName>
                </value>
                <value>
                    <fullName>Not a bug</fullName>
                </value>
                <value>
                    <fullName>Not Reproducible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <recordTypes>
        <fullName>Bug</fullName>
        <active>true</active>
        <description>Used to track defects or problems</description>
        <label>Bug</label>
    </recordTypes>
    <recordTypes>
        <fullName>ToDo</fullName>
        <active>true</active>
        <description>Used to track a unit of work that does not need to have anything checked into Source Control nor does it need to have auto assignment rules applied</description>
        <label>ToDo</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ADM_FeatureFreezeUtilsTest.cls
@isTest
private class ADM_FeatureFreezeUtilsTest {

    @isTest
    public static ADM_Team_Release__c setupTeamRelease() {
    	
        Test.startTest();
		ADM_Sprint__c sprint = ADM_ReleaseBurndownUtils.createTestClosedSprint();
		List<ADM_Work__c> works = [select id, Scheduled_Build__c, Product_Tag__c, Scrum_Team__c from ADM_Work__c where Sprint__c =:sprint.id];
		String build = works[0].Scheduled_Build__c;
		ADM_Work__c work = works[0];
		//update the team of the Product Tag autocreated in setupTestWork() to match the team used on the team release record.  
		ADM_Product_Tag__c tag = [select id, Name from ADM_Product_Tag__c where id =:work.Product_Tag__c];
		tag.Team__c = sprint.Scrum_Team__c;
		update tag;
		//ensure scrum team is populated
		work.Scrum_Team__c = sprint.Scrum_Team__c;
		update work;
		
		//process release burn down
		ADM_ReleaseBurndownUtils.updateReleaseBurndownsBulk(new Set<Id>{sprint.id});
		Test.stopTest();
		//assert team release was created		
		List<ADM_Team_Release__c> teamReleases = [select id, Scrum_Team__c, Scrum_Team__r.Name, Build__c from ADM_Team_Release__c where Build__c = :build];
		System.assert(teamReleases != null);
		System.assertEquals(1, teamReleases.size(), 'Found unexpeted # of team releases for build:' + build);
		
		ADM_Team_Release__c tRelease = teamReleases[0];
		
		return tRelease;
    	
    	
    }
        /*
	@testcaseID a1DB00000001IJE
	@userstoryID a07B0000000G2EMIA0
	@hierarchy GUS.ScrumforceToGUS.ScrumTeams.Release Support Information.New Feature Freeze Team Status
	@expected results Dashboards for #of P0 blocking bugs, # of bugs to verify per QE, # of bugs to fix per Dev, Open User Stories, # of open test failures > 1 week and # of TF per Dev appear under the "FF criteria status dashboard" section
	@author: jhatton
	*/

    static testMethod void testFeatureFreezeMetricsDashboard() {
    	   	ADM_Team_Release__c tr = setupTeamRelease();
			        
	        //file for feature freeze
	        ADM_Feature_Freeze_Status__c ffs = new ADM_Feature_Freeze_Status__c();
			ffs.Team_Release__c = tr.id;
            ffs.Team_Signoff_Status__c = 'Yes / meets criteria';
			insert ffs;
			ApexPages.StandardController stdC = new ApexPages.StandardController(ffs);
			ADM_FeatureFreezeChartsController ffc = new ADM_FeatureFreezeChartsController(stdC);
			//TODO how to assert correct behavior of code which relies on custom setting that will not
			//be populated when this code first deploys and will therefore cause tests to fail and block deployment
			try {
				ffc.getBlockingBugsReportID();
				ffc.getBlockingBugsReportParams();
				ffc.getBugsToVerifyReportID();
				ffc.getBugsToVerifyReportParams();
				ffc.getOpenBugsReportID();
				ffc.getOpenBugsReportParams();
				ffc.getOpenUserStoriesReportID();
				ffc.getOpenUserStoriesReportParams();
				ffc.getOpenTestFailuresReportID();
				ffc.getOpenTestFailuresByDevReportParams();
				ffc.getOpenTestFailuresByDevReportID();
				ffc.getOpenTestFailuresByDevReportParams();
			} catch(Exception e) {
				System.debug('exception in testFeatureFreezeMetricsDashboard:' + e);
			}	
			
    	
    }
    
    	/*
	@testcaseID a1DB00000000ryC
	@userstoryID a07B0000000ECUTIA4
	@hierarchy GUS.ScrumforceToGUS.ScrumTeams.Release Support Information.New Feature Freeze Team Status
	@expected results The Number of Open User Stories (0) on Feature Freeze Team Status page shows the following formulated number: # of open user stories for that team and build
	@author: jhatton
	*/
	
    
    static testMethod void testCountOpenUserStoriesByTeamAndBuild() {
        ADM_Team_Release__c tr = setupTeamRelease();
		//open a story
		ADM_Work__c work = ADM_Work.setupTestWork('User Story');
		//update the team of the Product Tag autocreated in setupTestWork() to match the team used on the team release record.  
		ADM_Product_Tag__c tag = [select id, Name from ADM_Product_Tag__c where id =:work.Product_Tag__c];
		tag.Team__c = tr.Scrum_Team__c;
		update tag;
		work.Scheduled_Build__c = tr.Build__c;
		work.Scrum_Team__c = tr.Scrum_Team__c; 
        work.Priority__c = 'P1';
        insert work;
        
        //file for feature freeze
        ADM_Feature_Freeze_Status__c ffs = new ADM_Feature_Freeze_Status__c();
		ffs.Team_Release__c = tr.id;
        ffs.Team_Signoff_Status__c = 'Yes / meets criteria';
		insert ffs;
		
		//expect 2 - one story with the initial team release and one we just created
		System.assertEquals(2, [select Number_Of_Open_User_Stories_0__c from ADM_Feature_Freeze_Status__c where id =:ffs.id].Number_Of_Open_User_Stories_0__c);
    }
    
    	/*
	@testcaseID a1DB00000000ryH
	@userstoryID a07B0000000ECUTIA4
	@hierarchy GUS.ScrumforceToGUS.ScrumTeams.Release Support Information.New Feature Freeze Team Status
	@expected results The Number of P0/Blocking Bugs (0) on Feature Freeze Team Status page shows the following formulated number: # of open P0 bugs for that team and build
	@author: jhatton
	*/
	
    static testMethod void testCountOpenBugsByTeamAndBuild() {
        ADM_Team_Release__c tr = setupTeamRelease();
		//open a story
		ADM_Work__c work = ADM_Work.setupTestWork('Bug', 'P1', 'Bug');
		//update the team of the Product Tag autocreated in setupTestWork() to match the team used on the team release record.  
		ADM_Product_Tag__c tag = [select id, Name from ADM_Product_Tag__c where id =:work.Product_Tag__c];
		tag.Team__c = tr.Scrum_Team__c;
		update tag;
		work.Scheduled_Build__c = tr.Build__c;
		work.Found_In_Build__c = tr.Build__c;
		work.Scrum_Team__c = tr.Scrum_Team__c;
		insert work;
        
        //file for feature freeze
        ADM_Feature_Freeze_Status__c ffs = new ADM_Feature_Freeze_Status__c();
		ffs.Team_Release__c = tr.id;
        ffs.Team_Signoff_Status__c = 'Yes / meets criteria';
		insert ffs;
		
		System.assertEquals(1, [select Number_of_Bugs_to_Fix_max_1_Dev__c from ADM_Feature_Freeze_Status__c where id =:ffs.id].Number_of_Bugs_to_Fix_max_1_Dev__c);
    }
    
    	/*
	@testcaseID a1DB00000000ryM
	@userstoryID a07B0000000ECUTIA4
	@hierarchy GUS.ScrumforceToGUS.ScrumTeams.Release Support Information.New Feature Freeze Team Status
	@expected results The Number of Bugs to Verify (max 1/QE) on Feature Freeze Team Status page shows the following formulated number: # of bugs in QA in progress for that team and build
	@author: jhatton
	*/
	
    static testMethod void testCountUntestedBugsByTeamAndBuild() {
        ADM_Team_Release__c tr = setupTeamRelease();
		//open a story
		ADM_Work__c work = ADM_Work.setupTestWork('Bug', 'P1', 'Bug');
		//update the team of the Product Tag autocreated in setupTestWork() to match the team used on the team release record.  
		ADM_Product_Tag__c tag = [select id, Name from ADM_Product_Tag__c where id =:work.Product_Tag__c];
		tag.Team__c = tr.Scrum_Team__c;
		update tag;
		work.Scheduled_Build__c = tr.Build__c;
		work.Found_In_Build__c = tr.Build__c;
		work.Scrum_Team__c = tr.Scrum_Team__c;
		work.Status__c = 'Fixed';
		work.QA_Engineer__c = UserInfo.getUserId();
		insert work;
        
        //file for feature freeze
        ADM_Feature_Freeze_Status__c ffs = new ADM_Feature_Freeze_Status__c();
		ffs.Team_Release__c = tr.id;
		ffs.Team_Signoff_Status__c = 'Yes / meets criteria';
		insert ffs;
		
		System.assertEquals(1, [select Number_of_Bugs_to_Verify_max_1_QE__c from ADM_Feature_Freeze_Status__c where id =:ffs.id].Number_of_Bugs_to_Verify_max_1_QE__c);
    }
    
    /* TODO:
    	Previous tests tally counts on creation of the Feature Freeeze Status record.  We also need tests to verify the record is kept up to date 
    	as work changes.
    	
    	However both the Team Release creation and the Feature Freeze Status updates are done asynchrnously.  Apex tests only allow one Test.start/stop
    	call per test.  
    		- Therefore if you use Test.start/stop on the creation of the team release record your Feature Freeze status asserts will always fail (as they haven't 
    		completed yet).
    		- Alternatively stubbing out a synthentic Team Release record reduces the realism and usefullness of the tests
    		-Sharing state (such as a team release record) between tests can lead to flappers and hard to debug failures due to one test leaving the
    		shared data in a format the next test wasn't expecting.  
    */		  
    
    static testMethod void testUpdateFeatureFreezeStatus() {
        ADM_Work__c work = ADM_Work.setupTestWork('Bug', 'P1', 'Bug');
        work.Status__c = 'Fixed';
        work.QA_Engineer__c = UserInfo.getUserId();
        insert work;
        
        ADM_Team_Release__c tr = new ADM_Team_Release__c();
        tr.Scrum_Team__c = work.Scrum_Team__c;
        tr.Build__c = work.Scheduled_Build__c;
        insert tr;
        
        //file for feature freeze
        ADM_Feature_Freeze_Status__c ffs = new ADM_Feature_Freeze_Status__c();
        ffs.Team_Release__c = tr.id;
        ffs.Team_Signoff_Status__c = 'Yes / meets criteria';
        insert ffs;
        
        ADM_Work__c work2 = ADM_Work.setupTestWork('Bug', 'P1', 'Bug');
        work2.Product_Tag__c = work.Product_Tag__c;
        work2.Scheduled_Build__c = work.Scheduled_Build__c;
        work2.Found_In_Build__c = work.Found_In_Build__c;
        work2.Scrum_Team__c = work.Scrum_Team__c;
        work2.Status__c = 'Fixed';
        work2.QA_Engineer__c = UserInfo.getUserId();
        insert work2;
        
        Test.startTest();
    	ADM_FeatureFreezeUtils.updateFeatureFreezeStatus(new List<ADM_Work__c>{work, work2}, new List<ADM_Work__c>{work, work2}, true);
    	Test.stopTest();
    	
    	ffs = [select Id, Number_of_Bugs_to_Verify_max_1_QE__c
                 from ADM_Feature_Freeze_Status__c 
                 where id = :ffs.Id];
        System.assertEquals(2, ffs.Number_of_Bugs_to_Verify_max_1_QE__c);
    }
    
    static testMethod void testUpdateSingleDevelopmentCycleStatus() {
        ADM_Work__c work = ADM_Work.setupTestWork('Bug', 'P1', 'Bug');
        work.Status__c = 'Fixed';
        work.QA_Engineer__c = UserInfo.getUserId();
        insert work;
        
        ADM_Team_Release__c tr = new ADM_Team_Release__c();
        tr.Scrum_Team__c = work.Scrum_Team__c;
        tr.Build__c = work.Scheduled_Build__c;
        insert tr;
        
        //file for feature freeze
        ADM_Feature_Freeze_Status__c ffs = new ADM_Feature_Freeze_Status__c();
        ffs.Team_Release__c = tr.id;
        ffs.Team_Signoff_Status__c = 'Yes / meets criteria';
        insert ffs;
        
        ADM_Work__c work2 = ADM_Work.setupTestWork('Bug', 'P1', 'Bug');
        work2.Product_Tag__c = work.Product_Tag__c;
        work2.Scheduled_Build__c = work.Scheduled_Build__c;
        work2.Found_In_Build__c = work.Found_In_Build__c;
        work2.Scrum_Team__c = work.Scrum_Team__c;
        work2.Status__c = 'Fixed';
        work2.QA_Engineer__c = UserInfo.getUserId();
        insert work2;
        
        Test.startTest();
        ADM_FeatureFreezeUtils.updateSingleDevelopmentCycleStatus(ffs.Id);
        Test.stopTest();
        
        ffs = [select Id, Number_of_Bugs_to_Verify_max_1_QE__c
                 from ADM_Feature_Freeze_Status__c 
                 where id = :ffs.Id];
        System.assertEquals(2, ffs.Number_of_Bugs_to_Verify_max_1_QE__c);
    }
}