mdapi-source/original-package/unpackaged/objects/ADM_Scrum_Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Scrum_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Allocation__c</fullName>
        <label>Allocation (%)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Member_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Scrum_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>Scrum_Team_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <displayFormat>STM-{00000}</displayFormat>
        <label>Team Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <recordTypes>
        <fullName>Internal</fullName>
        <active>true</active>
        <description>SFDC Employee</description>
        <label>Internal</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ADM_TeamSelectorControllerTest.cls
@isTest
private class ADM_TeamSelectorControllerTest {

	private static String message = 'No records to display';
/*
@userstory:  a07B0000000yiqiIAA
@testcaseID:  
@expected results: 
*/
    static testMethod void testWithValidUserId() {
    	ADM_Scrum_Team__c team = ADM_ScrumTeam.createTestScrumTeam();
    	ADM_Scrum_Team_Member__c t = new ADM_Scrum_Team_Member__c();
    	User u = ADM_WorkUser.createTestUser();
    	t.Allocation__c = 1;
    	t.Member_Name__c = u.Id;
    	t.RecordTypeId = [Select Id From RecordType Where Name = 'Internal'].Id;
    	t.Scrum_Team__c = team.Id;
    	insert t;
    	System.RunAs(u) {
	    	ADM_TeamSelectorController controller = new ADM_TeamSelectorController();
	        System.assertEquals('',controller.message);
	        System.assertEquals(false, Apexpages.hasMessages());
	        System.assertEquals(1, controller.allocations.size(), '' + controller.allocations);
	        System.assertEquals(t.Member_Name__c, controller.teamMemberId);        
        }
    } 
/*
@userstory:  a07B0000000yiqiIAA
@testcaseID:  
@expected results: 
*/
    static testMethod void testWithValidUserIdNoMemberships() {
    	User u = ADM_WorkUser.createTestUser();
    	System.RunAs(u) {
	    	ADM_TeamSelectorController controller = new ADM_TeamSelectorController();
	        System.assertEquals(message,controller.message);
	        System.assertEquals(false, Apexpages.hasMessages());
	        System.assertEquals(0, controller.allocations.size(), '' + controller.allocations);
	        System.assertEquals(u.Id, controller.teamMemberId);        
		}
    }


    @isTest
    public static void getCurrentTeamCountTest(){
        ADM_Scrum_Team__c team = ADM_ScrumTeam.createTestScrumTeam();
        ADM_Scrum_Team_Member__c t = new ADM_Scrum_Team_Member__c();
        User u = ADM_WorkUser.createTestUser();
        t.Allocation__c = 1;
        t.Member_Name__c = u.Id;
        t.RecordTypeId = [Select Id From RecordType Where Name = 'Internal'].Id;
        t.Scrum_Team__c = team.Id;
        insert t;
        System.RunAs(u) {
            ADM_TeamSelectorController controller = new ADM_TeamSelectorController();
            Integer c = controller.getCurrentTeamCount(); 
            String link = controller.getAllTeamsLink();
            System.assertEquals(c,1);
        }
    } 

}