mdapi-source/original-package/unpackaged/objects/ADM_Sprint__c.object
<CustomObject>
    <customHelpPage>ADM_CreateSprintOverview</customHelpPage>
    <description>Added to support User Story for Scrumforce integration into GUS.</description>
    <label>Sprint</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Closed_On__c</fullName>
        <label>Closed On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Priority_Rank__c</fullName>
        <label>Backlog Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <inlineHelpText>For bugs, priority is automatically determined based upon the combination of Impact and Frequency.

For user stories, P0 represents the highest priority, P4 the lowest.</inlineHelpText>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>P0</fullName>
                    <color>#0B6FCE</color>
                    <label>P0</label>
                </value>
                <value>
                    <fullName>P1</fullName>
                    <color>#FF0000</color>
                    <label>P1</label>
                </value>
                <value>
                    <fullName>P2</fullName>
                    <color>#E27001</color>
                    <label>P2</label>
                </value>
                <value>
                    <fullName>P3</fullName>
                    <color>#FFFF66</color>
                    <label>P3</label>
                </value>
                <value>
                    <fullName>P4</fullName>
                    <color>#78C953</color>
                    <label>P4</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Scheduled_Build__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Scheduled Build field is a lookup to the Build object.  Enter a pre-existing build where the change will be made.</inlineHelpText>
        <label>Scheduled Build</label>
        <referenceTo>ADM_Build__c</referenceTo>
        <relationshipLabel>Work (Scheduled Build)</relationshipLabel>
        <relationshipName>Scheduled_Build</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sprint</label>
        <referenceTo>ADM_Sprint__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Triaged</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Investigating</fullName>
                </value>
                <value>
                    <fullName>Ready for Review</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>QA In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Defunct</fullName>
                </value>
                <value>
                    <fullName>Closed - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Closed - Eng Internal</fullName>
                </value>
                <value>
                    <fullName>Closed - Known Bug Exists</fullName>
                </value>
                <value>
                    <fullName>Closed - New Bug Logged</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Approved</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Denied</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved With Internal Tools</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved Without Code Change</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Working as Designed</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Feature Request</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Will Not Fix</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Pending Release</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>More Info Reqd from Support</fullName>
                </value>
                <value>
                    <fullName>Never</fullName>
                </value>
                <value>
                    <fullName>Not a bug</fullName>
                </value>
                <value>
                    <fullName>Not Reproducible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Story_Points__c</fullName>
        <inlineHelpText>If you leave it empty on save it will automatically assign the value from the TE activity selected.</inlineHelpText>
        <label>Story Points</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Theme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Theme-Deprecated</label>
        <referenceTo>ADM_Theme__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/classes/ADM_SprintBacklogControllerExtension.cls
public with sharing class ADM_SprintBacklogControllerExtension {
    private String sprintId { get; set; }
    private List<ADM_Sprint__c> sprints { get; set; }
    Integer hasBeenLoaded { get; set; }
    transient String message { get; set; }
    public ADM_Sprint__c sprint { get; set; }
    public ADM_SprintBacklogControllerExtension(ApexPages.StandardController controller) {}
    
    public Apexpages.Standardsetcontroller setController {
        get {
            if(setController == null) {
                sprintId = System.currentPageReference().getParameters().get('id');
                sprint = [select Name from ADM_Sprint__c where Id = : sprintId];
                setController = new Apexpages.Standardsetcontroller(Database.getQueryLocator([
                    select Name, Theme__c, Subject__c, Priority_Rank__c, Priority__c, Story_Points__c, Status__c, Scheduled_Build__c, Closed_On__c
                    from ADM_Work__c
                    where Sprint__c = : sprintId
                ]));
                setController.setPageSize(20);
            }
            if(setController.getResultSize() == 0) {
            	ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO,'No records were found.'));
            }
            return setController;
        }
        set;
    }
    
    public List<ADM_Work__c> works {
        get {
            if(works == null) works = new List<ADM_Work__c>();
            
            for(ADM_Work__c work : (List<ADM_Work__c>) setController.getRecords()) {
                works.add(work);
            }
            return works;
        }
        set;
    }   
   
     // indicates whether there are more records after the current page set.  
     public Boolean hasNext {  
         get {  
             return setController.getHasNext();  
         }  
         set;  
     }  
   
     // indicates whether there are more records before the current page set.  
     public Boolean hasPrevious {  
         get {  
             return setController.getHasPrevious();  
         }  
         set;  
     }  
   
     // returns the page number of the current page set  
     public Integer pageNumber {  
         get {  
             return setController.getPageNumber();  
         }  
         set;  
     }  
   
     // returns the page size of the current page set  
     public Integer pageSize {  
         get {  
             return setController.getPageSize();  
         }  
         set;  
     }
     
     public Integer resultSize {
        get {
            return setController.getResultSize();
        }
        set;
     } 
   
     // returns the first page of records  
     public void first() {  
         setController.first();  
     }  
   
     // returns the last page of records  
     public void last() {  
         setController.last();  
     }  
   
     // returns the previous page of records  
     public void previous() {  
         setController.previous();  
     }  
   
     // returns the next page of records  
     public void next() {  
         setController.next();  
     }  
   
     // returns the PageReference of the original page, if known, or the home page.  
     public void cancel() {  
         setController.cancel();  
     }
     
     public Integer rowStart {
        get {
            if(!hasPrevious) {
                return 1;
            } else if(hasNext){
                return (works.size() * (pageNumber - 1)) + 1;
            } else {
                return resultSize - works.size() + 1;
            }
        }
        set;
     }
     
     public Integer rowEnd {
        get {
            if(!hasNext) {
                return resultSize;
            } else {
                return works.size() * pageNumber;
            }
        }
        set;
    }
}