mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Comments will be added to the Work record and included in an email to the names listed in the Email Notifications section after saving. Formatting will also be preserved when saving via in line edit.</inlineHelpText>
        <label>Comment</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <inlineHelpText>For bugs, priority is automatically determined based upon the combination of Impact and Frequency.

For user stories, P0 represents the highest priority, P4 the lowest.</inlineHelpText>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>P0</fullName>
                    <color>#0B6FCE</color>
                    <label>P0</label>
                </value>
                <value>
                    <fullName>P1</fullName>
                    <color>#FF0000</color>
                    <label>P1</label>
                </value>
                <value>
                    <fullName>P2</fullName>
                    <color>#E27001</color>
                    <label>P2</label>
                </value>
                <value>
                    <fullName>P3</fullName>
                    <color>#FFFF66</color>
                    <label>P3</label>
                </value>
                <value>
                    <fullName>P4</fullName>
                    <color>#78C953</color>
                    <label>P4</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sprint</label>
        <referenceTo>ADM_Sprint__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Triaged</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Investigating</fullName>
                </value>
                <value>
                    <fullName>Ready for Review</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>QA In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Defunct</fullName>
                </value>
                <value>
                    <fullName>Closed - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Closed - Eng Internal</fullName>
                </value>
                <value>
                    <fullName>Closed - Known Bug Exists</fullName>
                </value>
                <value>
                    <fullName>Closed - New Bug Logged</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Approved</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Denied</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved With Internal Tools</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved Without Code Change</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Working as Designed</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Feature Request</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Will Not Fix</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Pending Release</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>More Info Reqd from Support</fullName>
                </value>
                <value>
                    <fullName>Never</fullName>
                </value>
                <value>
                    <fullName>Not a bug</fullName>
                </value>
                <value>
                    <fullName>Not Reproducible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Test_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Test Plan</label>
        <referenceTo>QA_Test_Plan__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bug</fullName>
                </value>
                <value>
                    <fullName>Gack</fullName>
                </value>
                <value>
                    <fullName>Help</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Test Change</fullName>
                </value>
                <value>
                    <fullName>Test Case</fullName>
                </value>
                <value>
                    <fullName>Test Failure</fullName>
                </value>
                <value>
                    <fullName>Test Tool</fullName>
                </value>
                <value>
                    <fullName>Skunkforce</fullName>
                </value>
                <value>
                    <fullName>Bug List</fullName>
                </value>
                <value>
                    <fullName>Translation</fullName>
                </value>
                <value>
                    <fullName>Non Deterministic Test</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <recordTypes>
        <fullName>Bug</fullName>
        <active>true</active>
        <description>Used to track defects or problems</description>
        <label>Bug</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>ADM_Work__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A connection to the Agile Accelerator Work object used to track Bugs, Investigations and User Stories</description>
        <label>Work</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>AgileAcceleratorCases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/QA_Test_Case__c.object
<CustomObject>
    <description>QAForce2 Test Case Object</description>
    <fields>
        <fullName>Brief_Description__c</fullName>
        <label>Brief Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Execution_Type__c</fullName>
        <label>Execution Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manual</fullName>
                    <default>true</default>
                    <label>Manual</label>
                </value>
                <value>
                    <fullName>Automated</fullName>
                </value>
                <value>
                    <fullName>End To End</fullName>
                </value>
                <value>
                    <fullName>Boundary</fullName>
                </value>
                <value>
                    <fullName>Upgrade Script</fullName>
                </value>
                <value>
                    <fullName>Sanity</fullName>
                </value>
                <value>
                    <fullName>Silktest</fullName>
                </value>
                <value>
                    <fullName>Utest</fullName>
                </value>
                <value>
                    <fullName>.Net</fullName>
                </value>
                <value>
                    <fullName>CTI - script</fullName>
                </value>
                <value>
                    <fullName>Client Automation</fullName>
                </value>
                <value>
                    <fullName>Systest</fullName>
                </value>
                <value>
                    <fullName>ProdTest - Selenium</fullName>
                </value>
                <value>
                    <fullName>ProdTest - API</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hierarchy__c</fullName>
        <label>Hierarchy</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                    <default>true</default>
                    <label>Low</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Test Case</label>
    <nameField>
        <displayFormat>TC-{00000000}</displayFormat>
        <label>Test Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/QA_Test_Execution__c.object
<CustomObject>
    <description>QAForce2 Test Execution Object
Execution of a test case under a particular scenario, i.e., targeted release, build number</description>
    <fields>
        <fullName>Bugs__c</fullName>
        <description>Comma separated list of bugs associated to this test execution</description>
        <inlineHelpText>Comma separated list of bugs associated to this test execution</inlineHelpText>
        <label>Bugs</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>planned: the test will be executed some point in the future
in progress: test has started, result is not ready yet
passed: test executed and passed
failed: test executed and failed
blocked: test execution cannot progress until obstacles are removed</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                    <color>#0B6FCE</color>
                    <default>true</default>
                    <label>Planned</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <color>#FFFF66</color>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Passed</fullName>
                    <color>#419249</color>
                    <label>Passed</label>
                </value>
                <value>
                    <fullName>Failed</fullName>
                    <color>#FF0000</color>
                    <label>Failed</label>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                    <color>#FF6600</color>
                    <label>Blocked</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Test_Case__c</fullName>
        <description>Specifies the parent Test Case object.</description>
        <label>Test Case</label>
        <referenceTo>QA_Test_Case__c</referenceTo>
        <relationshipLabel>Test Executions</relationshipLabel>
        <relationshipName>Test_Executions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Specifies the execution type.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manual</fullName>
                    <default>true</default>
                    <label>Manual</label>
                </value>
                <value>
                    <fullName>Ftest</fullName>
                </value>
                <value>
                    <fullName>Silktest</fullName>
                </value>
                <value>
                    <fullName>Utest</fullName>
                </value>
                <value>
                    <fullName>.Net</fullName>
                </value>
                <value>
                    <fullName>CTI - script</fullName>
                </value>
                <value>
                    <fullName>Client Automation</fullName>
                </value>
                <value>
                    <fullName>Selenium</fullName>
                </value>
                <value>
                    <fullName>Systest</fullName>
                </value>
                <value>
                    <fullName>ProdTest - Selenium</fullName>
                </value>
                <value>
                    <fullName>ProdTest - API</fullName>
                </value>
                <value>
                    <fullName>ProdTest - Extended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Test Execution</label>
    <nameField>
        <displayFormat>{MM}{DD}{YY} - {0}</displayFormat>
        <label>Test Execution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Executions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/QA_AddTEtoUSExtension.cls
public with sharing class QA_AddTEtoUSExtension {
    public class TEResult{
        public QA_Test_Execution__c te { get; set; }
        public String isSuccess { get; set; }
        public String id { get; set; }
        public String tcName { get; set; }

        public TEResult(Database.SaveResult saveResult, QA_Test_Execution__c te, String tcName) {
            this.te = te;
            this.tcName = tcName;

            if(saveResult.isSuccess()) {
                isSuccess = '/img/approvals/checkbox_16x16.gif';
                id = saveResult.getId();
            } else {
                isSuccess = '/img/approvals/stopsign_16x16.gif';
                id = '';
            }
        }
    }

    public class ParameterException extends Exception {}

    public ADM_TextUtils admTextUtils = new ADM_TextUtils();
    public String curUSID { get; set; } //GET parameter for the User Story id
    public String curTPID { get; set; } //GET parameter for the Test Plan id
    public QA_Test_Execution__c baseTE { get; set; } //base TE to capture user input
    public ADM_Work__c curUS { get; set; } //the current US
    public ADM_Work__c[] possibleUS { get; set; } //possible USs if a TP id is passed in
    public Integer possibleUSSize {get; set;}
    public QA_TreeLibrary treeLib;
    public Integer currentStep { get; set; }
    public Boolean bugValidationError;

    public List<QA_Test_Case__c> selectedTestCases { get; set; } //selected TC list
    public List<TEResult> createdTEResults { get; set; } //selected TC list

    public QA_AddTEtoUSExtension(QA_TreeLibrary treeLib) {
        this.curUSID = System.currentPageReference().getParameters().get('usid');
        this.curTPID = System.currentPageReference().getParameters().get('tpid');

        if(this.curUSID != null) {
            this.curUS = ADM_Work.getOneBy('Id', this.curUSID);

            this.currentStep = 1;
        } else if(this.curTPID != null) {
            this.possibleUS = ADM_Work.getAllBy('Test_Plan__c', new List<String>{this.curTPID}, 1, 1000, 'Id', 'ASC');
            possibleUSSize = possibleUS.size();

            this.currentStep = 0;
        } else {
            throw new ParameterException('No User Story nor Test Plan ID provided.');
        }

        this.treeLib = treeLib;

        this.selectedTestCases = new List<QA_Test_Case__c>();
        this.createdTEResults = new List<TEResult>();
        this.baseTE = new QA_Test_Execution__c();
        this.bugValidationError = false;
    }

    public String getUserStoryInfo() {
        String html = '<table width=\"100%\">';
        html += '<tr><td width=\"150px\"><strong>User Story:</strong></td>';
        html += '<td><a target=\"_blank\" href=\"/' + this.curUS.Id + '\">' + this.curUS.Name + '</a></td></tr>';
        if(this.curUS.Description__c != null) {
            html += '<tr><td>' + admTextUtils.escapeHTML(this.curUS.Description__c) + '</td></tr>';
        }
        
        if(this.curUS.Sprint__r.Name != null) {
            html += '<tr><td><strong>Sprint:</strong></td>';
            html += '<td>' + admTextUtils.escapeHTML(this.curUS.Sprint__r.Name)+ '</td></tr>';
        }
        
        html += '</table>';

        return html;
    }

    public PageReference toStep2() {
        if(this.treeLib.tree.selectedIDs.isEmpty()) {
            this.treeLib.confirmationMessage = QA_TreeLibraryStatic.generateMessageBox(2, 'Please select at least one Test Case.');
        } else {
            this.selectedTestCases = [Select Id, Brief_Description__c, Hierarchy__c, Execution_Type__c, Priority__c from QA_Test_Case__c WHERE Id in :this.treeLib.tree.selectedIDs];
            this.currentStep = 2;
        }
        return null;
    }

    public PageReference createTEs() {
        //validate bug numbers
        Integer bugNum;
        this.bugValidationError = false;
        if(this.baseTE.Bugs__c != null) {
            //iterate through bug list and make sure all are valid bug ids
            for(String curBug : this.baseTE.Bugs__c.split(',')) {
                curBug = curBug.trim();

                //either in the form of "W-000000" or an integer between 1000 and 10000000
                if(curBug.startsWith('W-') && curBug.length() == 8) {
                    try{
                        bugNum = Integer.valueOf(curBug.substring(2)); //strip the "W-" and check if the rest is an integer
                    } catch(Exception e) { //not an integer
                        this.bugValidationError = true;
                        return null;
                    }
                //make sure its an integer between 1000 and 10000000
                } else if(curBug.length() >= 4 && curBug.length() <= 8) {
                    try{
                        bugNum = Integer.valueOf(curBug); //convert string to integer and make sure its the right size
                        if(bugNum < 1000 || bugNum > 10000000) {
                            this.bugValidationError = true;
                            return null;
                        }
                    } catch(Exception e) { //not an integer
                        this.bugValidationError = true;
                        return null;
                    }
                //not in the correct form
                } else {
                    this.bugValidationError = true;
                    return null;
                }
            }
        }

        //if no status selected, set it as planned
        if(this.baseTE.Status__c == null) this.baseTE.Status__c = 'Planned';
        //validations to make sure theres a date of last execution for passed and failed statuses
        if((baseTE.Status__c.equals('Passed') || baseTE.Status__c.equals('Failed')) && baseTE.Date_of_Last_Execution__c == null) return null;

        //create a new execution for each selected TE
        List<QA_Test_Execution__c> newTEs = new List<QA_Test_Execution__c>();
        for(QA_Test_Case__c curTC : this.selectedTestCases) {
            QA_Test_Execution__c newTE = new QA_Test_Execution__c();
            newTE.Test_Case__c = curTC.Id;
            newTE.Assignee__c = this.baseTE.Assignee__c;
            newTE.Type__c = this.baseTE.Type__c;
            newTE.User_Story__c = this.curUSID;
            newTE.Status__c = this.baseTE.Status__c;
            newTE.Bugs__c = this.baseTE.Bugs__c;
            newTE.Number_Of_Executions__c = this.baseTE.Number_Of_Executions__c;
            newTE.Build_of_Last_Execution__c = this.baseTE.Build_of_Last_Execution__c;
            newTE.Date_of_Last_Execution__c = this.baseTE.Date_of_Last_Execution__c;

            newTEs.add(newTE);
        }
        
        try {
            Database.SaveResult[] results = Database.insert(newTEs);
            for(Integer i=0; i<results.size(); i++) {
                this.createdTEResults.add(new TEResult(results[i], newTEs[i], this.selectedTestCases[i].Brief_Description__c));
            } 
    
            this.currentStep = 3;   
        } catch (System.DmlException e) {
            Apexpages.addMessages(e);
        }

        return null;
    }

    public String getBugValidationError() {
        if(this.bugValidationError) {
            return '<strong>Error: </strong>Bugs should be seperated by \',\' and be a number between 1000 - 10000000 or else it should start with \'W-\' followed by a six digit number';
        } else {
            return '';
        }
    }

    public Boolean getDateRequired() {
        if(baseTE.Status__c == 'Passed' || baseTE.Status__c == 'Failed') {
            return true;
        } else {
            return false;
        }
    }

    public PageReference toReturnPage() {
        if(curTPID != null) {
            return new PageReference('/' + curTPID);
        } else {
            return new PageReference('/' + curUSID);
        }
    }

}