mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Triaged</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Investigating</fullName>
                </value>
                <value>
                    <fullName>Ready for Review</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>QA In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Defunct</fullName>
                </value>
                <value>
                    <fullName>Closed - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Closed - Eng Internal</fullName>
                </value>
                <value>
                    <fullName>Closed - Known Bug Exists</fullName>
                </value>
                <value>
                    <fullName>Closed - New Bug Logged</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Approved</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Denied</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved With Internal Tools</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved Without Code Change</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Working as Designed</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Feature Request</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Will Not Fix</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Pending Release</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>More Info Reqd from Support</fullName>
                </value>
                <value>
                    <fullName>Never</fullName>
                </value>
                <value>
                    <fullName>Not a bug</fullName>
                </value>
                <value>
                    <fullName>Not Reproducible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <recordTypes>
        <fullName>Investigation</fullName>
        <active>true</active>
        <description>Used to request R&amp;D triage/diagnosis support for a customer support escalation</description>
        <label>Investigation</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ADM_InvestigationExtensionTest.cls
@IsTest
public with sharing class ADM_InvestigationExtensionTest {
    
    /**
     * Ensure that the doClone method returns the correct page
     */
    public static testMethod void testDoClone() {
        ADM_Work__c work = ADM_Work.createTestWork('Investigation');
        ApexPages.StandardController controller = new ApexPages.StandardController(work);
        ADM_InvestigationExtension extension = new ADM_InvestigationExtension(controller);
        String nameSpacePrefix = ADM_ConstantsSingleton.getInstance().getNameSpace();
        
        PageReference pageReference = extension.doClone();
        String qualifiedPageName = (nameSpacePrefix + 'ADM_InvestigationEdit').toLowerCase();   
        System.assert(pageReference.getUrl().containsIgnoreCase('/'+qualifiedPageName), 'Expected the page reference to go to the ADM_InvestigationEdit page: ' + pageReference.getUrl());
        System.assert(pageReference.getRedirect(), 'Expected the page reference to be a redirect');
        System.assertEquals(work.Id, pageReference.getParameters().get('id'), 'Expected the ID to be specified on the page reference');
        System.assertEquals('1', pageReference.getParameters().get('clone'), 'Expected the clone parameter to be specified on the page reference');
        System.assertEquals('/' + work.Id, pageReference.getParameters().get('retURL'), 'Expected the retURL to be specified on the page reference');
    }
    
    ///// Investigation SLAs
    
    /** Returns true if SLA_Due_Time is in the past, else false */
    @isTest
    static void testGetIsSLAOverdue() {
        ADM_Work__c work = ADM_Work.createTestWork('Investigation');
        ApexPages.StandardController controller = new ApexPages.StandardController(work);
        ADM_InvestigationExtension extension = new ADM_InvestigationExtension(controller);
		work.Due_Date__c = System.now().addHours(4);
        System.assertEquals(false, extension.getIsSLAOverdue());

        work.Due_Date__c = System.now().addHours(-4);
        System.assertEquals(true, extension.getIsSLAOverdue());
    }
    
    /** if Due_Date__c is null returns '',
     *  else if investigation has status New returns 'Acknowledgement Due',
     *  otherwise returns 'Update Due'
     */
    @isTest
    static void testGetSLACountdownLabel() {
        ADM_Work__c work = ADM_Work.createTestWork('Investigation');
        ApexPages.StandardController controller = new ApexPages.StandardController(work);
        ADM_InvestigationExtension extension = new ADM_InvestigationExtension(controller);
		
        Test.startTest();
        work.Due_Date__c = null;
        work.Status__c = 'New';
        System.assertEquals('', extension.getSLACountdownLabel());

		work.Due_Date__c = System.now();
        work.Status__c = 'New';
        System.assertEquals('Acknowledgement Due', extension.getSLACountdownLabel());

        work.Due_Date__c = System.now();
        work.Status__c = 'Investigating';
        System.assertEquals('Update Due From T&P', extension.getSLACountdownLabel());
        
        work.Due_Date__c = System.now();
        work.Status__c = 'More Info Reqd from Support';
        System.assertEquals('Update Due From Support', extension.getSLACountdownLabel());
        Test.stopTest();
    }
    
    /** Due_Date__c | Style should be:
     * 
     *   null | empty string
     *   in the past | color:red
     *   <1 hr from now | color:red
     *   >1 and <4 hrs from now | color:darkorange
     *   >4 hrs from now | color:green
     */    
    @isTest
    static void testGetSLACountdownStyle() {
        ADM_Work__c work = ADM_Work.createTestWork('Investigation');
        ApexPages.StandardController controller = new ApexPages.StandardController(work);
        ADM_InvestigationExtension extension = new ADM_InvestigationExtension(controller);
		
        Test.startTest();
        work.Due_Date__c = null;
        System.assertEquals('', extension.getSLACountdownStyle());
        
        work.Due_Date__c = System.now().addHours(-1);
        System.assertEquals('color:red', extension.getSLACountdownStyle());
        
        work.Due_Date__c = System.now().addMinutes(55);
        System.assertEquals('color:red', extension.getSLACountdownStyle());
        
        work.Due_Date__c = System.now().addHours(3);
        System.assertEquals('color:darkorange', extension.getSLACountdownStyle());
        
        work.Due_Date__c = System.now().addHours(5);
        System.assertEquals('color:green', extension.getSLACountdownStyle());
    }
    
    /** Due_Date__c | LabelStyle should be:
     * 
     *   null | empty string
     *   in the past | color:red
     *   <1 hr from now | color:red
     *   >1 hrs from now | empty string
     */    
    @isTest
    static void testGetSLACountdownLabelStyle() {
        ADM_Work__c work = ADM_Work.createTestWork('Investigation');
        ApexPages.StandardController controller = new ApexPages.StandardController(work);
        ADM_InvestigationExtension extension = new ADM_InvestigationExtension(controller);
		
        Test.startTest();
        work.Due_Date__c = null;
        System.assertEquals('', extension.getSLACountdownLabelStyle());
        
        work.Due_Date__c = System.now().addHours(-1);
        System.assertEquals('color:red', extension.getSLACountdownLabelStyle());
        
        work.Due_Date__c = System.now().addMinutes(55);
        System.assertEquals('color:red', extension.getSLACountdownLabelStyle());
        
        work.Due_Date__c = System.now().addHours(3);
        System.assertEquals('', extension.getSLACountdownLabelStyle());
        
        work.Due_Date__c = System.now().addHours(5);
        System.assertEquals('', extension.getSLACountdownLabelStyle()); 
    }
    
    /** Due_Date__c | Output should be:
     * 
     *   null | empty string
	 *
	 *   in the past | starts with 'Overdue by '
	 *   in the future | starts with 'In '
	 * 
     *   format: [x Day[s]] [y Hour[s]] [z Minute[s]]
     */    
    @isTest
    static void testGetSLADueTimeDiff() {
        ADM_Work__c work = ADM_Work.createTestWork('Investigation');
        ApexPages.StandardController controller = new ApexPages.StandardController(work);
        ADM_InvestigationExtension extension = new ADM_InvestigationExtension(controller);
		
        // padding all times by 30 sec to prevent failed assertions due to clock timing
        
        Test.startTest();
        work.Due_Date__c = null;
        System.assertEquals('', extension.getSLADueTimeDiff());
        
        work.Due_Date__c = System.now().addSeconds(1*60 + 30);
        System.assertEquals('In 1 Minute ', extension.getSLADueTimeDiff());
        
        work.Due_Date__c = System.now().addSeconds(5*60 + 30);
        System.assertEquals('In 5 Minutes ', extension.getSLADueTimeDiff());
        
        work.Due_Date__c = System.now().addSeconds(1*3600 + 30);
        System.assertEquals('In 1 Hour ', extension.getSLADueTimeDiff());
        
        work.Due_Date__c = System.now().addSeconds(4*3600 + 30);
        System.assertEquals('In 4 Hours ', extension.getSLADueTimeDiff());
        
        work.Due_Date__c = System.now().addSeconds(1*24*3600 + 30);
        System.assertEquals('In 1 Day ', extension.getSLADueTimeDiff());
        
        work.Due_Date__c = System.now().addSeconds(4*24*3600 + 30);
        System.assertEquals('In 4 Days ', extension.getSLADueTimeDiff());
        
        work.Due_Date__c = System.now().addSeconds(10*3600 + 29*60 + 30);
        System.assertEquals('In 10 Hours 29 Minutes ', extension.getSLADueTimeDiff());
        
        work.Due_Date__c = System.now().addSeconds(2*24*3600 + 10*3600 + 29*60 + 30);
        System.assertEquals('In 2 Days 10 Hours 29 Minutes ', extension.getSLADueTimeDiff());
        
        work.Due_Date__c = System.now().addSeconds(-(9*60 + 30));
        System.assertEquals('Overdue by 9 Minutes ', extension.getSLADueTimeDiff());
    }
}