mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If you leave this field empty on save you will be the Assignee.</inlineHelpText>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assignee</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Details__c</fullName>
        <inlineHelpText>User type (As a...) Goal (I want to...) Reason (so that...) Additional Details</inlineHelpText>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Details_and_Steps_to_Reproduce__c</fullName>
        <inlineHelpText>Text contents of this field will be sent in initial record creation only</inlineHelpText>
        <label>Details and Steps to Reproduce</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>QA_Engineer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>QA Engineer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QA_Engineer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Triaged</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Investigating</fullName>
                </value>
                <value>
                    <fullName>Ready for Review</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>QA In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Defunct</fullName>
                </value>
                <value>
                    <fullName>Closed - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Closed - Eng Internal</fullName>
                </value>
                <value>
                    <fullName>Closed - Known Bug Exists</fullName>
                </value>
                <value>
                    <fullName>Closed - New Bug Logged</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Approved</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Denied</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved With Internal Tools</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved Without Code Change</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Working as Designed</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Feature Request</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Will Not Fix</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Pending Release</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>More Info Reqd from Support</fullName>
                </value>
                <value>
                    <fullName>Never</fullName>
                </value>
                <value>
                    <fullName>Not a bug</fullName>
                </value>
                <value>
                    <fullName>Not Reproducible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <recordTypes>
        <fullName>Bug</fullName>
        <active>true</active>
        <description>Used to track defects or problems</description>
        <label>Bug</label>
    </recordTypes>
    <recordTypes>
        <fullName>Investigation</fullName>
        <active>true</active>
        <description>Used to request R&amp;D triage/diagnosis support for a customer support escalation</description>
        <label>Investigation</label>
    </recordTypes>
    <recordTypes>
        <fullName>ToDo</fullName>
        <active>true</active>
        <description>Used to track a unit of work that does not need to have anything checked into Source Control nor does it need to have auto assignment rules applied</description>
        <label>ToDo</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ADM_CoreValuesTest.cls
@isTest
private class ADM_CoreValuesTest
{
	 /*
      @testcaseID a1DB00000000q8Q
      @hierarchy GUS.ScrumforcetoGUS.Work Page.User Story.Create Page
      @userstory a0790000000DRvq
      @expectedResults: The Emailed user story contains the following fields: Link, type, subject, Product Area, Major Func Area, Priority, Status, Assignee, QA Engineer, Scrum Team and comments
      @author jhatton
    */
    static testMethod void testGetCoreValuesForUserStory(){
        User u = ADM_WorkUser.createTestUser();
        
        ADM_Work__c w = ADM_Work.createTestWork('User Story');
        w.Assignee__c = u.id;
        w.QA_Engineer__c = u.id;
        w.Details__c = 'This is a test user story';
        update w;
        w = ADM_Work.getById(w.Id);
        
        //get the maps for use with the getCoreValues function
        Map<Id, RecordType> workRecordTypesById = new Map<Id, RecordType>(ADM_RecordType.getAll());
        Map<Id, User> users = new Map<Id, User>{u.Id => u};
        Test.startTest();
        
        Map<String, String> coreValues = ADM_CoreValues.getCoreValues(w, users, workRecordTypesById);
        Test.stopTest();
        
        //verify the core has all of the values
        for(String key : ADM_CoreValues.getKeys('User Story', false)) {
            System.assert(coreValues.containsKey(key), 'Expected core values to contain key ' + key);
        }
        
        //verify the field values in core
        System.assertEquals(workRecordTypesById.get(w.RecordTypeId).Name, coreValues.get( 'Type' ), 'Type in core values map should match the name of the Record Type associated to the work record');
        System.assertEquals(w.Subject__c, coreValues.get( 'Subject' ), 'Subject in core values map should match the subject of the work record');
        System.assertEquals(w.Status__c, coreValues.get( 'Status' ), 'Status in core values map should match the subject of the work record');
        System.assertEquals(u.Name, coreValues.get('Assignee'), 'Assignee in core values map should match the name of Assignee associated to the work record'); 
        System.assertEquals(u.Name, coreValues.get('QA Engineer'), 'QA Engineer in core values map should match the name of the QA Engineer associated to the work record');
        System.assertEquals(w.Details__c, coreValues.get('Description'), 'Description didn\'t match');//https://gus.my.salesforce.com/apex/adm_userstorydetail?id=a07B0000000dypR&sfdc.override=1
    }
    
    /*
      @testcaseID a1DB00000000q8F
      @hierarchy GUS.BugforceToGUS.Work Page.BugsCreatedInGus.Edit and New page
      @userstory a0790000000DRvq
      @expectedResults: User receives an email from the bug just created or edited with the following fields: Link, Type, Subject, Product Area, Major Func Area, Priority, Status, Assignee, QA Engineer and Scrum Team. Also Comments are added at the bottom of the email
      @author alexis.williams
    */
    static testMethod void testGetCoreValuesForBug(){
        User u = ADM_WorkUser.createTestUser();
        
        ADM_Work__c w = ADM_Work.createTestWork('Bug');
        w.Details_and_Steps_to_Reproduce__c = 'test details';
        w.Assignee__c = u.id;
        w.QA_Engineer__c = u.id;
        update w;
        w = ADM_Work.getById(w.Id);
        
        //get the maps for use with the getCoreValues function
        Map<Id, RecordType> workRecordTypesById = new Map<Id, RecordType>(ADM_RecordType.getAll());
        Map<Id, User> users = new Map<Id, User>{u.Id => u}; 

        Map< String, String > coreValues = ADM_CoreValues.getCoreValues(true, w, users, workRecordTypesById);
        
        //verify the core has all of the values
        for(String key : ADM_CoreValues.getKeys('Bug', true)) {
            System.assert(coreValues.containsKey(key), 'Expected core values to contain key ' + key);
        }
        
        //verify the field values in core
        System.assertEquals('Bug', coreValues.get('Type'), 'Type in core values map should match the name of the Record Type associated to the work record');
        System.assertEquals(w.Subject__c, coreValues.get('Subject'), 'Subject in core values map should match the subject of the work record');
        System.assertEquals(u.Name, coreValues.get('Assignee'), 'Assignee in core values map should match the name of Assignee associated to the work record'); 
        System.assertEquals(u.Name, coreValues.get('QA Engineer'), 'QA Engineer in core values map should match the name of the QA Engineer associated to the work record');
        System.assertEquals(w.Details_and_Steps_to_Reproduce__c, coreValues.get( 'Details and Steps to Reproduce' ) );
    }
    
    /*
      @testcaseID a1DB00000000q8P
      @hierarchy GUS.ScrumforceToGUS.Investigation Process.New Investigation page
      @userstory a0790000000DRvq
      @expectedResults: The following fields get emailed on investigation creation: Link, Type, Subject, Product Area, Major Func Area, Status, Assignee, QA Engineer, Scrum Team, Severity Level, Details and Steps to Reproduce and comments
      @author alexis.williams
    */
    static testMethod void testGetCoreValuesForInvestigation(){
        User u = ADM_WorkUser.createTestUser();
        ADM_Work__c w = ADM_Work.createTestWork('Investigation');
        w.Assignee__c = u.id;
        w.QA_Engineer__c = u.id;

        //get the maps for use with the getCoreValues function
        Map<Id, RecordType> workRecordTypesById = new Map<Id, RecordType>(ADM_RecordType.getAll());
        Map<Id, User> users = new Map<Id, User>{u.Id => u}; 

        Map< String, String > coreValues = ADM_CoreValues.getCoreValues(w, users, workRecordTypesById);
        
        //verify the core has all of the values
        for(String key : ADM_CoreValues.getKeys('Investigation', false)) {
            System.assert(coreValues.containsKey(key), 'Expected core values to contain key ' + key);
        }
        
        //verify the field values in core
        System.assertEquals('Investigation', coreValues.get('Type'), 'Type in core values map should match the name of the Record Type associated to the work record');
        System.assertEquals(w.Subject__c, coreValues.get('Subject'), 'Subject in core values map should match the subject of the work record');
        System.assertEquals(u.Name, coreValues.get('Assignee'), 'Assignee in core values map should match the name of Assignee associated to the work record'); 
        System.assertEquals(u.Name, coreValues.get('QA Engineer'), 'QA Engineer in core values map should match the name of the QA Engineer associated to the work record');
    }
    
    /*
      @testcaseID a1DB00000000q8Z
      @hierarchy GUS.ScrumforcetoGUS.Work Page.ToDo.Create Page
      @userstory a0790000000DRvq
      @expectedResults: The following fields get emailed: link, type, subject, scheduled build, priority, status, assignee, scrum team and comments
      @author alexis.williams
    */
    static testMethod void testGetCoreValuesForToDo (){
        User u = ADM_WorkUser.createTestUser();
        ADM_Work__c w = ADM_Work.createTestWork('ToDo');
        w.Assignee__c = u.id;
        w.QA_Engineer__c = u.id;
        
        //get the maps for use with the getCoreValues function
        Map<Id, RecordType> workRecordTypesById = new Map<Id, RecordType>(ADM_RecordType.getAll());
        Map<Id, User> users = new Map<Id, User>{u.Id => u};
        
        Map< String, String > coreValues = ADM_CoreValues.getCoreValues(w, users, workRecordTypesById);
        
        //verify the core has all of the values
        for(String key : ADM_CoreValues.getKeys('ToDo', false)) {
            System.assert(coreValues.containsKey(key), 'Expected core values to contain key ' + key);
        }
        
        //verify the field values in core
        System.assertEquals('ToDo', coreValues.get('Type'), 'Type in core values map should match the name of the Record Type associated to the work record');
        System.assertEquals(w.Subject__c, coreValues.get('Subject'), 'Subject in core values map should match the subject of the work record');
        System.assertEquals(u.Name, coreValues.get('Assignee'), 'Assignee in core values map should match the name of Assignee associated to the work record'); 
        
        //verify that fields are not in the list of core values
        System.assertEquals(false, coreValues.containsKey('QA Engineer'), 'Expected core values to not contain the QA Engineer');
    }
}