mdapi-source/original-package/unpackaged/objects/ADM_Deleted_Task__c.object
<CustomObject>
    <description>Due to a lack of &quot;deletion&quot; events in the streaming API, we have to store the deleted tasks so subscribers can be notified.</description>
    <fields>
        <fullName>Work__c</fullName>
        <description>ID of the work item. This is not a relationship field because the work record may be deleted by the time this value is needed.</description>
        <label>Work</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Deleted Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deleted Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Scrum_Team__c.object
<CustomObject>
    <fields>
        <fullName>Capex_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This team can mark User Stories and Tasks as Capital Expenditures</description>
        <inlineHelpText>This team can mark User Stories and Tasks as Capital Expenditures</inlineHelpText>
        <label>Capitalizable</label>
        <type>Checkbox</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Scrum_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Allocation__c</fullName>
        <label>Allocation (%)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Member_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Scrum_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Analyst</fullName>
                </value>
                <value>
                    <fullName>Architect</fullName>
                </value>
                <value>
                    <fullName>BSA</fullName>
                </value>
                <value>
                    <fullName>Business Owner</fullName>
                </value>
                <value>
                    <fullName>Capacity Planner</fullName>
                </value>
                <value>
                    <fullName>Data Center Engineer</fullName>
                </value>
                <value>
                    <fullName>DBA</fullName>
                </value>
                <value>
                    <fullName>Developer</fullName>
                </value>
                <value>
                    <fullName>Dev Manager</fullName>
                </value>
                <value>
                    <fullName>Doc Editor</fullName>
                </value>
                <value>
                    <fullName>Doc Manager</fullName>
                </value>
                <value>
                    <fullName>Engineering Manager</fullName>
                </value>
                <value>
                    <fullName>Network Engineer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Performance Engineer</fullName>
                </value>
                <value>
                    <fullName>Product Owner</fullName>
                </value>
                <value>
                    <fullName>Program Manager</fullName>
                </value>
                <value>
                    <fullName>Provisioning Specialist / Asset Manager</fullName>
                </value>
                <value>
                    <fullName>QA Engineer</fullName>
                </value>
                <value>
                    <fullName>QA Manager</fullName>
                </value>
                <value>
                    <fullName>Release Engineer</fullName>
                </value>
                <value>
                    <fullName>Release Manager</fullName>
                </value>
                <value>
                    <fullName>Scrum Master</fullName>
                </value>
                <value>
                    <fullName>Security Engineer</fullName>
                </value>
                <value>
                    <fullName>Site Reliability Engineer</fullName>
                </value>
                <value>
                    <fullName>Software Engineer</fullName>
                </value>
                <value>
                    <fullName>SysAdmin</fullName>
                </value>
                <value>
                    <fullName>SysAdmin Linux</fullName>
                </value>
                <value>
                    <fullName>SysAdmin Storage</fullName>
                </value>
                <value>
                    <fullName>SysAdmin Win</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>Scrum_Team_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <displayFormat>STM-{00000}</displayFormat>
        <label>Team Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <recordTypes>
        <fullName>Planned</fullName>
        <active>true</active>
        <description>Planned head count</description>
        <label>Planned</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Task__c.object
<CustomObject>
    <description>Created to import task data from SF</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Waiting on someone else</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Work__c</fullName>
        <label>Work</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Theme__c.object
<CustomObject>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Optional relationship with a scrum team so teams can organize their themes</description>
        <label>Scrum Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipName>Themes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Theme</label>
    <nameField>
        <label>Theme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Themes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If you leave this field empty on save you will be the Assignee.</inlineHelpText>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assignee</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Closed__c</fullName>
        <formula>CASE(  Status__c, &quot;Tested&quot;, 1, &quot;Closed&quot;, 1, &quot;Closed-Untested&quot;, 1, &quot;Closed-U/Ftest&quot;, 1, &quot;Completed&quot;, 1, &quot;Not Reproducible&quot;, 1, &quot;Never&quot;, 1, &quot;Not a bug&quot;, 1, &quot;Duplicate&quot;, 1, &quot;Closed - Duplicate&quot; , 1, &quot;Closed - Known Bug Exists&quot;, 1, &quot;Closed - New Bug Logged&quot;, 1, &quot;Closed - No Fix - Working as Designed&quot;,1, &quot;Closed - No Fix - Feature Request&quot;,1, &quot;Closed - No Fix - Will Not Fix&quot;,1, &quot;Closed - LAP Request Approved&quot;, 1, &quot;Closed - LAP Request Denied&quot;, 1, &quot;Closed - Resolved Without Code Change&quot;, 1, &quot;Rejected&quot;, 1, &quot;Closed - Resolved With Internal Tools&quot;, 1, &quot;Closed - Defunct&quot;,1,&quot;Closed - Doc/Usability&quot;,1,&quot;Closed - Resolved with DB Script&quot;,1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Closed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Triaged</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Investigating</fullName>
                </value>
                <value>
                    <fullName>Ready for Review</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>QA In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Defunct</fullName>
                </value>
                <value>
                    <fullName>Closed - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Closed - Eng Internal</fullName>
                </value>
                <value>
                    <fullName>Closed - Known Bug Exists</fullName>
                </value>
                <value>
                    <fullName>Closed - New Bug Logged</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Approved</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Denied</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved With Internal Tools</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved Without Code Change</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Working as Designed</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Feature Request</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Will Not Fix</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Pending Release</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>More Info Reqd from Support</fullName>
                </value>
                <value>
                    <fullName>Never</fullName>
                </value>
                <value>
                    <fullName>Not a bug</fullName>
                </value>
                <value>
                    <fullName>Not Reproducible</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/classes/ADM_TasksController.cls
global with sharing class ADM_TasksController {

private transient ADM_Scrum_Team_Member__c[] m_scrumTeamMembers = null;

private ADM_ConstantsSingleton signletonConstants = ADM_ConstantsSingleton.getInstance();

public static String ERROR_CAPEX_TASK_ON_CLOSED_STORY = 'You cannot add Quality tasks to a closed user story. Please change user story status to add Quality tasks.';
/*
public ADM_TasksController(){
    initialize();
}

/**
 * Initializes the controller with the data for the specified Sprint
 */
/*
private void initialize() {
    m_scrumTeamMembers = getTeamMembersForTeam(work.Scrum_Team__c);
}
*/

public ADM_Work__c work {
    get;
    set;
}

/**
 * Gets a list of all the team members associated to the specified team.
 */
private static List<ADM_Scrum_Team_Member__c> getTeamMembersForTeam(Id scrumTeamId) {
    return [SELECT Member_Name__r.Id, Member_Name__r.Name, Member_Name__r.FirstName, Member_Name__r.LastName, Member_Name__r.SmallPhotoUrl, Allocation__c, Role__c FROM ADM_Scrum_Team_Member__c WHERE Scrum_Team__r.Id  = :scrumTeamId AND Member_Name__r.Id != null ORDER BY Member_Name__r.Name ];
}

public String getUserSmallPhotoUrl() {
    String userId = UserInfo.getUserId();
    User activeUser = [SELECT SmallPhotoUrl FROM User WHERE Id = :userId LIMIT 1];
    return activeUser.SmallPhotoUrl;
}

public ADM_UserStoryAndTaskWrapper getWorkAndTasks() {
    ADM_Work__c[] works = [SELECT Id, Name, Subject__c, Closed__c, Assignee__r.FirstName, Assignee__r.LastName, Assignee__r.Name, Assignee__r.SmallPhotoUrl, LastModifiedDate, Status__c, RecordType.Name, Capex_Enabled__c, (SELECT Id, Assigned_To__c, Assigned_To__r.Name, Assigned_To__r.FirstName, Assigned_To__r.SmallPhotoUrl, Hours_Remaining__c, Actual_Hours__c, LastModifiedDate, Subject__c, Status__c, Work__c, Work__r.Capex_Enabled__c, Order__c, Capex_Enabled__c FROM Tasks__r ORDER BY Order__c ASC NULLS LAST, CreatedDate ASC) FROM ADM_Work__c WHERE Id = :work.Id];
    List<ADM_UserStoryAndTaskWrapper> workAndTasks = new List<ADM_UserStoryAndTaskWrapper>();
    for(ADM_Work__c work : works) {
        ADM_UserStoryAndTaskWrapper workWrapper = new ADM_UserStoryAndTaskWrapper(work, work.RecordType);
        workAndTasks.add(workWrapper);
    }
    return workAndTasks.get(0);
}

    /**
     * Gets the list of team members associated to this sprint
     */
    public List<ADM_Scrum_Team_Member__c> getTeamMembers() {
        m_scrumTeamMembers = getTeamMembersForTeam(work.Scrum_Team__c);
        return m_scrumTeamMembers;
    }


    /**
     * Create a lightweight version of the ADM_UserStoryAndTaskWrapper so that when
     * it is serialized by the RemoteAction it only contains the sobject properties.
     */
    global class ADM_VirtualWallWork {

        public ADM_Work__c work { get; set; }
        public List<ADM_Task__c> notStartedTasks { get; set; }
        public List<ADM_Task__c> inProgressTasks { get; set; }
        public List<ADM_Task__c> completedTasks { get; set; }

        public ADM_VirtualWallWork(ADM_UserStoryAndTaskWrapper wrapper) {
            this.work = wrapper.getWork();
            this.notStartedTasks = wrapper.getPlannedTasks();
            this.inProgressTasks = wrapper.getInProgressTasks();
            this.completedTasks = wrapper.getCompletedTasks();
        }
    }

    global class TaskOrderChangeRequest {
        public Id workId;
        public List<Id> plannedTasks;
        public List<Id> inProgressTasks;
        public List<Id> completedTasks;
    }

    global virtual class SaveResponse {
        public Id Id;
        public User Assignee;
        public DateTime LastModifiedDate;

        global SaveResponse(Id id, User assignee, DateTime lastModifiedDate) {
            this.Id = id;
            this.Assignee = assignee;
            this.LastModifiedDate = lastModifiedDate;
        }
    }

    global virtual class TaskSaveResponse extends SaveResponse {
        public ADM_Task__c item;

        public TaskSaveResponse(ADM_Task__c task) {
            super(task.Id, task.Assigned_To__r, task.LastModifiedDate);
            this.item = task;
        }
    }

    public Boolean packagedOrg{
        get{
          return signletonConstants.isPackagedOrg();
        }
        set;

    }

    public String nameSpace{
        get{
          return signletonConstants.getNameSpace();
        }
        set;

    }

    @RemoteAction
    global static ADM_VirtualWallWork getWorkById(String workId) {
        ADM_Work__c[] works = [SELECT Id, Name, Closed__c, Subject__c, Assignee__r.Id, Assignee__r.FirstName, Assignee__r.LastName, Assignee__r.Name, Assignee__r.SmallPhotoUrl, LastModifiedById, LastModifiedBy.FirstName, LastModifiedBy.LastName, LastModifiedBy.Name, LastModifiedDate, Status__c, Sprint__c, RecordType.Name, Theme__r.Name, Scheduled_Build__r.Name, Story_Points__c, (SELECT Id, Assigned_To__c, Assigned_To__r.Name, Assigned_To__r.FirstName, Assigned_To__r.SmallPhotoUrl, Hours_Remaining__c, Subject__c, Status__c, Work__c, Order__c, LastModifiedById, LastModifiedBy.FirstName, LastModifiedBy.LastName, LastModifiedBy.Name, LastModifiedDate FROM Tasks__r ORDER BY Order__c ASC NULLS LAST, CreatedDate ASC) FROM ADM_Work__c WHERE Id = :workId and RecordType.Name !=:ADM_Work.TEMPLATE_RECORD_TYPE_NAME and RecordType.Name != :ADM_Work.RECORD_TYPE_NAME_INVESTIGATION];
        if(works.size() == 0) {
            return null;
        } else {
            return new ADM_VirtualWallWork(new ADM_UserStoryAndTaskWrapper(works[0]));
        }
    }

    /**
     * Given the list of tasks, the order is updated sequentially. Any task
     * assigned to the given work item but not in the array of tasks is given
     * a null order.
     *
     * More specifically, if given the following list of ID values
     *    [a0sB00000008dmW, a0sB00000008jhA, a0sB00000008dpQ]
     *
     * Results in the following updates
     *    task[Id=a0sB00000008dmW].Order__c = 1
     *    task[Id=a0sB00000008jhA].Order__c = 2
     *    task[Id=a0sB00000008dpQ].Order__c = 3
     */
    @RemoteAction
    global static ADM_VirtualWallWork updateTaskOrder(TaskOrderChangeRequest request) {
        Id workId = request.workId;

        System.debug('plannedTasks: ' + request.plannedTasks.size());
        System.debug('inProgressTasks: ' + request.inProgressTasks.size());
        System.debug('completedTasks: ' + request.completedTasks.size());

        Map<Id, ADM_Task__c> taskMap = new Map<Id, ADM_Task__c>([SELECT Id, Status__c, Order__c From ADM_Task__c WHERE Work__c = :workId]);

        //reset all order values to null
        for(ADM_Task__c task : taskMap.values()) {
            task.Order__c = null;
        }

        //change the planned tasks to the order specified
        for(Integer index = 0; index < request.plannedTasks.size(); index++) {
            String taskId = request.plannedTasks.get(index);

            //if the ID specified in the order is not a valid task ID skip it
            if(!taskMap.containsKey(taskId)) {
                System.debug(LoggingLevel.WARN, 'ID at index ' + index + ' is not a valid task ID. Skipping this index.');
                continue;
            }

            ADM_Task__c task = taskMap.get(taskId);
            task.Order__c = index + 1;
            if(task.Status__c == 'In Progress' || task.Status__c == 'Completed') {
                task.Status__c = 'Not Started';
            }
        }

        //change the in progress tasks to the order specified
        for(Integer index = 0; index < request.inProgressTasks.size(); index++) {
            String taskId = request.inProgressTasks.get(index);

            //if the ID specified in the order is not a valid task ID skip it
            if(!taskMap.containsKey(taskId)) {
                System.debug(LoggingLevel.WARN, 'ID at index ' + index + ' is not a valid task ID. Skipping this index.');
                continue;
            }

            ADM_Task__c task = taskMap.get(taskId);
            task.Order__c = index + 1;
            if(task.Status__c != 'In Progress') {
                task.Status__c = 'In Progress';
            }
        }

        //change the completed tasks to the order specified
        for(Integer index = 0; index < request.completedTasks.size(); index++) {
            String taskId = request.completedTasks.get(index);

            //if the ID specified in the order is not a valid task ID skip it
            if(!taskMap.containsKey(taskId)) {
                System.debug(LoggingLevel.WARN, 'ID at index ' + index + ' is not a valid task ID. Skipping this index.');
                continue;
            }

            ADM_Task__c task = taskMap.get(taskId);
            task.Order__c = index + 1;
            if(task.Status__c != 'Completed') {
                task.Status__c = 'Completed';
            }
        }

        Database.update(taskMap.values());

        ADM_VirtualWallWork updatedWork = getWorkById(workId);
        return updatedWork;
    }

    /**
     * Given the list of tasks, the order is updated sequentially. Any task
     * assigned to the given work item but not in the array of tasks is given
     * a null order.
     *
     * More specifically, if given the following list of ID values
     *    [a0sB00000008dmW, a0sB00000008jhA, a0sB00000008dpQ]
     *
     * Results in the following updates
     *    task[Id=a0sB00000008dmW].Order__c = 1
     *    task[Id=a0sB00000008jhA].Order__c = 2
     *    task[Id=a0sB00000008dpQ].Order__c = 3
     */
    @AuraEnabled
    public static String updateTaskOrderAura(String jsonRequest) {
        TaskOrderChangeRequest request = (TaskOrderChangeRequest) JSON.deserialize(jsonRequest, TaskOrderChangeRequest.class);
        Id workId = request.workId;

        System.debug('plannedTasks: ' + request.plannedTasks.size());
        System.debug('inProgressTasks: ' + request.inProgressTasks.size());
        System.debug('completedTasks: ' + request.completedTasks.size());

        Map<Id, ADM_Task__c> taskMap = new Map<Id, ADM_Task__c>([SELECT Id, Status__c, Order__c From ADM_Task__c WHERE Work__c = :workId]);

        //reset all order values to null
        for(ADM_Task__c task : taskMap.values()) {
            task.Order__c = null;
        }

        //change the planned tasks to the order specified
        for(Integer index = 0; index < request.plannedTasks.size(); index++) {
            String taskId = request.plannedTasks.get(index);

            //if the ID specified in the order is not a valid task ID skip it
            if(!taskMap.containsKey(taskId)) {
                System.debug(LoggingLevel.WARN, 'ID at index ' + index + ' is not a valid task ID. Skipping this index.');
                continue;
            }

            ADM_Task__c task = taskMap.get(taskId);
            task.Order__c = index + 1;
            if(task.Status__c == 'In Progress' || task.Status__c == 'Completed') {
                task.Status__c = 'Not Started';
            }
        }

        //change the in progress tasks to the order specified
        for(Integer index = 0; index < request.inProgressTasks.size(); index++) {
            String taskId = request.inProgressTasks.get(index);

            //if the ID specified in the order is not a valid task ID skip it
            if(!taskMap.containsKey(taskId)) {
                System.debug(LoggingLevel.WARN, 'ID at index ' + index + ' is not a valid task ID. Skipping this index.');
                continue;
            }

            ADM_Task__c task = taskMap.get(taskId);
            task.Order__c = index + 1;
            if(task.Status__c != 'In Progress') {
                task.Status__c = 'In Progress';
            }
        }

        //change the completed tasks to the order specified
        for(Integer index = 0; index < request.completedTasks.size(); index++) {
            String taskId = request.completedTasks.get(index);

            //if the ID specified in the order is not a valid task ID skip it
            if(!taskMap.containsKey(taskId)) {
                System.debug(LoggingLevel.WARN, 'ID at index ' + index + ' is not a valid task ID. Skipping this index.');
                continue;
            }

            ADM_Task__c task = taskMap.get(taskId);
            task.Order__c = index + 1;
            if(task.Status__c != 'Completed') {
                task.Status__c = 'Completed';
            }
        }

        Database.update(taskMap.values());

        String updatedWork = ADM_SprintVirtualWallController.getWorkWrapperAsJSON(workId);
        return updatedWork;
    }

    /**
     * Gets the order of the tasks for the specified work item.
     */
    @RemoteAction
    global static TaskOrderResponse getTaskOrder(String workId) {
        ADM_VirtualWallWork work = getWorkById(workId);
        if(work != null) {
           return new TaskOrderResponse(work);
        } else {
            return null;
        }
    }

    @RemoteAction
    global static ADM_Task__c getTaskById(String taskId) {
        ADM_Task__c[] tasks = [select Actual_Hours__c, Assigned_To__c, Assigned_To__r.Id, Assigned_To__r.FirstName, Assigned_To__r.LastName, Assigned_To__r.Name, Assigned_To__r.SmallPhotoUrl, Comments__c, Hours_Remaining__c, Id, LastModifiedById, LastModifiedBy.FirstName, LastModifiedBy.LastName, LastModifiedBy.Name, LastModifiedDate, Name, Order__c, Starting_Hours__c, Status__c, Subject__c, Work__c, Work__r.Capex_Enabled__c, Capex_Enabled__c from ADM_Task__c where Id = :taskId limit 1];
        if(tasks.size() == 0) {
            return null;
        } else {
            return tasks[0];
        }
    }

    @RemoteAction
    global static ADM_Deleted_Task__c getDeletedTaskById(String logId) {
        ADM_Deleted_Task__c[] logEntries = [select Name, Work__c, Task__c, LastModifiedById, LastModifiedBy.FirstName, LastModifiedBy.LastName, LastModifiedBy.Name, LastModifiedDate from ADM_Deleted_Task__c where Id = :logId];
        if(logEntries.size() == 0) {
            return null;
        } else {
            return logEntries[0];
        }
    }

    /**
     * Saves the specified work object.
     */
    @RemoteAction
    global static SaveResponse saveTask(ADM_Task__c task, DateTime lastModifiedDate) {
        if(task == null) {
            return null;
        }

        if(lastModifiedDate != null && task.Id != null) {
            List<ADM_Task__c> currentTaskList = [select Id, Name, LastModifiedDate, LastModifiedBy.Name from ADM_Task__c where Id = :task.Id];
            if(!currentTaskList.isEmpty()) {
                ADM_Task__c currentTask = currentTaskList.get(0);

                //check to see if the record has been modified since the current user has downloaded
                if(currentTask.LastModifiedDate != lastModifiedDate && currentTask.LastModifiedBy.Id != UserInfo.getUserId()) {
                   throw new ADM_ApplicationException('Egads! ' + currentTask.LastModifiedBy.Name + ' modified task ' + currentTask.Name + ' since your last sync. Refresh the page to retrieve the latest data.');
                }
            }
        }

        try {
            upsert task;
        } catch(Exception e) {
            String errMsg = e.getMessage();
            String[] taskErrorNonEmployee = ADM_Task.TASK_ERROR_NONEMPLOYEE.split('<0>');

            if (errMsg.containsIgnoreCase(ERROR_CAPEX_TASK_ON_CLOSED_STORY)) {
                throw new ADM_ApplicationException(ERROR_CAPEX_TASK_ON_CLOSED_STORY);
            } else if (errMsg.containsIgnoreCase(taskErrorNonEmployee[0]) && errMsg.containsIgnoreCase(taskErrorNonEmployee[1])) {
                throw new ADM_ApplicationException(errMsg.substring(errMsg.indexOf(taskErrorNonEmployee[0]), errMsg.indexOf(taskErrorNonEmployee[1]) + (taskErrorNonEmployee[1].length())));
            } else {
                throw new ADM_ApplicationException(errMsg);
            }
        }

        task = getTaskById(task.Id);
        return new TaskSaveResponse(task);
    }

    /**
     * Deletes the task corresponding to the ID from the database.
     * @returns Returns true if the deletion was successful.
     */
    @RemoteAction
    global static Boolean deleteTask(Id taskId) {
        List<ADM_Task__c> tasks = [select Id from ADM_Task__c where Id = :taskId limit 1];
        if(!tasks.isEmpty()) {
           delete tasks;
        }
        return true;
    }

    /**
     * Deletes the task corresponding to the ID from the database.
     * @returns Returns true if the deletion was successful.
     */
    @AuraEnabled
    global static Boolean deleteTaskAura(Id recordId) {
        List<ADM_Task__c> tasks = [select Id from ADM_Task__c where Id = :recordId limit 1];
        if(!tasks.isEmpty()) {
           delete tasks;
        }
        return true;
    }


    @AuraEnabled
    public static String deleteTaskAuraNew(Id recordId) {
        List<ADM_Task__c> tasks = [select Id, Work__c from ADM_Task__c where Id = :recordId limit 1];

        Id workId = tasks[0].Work__c;

        if(!tasks.isEmpty()) {
           delete tasks;
        }
        return ADM_SprintVirtualWallController.getWorkWrapperAsJSON(workId);
    }

    @AuraEnabled
    public static String getUserInfoAura() {
        User u = [select Id, Name, SmallPhotoUrl from User where Id = :UserInfo.getUserId() limit 1];
        
        return JSON.serialize(u);
    }

    @AuraEnabled
    public static void setShowDeleteTaskDialogAura() {
        ADM_User_Preferences__c preferences = ADM_User_Preferences__c.getInstance(UserInfo.getUserId());
        
        preferences.ShowDeleteTaskDialog__c = false;
        
        upsert preferences;
    }

    @RemoteAction
    global static Boolean changeTaskStatusToInProgress(Id taskId) {
        return changeTaskStatusTo(taskId, 'In Progress');
    }

    @RemoteAction
    global static Boolean changeTaskStatusToPlanned(Id taskId) {
        return changeTaskStatusTo(taskId, 'Not Started');
    }

    @RemoteAction
    global static Boolean changeTaskStatusToCompleted(Id taskId) {
        return changeTaskStatusTo(taskId, 'Completed');
    }


    /**
     * Utility function for changing the status of a task to the specified value
     */
     @RemoteAction
    global static Boolean changeTaskStatusTo(Id taskId, String statusValue) {
        ADM_Task__c t = [select Id, Status__c from ADM_Task__c where Id = :taskId limit 1];
        if (t != null) {
            t.Status__c = statusValue;
            update t;
        }
        return true;
    }

    /**
     * Lightweight object sent when a client wants to get the order of the tasks
     * associated to a work item (using #getTaskOrder).
     */
    global class TaskOrderResponse {
        public Id workId;
        public List<Id> notStartedTasks = new List<Id>();
        public List<Id> inProgressTasks = new List<Id>();
        public List<Id> completedTasks = new List<Id>();

        public TaskOrderResponse(ADM_VirtualWallWork work) {
            workId = work.work.Id;

            for(ADM_Task__c task : work.notStartedTasks) {
                notStartedTasks.add(task.Id);
            }
            for(ADM_Task__c task : work.inProgressTasks) {
                inProgressTasks.add(task.Id);
            }
            for(ADM_Task__c task : work.completedTasks) {
                completedTasks.add(task.Id);
            }
        }
    }

}