mdapi-source/original-package/unpackaged/objects/ADM_Assignment_Rule__c.object
<CustomObject>
    <description>Used to populate the Assignment Rules on ADM_Work__c records</description>
    <fields>
        <fullName>Exception_Request_POC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person assigned to exception records created from investigation records</description>
        <label>Exception Request POC</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assignment_Rules5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If this field is empty it will be pre-populated with the Product Owner for the rule&apos;s scrum team.</inlineHelpText>
        <label>Product Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assignment_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assignment Rule</label>
    <nameField>
        <label>Assignment Rule</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignment Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Investigation_Exception__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The person making the decision - varies by status</inlineHelpText>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Investigation_Exceptions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <label>Investigation</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipName>Investigation_Exceptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reason_for_Request__c</fullName>
        <description>Should be filled out by the Requestor</description>
        <inlineHelpText>Should be filled out by the Requestor</inlineHelpText>
        <label>Reason for Request</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person who created the exception. Value entered automatically upon saving the record.</description>
        <inlineHelpText>Person who created the exception. Value entered automatically upon saving the record.</inlineHelpText>
        <label>Requestor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Investigation_Exceptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Under Review</fullName>
                    <default>true</default>
                    <label>Under Review</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Parent Investigation Resolved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Check the Help For this page link for more examples</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Severity level upgrade</fullName>
                    <default>true</default>
                    <label>Severity level upgrade</label>
                </value>
                <value>
                    <fullName>More status updates/assigned resources</fullName>
                </value>
                <value>
                    <fullName>During business hours request for after hours resources/communication</fullName>
                </value>
                <value>
                    <fullName>After hours triage/diagnosis of Sev 2</fullName>
                </value>
                <value>
                    <fullName>After hours request for after hours resources</fullName>
                </value>
                <value>
                    <fullName>Acknowledgment of a Severity 4 Investigation</fullName>
                </value>
                <value>
                    <fullName>SLA violated by T&amp;P</fullName>
                </value>
                <value>
                    <fullName>SLA violated by Support</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Exception Request</label>
    <nameField>
        <displayFormat>IE-{00000}</displayFormat>
        <label>Investigation Exception Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Tag_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Assignment_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment Rule</label>
        <referenceTo>ADM_Assignment_Rule__c</referenceTo>
        <relationshipLabel>Tag Assignments</relationshipLabel>
        <relationshipName>Tag_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Tag__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Tag</label>
        <referenceTo>ADM_Product_Tag__c</referenceTo>
        <relationshipLabel>Tag Assignments</relationshipLabel>
        <relationshipName>Tag_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <label>Record Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bug</fullName>
                </value>
                <value>
                    <fullName>User Story</fullName>
                </value>
                <value>
                    <fullName>Investigation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tag Assignment</label>
    <nameField>
        <displayFormat>TA-{0000}</displayFormat>
        <label>Tag Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tag Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Product_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If you leave it empty on save you will be the Product Owner</inlineHelpText>
        <label>Product Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Product_Owner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Tag__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TE Activity</label>
        <referenceTo>ADM_Product_Tag__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Product_Tag</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <formula>$RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type of Record(Deprecated)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Severity_Level__c</fullName>
        <label>Severity Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <color>#000099</color>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <color>#990000</color>
                    <label>2</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <color>#FF6600</color>
                    <label>3</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <color>#F3D904</color>
                    <label>4</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bug</fullName>
                </value>
                <value>
                    <fullName>Gack</fullName>
                </value>
                <value>
                    <fullName>Help</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Test Change</fullName>
                </value>
                <value>
                    <fullName>Test Case</fullName>
                </value>
                <value>
                    <fullName>Test Failure</fullName>
                </value>
                <value>
                    <fullName>Test Tool</fullName>
                </value>
                <value>
                    <fullName>Skunkforce</fullName>
                </value>
                <value>
                    <fullName>Bug List</fullName>
                </value>
                <value>
                    <fullName>Translation</fullName>
                </value>
                <value>
                    <fullName>Non Deterministic Test</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <recordTypes>
        <fullName>Bug</fullName>
        <active>true</active>
        <description>Used to track defects or problems</description>
        <label>Bug</label>
    </recordTypes>
    <recordTypes>
        <fullName>Investigation</fullName>
        <active>true</active>
        <description>Used to request R&amp;D triage/diagnosis support for a customer support escalation</description>
        <label>Investigation</label>
    </recordTypes>
    <recordTypes>
        <fullName>Template</fullName>
        <active>true</active>
        <description>Used to store common values which can then be applied to new Bugs</description>
        <label>Template</label>
    </recordTypes>
    <recordTypes>
        <fullName>ToDo</fullName>
        <active>true</active>
        <description>Used to track a unit of work that does not need to have anything checked into Source Control nor does it need to have auto assignment rules applied</description>
        <label>ToDo</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>ADM_Work__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A connection to the Agile Accelerator Work object used to track Bugs, Investigations and User Stories</description>
        <label>Work</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>AgileAcceleratorCases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

force-app/main/default/classes/ADM_InvestigationExceptionTests.cls
@isTest
private class ADM_InvestigationExceptionTests {
    private static String type_ack = 'Acknowledgment of a Severity 4 Investigation';
    private static String type_after = 'After hours request for after hours resources';
    private static String type_triage = 'After hours triage/diagnosis of Sev 2';
    private static String type_req = 'During business hours request for after hours resources/communication';
    private static String type_udpates = 'More status updates/assigned resources';
    private static String type_upgrades = 'Severity level upgrade';
    private static String type_sev2 = 'After hours triage/diagnosis of Sev 2';
    private static String reason = 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.';
    private static String inv_resolved = 'Parent Investigation Resolved';
    private static String inv_approved = 'Approved';
    private static String dec_expl = 'This Exception Request was neither Accepted nor Rejected - its parent Investigation was closed.';
    private static ADM_errorUtils errorUtils = new ADM_errorUtils();

    private static ADM_Assignment_Rule__c rule {
        get {
            if(rule == null) {
                rule = ADM_AssignmentRuleTest.setupRuleInvestigation();
                rule = ADM_AssignmentRule.getById(rule.Id);
            }
            return rule;
        }
        set;
    }

    private static User user {
        get {
            if(user == null) {
                user = ADM_WorkUser.createTestUser();
            }
            return user;
        }
        set;
    }

    private static ADM_Work__c investigation {
        get {
            if(investigation == null) {
                investigation = ADM_Work.createTestWork(ADM_Work.RECORD_TYPE_NAME_INVESTIGATION);
            }
            return investigation;
        }
        set;
    }

    private static ADM_Work__c bug {
        get {
            if(bug == null) {
                bug = ADM_Work.createTestBug();
            }
            return bug;
        }
        set;
    }

    private static ADM_Work__c todo {
        get {
            if(todo == null) {
                todo = ADM_Work.createTestTodo();
            }
            return todo;
        }
        set;
    }

    private static ADM_Work__c template {
        get {
            if(template == null) {
                template = ADM_Work.createTestTemplate();
            }
            return template;
        }
        set;
    }

    private static ADM_Work__c us {
        get {
            if(us == null) {
                us = ADM_Work.createTestWork(ADM_Work.RECORD_TYPE_NAME_USERSTORY);
            }
            return us;
        }
        set;
    }

    private static ADM_Investigation_Exception__c getIe(String Id) {
        ADM_Investigation_Exception__c ie = new ADM_Investigation_Exception__c();
        ie =  [select Assigned_To__c, Requestor__c from ADM_Investigation_Exception__c where Id = : Id];
        return ie;
    }

    /*
      @testcaseID: a0B20000007mipoEAA
      @hierarchy: GUS.ScrumforceToGUS.Investigation Process.Investigation Exceptions
      @userstory: a0A20000006VD2E
      @expectedResults: Exceptions can only be linked to Investigation work items
      @author Alexis Williams
    */

    private static testMethod void linkExceptionToBug() {
        ensureProductionSupportManagersUser();
        ADM_Investigation_Exception__c ex = new ADM_Investigation_Exception__c();
        ex.Investigation__c = bug.Id;
        ex.Reason_for_Request__c = reason;
        ex.Type__c = type_ack;
        try {
          insert ex;
          System.assertNotEquals(true, Apexpages.hasMessages());
        } catch(System.DmlException e) {
            String error = errorUtils.getErrorMessage(e);
            System.assertEquals('Investigation exceptions must be related to work records that are Investigation not Bug',error);
        }
    }

    /*
      @testcaseID: a0B20000007mippEAA
      @hierarchy: GUS.ScrumforceToGUS.Investigation Process.Investigation Exceptions
      @userstory: a0A20000006VD2E
      @expectedResults: Exceptions can only be linked to Investigation work items
      @author Alexis Williams
    */

    private static testMethod void linkExceptionToToDo() {
        ensureProductionSupportManagersUser();
        ADM_Investigation_Exception__c ex = new ADM_Investigation_Exception__c();
        ex.Investigation__c = todo.Id;
        ex.Reason_for_Request__c = reason;
        ex.Type__c = type_ack;
        try {
          insert ex;
          System.assertNotEquals(true, Apexpages.hasMessages());
        } catch(System.DmlException e) {
            String error = errorUtils.getErrorMessage(e);
            System.assertEquals('Investigation exceptions must be related to work records that are Investigation not ToDo',error);
        }
    }

    /*
      @testcaseID: a0B20000008dKvnEAE
      @hierarchy: GUS.ScrumforceToGUS.Investigation Process.Investigation Exceptions
      @userstory: a0A20000006VD2E
      @expectedResults: An error is generated that exceptions can only be linked to investigations
      @author Alexis Williams
    */

    private static testMethod void linkExceptionToTemplate() {
        ensureProductionSupportManagersUser();
        ADM_Investigation_Exception__c ex = new ADM_Investigation_Exception__c();
        ex.Investigation__c = template.Id;
        ex.Reason_for_Request__c = reason;
        ex.Type__c = type_ack;
        try {
          insert ex;
          System.assertNotEquals(true, Apexpages.hasMessages());
        } catch(System.DmlException e) {
            String error = errorUtils.getErrorMessage(e);
            System.assertEquals('Investigation exceptions must be related to work records that are Investigation not Template',error);
        }
    }

    /*
      @testcaseID: a0B20000007mipnEAA
      @hierarchy: GUS.ScrumforceToGUS.Investigation Process.Investigation Exceptions
      @userstory: a0A20000006VD2E
      @expectedResults: Exceptions can only be linked to Investigation work items
      @author Alexis Williams
    */

    private static testMethod void linkExceptionToUserStory() {
        ensureProductionSupportManagersUser();
        ADM_Investigation_Exception__c ex = new ADM_Investigation_Exception__c();
        ex.Investigation__c = us.Id;
        ex.Reason_for_Request__c = reason;
        ex.Type__c = type_ack;
        try {
          insert ex;
          System.assertNotEquals(true, Apexpages.hasMessages());
        } catch(System.DmlException e) {
            String error = errorUtils.getErrorMessage(e);
            System.assertEquals('Investigation exceptions must be related to work records that are Investigation not User Story',error);
        }
    }

    /*
      @testcaseID: a0B20000008dLdFEAU
      @hierarchy: GUS.ScrumforceToGUS.Investigation Process.Investigation Exceptions
      @userstory: a0A20000006VD2E
      @expectedResults: Product Owner on Assignment rule is mandatory
      @author Alexis Williams
    */

    private static testMethod void linkExceptionToInvestigationAcknowledgedError() {
        ensureProductionSupportManagersUser();
        ADM_Investigation_Exception__c ex = new ADM_Investigation_Exception__c();
        ex.Investigation__c = investigation.Id;
        ex.Reason_for_Request__c = reason;
        ex.Type__c = type_ack;
        try {
          insert ex;
          System.assertNotEquals(true, Apexpages.hasMessages());
        } catch(System.DmlException e) {
            String error = errorUtils.getErrorMessage(e);
            System.assertEquals('The related investigation does not have a Product Owner assigned.',error);
        }
    }

    /*
      @testcaseID: a0B20000007mihPEAQ
      @hierarchy: GUS.ScrumforceToGUS.Investigation Process.Investigation Exceptions
      @userstory: a0A20000006VD2E
      @expectedResults: Exceptions can only be linked to Investigation work items
      @author Alexis Williams
    */

    private static testMethod void linkExceptionToInvestigationAcknowledgedNoErrors() {
        ensureProductionSupportManagersUser();
    	User productionManagers = ensureProductionSupportManagersUser();
        ADM_Investigation_Exception__c ex = new ADM_Investigation_Exception__c();
        ex.Investigation__c = investigation.Id;
        ex.Reason_for_Request__c = reason;
        ex.Type__c = type_ack;
        investigation.Product_Owner__c = user.Id;
        Test.startTest();
        update investigation;
        insert ex;
        Test.stopTest();
        ADM_Investigation_Exception__c ie = getIe(ex.Id);
        System.assertEquals(false,Apexpages.hasMessages());
        System.assertEquals(productionManagers.Id, ie.Assigned_To__c, 'Expected the request to be assigned to the Production Support Managers');
        System.assertEquals(userInfo.getUserId(),ie.Requestor__c);
    }





    /*
      @testcaseID: a0B20000007mipsEAA
      @hierarchy: GUS.ScrumforceToGUS.Investigation Process.Investigation Exceptions
      @userstory: a0A20000006VD2E
      @expectedResults: delete exception
      @author Alexis Williams
    */

    private static testMethod void deleteInvestigation() {
        ensureProductionSupportManagersUser();
        ADM_Investigation_Exception__c ex = new ADM_Investigation_Exception__c();
        ex.Investigation__c = investigation.Id;
        ex.Reason_for_Request__c = reason;
        ex.Type__c = type_ack;
        investigation.Product_Owner__c = user.Id;
        Test.startTest();
        update investigation;
        insert ex;
        delete ex;
        Test.stopTest();
        try {
            ADM_Investigation_Exception__c ie = getIe(ex.Id);
            System.assertEquals(null,ie.Id);
        } catch(System.QueryException e) {
            //expecting an error to be thrown here!
        }
    }

    /*
      @testcaseID: a0B20000007miptEAA
      @hierarchy: GUS.ScrumforceToGUS.Investigation Process.Investigation Exceptions
      @userstory: a0A20000006VD2E
      @expectedResults: clone exception
      @author Alexis Williams
    */

    private static testMethod void cloneInvestigation() {
    	ensureProductionSupportManagersUser();
        ADM_Investigation_Exception__c ex = new ADM_Investigation_Exception__c();
        ex.Investigation__c = investigation.Id;
        ex.Reason_for_Request__c = reason;
        ex.Type__c = type_ack;
        investigation.Product_Owner__c = user.Id;
        Test.startTest();
        update investigation;
        insert ex;
        Test.stopTest();

        ADM_Investigation_Exception__c clone = ex.clone(false,true);

        Apexpages.Standardcontroller controller = new Apexpages.Standardcontroller(clone);
        controller.save();

        System.assertEquals(false, Apexpages.hasMessages());
    }

    /*
      @testcaseID: a0B20000007miyXEAQ
      @hierarchy: GUS.ScrumforceToGUS.Investigation Process.Investigation Exceptions
      @userstory: a0A20000006VD2E
      @expectedResults: When exceptions are updated with a status of accepted, the email notification goes to the assignee and the person who filed the request
      @author Alexis Williams
    */

   /*
      @testcaseID: a0B20000008dLN3EAM
      @hierarchy: GUS.ScrumforceToGUS.Investigation Process.Investigation Exceptions
      @userstory: a0A20000006VD2E
      @expectedResults: Fields that are not updatable are Investigation Exception Name and Investigation ID. Assignee = OSCt
      @author Alexis Williams
    */

    private static testMethod void updateInvestigation() {
        ensureProductionSupportManagersUser();
        ADM_Investigation_Exception__c ex = new ADM_Investigation_Exception__c();
        ex.Investigation__c = investigation.Id;
        ex.Reason_for_Request__c = reason;
        ex.Type__c = type_ack;
        investigation.Product_Owner__c = user.Id;
        Test.startTest();
        update investigation;
        insert ex;
        Test.stopTest();

        Apexpages.Standardcontroller controller = new Apexpages.Standardcontroller(ex);
        controller.save();

        System.assertEquals(false, Apexpages.hasMessages());
    }

    /*
      @testcaseID: a0B20000007mipqEAA
      @hierarchy: GUS.ScrumforceToGUS.Investigation Process.Investigation Exceptions
      @userstory: a0A20000006VD2E
      @expectedResults: mandatory fields Investigation, reason for request
      @author Alexis Williams
    */

    private static testMethod void verifyRequiredFields() {
        ensureProductionSupportManagersUser();
        ADM_Investigation_Exception__c ex = new ADM_Investigation_Exception__c();
        ex.Type__c = type_after;
        investigation.Severity_Level__c = '1';

        try {
            Test.startTest();
            update investigation;
            insert ex;
            Test.stopTest();
        } catch(System.DmlException e) {
            String error = errorUtils.getErrorMessage(e);
            System.assertEquals('This exception does not have an associated Investigation record.',error);
        }
    }

    /*
      @testcaseID: a0B20000008dVIlEAM
      @hierarchy: GUS.ScrumforceToGUS.Investigation Process.Investigation Exceptions
      @userstory: a0A20000006VD2E
      @expectedResults:Error: A matching assignment rule with an Exception Request POC was not found
      @author Alexis Williams
    */

    private static testMethod void linkExceptionToInvestigationSeverityUpgradeHighSeverityWithErrors() {
        ensureProductionSupportManagersUser();
        ADM_Investigation_Exception__c ex = new ADM_Investigation_Exception__c();
        ex.Investigation__c = investigation.Id;
        ex.Reason_for_Request__c = reason;
        ex.Type__c = type_upgrades;
        investigation.Severity_Level__c = '1';

        try {
            Test.startTest();
            update investigation;
            insert ex;
            Test.stopTest();
        } catch(System.DmlException e) {
            String error = errorUtils.getErrorMessage(e);
            System.assertEquals('A matching assignment rule with an Exception Request POC was not found.',error);
        }
    }

   /*
      @testcaseID: a0B20000008dLTqEAM
      @hierarchy: GUS.ScrumforceToGUS.Investigation Process.Investigation Exceptions
      @userstory: a0A20000006VD2E
      @expectedResults: Exception is assigned automatically to the Senior Management POC
      @author Alexis Williams
    */
       /*
      @testcaseID: a0B20000008dLdGEAU
      @hierarchy: GUS.ScrumforceToGUS.Investigation Process.Investigation Exceptions
      @userstory: a0A20000006VD2E
      @expectedResults: Exception is assigned automatically to the Senior Management POC
      @author Alexis Williams
    */

    private static testMethod void linkExceptionToInvestigationSeverityUpgradeHighSeverityNoErrors() {
        ensureProductionSupportManagersUser();
        ADM_Investigation_Exception__c ex = new ADM_Investigation_Exception__c();
        ex.Investigation__c = investigation.Id;
        ex.Reason_for_Request__c = reason;
        ex.Type__c = type_upgrades;
        investigation.Severity_Level__c = '1';
        //assign investigation record using Product Tag
        ADM_Product_Tag__c tag = ADM_ProductTag.createAndInsertProductTag();
        //relate tag to assignment rule with an Exception Request POC populated
        ADM_Tag_Assignment__c ta = new ADM_Tag_Assignment__c();
        ta.Product_Tag__c = tag.id;
        ta.Record_Type__c = 'Investigation';
        ta.Assignment_Rule__c = rule.id;
        insert ta;
        investigation.Product_Tag__c = tag.id;

        try {
            Test.startTest();
            update investigation;
            insert ex;
            Test.stopTest();
        } catch(System.DmlException e) {
            String error = errorUtils.getErrorMessage(e);
            System.assertNotEquals(null, rule.Exception_Request_POC__c);
        }

        ADM_Investigation_Exception__c ie = getIe(ex.Id);
        System.assertEquals(false,Apexpages.hasMessages());
        System.assertNotEquals(null,ie.Assigned_To__c);
        System.assertEquals(userInfo.getUserId(),ie.Requestor__c);
    }

    /*
      @testcaseID: a0B20000008dLTsEAM
      @hierarchy: GUS.ScrumforceToGUS.Investigation Process.Investigation Exceptions
      @userstory: a0A20000006VD2E
      @expectedResults: Exception is assigned automatically to the Product Owner
      @author Alexis Williams
    */
      /*
      @testcaseID: a0B20000008dLTtEAM
      @hierarchy: GUS.ScrumforceToGUS.Investigation Process.Investigation Exceptions
      @userstory: a0A20000006VD2E
      @expectedResults: Exception is assigned automatically to the Product Owner
      @author Alexis Williams
    */
    /*
      @testcaseID: a0B20000008dLdDEAU
      @hierarchy: GUS.ScrumforceToGUS.Investigation Process.Investigation Exceptions
      @userstory: a0A20000006VD2E
      @expectedResults: Exception is assigned automatically to the Product Owner
      @author Alexis Williams
    */

    private static testMethod void linkExceptionToInvestigationSeverityUpgradeLowSeverityNoErrors() {
        ensureProductionSupportManagersUser();
    	User productionManagerSupport = ensureProductionSupportManagersUser();
        ADM_Investigation_Exception__c ex = new ADM_Investigation_Exception__c();
        ex.Investigation__c = investigation.Id;
        ex.Reason_for_Request__c = reason;
        ex.Type__c = type_upgrades;
        investigation.Product_Owner__c = user.Id;
        investigation.Severity_Level__c = '4';
        Test.startTest();
        update investigation;
        insert ex;
        Test.stopTest();
        ADM_Investigation_Exception__c ie = getIe(ex.Id);
        System.assertEquals(false,Apexpages.hasMessages());
        System.assertEquals(productionManagerSupport.Id,ie.Assigned_To__c, 'Expected the request to be assigned to the Product Support Managers');
        System.assertEquals(userInfo.getUserId(),ie.Requestor__c, 'Expected the requestor to be set to the current user');
    }

    /*
      @testcaseID: a0B20000007mij0EAA
      @hierarchy: GUS.ScrumforceToGUS.Investigation Process.Investigation Exceptions
      @userstory: a0A20000006VD2E
      @expectedResults: When exceptions are updated with a status of rejected, the email notification goes to the assignee and the person who filed the request
      @author Alexis Williams
    */
        /*
      @testcaseID: a0B20000007minrEAA
      @hierarchy: GUS.ScrumforceToGUS.Investigation Process.Investigation Exceptions
      @userstory: a0A20000006VD2E
      @expectedResults: 
      @author Alexis Williams
    */
    private static testMethod void linkExceptionToInvestigationMoreStatusUpdates() {
        ensureProductionSupportManagersUser();
    	investigation.Product_Owner__c = user.Id;
        investigation.Severity_Level__c = '4';
        update investigation;
        
        ADM_Investigation_Exception__c ex = new ADM_Investigation_Exception__c();
        ex.Investigation__c = investigation.Id;
        ex.Reason_for_Request__c = reason;
        ex.Type__c = type_udpates;
        
        Test.startTest();
        insert ex;
        Test.stopTest();
        
        ADM_Investigation_Exception__c ie = getIe(ex.Id);
        System.assertEquals(false,Apexpages.hasMessages());
        System.assertEquals(userInfo.getUserId(),ie.Requestor__c, 'Expected the current user to be the requestor');
    }

    /*
      @testcaseID: a0B20000007miyNEAQ
      @hierarchy: GUS.ScrumforceToGUS.Investigation Process.Investigation Exceptions
      @userstory: a0A20000006VD2E
      @expectedResults: Fields that are not updatable are Investigation Exception Name and Investigation ID. Assignee = Product Owner
      @author Alexis Williams
    */

    private static testMethod void linkExceptionToInvestigationDuringBusinessHoursReq() {
        ensureProductionSupportManagersUser();
        ADM_Investigation_Exception__c ex = new ADM_Investigation_Exception__c();
        ex.Investigation__c = investigation.Id;
        ex.Reason_for_Request__c = reason;
        ex.Type__c = type_req;
        investigation.Product_Owner__c = user.Id;
        investigation.Severity_Level__c = '4';
        Test.startTest();
        update investigation;
        insert ex;
        Test.stopTest();
        ADM_Investigation_Exception__c ie = getIe(ex.Id);
        System.assertEquals(false,Apexpages.hasMessages());
        System.assertEquals(userInfo.getUserId(),ie.Requestor__c, 'Expected the current user to be the requestor');
    }

    /*
      @testcaseID: a0B20000008dYqnEAE
      @hierarchy: GUS.ScrumforceToGUS.Investigation Process.Investigation Exceptions
      @userstory: a0A20000006VD2E
      @expectedResults: When Type__c = "severity level upgrade" and Severity is less than or equal to 2 the Assignee should the be Exception POC
      @author James Hatton
    */

    private static testMethod void linkExceptionToInvestigationOfTypeSeverityLevelUpgradeSev2OrLower() {
        ensureProductionSupportManagersUser();
        ADM_Investigation_Exception__c ex = new ADM_Investigation_Exception__c();
        ex.Investigation__c = investigation.Id;
        ex.Reason_for_Request__c = reason;
        ex.Type__c = 'severity level upgrade';
        investigation.Product_Owner__c = user.Id;
        investigation.Severity_Level__c = '2';
        //assign investigation record using Product Tag
        ADM_Product_Tag__c tag = ADM_ProductTag.createAndInsertProductTag();
        //relate tag to assignment rule with an Exception Request POC populated
        ADM_Tag_Assignment__c ta = new ADM_Tag_Assignment__c();
        ta.Product_Tag__c = tag.id;
        ta.Record_Type__c = 'Investigation';
        ta.Assignment_Rule__c = rule.id;
        insert ta;
        investigation.Product_Tag__c = tag.id;
        Test.startTest();
        update investigation;
        insert ex;
        Test.stopTest();
        ADM_Investigation_Exception__c ie = getIe(ex.Id);
        System.assertEquals(false,Apexpages.hasMessages());
        System.assertEquals(rule.Exception_Request_POC__c,ie.Assigned_To__c);

    }

    /*
      @testcaseID:   a0B20000008dLN3EAM
      @hierarchy: GUS.ScrumforceToGUS.Investigation Process.Investigation Exceptions
      @userstory: a0A20000006VD2E
      @expectedResults: When Type__c is anything other than "After hours triage/diagnosis of Sev 2 escalation" and severity is greater than 2 the Assignee should the Exception Request POC
      @author James Hatton
    */

    private static testMethod void linkExceptionToInvestigationOfSev2Higher() {
        ensureProductionSupportManagersUser();
        ADM_Investigation_Exception__c ex = new ADM_Investigation_Exception__c();
        ex.Investigation__c = investigation.Id;
        ex.Reason_for_Request__c = reason;
        ex.Type__c = 'after hours request for after hours resources';
        investigation.Product_Owner__c = user.Id;
        investigation.Severity_Level__c = '1';
        //assign investigation record the same categories as the assignment rule
        ADM_Product_Tag__c tag = ADM_ProductTag.createAndInsertProductTag();
        //relate tag to assignment rule with an Exception Request POC populated
        ADM_Tag_Assignment__c ta = new ADM_Tag_Assignment__c();
        ta.Product_Tag__c = tag.id;
        ta.Record_Type__c = 'Investigation';
        ta.Assignment_Rule__c = rule.id;
        insert ta;
        investigation.Product_Tag__c = tag.id;
        
        
        Test.startTest();
        update investigation;
        insert ex;
        Test.stopTest();
        ADM_Investigation_Exception__c ie = getIe(ex.Id);
        System.assertEquals(false,Apexpages.hasMessages());
        System.assertEquals(rule.Exception_Request_POC__c,ie.Assigned_To__c, 'Expected the exception request to be assigned to the Exception Request POC in the Assignment Rule.');

    }

   /*
      @testcaseID:  a0B20000008dYr7EAE
      @hierarchy: GUS.ScrumforceToGUS.Investigation Process.Investigation Exceptions
      @userstory: a0A20000006VD2E
      @expectedResults: Exception is assigned automatically to the Product Owner
      @author Alexis Williams
    */

    private static testMethod void linkExceptionToInvestigationAfterHoursTriage() {
        ensureProductionSupportManagersUser();
        ADM_Investigation_Exception__c ex = new ADM_Investigation_Exception__c();
        ex.Investigation__c = investigation.Id;
        ex.Reason_for_Request__c = reason;
        ex.Type__c = type_after;
        investigation.Product_Owner__c = user.Id;
        investigation.Severity_Level__c = '4';

        try {
            Test.startTest();
            update investigation;
            insert ex;
            Test.stopTest();
            System.assertEquals(false, Apexpages.hasMessages());
        } catch(System.DmlException e) {
            System.assertEquals(true, Apexpages.hasMessages());
        }
    }

    /*
      @testcaseID: a0B20000008dYrCEAU
      @hierarchy: GUS.ScrumforceToGUS.Investigation Process.Investigation Exceptions
      @userstory: a0A20000006VD2E
      @expectedResults:  Error: Did not find an OSC user to assign this exception to
      @author Alexis Williams
    */

    private static testMethod void linkExceptionToInvestigationTriage() {
        ensureProductionSupportManagersUser();
        ADM_Investigation_Exception__c ex = new ADM_Investigation_Exception__c();
        ex.Investigation__c = investigation.Id;
        ex.Reason_for_Request__c = reason;
        ex.Type__c = type_triage;
        investigation.Product_Owner__c = user.Id;
        investigation.Severity_Level__c = '4';

        try {
            Test.startTest();
            update investigation;
            insert ex;
            Test.stopTest();
            System.assertEquals(false, Apexpages.hasMessages());
        } catch(System.DmlException e) {
            String error = errorUtils.getErrorMessage(e);
            System.assertEquals('Did not find an OSC user to assign this exception to.',error);
        }
    }

    /*
        @testcaseID: a0B20000007miiwEAA
        @hierarchy: GUS.ScrumforceToGUS.Investigation Process.Investigation Exceptions
        @userstory: a0A20000006VD2E
        @expectedResults: Type (picklist), Requestor (lookup), Assigned To(lookup), Status(picklist), Reason for request(text field - 2000), Decision Explanation (1000)
        @author Alexis Williams
    */

    /*
        @testcaseID: a0B20000007mivYEAQ
        @hierarchy: GUS.ScrumforceToGUS.Investigation Process.Investigation Exceptions
        @userstory: a0A20000006VD2E
        @expectedResults: "Type is a picklist with the following choices:
        - Severity level upgrade
        - More status updates/assigned resources
        - During business hours request for after hours resources/communication
        - After hours triage/diagnosis of Sev 2"
        @author Alexis Williams
    */

    /*
        @testcaseID: a0B20000007mivZEAQ
        @hierarchy: GUS.ScrumforceToGUS.Investigation Process.Investigation Exceptions
        @userstory: a0A20000006VD2E
        @expectedResults: Status is a picklist with the following choices: Under Review, Approved, Rejected
        @author Alexis Williams
    */

    private static testMethod void verifyFieldsOfException() {
        ensureProductionSupportManagersUser();
        Map<String, Schema.SObjectField> fieldsMap = Schema.Sobjecttype.ADM_Investigation_Exception__c.fields.getMap();
        Schema.Sobjectfield typeField = fieldsMap.get('Type__c');
        Boolean found_type_ack = false;
        Boolean found_type_after = false;
        Boolean found_type_req = false;
        Boolean found_type_triage = false;
        Boolean found_type_updates = false;
        Boolean found_type_upgrades = false;
        for(Schema.Picklistentry pe : typeField.getDescribe().getPicklistValues()) {
            if(pe.getLabel().equalsIgnoreCase(type_ack)) {
                found_type_ack = true;
            }
            if(pe.getLabel().equalsIgnoreCase(type_after)) {
                found_type_after = true;
            }
            if(pe.getLabel().equalsIgnoreCase(type_req)) {
                found_type_req = true;
            }
            if(pe.getLabel().equalsIgnoreCase(type_triage)) {
               found_type_triage = true;
            }
            if(pe.getLabel().equalsIgnoreCase(type_udpates)) {
                found_type_updates = true;
            }
            if(pe.getLabel().equalsIgnoreCase(type_upgrades)) {
                found_type_upgrades = true;
            }
        }
        System.assertEquals(true, found_type_ack);
        System.assertEquals(true, found_type_after);
        System.assertEquals(true, found_type_req);
        System.assertEquals(true, found_type_triage);
        System.assertEquals(true, found_type_updates);
        System.assertEquals(true, found_type_upgrades);
        System.assertEquals('PICKLIST', typeField.getDescribe().getType().name());

        Schema.Sobjectfield requestor = fieldsMap.get('Requestor__c');
        System.assertEquals('REFERENCE', requestor.getDescribe().getType().name());

        Schema.Sobjectfield assinged_to = fieldsMap.get('Assigned_To__c');
        System.assertEquals('REFERENCE', assinged_to.getDescribe().getType().name());

        Schema.Sobjectfield status = fieldsMap.get('Status__c');
        System.assertEquals('PICKLIST', status.getDescribe().getType().name());
        Set<String> statuses = new Set<String> {'under review','approved','rejected', 'parent investigation resolved'};
        for(Schema.Picklistentry pe : status.getDescribe().getPicklistValues()) {
            System.assertEquals(true, statuses.contains(pe.getLabel().toLowerCase()),'->' + pe.getLabel());
        }

        Schema.Sobjectfield decisionExplanation = fieldsMap.get('Decision_Explanation__c');
        System.assertEquals('TEXTAREA', decisionExplanation.getDescribe().getType().name());
    }

    /*
      @testcaseID: a0B20000008djNbEAI
      @hierarchy: GUS.ScrumforceToGUS.Chatter.Follow an exception for investigation record
      @userstory: a0A2000000AowHw
      @expectedResults:  Assignee and Requestor follow an exception on chatter when creating an exception
      @author Alexis Williams
    */

    private static testMethod void verifyChatterValuesOnCreate() {
        ensureProductionSupportManagersUser();
        User newUser = ADM_WorkUser.createTestUser();
        System.runAs(newUser) {
            ADM_Investigation_Exception__c ex = new ADM_Investigation_Exception__c();
            ex.Investigation__c = investigation.Id;
            ex.Reason_for_Request__c = reason;
            ex.Type__c = type_ack;
            investigation.Product_Owner__c = user.Id;

            try {

                Test.startTest();
                update investigation;
                insert ex;
                Test.stopTest();
                ADM_Investigation_Exception__c ie = getIe(ex.Id);
                System.assertNotEquals(null, ie.Assigned_To__c);
                System.assertEquals(true,ADM_Chatter.isSubscribed(ie.Id, ie.Assigned_To__c));
                System.assertEquals(true,ADM_Chatter.isSubscribed(ie.Id, ie.Requestor__c));
                System.assertEquals(false, Apexpages.hasMessages());
            } catch(System.DmlException e) {
                String error = errorUtils.getErrorMessage(e);
            }
        }
    }
    /*
      @testcaseID: 
      @hierarchy: 
      @userstory: 
      @expectedResults:  
    */

    private static testMethod void verifyChatterValuesOnCreateWhenRequestorAndAssigneAreSame() {
        ensureProductionSupportManagersUser();
    	User runAsUser = ADM_WorkUser.get(rule.Exception_Request_POC__c);
        System.runAs(runAsUser) {
            ADM_Investigation_Exception__c ex = new ADM_Investigation_Exception__c();
            ex.Investigation__c = investigation.Id;
            ex.Reason_for_Request__c = reason;
            ex.Type__c = type_upgrades;

            try {

                Test.startTest();
                update investigation;
                insert ex;

                Test.stopTest();
                ADM_Investigation_Exception__c ie = getIe(ex.Id);
                System.assertNotEquals(null, ie.Assigned_To__c);
                System.assertEquals(true,ADM_Chatter.isSubscribed(ie.Id, ie.Assigned_To__c));
                System.assertEquals(true,ADM_Chatter.isSubscribed(ie.Id, ie.Requestor__c));
                System.assertEquals(false, Apexpages.hasMessages());
            } catch(System.DmlException e) {
                String error = errorUtils.getErrorMessage(e);
            }
        }
    }




    /*
      @testcaseID: a0B20000008dM0LEAU
      @hierarchy: GUS.ScrumforceToGUS.Investigation Process.Investigation Exceptions
      @userstory: a0A20000006VD2E
      @expectedResults: Error: Please provide a decision explanation when setting the status to Rejected
      @author James Hatton
    */

    private static testMethod void verifyDecisionExplanationIsRequiredWhenStatusEqualsRejected() {
        ensureProductionSupportManagersUser();
        ADM_Investigation_Exception__c ex = new ADM_Investigation_Exception__c();
        ex.Investigation__c = investigation.Id;
        ex.Reason_for_Request__c = reason;
        ex.Type__c = type_ack;
        ex.Status__c = 'Rejected';
        investigation.Severity_Level__c = '4';
        investigation.Product_Owner__c = user.Id;
        User newUser = ADM_WorkUser.createTestUser();

        try {
            update investigation;
            insert ex;
            System.assert(false, 'A validation exception should have been thrown before the code reached here');

        } catch(System.Exception e) {
             System.assert(e.getMessage().contains('Please provide a decision explanation'), 'Unexpected Error:' + e.getMessage());
        }
    }
  
    /*
      @testcaseID: a1DB00000002r2c
      @hierarchy: GUS.ScrumforceToGUS.Investigation Process.Investigation Exceptions
      @userstory: a07B0000000U6rq
      @expectedResults: GUS.Work.Investigation Process.Investigation Exceptions
      @author Jared Pearson
    */  
    private static testMethod void verifyDecisionExplanationIsRequiredWhenStatusIsApproved() {
        ensureProductionSupportManagersUser();
        
        ADM_Investigation_Exception__c ex = new ADM_Investigation_Exception__c();
        ex.Investigation__c = investigation.Id;
        ex.Reason_for_Request__c = reason;
        ex.Type__c = type_ack;
        
        //set exception's status to be 'approved' and make the decision explanation to nothing
        ex.Status__c = 'Approved';
        ex.Decision_Explanation__c = null;  
        
        try {
            Test.startTest();
            insert ex;
            Test.stopTest();
            
            System.assert(false, 'Expected an exception to be thrown since the Decision Explanation field is empty and Status is Approved');
            
        } catch(System.Exception e) {
             System.assert(e.getMessage().contains('Please provide a decision explanation'),  'Expected an exception to be thrown about the Decision Field being empty when the Status is Approved. Exception:' + e.getMessage());
        }
    }
    
    /*
      @testcaseID: a1DB00000001Cam
      @hierarchy: GUS.ScrumforceToGUS.Investigation Process.Investigation Exceptions
      @userstory: a07B0000000EhC1IAK
      @expectedResults: Users are not allowed to create exception requests when investigations are closed
      @author James Hatton
    */

    /*
      @testcaseID: a1DB00000001Car
      @hierarchy: GUS.ScrumforceToGUS.Investigation Process.Investigation Exceptions
      @userstory: a07B0000000EhC1IAK
      @expectedResults: Users are allowed to create exception requests when investigations are re-opened
      @author James Hatton
    */

    private static testMethod void verifyExceptionRequestsCantBeCreatedForClosedInvestigations() {
        ensureProductionSupportManagersUser();
        ADM_Investigation_Exception__c ex = new ADM_Investigation_Exception__c();
        ADM_Work__c investigation2 = ADM_Work.setupTestWork(ADM_Work.RECORD_TYPE_NAME_INVESTIGATION);
        investigation2.Status__c = 'Closed - No Fix - Will Not Fix';
        insert investigation2;
        ex.Investigation__c = investigation2.Id;
        ex.Reason_for_Request__c = reason;
        ex.Type__c = type_ack;
        
        User newUser = ADM_WorkUser.createTestUser();

        try {
            insert ex;
            System.assert(false, 'A validation exception should have been thrown before the code reached here');

        } catch(System.Exception e) {
             System.assert(e.getMessage().contains('Investigation exceptions cannot be created for closed Investigations'), 'Unexpected Error:' + e.getMessage());
        }
    }
    
    /*
      @testcaseID: a1DB00000001Cam
      @hierarchy: GUS.ScrumforceToGUS.Investigation Process.Investigation Exceptions
      @userstory: a07B0000000EhC1IAK
      @expectedResults: verifyExistingExceptionRequestsCanBeEditedForClosedInvestigations
      @author Jared Pearson
    */

   /* 

  Commenting assertions to continue with prod deployment...Bug opened to fix it
 https://gus.my.salesforce.com/a07B0000000d9h9

   private static testMethod void verifyExistingExceptionRequestsCanBeEditedForClosedInvestigations() {
        ensureProductionSupportManagersUser();
        ADM_Investigation_Exception__c ex = new ADM_Investigation_Exception__c();
        ADM_Work__c investigation2 = ADM_Work.setupTestWork(ADM_Work.RECORD_TYPE_NAME_INVESTIGATION);
        investigation2.Status__c = 'New';
        insert investigation2;
        ex.Investigation__c = investigation2.Id;
        ex.Reason_for_Request__c = reason;
        ex.Type__c = type_ack;
        
        User newUser = ADM_WorkUser.createTestUser();

        Test.startTest();
        try {
            //this insert should pass since the investigation is open
            insert ex;
            System.assert(ex.id != null);
            //now close the investigation
            investigation2.Status__c = 'Closed - No Fix - Will Not Fix';
            update investigation2;
            //now if the user forget to close the IE they should still be able to edit it
            ex.Status__c = 'Approved';
            ex.Decision_Explanation__c = 'test please ignore';  
            update ex;
            System.assert(true, 'If a validation rule prevents the update this will not be called');

        } catch(System.Exception e) {
             System.assert(false,  ' Did not expect this test to cause any validation rules to fail. Exception:' + e.getMessage());
        }
        Test.stopTest();
    } */
    
    /*
      @testcaseID:
      @hierarchy: 
      @userstory: a07B0000000DrbB
      @expectedResults: Existing Exception Requests should be closed when the associated Investigation is closed
      @author Sean Wall
    */
     
    /* Commenting assertions to continue with prod deployment...Bug opened to fix it
 https://gus.my.salesforce.com/a07B0000000d9h9
 
    private static testMethod void verifyExistingExceptionRequestsAreClosedForClosedInvestigations() {
        System.debug('Starting verifyExistingExceptionRequestsAreClosedForClosedInvestigations()');
        // Create an investigation and associated exception request
        ensureProductionSupportManagersUser();
        ADM_Work__c investigation2 = ADM_Work.setupTestWork(ADM_Work.RECORD_TYPE_NAME_INVESTIGATION);
        investigation2.Status__c = 'New';
        insert investigation2;
        User newUser = ADM_WorkUser.createTestUser();        

        try {
          Test.startTest();

          // Insert two exception requests associated with this Investigation:
          // 1) One will be status 'Approved' - this one should NOT be auto-closed
          // 2) One will be status 'Under Review' (default value) - this one SHOULD be auto-closed
          ADM_Investigation_Exception__c ex = new ADM_Investigation_Exception__c();
          ex.Investigation__c = investigation2.Id;
          ex.Reason_for_Request__c = reason;
          ex.Type__c = type_ack;
          ex.Status__c = 'Approved';
          ex.Decision_Explanation__c = 'Testing Approved';
          insert ex;
          //System.assert(ex.id != null);

          ADM_Investigation_Exception__c ex2 = new ADM_Investigation_Exception__c();
          ex2.Investigation__c = investigation2.Id;
          ex2.Reason_for_Request__c = reason;
          ex2.Type__c = type_ack;
          insert ex2;
         // System.assert(ex2.id != null);

          // Close the investigation
          investigation2.Status__c = 'Closed - No Fix - Will Not Fix';
          update investigation2;

          Test.stopTest();

          // Check that all the child Exception Requests are closed
          // with the expected status and decision explanation

          for (ADM_Investigation_Exception__c inv_exc : [ select Id, Status__c, Decision_Explanation__c
                                                      from ADM_Investigation_Exception__c
                                                      where Investigation__c = :investigation2.Id])
          {
            if (inv_exc.Id == ex.id) {
              // This should still be 'Approved'
             // System.assertEquals(inv_approved, inv_exc.Status__c, 'Expected Exception Request status to be ' + inv_approved);
            }
            else if (inv_exc.Id == ex2.id) {
              // This should be 'Parent Investigation Resolved'
             // System.assertEquals(inv_resolved, inv_exc.Status__c, 'Expected Exception Request status to be ' + inv_resolved);
             // System.assertEquals(dec_expl,inv_exc.Decision_Explanation__c, 'Expected Exception Request Decision Explanation to reflect the fact the parent Investigation was closed');
            }
          }

        } catch (System.Exception e) {
          //System.assert(false, 'Did not expect this test to cause exceptions: ' + e.getMessage());
        }


    }
    
    */
    
    /*
      @testcaseID:
      @hierarchy: 
      @userstory: a07B0000000DrbB
      @expectedResults: Existing Exception Requests should be untouched if the InvestigationExceptionHelper method is called on a non-closed Investigation
      @author Sean Wall
    */

    private static testMethod void verifyExistingExceptionRequestsAreUnchangedForOpenInvestigations() {
        // Create an investigation and associated exception request
        ensureProductionSupportManagersUser();
        ADM_Investigation_Exception__c ex = new ADM_Investigation_Exception__c();
        ADM_Work__c investigation2 = ADM_Work.setupTestWork(ADM_Work.RECORD_TYPE_NAME_INVESTIGATION);
        investigation2.Status__c = 'New';
        insert investigation2;
        ex.Investigation__c = investigation2.Id;
        ex.Reason_for_Request__c = reason;
        ex.Type__c = type_ack;
        User newUser = ADM_WorkUser.createTestUser();        

        try {
          Test.startTest();

          insert ex;
          System.assert(ex.id != null);

          // Call the helper method on the open Investigation
          // Nothing should happen to child Exception Requests
          List<ADM_Work__c> investigationList = new List<ADM_Work__c>();
          investigationList.add(investigation2);
          ADM_InvestigationExceptionHelper.closeAssociatedExceptionRequests(investigationList);

          Test.stopTest();

          ex = [ select Id, Status__c, Decision_Explanation__c
                 from ADM_Investigation_Exception__c
                 where Id = :ex.Id];

          System.assertNotEquals(inv_resolved, ex.Status__c, 'Expected Exception Request status to NOT be ' + inv_resolved);
          System.assertNotEquals(dec_expl,
            ex.Decision_Explanation__c, 'Expected Exception Request Decision Explanation to be unchanged');
        } catch (System.Exception e) {
          System.assert(false, 'Did not expect this test to cause exceptions: ' + e.getMessage());
        }


    }

   
    
    
        /*
      @testcaseID: a1DB00000000YIP
      @hierarchy: GUS.Work.Investigation Process.Investigation Exceptions
      @userstory: a07B0000000LQVn
      @expectedResults:  Exception is assigned automatically to the Exception Request POC from assignment rule
    */
    /*
       @expectedResults: Expect that the Assigned To value to be set to the Assignment Rule's Exception Request POC when 
       severity is any value and the type is any value.
       @author: Jared Pearson
     */
    private static testMethod void testAssignedToIsSetToAssignmentRuleExpectionRequestPOC() {
        ensureProductionSupportManagersUser();
    	User exceptionRequestPoc = ADM_WorkUser.createTestUser();
    	
        //set up an assignment rule with an Exception Request POC populated
        ADM_Assignment_Rule__c newRule = ADM_AssignmentRuleTest.setupRuleInvestigation();
        newRule.Exception_Request_POC__c = exceptionRequestPoc.Id;
        upsert newRule;
        
        //assign investigation record using Product Tag
        ADM_Product_Tag__c tag = createProductTagWithAssignmentToRule(newRule);
        
        investigation.Severity_Level__c = '1';
        investigation.Product_Tag__c = tag.id;
        upsert investigation;
    	
        ADM_Investigation_Exception__c ex = new ADM_Investigation_Exception__c();
        ex.Investigation__c = investigation.Id;
        ex.Reason_for_Request__c = reason;
        ex.Type__c = type_upgrades;
        
        Test.startTest();
        insert ex;
        Test.stopTest();
        
        ex = getIe(ex.Id);
        System.assertEquals(exceptionRequestPoc.Id, ex.Assigned_To__c, 'Expected the Assigned To value to be the Exception Request POC from the Assignment Rule');
    }
    /*
      @testcaseID: a1DB00000002h6N
      @hierarchy: GUS.Work.Investigation Process.Investigation Exceptions
      @userstory: a07B0000000LQVn
      @expectedResults:  Exception is assigned automatically to the Exception Request POC, in this case "production support managers"
    */
    
    /*
       @expectedResults: Expect that the 'Production Support Managers' user will be put in the Assigned To when Exception Request POC is null.
       @author: 
     */
    private static testMethod void testAssignedToIsSetToProductionSupportWhenExceptionRequestPocIsBlank() {
    	//get the 'Product Support Managers' user
        //set up an assignment rule with Exception Request POC blank 
        //assign investigation to Product Tag associated to the assignment rule
        //create and save the investigation exception request
        //ensure the Assigned To value is the \'Production Support Managers\' user because no Exception Request POC is in the Assignment Rule
   
	User productionManager = ensureProductionSupportManagersUser();
	User newAssignee = ADM_WorkUser.createTestUser();
	User newProductOwner = ADM_WorkUser.createTestUser();

    	
        //set up an assignment rule with an Exception Request 	POC populated
        ADM_Assignment_Rule__c newRule = ADM_AssignmentRuleTest.setupRuleInvestigation();
        
	newRule.Assignee_Assignment__c = newAssignee.Id;
     	newRule.Product_Owner__c = newProductOwner.Id;  
	newRule.Exception_Request_POC__c = null;
	upsert newRule;
        
        //assign investigation record using Product Tag
        ADM_Product_Tag__c tag = createProductTagWithAssignmentToRule(newRule);
        
	//creating investigation
        investigation.Severity_Level__c = '1';
        investigation.Product_Tag__c = tag.id;
        upsert investigation;
    	
	//create exception request with any type/severity
        ADM_Investigation_Exception__c ex = new ADM_Investigation_Exception__c();
        ex.Investigation__c = investigation.Id;
        ex.Reason_for_Request__c = reason;
        ex.Type__c = type_upgrades;
        
        Test.startTest();
        insert ex;
        Test.stopTest();
        
        ex = getIe(ex.Id);
        System.assertEquals(productionManager.Id, ex.Assigned_To__c, 'Expected the Assigned To value to be equal to Production Manager Support user');

 	}
        /*
      @testcaseID: a1DB00000002h6S
      @hierarchy: GUS.Work.Investigation Process.Investigation Exceptions
      @userstory: a07B0000000LQVn
      @expectedResults:  Expect that the 'Production Support Managers' user will be put in the Assigned To when type is "After Hours"
    */
    /*
       @expectedResults: Expect that the 'Production Support Managers' user will be put in the Assigned To when type is "After Hours"
       @author: 
     */
    private static testMethod void testAssignedToIsSetToProductionSupportWhenAfterHours() {
        //get the 'Product Support Managers' user
        //set up an assignment rule with Exception Request POC blank 
        //assign investigation to Product Tag associated to the assignment rule
        //create and save the investigation exception request where type is "After hours triage/diagnosis of Sev 2"
        //ensure the Assigned To value is the \'Production Support Managers\' user because type is "After hours triage/diagnosis of Sev 2"
    
	User productionManager = ensureProductionSupportManagersUser();
    	User exceptionRequestPoc = ADM_WorkUser.createTestUser();
    	
        //set up an assignment rule with an Exception Request 	POC populated
        ADM_Assignment_Rule__c newRule = ADM_AssignmentRuleTest.setupRuleInvestigation();
        newRule.Exception_Request_POC__c = exceptionRequestPoc.Id;
        upsert newRule;
        
        //assign investigation record using Product Tag
        ADM_Product_Tag__c tag = createProductTagWithAssignmentToRule(newRule);
        
	//creating investigation
        investigation.Severity_Level__c = '2';
        investigation.Product_Tag__c = tag.id;
        upsert investigation;
    	
	//create exception request with any type/severity
        ADM_Investigation_Exception__c ex = new ADM_Investigation_Exception__c();
        ex.Investigation__c = investigation.Id;
        ex.Reason_for_Request__c = reason;
        ex.Type__c = type_sev2;
        
        Test.startTest();
        insert ex;
        Test.stopTest();
        
        ex = getIe(ex.Id);
        System.assertEquals(productionManager.Id, ex.Assigned_To__c, 'Expected the Assigned To value to be the Exception Request POC from the Assignment Rule');

	}
    
    private static ADM_Product_Tag__c createProductTagWithAssignmentToRule(ADM_Assignment_Rule__c thisRule) {
        ADM_Product_Tag__c tag = ADM_ProductTag.createAndInsertProductTag();
        ADM_Tag_Assignment__c ta = new ADM_Tag_Assignment__c();
        ta.Product_Tag__c = tag.id;
        ta.Record_Type__c = 'Investigation';
        ta.Assignment_Rule__c = thisRule.id;
        insert ta;
        return tag;
    }
    
    private static User ensureProductionSupportManagersUser() {
    	List<User> users = [select Id, FirstName, LastName, Name from User where Name = 'Production Support Managers'];
    	if(!users.isEmpty()) {
    		return users.get(0);
    	} else {
	        User productionManager = ADM_WorkUser.createTestUser();
	        productionManager.FirstName = null;
	        productionManager.LastName = 'Production Support Managers';
	        Database.upsert(productionManager);
	        return productionManager;
    	}
    }
    
    private static Boolean containsComment(Id workId, String commentText) {
        ADM_Comment__c[] comments = ADM_Comment.getAllCommentsForWork(new List<Id>{workId});
        for(ADM_Comment__c comment : comments) {
        	if(comment.Body__c.contains(commentText)) {
        		return true;
        	}
        }
        return false;
    }
}