mdapi-source/original-package/unpackaged/objects/ADM_Scrum_Team__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Team_Email_Group_ID__c</fullName>
        <label>Team Email Group ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Program</fullName>
                    <default>true</default>
                    <label>Program</label>
                </value>
                <value>
                    <fullName>Program of Programs</fullName>
                </value>
                <value>
                    <fullName>Portfolio</fullName>
                </value>
                <value>
                    <fullName>Workrgoup</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Scrum_Team_Cache__c.object
<CustomObject>
    <description>Used for action chaining since you can no longer create a setup object when conducting any type of DML with a custom object. Specifically we will later look at all of the scrum team cache objects that we&apos;ve inserted to create Groups</description>
    <fields>
        <fullName>Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates a corresponding scrum team record was deleted causing this record to be created</description>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Group_ID__c</fullName>
        <description>Used to delete group memberships</description>
        <label>Group ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inserted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates a corresponding scrum team record was inserted causing this record to be created</description>
        <label>Inserted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ScrumteamOrScrumteamMember__c</fullName>
        <description>Using text field instead because we will be creating objects after scrum teams have been deleted to clean up the setup object called Group which would cause an error if this was a lookup field!</description>
        <label>Scrumteam Or Scrumteam Member</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <defaultValue>&quot;Regular&quot;</defaultValue>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Scrum Team Cache</label>
    <nameField>
        <displayFormat>STC-{00000}</displayFormat>
        <label>Scrum Team Cache Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scrum Team Caches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Scrum_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Allocation__c</fullName>
        <label>Allocation (%)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Group_ID__c</fullName>
        <formula>Scrum_Team__r.Team_Email_Group_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Scrum_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Record_Type_Copy__c</fullName>
        <defaultValue>$RecordType.Name</defaultValue>
        <label>Record Type Copy</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Analyst</fullName>
                </value>
                <value>
                    <fullName>Architect</fullName>
                </value>
                <value>
                    <fullName>BSA</fullName>
                </value>
                <value>
                    <fullName>Business Owner</fullName>
                </value>
                <value>
                    <fullName>Capacity Planner</fullName>
                </value>
                <value>
                    <fullName>Data Center Engineer</fullName>
                </value>
                <value>
                    <fullName>DBA</fullName>
                </value>
                <value>
                    <fullName>Developer</fullName>
                </value>
                <value>
                    <fullName>Dev Manager</fullName>
                </value>
                <value>
                    <fullName>Doc Editor</fullName>
                </value>
                <value>
                    <fullName>Doc Manager</fullName>
                </value>
                <value>
                    <fullName>Engineering Manager</fullName>
                </value>
                <value>
                    <fullName>Network Engineer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Performance Engineer</fullName>
                </value>
                <value>
                    <fullName>Product Owner</fullName>
                </value>
                <value>
                    <fullName>Program Manager</fullName>
                </value>
                <value>
                    <fullName>Provisioning Specialist / Asset Manager</fullName>
                </value>
                <value>
                    <fullName>QA Engineer</fullName>
                </value>
                <value>
                    <fullName>QA Manager</fullName>
                </value>
                <value>
                    <fullName>Release Engineer</fullName>
                </value>
                <value>
                    <fullName>Release Manager</fullName>
                </value>
                <value>
                    <fullName>Scrum Master</fullName>
                </value>
                <value>
                    <fullName>Security Engineer</fullName>
                </value>
                <value>
                    <fullName>Site Reliability Engineer</fullName>
                </value>
                <value>
                    <fullName>Software Engineer</fullName>
                </value>
                <value>
                    <fullName>SysAdmin</fullName>
                </value>
                <value>
                    <fullName>SysAdmin Linux</fullName>
                </value>
                <value>
                    <fullName>SysAdmin Storage</fullName>
                </value>
                <value>
                    <fullName>SysAdmin Win</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>Scrum_Team_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <displayFormat>STM-{00000}</displayFormat>
        <label>Team Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <recordTypes>
        <fullName>Internal</fullName>
        <active>true</active>
        <description>SFDC Employee</description>
        <label>Internal</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/classes/ADM_ScrumTeamMemberUtils.cls
public with sharing class ADM_ScrumTeamMemberUtils {
    private List<String> getSuccesses(List<ADM_Scrum_Team_Cache__c> caches) {       
        List<String> cacheIds = new List<String>(); 
        Database.Saveresult[] results = Database.insert(caches,false);
        
        for(Database.Saveresult result : results) {
            if(result.isSuccess()) {
                cacheIds.add(result.getId()); 
            } else {
                System.debug('an error occurred: ' + result.getErrors());               
            }
        }
        
        return cacheIds;
    }
    
    public void createScrumteamCaches(ADM_Scrum_Team_Member__c[] members, Boolean isInsert, Boolean isDelete) {
        List<ADM_Scrum_Team_Cache__c> caches = ADM_ScrumteamCacheUtils.getTeamMemberCaches(members, isInsert, isDelete);
        List<String> cacheIds = new List<String>(); 
        
        Database.Saveresult[] results = Database.insert(caches,false);
        
        for(Database.Saveresult result : results) {
            if(result.isSuccess()) {
                cacheIds.add(result.getId()); 
            } else {
                System.debug('an error occurred: ' + result.getErrors());               
            }
        }
        
        //don't create public group membership for Agile Accelerator package
        if(!ADM_ConstantsSingleton.getInstance().isPackagedOrg() || Test.isRunningTest()) {
            if(!cacheIds.isEmpty()) {
                if(isInsert) {
                    asynchronouslyCreateGroupMembers(cacheIds);
                } else if(isDelete) {
                    asynchronouslyDeleteGroupMembers(cacheIds);
                }
            }
        }    
    }
    
    public void createScrumteamCaches(ADM_Scrum_Team_Member__c[] members2add, ADM_Scrum_Team_Member__c[] members2remove) {
        List<ADM_Scrum_Team_Cache__c> caches = new List<ADM_Scrum_Team_Cache__c>();
        caches.addAll(ADM_ScrumteamCacheUtils.getTeamMemberCaches(members2add, true, false));
        caches.addAll(ADM_ScrumteamCacheUtils.getTeamMemberCaches(members2remove, false, true));
        List<String> cacheIds = new List<String>(); 
        
        Database.Saveresult[] results = Database.insert(caches,false);
        
        for(Database.Saveresult result : results) {
            if(result.isSuccess()) {
                cacheIds.add(result.getId()); 
            } else {
                System.debug('an error occurred: ' + result.getErrors());               
            }
        }
        
        if(!cacheIds.isEmpty()) {
            asynchronouslyHandleGroupMembers(cacheIds);
        }
    }  
    
    @Future
    private static void asynchronouslyHandleGroupMembers(List<String> cacheIds) {
        List<GroupMember> groupMembers = new List<GroupMember>();
        
        Map<Id,ADM_Scrum_Team_Cache__c> caches = new Map<Id,ADM_Scrum_Team_Cache__c>([select Group_ID__c, Name__c, Deleted__c, Inserted__c, Type__c, ScrumteamOrScrumteamMember__c from ADM_Scrum_Team_Cache__c where Id in : cacheIds]);
        
        List<String> memberIdsFromCaches = ADM_ScrumteamCacheUtils.idsFromScrumTeamField(caches.values());
        
        Map<Id,ADM_Scrum_Team_Member__c> members = new Map<Id,ADM_Scrum_Team_Member__c>([select Id, Name, Scrum_Team__c from ADM_Scrum_Team_Member__c where Id in : memberIdsFromCaches]);
        
        List<String> scrumteamIds = scrumteamIdsFromScrumteamMembers(members.values());
        
        Map<Id,ADM_Scrum_Team__c> scrumteams = new Map<Id,ADM_Scrum_Team__c>([select Id, Name, Team_Email_Group_ID__c from ADM_Scrum_Team__c where Id in : scrumteamIds]);
        
        List<ADM_Scrum_Team_Cache__c> caches2Delete = new List<ADM_Scrum_Team_Cache__c>();
        List<ADM_Scrum_Team_Cache__c> caches2Add = new List<ADM_Scrum_Team_Cache__c>();
        
        if(!caches.isEmpty()) {
            for(ADM_Scrum_Team_Cache__c cache : caches.values()) {
                    if(cache.Deleted__c) {
                        caches2Delete.add(cache);
                    } else if(cache.Inserted__c) {
                        caches2Add.add(cache);
                    }
            }
            //#1). Take care of the deletes first            
            for(ADM_Scrum_Team_Cache__c cache2Delete : caches2Delete) {
                for(GroupMember[] m_members : [Select g.Id From GroupMember g where g.GroupId =: cache2Delete.Group_ID__c and UserOrGroupId =: cache2Delete.Name__c]) {
                    groupMembers.addAll(m_members);                 
                }
            }
            
            if(!groupMembers.isEmpty()) {
                Database.Deleteresult[] results = Database.delete(groupMembers,false);
                
                for(Database.Deleteresult result : results) {
                    if(!result.isSuccess()) {
                        System.debug('Error occurred deleting group: ' + result.getErrors());
                    }
                }   
            }
            
            groupMembers = new List<GroupMember>();
            
            //#2). Take care of the adds now
            for(ADM_Scrum_Team_Cache__c cacheAdd : caches2Add) {
                try {
                    ADM_Scrum_Team_Member__c member = members.get(cacheAdd.ScrumteamOrScrumteamMember__c);
                    ADM_Scrum_Team__c team = scrumteams.get(member.Scrum_Team__c);          
                    groupMembers.add(new GroupMember(GroupId = team.Team_Email_Group_ID__c, UserOrGroupId = cacheAdd.Name__c));
                } catch(System.Exception e) {
                   System.debug('An error occurred getting the members and or teams!' + e); 
                }   
            }
            
            if(!groupMembers.isEmpty()) {
                Database.Saveresult[] results = Database.insert(groupMembers,false);
                
                for(Database.Saveresult result : results) {
                    if(!result.isSuccess()) {
                        System.debug('Error occurred inserted a group: ' + result.getErrors());
                    }
                }   
            }            
        }
    }
    
    @Future
    private static void asynchronouslyDeleteGroupMembers(List<String> cacheIds) {
        List<GroupMember> groupMembers = new List<GroupMember>();
        
        for(ADM_Scrum_Team_Cache__c cache : [select Group_ID__c, Name__c, Type__c, ScrumteamOrScrumteamMember__c from ADM_Scrum_Team_Cache__c where Id in : cacheIds]) {
            for(GroupMember[] members : [Select g.Id From GroupMember g where g.GroupId =: cache.Group_ID__c and UserOrGroupId =: cache.Name__c]) {
                Database.Deleteresult[] results = Database.delete(members,false);
                
                for(Database.Deleteresult result : results) {
                    if(!result.isSuccess()) {
                        System.debug('Error occurred deleting group: ' + result.getErrors());
                    }
                }
            }
        }
    }  
    
    public static List<String> scrumteamIdsFromScrumteamMembers(List<ADM_Scrum_Team_Member__c> members) {
        List<String> ids = new List<String>();
        if(!members.isEmpty()) {
            for(ADM_Scrum_Team_Member__c member : members) {
                ids.add(member.Scrum_Team__c);
            }
        }
        
        return ids;
    } 
    
    public List<String> getScrumTeamIds() {
        List<ADM_Scrum_Team_Member__c> membership = [select id, Scrum_Team__c, Member_Name__c from ADM_Scrum_Team_Member__c where Member_Name__c =:UserInfo.getUserId() and Scrum_Team__c != null and Scrum_Team__r.Active__c = true order by Allocation__c DESC];
        List<String> teamIds = new List<String>();
        if(membership != null) {
            for(ADM_Scrum_Team_Member__c member: membership){
              teamIds.add(member.Scrum_Team__c);
            }
        }

        return teamIds;
    }
    
    @Future
    private static void asynchronouslyCreateGroupMembers(List<String> cacheIds) {
        try{
            List<GroupMember> groupMembers = new List<GroupMember>();
            Map<Id,ADM_Scrum_Team_Cache__c> caches = new Map<Id,ADM_Scrum_Team_Cache__c>([select Name__c, Type__c, ScrumteamOrScrumteamMember__c from ADM_Scrum_Team_Cache__c where Id in : cacheIds]);
            List<String> memberIdsFromCaches = ADM_ScrumteamCacheUtils.idsFromScrumTeamField(caches.values());
            Map<Id,ADM_Scrum_Team_Member__c> members = new Map<Id,ADM_Scrum_Team_Member__c>([select Id, Name, Scrum_Team__c from ADM_Scrum_Team_Member__c where Id in : memberIdsFromCaches]);
            List<String> scrumteamIds = scrumteamIdsFromScrumteamMembers(members.values());
            Map<Id,ADM_Scrum_Team__c> scrumteams = new Map<Id,ADM_Scrum_Team__c>([select Id, Name, Team_Email_Group_ID__c from ADM_Scrum_Team__c where Id in : scrumteamIds]);
            
            if(!caches.isEmpty()) {
                for(ADM_Scrum_Team_Cache__c cache : caches.values()) {
                    try {
                        ADM_Scrum_Team_Member__c member = members.get(cache.ScrumteamOrScrumteamMember__c);
                        ADM_Scrum_Team__c team = scrumteams.get(member.Scrum_Team__c);          
                        groupMembers.add(new GroupMember(GroupId = team.Team_Email_Group_ID__c, UserOrGroupId = cache.Name__c));
                    } catch(System.Exception e) {
                       System.debug('An error occurred getting the members and or teams!' + e); 
                    }
                }
                
                Database.Saveresult[] results = Database.insert(groupMembers,false);
                
                for(Database.Saveresult result : results) {
                    if(!result.isSuccess()) {
                        System.debug('Error occurred inserted a group: ' + result.getErrors());
                    }
                }
            }
        }
        catch(Exception exp){
            ADM_ExceptionHandler.saveException(exp, 'Error occurred while inserting group member by Future method');
        }
    }
    
    public static ADM_Scrum_Team_Member__c createScrumteamMember(String ScrumteamId, User user) {
        ADM_Scrum_Team_Member__c member = new ADM_Scrum_Team_Member__c(Member_Name__c = user.Id, Scrum_Team__c = ScrumteamId, Allocation__c = 10);
        insert member;
        return member;
    }
    
    public static Map<Id, ADM_Scrum_Team__c> getScrumTeams(List<String> ids) {
        Map<Id,ADM_Scrum_Team__c> teams = new Map<Id,ADM_Scrum_Team__c>([select Name, (select Member_Name__c, Allocation__c from Scrum_Team_members__r) from ADM_Scrum_Team__c where Id in : ids]);
        return teams;
    }
    
    public static Map<Id, ADM_AllocationWrapper> totalAllocationByMemberId(Set<Id> ids) {
        //max allocation percentage is only enfored for Internal members
        List<ADM_Scrum_Team_Member__c> members = [select id, Member_Name__c, Allocation__c, Scrum_Team__r.Name from ADM_Scrum_Team_Member__c where Record_Type_Copy__c =:'Internal' and Scrum_Team__r.Active__c = true and Member_Name__c in : ids];
        Map<Id, ADM_AllocationWrapper> allocationMap = new Map<Id, ADM_AllocationWrapper>();
        String description = '';
        for(ADM_Scrum_Team_Member__c m : members) {
            if(m != null) {
                if(m.Allocation__c == null) m.Allocation__c = 0.0;
                description += m.Scrum_Team__r.Name + ': ' + m.Allocation__c + '%, '; 
                if(allocationMap.containsKey(m.Member_Name__c)) { 
                    ADM_AllocationWrapper aw = allocationMap.get(m.Member_Name__c);
                    aw.getAllocationBreakDown().put(m.id, m.Allocation__c);
                    aw.allocationDescription = description;
                    aw.allocation += m.Allocation__c;
                    //re-insert
                    allocationMap.put(m.Member_Name__c, aw);
                } else {
                    allocationMap.put(m.Member_Name__c, new ADM_AllocationWrapper(m.Allocation__c, description, m.id));
                }
            }
        }
        return allocationMap;
    }
    
    /**
     * Determine if the specified user Id is a member within the given list of team members.
     */
    public static Boolean containsUser(List<ADM_Scrum_Team_Member__c> teamMembers, Id userId) {
        for(ADM_Scrum_Team_Member__c teamMember : teamMembers) {
            if(teamMember.Member_Name__c == userId) {
                return true;
            }
        }
        return false;
    }
    
    /**
     * Returns a list of all the team members that are in the scrum master role
     */
    public static List<ADM_Scrum_Team_Member__c> getScrumMasters(List<ADM_Scrum_Team_Member__c> teamMembers) {
        List<ADM_Scrum_Team_Member__c> scrumMasters = new List<ADM_Scrum_Team_Member__c>();
        for(ADM_Scrum_Team_Member__c teamMember : teamMembers) {
            if(teamMember.Role__c == 'Scrum Master') {
                scrumMasters.add(teamMember);
            }
        }
        return scrumMasters;
    }
}