mdapi-source/original-package/unpackaged/objects/ADM_Epic__c.object
<CustomObject>
    <label>Epic</label>
    <nameField>
        <label>Epic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Epics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Epic_Burndown_Item__c.object
<CustomObject>
    <fields>
        <fullName>Epic__c</fullName>
        <label>Epic</label>
        <referenceTo>ADM_Epic__c</referenceTo>
        <relationshipLabel>Epic Burndown Items</relationshipLabel>
        <relationshipName>Epic_Burndown_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Metric__c</fullName>
        <label>Metric</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Epic Burndown Item</label>
    <nameField>
        <displayFormat>EBI-{0000000000}</displayFormat>
        <label>Epic Burndown Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Epic Burndown Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Epic__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Epic</label>
        <referenceTo>ADM_Epic__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Triaged</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Investigating</fullName>
                </value>
                <value>
                    <fullName>Ready for Review</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>QA In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Defunct</fullName>
                </value>
                <value>
                    <fullName>Closed - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Closed - Eng Internal</fullName>
                </value>
                <value>
                    <fullName>Closed - Known Bug Exists</fullName>
                </value>
                <value>
                    <fullName>Closed - New Bug Logged</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Approved</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Denied</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved With Internal Tools</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved Without Code Change</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Working as Designed</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Feature Request</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Will Not Fix</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Pending Release</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>More Info Reqd from Support</fullName>
                </value>
                <value>
                    <fullName>Never</fullName>
                </value>
                <value>
                    <fullName>Not a bug</fullName>
                </value>
                <value>
                    <fullName>Not Reproducible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Story_Points__c</fullName>
        <inlineHelpText>If you leave it empty on save it will automatically assign the value from the TE activity selected.</inlineHelpText>
        <label>Story Points</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <recordTypes>
        <fullName>Bug</fullName>
        <active>true</active>
        <description>Used to track defects or problems</description>
        <label>Bug</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PPM_PortfolioScheduledJobTest.cls
@IsTest
public class PPM_PortfolioScheduledJobTest {
    
    static testMethod void testEpicBurndownOpen() {

        ADM_Epic__c epic = ADM_Epic.createTestEpic();

        ADM_Work__c test_story =  ADM_Work.setupTestWork('User Story');
        test_story.Epic__c = epic.Id; 
        upsert test_story;
        
        ADM_Work__c test_bug =  ADM_Work.setupTestWork('Bug');
        test_bug.Epic__c = epic.Id; 
        upsert test_bug;

        Test.startTest();       
        
        PPM_PortfolioScheduledJob job = new PPM_PortfolioScheduledJob();
            job.execute(null);

        Test.stopTest();

        // There should be two items in the open state
        List<ADM_Epic_Burndown_Item__c> epic_burn = [SELECT Id,Status__c FROM ADM_Epic_Burndown_Item__c WHERE Epic__c =:epic.Id];  
        System.assertEquals( 2 , epic_burn.size());
        System.assertEquals( 'Open' , epic_burn.get(0).Status__c);
        System.assertEquals( 'Open' , epic_burn.get(1).Status__c);

    }

    static testMethod void testEpicBurndownClosed() {

        ADM_Epic__c epic = ADM_Epic.createTestEpic();
   
        ADM_Work__c test_story =  ADM_Work.setupTestWork('User Story');
        test_story.Epic__c = epic.Id; 
        test_story.Status__c = 'Closed';
        upsert test_story;
        
        ADM_Work__c test_bug =  ADM_Work.setupTestWork('Bug');
        test_bug.Epic__c = epic.Id; 
        test_bug.Status__c = 'Closed';
        upsert test_bug;

        Test.startTest();       
        
        PPM_PortfolioScheduledJob job = new PPM_PortfolioScheduledJob();
            job.execute(null);

        Test.stopTest();

        List<ADM_Epic_Burndown_Item__c> epic_burn = [SELECT Id,Status__c FROM ADM_Epic_Burndown_Item__c WHERE Epic__c =:epic.Id];  
        System.assertEquals( 2 , epic_burn.size());
        System.assertEquals( 'Closed' , epic_burn.get(0).Status__c);
        System.assertEquals( 'Closed' , epic_burn.get(1).Status__c);

    }

    static testMethod void testEpicBurndownStoryPoint() {

        ADM_Epic__c epic = ADM_Epic.createTestEpic();

        ADM_Work__c test_story =  ADM_Work.setupTestWork('User Story');
        test_story.Epic__c = epic.Id; 
        test_story.Story_Points__c = 3;
        upsert test_story;
        
        Test.startTest();       
        
        PPM_PortfolioScheduledJob first_job = new PPM_PortfolioScheduledJob();
            first_job.execute(null);

        Test.stopTest();

        List<ADM_Epic_Burndown_Item__c> epic_burn = [SELECT Id,Metric__c FROM ADM_Epic_Burndown_Item__c WHERE Epic__c =:epic.Id];  
        System.assertEquals( 1 , epic_burn.size());
        System.assertEquals( 3 , epic_burn.get(0).Metric__c);

    }

}