mdapi-source/original-package/unpackaged/objects/ADM_Application__c.object
<CustomObject>
    <description>Application lists resources associated with the release and management of any system that is released (has Releases).</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Application_Approver__c.object
<CustomObject>
    <description>List of approvers for Releases or eReleases.</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Application that this Approver supports.</description>
        <label>Application</label>
        <referenceTo>ADM_Application__c</referenceTo>
        <relationshipLabel>Application Approvers</relationshipLabel>
        <relationshipName>Application_Approvers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Context__c</fullName>
        <description>Inform Only -- This Approver will receive notification when an approval request is made.
May Approve -- This Approver, or any other Approver with the same role, may approve the request.
Must Approve -- This Approver must approve all requests. If multiple Approvers have Must Approve context for a role, all of them will be required to approve the request.
Notify When Approved -- The Approver will be notified only when the request has been Approved.</description>
        <inlineHelpText>Inform Only -- will receive all notifications; 
May Approve -- may approve the request;
Must Approve -- must approve all requests; 
Notify When Approved -- will be notified only when the request has been Approved.
Primary -- Cloud
Secondary -- Cloud</inlineHelpText>
        <label>Approval Context</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Approver_Role__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Inform Only</fullName>
                </value>
                <value>
                    <fullName>May Approve</fullName>
                </value>
                <value>
                    <fullName>Must Approve</fullName>
                </value>
                <value>
                    <fullName>Notify When Approved</fullName>
                </value>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Secondary</fullName>
                </value>
                <value>
                    <fullName>Exception Primary</fullName>
                </value>
                <value>
                    <fullName>Exception Secondary</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approval_Type__c</fullName>
        <description>Type of approvals in which this Approver participates.</description>
        <inlineHelpText>Select the type of approvals in which this Approver participates.</inlineHelpText>
        <label>Approval Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>eRelease</fullName>
                </value>
                <value>
                    <fullName>Major</fullName>
                </value>
                <value>
                    <fullName>Patch</fullName>
                </value>
                <value>
                    <fullName>Releases</fullName>
                </value>
                <value>
                    <fullName>eReleases</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approver_Email__c</fullName>
        <description>Email of Approver (may be blank if email is same as User email).</description>
        <inlineHelpText>Email of Approver. If Approver is specified, may be blank or must match Approver&apos;s User email. If Approver is not specified, this field may be set to a distribution list.</inlineHelpText>
        <label>Approver Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Approver_Role__c</fullName>
        <description>The role that this Approver performs.</description>
        <inlineHelpText>Approval Role. Note: &quot;Distribution List&quot; indicated this Approver is for notifications only. &quot;Functional&quot; requires that a Team be entered in the Functional Role field.</inlineHelpText>
        <label>Approver Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Buildmaster</fullName>
                </value>
                <value>
                    <fullName>Cloud Leader</fullName>
                </value>
                <value>
                    <fullName>Development Engineer</fullName>
                </value>
                <value>
                    <fullName>Development Manager</fullName>
                </value>
                <value>
                    <fullName>Distribution List</fullName>
                </value>
                <value>
                    <fullName>Executive</fullName>
                </value>
                <value>
                    <fullName>Functional</fullName>
                </value>
                <value>
                    <fullName>Performance</fullName>
                </value>
                <value>
                    <fullName>Quality Engineer</fullName>
                </value>
                <value>
                    <fullName>QE Manager</fullName>
                </value>
                <value>
                    <fullName>Release Coverage</fullName>
                </value>
                <value>
                    <fullName>Release Engineer</fullName>
                </value>
                <value>
                    <fullName>Release Manager</fullName>
                </value>
                <value>
                    <fullName>TechOps Engineer</fullName>
                </value>
                <value>
                    <fullName>TechOps Manager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Users record of the Approver.</description>
        <inlineHelpText>Approver. Must be blank if Approver Email is a distribution list.</inlineHelpText>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Application_Approvers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Approver</label>
    <nameField>
        <displayFormat>AA-{00000}</displayFormat>
        <label>Application Approver Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Approvers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ADM_ApplicationApprover.cls
/**
 *    @userstory W-1224650: eRelease Request process takes up too many workflows
 *    @author snahm
 */

/*
 * This class will include utility methods for accessing the Application Approver
 * objects related to an Application.  
 */


public with sharing class ADM_ApplicationApprover {
	
	/*
 	 * These strings need to be kept consistent with the corresponding picklists
 	 */
 
	// ADM_Application__c.Approval_Type__c picklist
	public static final String TYPE_RELEASES = 'Releases';
	public static final String TYPE_ERELEASES = 'eReleases';
	public static final String TYPE_BOTH = 'Releases; eReleases';


	// ADM_Application__c.Approval_Role__c picklist
	public static final String ROLE_DEV = 'Development Manager';
	public static final String ROLE_QE = 'QE Manager';
	public static final String ROLE_RE = 'Release Engineer';
	public static final String ROLE_RM = 'Release Manager';
	public static final String ROLE_TECHOPS = 'TechOps Manager';

	// ADM_Application__c.Approval_Context__c picklist
	public static final String CONTEXT_INFORM = 'Inform Only';
	public static final String CONTEXT_MAY = 'May Approve';
	public static final String CONTEXT_MUST = 'Must Approve';
	public static final String CONTEXT_NOTIFY = 'Notify When Approved';

	/*
	 * Takes a List of Application Approvers and a Map of Users from that list and returns a List of Users that 
	 * match the type, role and context criteria. "null" for any of these three filters means "all".
	 *
	 * Multiple context values can be specified; the contextSet param is Set of strings that match the Context picklist values.
	 */	
	public static Set<User> approverUsers(List<ADM_Application_Approver__c> approvers, Map<Id, User> users, 
			String type, String role, Set<String> contextSet) {
		Set<String> aaTypeSet = new Set<String>();
		if (type != null && type.equals(TYPE_BOTH)) {
			type = null;
		}
		Set<Id> selected = new Set<Id>();
		for (ADM_Application_Approver__c aa : approvers) {
			aaTypeSet.addAll(aa.Approval_Type__c.deleteWhitespace().split(';'));
			if ((type == null || aaTypeSet.contains(type)) &&
				(contextSet == null || contextSet.contains(aa.Approval_Context__c)) &&
				(role == null || role.equals(aa.Approver_Role__c))) {
					selected.add(aa.Approver__c);
			}
			aaTypeSet.clear();
		}
		Set<User> returnUsers = new Set<User>();
		for (Id uId : selected) {
			User u = users.get(uId);
			if (u != null) {
				returnUsers.add(u);
			}
		}
		return returnUsers;
	}
	/*
	 * Similar to above, but returns Emails instead.
	 */	
	public static Set<String> approverEmails(List<ADM_Application_Approver__c> approvers, Map<Id, User> users, 
			String type, String role, Set<String> contextSet) {
		Set<String> aaTypeSet = new Set<String>();
		if (type != null && type.equals(TYPE_BOTH)) {
			type = null;
		}
		Set<String> selected = new Set<String>();
		List<Id> selectedUser = new List<Id>();
		for (ADM_Application_Approver__c aa : approvers) {

			aaTypeSet.addAll(aa.Approval_Type__c.deleteWhitespace().split(';'));
			if ((type == null || aaTypeSet.contains(type)) &&
				(contextSet == null || contextSet.contains(aa.Approval_Context__c)) &&
				(role == null || role.equals(aa.Approver_Role__c))) {
				if (aa.Approver__c != null) {		// If Approver_Email__c is a dlist, Approver__c will be null
					User u = users.get(aa.Approver__c);
					if (u != null) {
						selected.add(u.Email);		// If Approver User is not null, need to return the Approver's email
					}
				} else {											
					selected.add(aa.Approver_Email__c);
				}
			}
			aaTypeSet.clear();							
		}

		return selected;
	}	
	
	public static ADM_Application_Approver__c createTestApplicationApprover(ADM_Application__c appl, User appU, String apprEmail,
        String context, String type) {
        
        return createTestApplicationApprover(appl, appU, apprEmail, context, type, ROLE_RM);
    }
    
    public static ADM_Application_Approver__c createTestApplicationApprover(ADM_Application__c appl, User appU, String apprEmail,
        String context, String type, String role) {
        
        ADM_Application_Approver__c aa = new ADM_Application_Approver__c(Application__c=null, Approver__c=null, Approver_Email__c=apprEmail,
            Approval_Context__c=context, Approval_Type__c=type, Approver_Role__c=role);
        if (appl != null) {
       		aa.Application__c=appl.id;
        }
        if (appU != null) {
        	aa.Approver__c=appU.id;
        }
        Database.insert(aa);
        return aa;      
    }
    
    /*
     * Sets up three test users.  For tests.
     */
    public static List<User> createTestUsers() {
		List <User> testUsers = new List<User>();  	

        Profile p = null;
        try {
            p = [select id from profile where name='GUS Release Manager'];
        } catch (System.Exception e) {
            System.debug('ApplicationApprover_TriggerTest: did not find GUS Release Manager profile. Will use System Administrator profile.');
        }
        if (p == null)                    // GUS RM profile doesn't exist in this org
            p = [select id from profile where name='System Administrator'];

        User aaU1 = new User(alias = 'mdillon', email='mdillon@test.test', firstname='Matt', lastname='Dillon',
                    emailencodingkey='UTF-8', languagelocalekey='en_US', localesidkey='en_US', timezonesidkey='America/Los_Angeles',
                    profileid = p.Id, username='mdillon@test.test');
        Database.insert(aaU1);
        testUsers.add(aaU1);
        User aaU2 = new User(alias = 'cgoode', email='cgoode@test.test', firstname='Chester', lastname='Goode', 
                    emailencodingkey='UTF-8', languagelocalekey='en_US', localesidkey='en_US', timezonesidkey='America/Los_Angeles',
                    profileid = p.Id, username='cgoode@test.test');
        Database.insert(aaU2);
        testUsers.add(aaU2);
        
        User aaU3 = new User(alias = 'gadams', email='gadams@test.test', firstname='Doc', lastname='Adams',
                    emailencodingkey='UTF-8', languagelocalekey='en_US', localesidkey='en_US', timezonesidkey='America/Los_Angeles', 
                    profileid = p.Id, username='gadams@test.test');
        Database.insert(aaU3);
        testUsers.add(aaU3);
        return (testUsers);
    }
    
	/*
	 * Creates four test Application Approvers for the specified Application
	 */
	public static List <ADM_Application_Approver__c> createTestApplicationApprovers(ADM_Application__c app) {
	 	User[] testUser = createTestUsers();
	 	List <ADM_Application_Approver__c> aa = new List<ADM_Application_Approver__c>();
	 	aa.add(createTestApplicationApprover(app, 
	 		testUser[0], testUser[0].email, CONTEXT_MUST, TYPE_BOTH, ROLE_QE));
	 	aa.add(createTestApplicationApprover(app, 
	 		testUser[1], testUser[1].email, CONTEXT_MAY, TYPE_RELEASES, ROLE_DEV));
	 	aa.add(createTestApplicationApprover(app, 
	 		null, 'devnull@salesforce.com', CONTEXT_INFORM, TYPE_ERELEASES));
	 	aa.add(createTestApplicationApprover(app, 
	 		testUser[2], testUser[2].email, CONTEXT_MUST, TYPE_RELEASES));
	 	return(aa);
	}
	
}