mdapi-source/original-package/unpackaged/objects/ADM_Epic_Burndown_Item__c.object
<CustomObject>
    <fields>
        <fullName>Closed__c</fullName>
        <label>Closed</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Compound_Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <inlineHelpText>A compound key of Date-Work Id to guarantee each work record only has 1 entry per day</inlineHelpText>
        <label>Compound Key</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Epic__c</fullName>
        <label>Epic</label>
        <referenceTo>ADM_Epic__c</referenceTo>
        <relationshipLabel>Epic Burndown Items</relationshipLabel>
        <relationshipName>Epic_Burndown_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Metric__c</fullName>
        <label>Metric</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Epic Burndown Item</label>
    <nameField>
        <displayFormat>EBI-{0000000000}</displayFormat>
        <label>Epic Burndown Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Epic Burndown Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Closed__c</fullName>
        <formula>CASE(  Status__c, &quot;Tested&quot;, 1, &quot;Closed&quot;, 1, &quot;Closed-Untested&quot;, 1, &quot;Closed-U/Ftest&quot;, 1, &quot;Completed&quot;, 1, &quot;Not Reproducible&quot;, 1, &quot;Never&quot;, 1, &quot;Not a bug&quot;, 1, &quot;Duplicate&quot;, 1, &quot;Closed - Duplicate&quot; , 1, &quot;Closed - Known Bug Exists&quot;, 1, &quot;Closed - New Bug Logged&quot;, 1, &quot;Closed - No Fix - Working as Designed&quot;,1, &quot;Closed - No Fix - Feature Request&quot;,1, &quot;Closed - No Fix - Will Not Fix&quot;,1, &quot;Closed - LAP Request Approved&quot;, 1, &quot;Closed - LAP Request Denied&quot;, 1, &quot;Closed - Resolved Without Code Change&quot;, 1, &quot;Rejected&quot;, 1, &quot;Closed - Resolved With Internal Tools&quot;, 1, &quot;Closed - Defunct&quot;,1,&quot;Closed - Doc/Usability&quot;,1,&quot;Closed - Resolved with DB Script&quot;,1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Closed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Epic__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Epic</label>
        <referenceTo>ADM_Epic__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Triaged</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Investigating</fullName>
                </value>
                <value>
                    <fullName>Ready for Review</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>QA In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Defunct</fullName>
                </value>
                <value>
                    <fullName>Closed - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Closed - Eng Internal</fullName>
                </value>
                <value>
                    <fullName>Closed - Known Bug Exists</fullName>
                </value>
                <value>
                    <fullName>Closed - New Bug Logged</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Approved</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Denied</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved With Internal Tools</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved Without Code Change</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Working as Designed</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Feature Request</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Will Not Fix</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Pending Release</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>More Info Reqd from Support</fullName>
                </value>
                <value>
                    <fullName>Never</fullName>
                </value>
                <value>
                    <fullName>Not a bug</fullName>
                </value>
                <value>
                    <fullName>Not Reproducible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Story_Points__c</fullName>
        <inlineHelpText>If you leave it empty on save it will automatically assign the value from the TE activity selected.</inlineHelpText>
        <label>Story Points</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PPM_PortfolioBatch.cls
public class PPM_PortfolioBatch implements Database.Batchable<sObject>{
    
    private final String query;
   

   public PPM_PortfolioBatch(String q){
        query = q;
      
   }
    
    
    public Database.querylocator start(Database.BatchableContext bc){
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<sObject> scope){
        
        //grab all epics whose related work has been modified within the last 90 days, Call these "activeEpics"
       List<Id> activeEpicIds = new List<Id>();
        for(SObject so: scope) {
           ADM_Work__c activeWork = (ADM_Work__c)so;
           activeEpicIds.add(activeWork.Epic__c);    
       }
       System.debug('PPM_PortfolioScheduledJob() activeEpicIds size:' + activeEpicIds.size());
        
        
        //create portfolio burn down items
        List<ADM_Epic_Burndown_Item__c> items = new List<ADM_Epic_Burndown_Item__c>();
        System.debug('PPM_PortfolioBatch() scope size:' + scope.size()); 
        //get work related to active epics 
        //get work related to active epics 
        for(ADM_Work__c work: [select id, Epic__c, Story_Points__c, Status__c, Closed__c, LastModifiedDate from ADM_Work__c where Epic__c in:activeEpicIds]) {
        
            ADM_Epic_Burndown_Item__c item = new ADM_Epic_Burndown_Item__c();
            item.Closed__c = work.Closed__c;
            if(item.Closed__c == 0) {
                item.Status__c = 'Open';
            } else {
                item.Status__c = 'Closed';            
            }
            item.Metric__c = work.Story_Points__c;
            item.Epic__c = work.Epic__c;
            
            //for testing sometime useful to put a dummy date vs waiting for calendar day.  For prod we replace last Modified Date with System.today so that each time this runs its the current date
            /*DateTime dT = work.LastModifiedDate;
            Date myDate = date.newinstance(dT.year(), dT.month(), dT.day());
            item.Date__c = myDate;*/
            item.Date__c = System.today();
            item.Compound_Key__c = System.today().format() + '_' + work.id;
            items.add(item);
        }
        System.debug('PPM_PortfolioBatch() epic burndown items size:' + items.size()); 
        Database.insert(items, false);
    }
        
    

    public void finish(Database.BatchableContext BC) {
    
    }
    
}