mdapi-source/original-package/unpackaged/objects/ADM_Scrum_Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Scrum_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Allocation__c</fullName>
        <label>Allocation (%)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Member_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Scrum_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>Scrum_Team_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <displayFormat>STM-{00000}</displayFormat>
        <label>Team Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <recordTypes>
        <fullName>Internal</fullName>
        <active>true</active>
        <description>SFDC Employee</description>
        <label>Internal</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ADM_ProfileTeamAllocationControllerTest.cls
@isTest
private class ADM_ProfileTeamAllocationControllerTest {

	private static String message = 'No records to display';
/*
@userstory:  a07B0000000F9LW
@testcaseID:  a1DB00000000qsX
@expected results: User is taken to the Team Member allocation and all allocations for that team member are shown, using the following columns: Team Member record, role, team and allocation
hierarchy: GUS.ScrumTeamMembers.User View Allocation link
*/
    static testMethod void testWithValidUserId() {
    	ADM_Scrum_Team__c team = ADM_ScrumTeam.createTestScrumTeam();
    	ADM_Scrum_Team_Member__c t = new ADM_Scrum_Team_Member__c();
    	User u = ADM_WorkUser.createTestUser();
    	t.Allocation__c = 1;
    	t.Member_Name__c = u.Id;
    	t.RecordTypeId = [Select Id From RecordType Where Name = 'Internal'].Id;
    	t.Scrum_Team__c = team.Id;
    	insert t;
    	System.currentPageReference().getParameters().put('sfdc.userId',t.Member_Name__c);
    	ADM_ProfileTeamAllocationController controller = new ADM_ProfileTeamAllocationController();
        System.assertEquals('',controller.message);
        System.assertEquals(false, Apexpages.hasMessages());
        System.assertEquals(1, controller.allocations.size(), '' + controller.allocations);
        System.assertEquals(t.Member_Name__c, controller.teamMemberId);        
    } 
/*
@userstory:  a07B0000000F9LW
@testcaseID:  a1DB00000000qsM
@expected results: User is taken to the Team Member allocation and "no records to display" is shown
hierarchy: GUS.ScrumTeamMembers.User View Allocation link
*/
    static testMethod void testWithValidUserIdNoMemberships() {
    	User u = ADM_WorkUser.createTestUser();
    	System.currentPageReference().getParameters().put('sfdc.userId',u.Id);
    	ADM_ProfileTeamAllocationController controller = new ADM_ProfileTeamAllocationController();
        System.assertEquals(message,controller.message);
        System.assertEquals(false, Apexpages.hasMessages());
        System.assertEquals(0, controller.allocations.size(), '' + controller.allocations);
        System.assertEquals(u.Id, controller.teamMemberId);        
    }
	
}