mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Details_and_Steps_to_Reproduce__c</fullName>
        <inlineHelpText>Text contents of this field will be sent in initial record creation only</inlineHelpText>
        <label>Details and Steps to Reproduce</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Frequency reflects how often the target user will encounter the issue.</inlineHelpText>
        <label>Frequency</label>
        <referenceTo>ADM_Frequency__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Impact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Impact</label>
        <referenceTo>ADM_Impact__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority_Default__c</fullName>
        <description>Used to store what the previous priority value might have been for reporting purposes.</description>
        <label>Priority (default)</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <inlineHelpText>For bugs, priority is automatically determined based upon the combination of Impact and Frequency.

For user stories, P0 represents the highest priority, P4 the lowest.</inlineHelpText>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>P0</fullName>
                    <color>#0B6FCE</color>
                    <label>P0</label>
                </value>
                <value>
                    <fullName>P1</fullName>
                    <color>#FF0000</color>
                    <label>P1</label>
                </value>
                <value>
                    <fullName>P2</fullName>
                    <color>#E27001</color>
                    <label>P2</label>
                </value>
                <value>
                    <fullName>P3</fullName>
                    <color>#FFFF66</color>
                    <label>P3</label>
                </value>
                <value>
                    <fullName>P4</fullName>
                    <color>#78C953</color>
                    <label>P4</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Triaged</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Investigating</fullName>
                </value>
                <value>
                    <fullName>Ready for Review</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>QA In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Defunct</fullName>
                </value>
                <value>
                    <fullName>Closed - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Closed - Eng Internal</fullName>
                </value>
                <value>
                    <fullName>Closed - Known Bug Exists</fullName>
                </value>
                <value>
                    <fullName>Closed - New Bug Logged</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Approved</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Denied</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved With Internal Tools</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved Without Code Change</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Working as Designed</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Feature Request</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Will Not Fix</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Pending Release</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>More Info Reqd from Support</fullName>
                </value>
                <value>
                    <fullName>Never</fullName>
                </value>
                <value>
                    <fullName>Not a bug</fullName>
                </value>
                <value>
                    <fullName>Not Reproducible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bug</fullName>
                </value>
                <value>
                    <fullName>Gack</fullName>
                </value>
                <value>
                    <fullName>Help</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Test Change</fullName>
                </value>
                <value>
                    <fullName>Test Case</fullName>
                </value>
                <value>
                    <fullName>Test Failure</fullName>
                </value>
                <value>
                    <fullName>Test Tool</fullName>
                </value>
                <value>
                    <fullName>Skunkforce</fullName>
                </value>
                <value>
                    <fullName>Bug List</fullName>
                </value>
                <value>
                    <fullName>Translation</fullName>
                </value>
                <value>
                    <fullName>Non Deterministic Test</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <recordTypes>
        <fullName>Bug</fullName>
        <active>true</active>
        <description>Used to track defects or problems</description>
        <label>Bug</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ADM_BugExtension.cls
global with sharing class ADM_BugExtension extends ADM_WorkCommonExtension {
    private static final String OPTION_NONE_LABEL = '--None--';
    private transient List<SelectOption> impactOptions;
    private transient List<SelectOption> frequencyOptions;
    private transient List<SelectOption> priorityOptions; 

    public ADM_BugExtension(ApexPages.StandardController stdController) {
        super(stdController);
    }
    
    public String currentPriority { 
        get;
        set;
    }

    public String calculatedPriority {
        get {
            if(calculatedPriority == null) {
                if(getSelectedWork().Frequency__c != null && getSelectedWork().Impact__c != null) {
                    calculatedPriority = ADM_WorkRemoteActionsExtension.calculatePriority(getSelectedWork().Frequency__c, getSelectedWork().Impact__c);
                }
            }
            return calculatedPriority;
        }
        set;
    } 
    
    public List<SelectOption> getImpactOptions() {
        if(impactOptions == null) {
            impactOptions = ADM_BugUtils.getImpactsForBug();
        }
        return impactOptions;
    }
    
    public List<SelectOption> getFrequencyOptions() {
        if(null == frequencyOptions){
            frequencyOptions = ADM_BugUtils.getFrequencyOptions();
        }
        return frequencyOptions;
    }

    public List<SelectOption> getPriorityOptions() {
        if(priorityOptions == null) {
            Schema.DescribeFieldResult fieldResult = ADM_Work__c.Priority__c.getDescribe();
            List<Schema.PicklistEntry> pickListEntries = fieldResult.getPicklistValues();
            priorityOptions = new List<SelectOption>();

            for(Schema.Picklistentry pickListEntry : pickListEntries) {
                priorityOptions.add(new SelectOption(pickListEntry.getLabel(), pickListEntry.getValue()));
            }
        }
        return priorityOptions;
    }
    
    public PageReference doClone() {
        PageReference pr;
        boolean isSFXPagePreferred = ADM_ConstantsSingleton.getInstance().getUserLightningExperiencePreferred(); 
        if(isSFXPagePreferred){
            pr = Page.ADM_BugEditSds;           
        }
        else{
             pr = Page.ADM_BugEdit;
        }
        pr.setRedirect(true);
        pr.getParameters().put('id', getSelectedWork().Id);
        pr.getParameters().put('clone','1');
        pr.getParameters().put('retURL','/' + getSelectedWork().Id);
        return pr;
    }

     public Pagereference doSaveBugAndNew(){
        setPriorityDefault(getSelectedWork());
        return doSaveAndNew();
     }

    public Pagereference doSaveBugAndDetail(){
        setPriorityDefault(getSelectedWork());
        return doSaveAndDetail();
    }

     private void setPriorityDefault(ADM_Work__c work) {
        work.Priority_Default__c = ADM_WorkRemoteActionsExtension.calculatePriority(work.Frequency__c, work.Impact__c);
     }

    
    protected override RecordType getDefaultRecordType() {
        return ADM_RecordType.ensureByName('Bug', 'ADM_Work__c');
    }
    
    protected override void setDefaultValues(ADM_Work__c work) {
        super.setDefaultValues(work); 
        
        //set the default properties for a Bug
        getSelectedWork().Status__c = 'New';
        getSelectedWork().Type__c = 'Bug';
    }
    
    public Boolean getDetailsAndStepsToReproduceContainsHTML() {
        try {
            return ADM_TextUtils.containsHTML(getSelectedWork().Details_And_Steps_To_Reproduce__c);
        } catch (Exception e) {
            //if something goes wrong it's safer to assume it contains html and render the rich text editor then assume plain text and show raw html tags
            System.debug(LoggingLevel.ERROR, 'Exception checking for html:' + e);
            return true;    
        }   
    }
    
}