mdapi-source/original-package/unpackaged/objects/ADM_Scrum_Team__c.object
<CustomObject>
    <fields>
        <fullName>Status_Change_Notify__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Status Change Notify</label>
        <type>Checkbox</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Status_History__c.object
<CustomObject>
    <fields>
        <fullName>Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ADM_Status_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Scheduled_Build__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scheduled_Build</label>
        <referenceTo>ADM_Build__c</referenceTo>
        <relationshipLabel>ADM_Status_Histories</relationshipLabel>
        <relationshipName>ADM_Status_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work ID</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipLabel>ADM_Status_Histories</relationshipLabel>
        <relationshipName>ADM_Status_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ADM_Status_History</label>
    <nameField>
        <label>ADM_Status_History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ADM_Status_Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If you leave this field empty on save you will be the Assignee.</inlineHelpText>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assignee</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Perforce_Status__c</fullName>
        <label>Source Control Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open Once</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Scheduled_Build__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Scheduled Build field is a lookup to the Build object.  Enter a pre-existing build where the change will be made.</inlineHelpText>
        <label>Scheduled Build</label>
        <referenceTo>ADM_Build__c</referenceTo>
        <relationshipLabel>Work (Scheduled Build)</relationshipLabel>
        <relationshipName>Scheduled_Build</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scrum_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Work</relationshipLabel>
        <relationshipName>Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Triaged</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Investigating</fullName>
                </value>
                <value>
                    <fullName>Ready for Review</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>QA In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Closed - Defunct</fullName>
                </value>
                <value>
                    <fullName>Closed - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Closed - Eng Internal</fullName>
                </value>
                <value>
                    <fullName>Closed - Known Bug Exists</fullName>
                </value>
                <value>
                    <fullName>Closed - New Bug Logged</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Approved</fullName>
                </value>
                <value>
                    <fullName>Closed - LAP Request Denied</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved With Internal Tools</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved Without Code Change</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Working as Designed</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Feature Request</fullName>
                </value>
                <value>
                    <fullName>Closed - No Fix - Will Not Fix</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Integrate</fullName>
                </value>
                <value>
                    <fullName>Pending Release</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>More Info Reqd from Support</fullName>
                </value>
                <value>
                    <fullName>Never</fullName>
                </value>
                <value>
                    <fullName>Not a bug</fullName>
                </value>
                <value>
                    <fullName>Not Reproducible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/classes/ADM_AfterInsertOrUpdate.cls
public class ADM_AfterInsertOrUpdate {

    @future
    public static void updateStatusHistoryTableIfNeeded(Id[] workIds) { 

        List<ADM_Work__c> works = [SELECT Id, Perforce_Status__c, Scrum_Team__c, Scheduled_Build__c, Assignee__c FROM ADM_Work__c WHERE Id IN :workIds ];
        Long startTimer = System.currentTimeMillis();

        ADM_Scrum_Team__c scrumTeam = null;
        
        if ( works.size() < 1 ){
            System.debug('The work item wasnt available. Exiting in : ' +(System.currentTimeMillis()-startTimer ) + ' : milliseconds');
            return;
        }

        Id scrumTeamId = works.get(0).Scrum_Team__c;
 
        if ( scrumTeamId == null ){
            System.debug('The work item didn\'t have a corresponding scrum team exit in : ' +(System.currentTimeMillis()-startTimer ) + ' : milliseconds');
            return;
        }

        List<ADM_Scrum_Team__c> scrum_list = [SELECT Id, Status_Change_Notify__c,Name FROM ADM_Scrum_Team__c WHERE Id=:scrumTeamId];           
        if (  scrum_list.size() > 0 ){
            scrumTeam = scrum_list.get(0);
        } else {
            System.debug('No matching scrum team was found, so exiting in : ' +(System.currentTimeMillis()-startTimer ) + ' : milliseconds');
            return;
        }

        // List set for Status History
        List<ADM_Status_History__c> status_history_list = new List<ADM_Status_History__c>();
        for(Integer i = 0; i < works.size(); i++) {
            
                ADM_Work__c newWork = works[i];
                         
                if ( scrumTeam.Status_Change_Notify__c == true ){        
                    
                    ADM_Status_History__c status_history = new ADM_Status_History__c();
                    status_history.Processed__c = false;
                    status_history.Status__c = 'Source control status changed to :' + newWork.Perforce_Status__c;
                    status_history.Work_ID__c = newWork.Id;
                    status_history.Scheduled_Build__c = newWork.Scheduled_Build__c;
                    status_history.Assignee__c = newWork.Assignee__c;
                    status_history_list.add(status_history);
                    
                } // If status change
            
        } // End for loop

        // Saving entry outside of loop
        if ( status_history_list.size() > 0 ){
            insert status_history_list;
        }

        System.debug('ADM_Status_History_c total insertion time in milliseconds : ' +(System.currentTimeMillis()-startTimer ) + ' :' );
    }
}