mdapi-source/original-package/unpackaged/objects/ADM_Comment__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Comment</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Comment_Created_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Comment Created By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comment_Created_Date__c</fullName>
        <label>Comment Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Preserve_Formatting__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to decide if we are going to surround our comment body with a &quot;PRE&quot; tag</description>
        <label>Preserve Formatting</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Work__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work</label>
        <referenceTo>ADM_Work__c</referenceTo>
        <relationshipLabel>Comments</relationshipLabel>
        <relationshipName>Comment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Comment</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000}</displayFormat>
        <label>Story Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/ADM_Work__c.object
<CustomObject>
    <description>Multipurpose object that defines bugs, defects, incidents, user stories, test cases, etc.</description>
    <fields>
        <fullName>Comment_Copy__c</fullName>
        <label>Comment Copy</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Last_Modified_By_Copy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for email2gus in order to show who created a comment.</description>
        <label>Last Modified By Copy</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Work3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Preserve_Formatting_Copy__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Preserve Formatting Copy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Preserve_Formatting__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Preserve Formatting</label>
        <type>Checkbox</type>
    </fields>
    <label>Work</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Work ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/classes/ADM_CommentWrapper.cls
public class ADM_CommentWrapper {
    
    public ADM_CommentWrapper(ADM_Work__c work, List<ADM_WorkUtils.Change> changes, List<String> descriptions, User author) {
        this.work = work;
        this.changeList = new List<String>();
        this.body = renderCommentBody(changes, descriptions);
        this.author = author;
    }
    
    public ADM_CommentWrapper(ADM_Work__c newWork, List<String> newChangeList, User author) {
        this(newWork, newChangeList, '', author);
    }
    
    public ADM_CommentWrapper(ADM_Work__c newWork, List<String> newChangeList, String newBody, User author) {
        this.work = newWork;
        this.changeList = newChangeList;
        this.body = renderCommentBody(changeList, newBody);
        this.author = author; 
    }
    
    public ADM_Work__c work {get; set;}
    public List<String> changeList {get; set;}
    public String body {get; set;}
    public User author {get; set;}
    
    public ADM_Comment__c toComment() {
        if(ADM_TextUtils.isBlank(this.body)) {
            return null;
        }
        
        ADM_Comment__c comment = new ADM_Comment__c();
        comment.Body__c = body;
        comment.Work__c = work.Id;
        comment.Comment_Created_Date__c = System.now();
        comment.Preserve_Formatting__c = work.Preserve_Formatting_Copy__c;     
        
        //attempt to store the real comment author for comments submitted via email2apex
        if(author.username.toLowerCase().contains('email2') && work.Last_Modified_By_Copy__c != null) {
            System.debug('Using Last Mod as author of the comment');
            comment.Comment_Created_By__c = work.Last_Modified_By_Copy__c; 
        } else {
            System.debug('Using the current user as the author of the comment');
            comment.Comment_Created_By__c = author.id;
        }
        
        return comment;
    }
    
    private String renderCommentBody(List<ADM_WorkUtils.Change> changes, List<String> descriptions) {
        List<String> changeDescriptionParts = new List<String>();
        Boolean hasChanges = changes != null && changes.size() > 0;
        
        if(hasChanges) {
            for(ADM_WorkUtils.Change change : changes) {
                //skip the Comment_Copy__c change
                if(change.fieldName.equals('Comment_Copy__c')) {
                    continue;
                }
                
                //add a human readable message of the changes
                String fieldLabel = ADM_Work.getFieldLabel(change.fieldName);
                String message = null;
                if(change.isAdd()) {
                    message = fieldLabel + ', ' + change.newValue + ', has been added.';
                } else if(change.isRemove()) {
                    message = fieldLabel + ', ' + change.oldValue + ', has been deleted.';
                } else {
                    message = fieldLabel + ' changed from ' + change.oldValue + ' to ' + change.newValue;
                }
                changeDescriptionParts.add(message);
            }
        }
        
        //add the comment
        if(descriptions != null) {
            for(Integer index = 0; index < descriptions.size(); index++) {
                String description = descriptions.get(index);
                
                //add an empty line before each description
                if(index > 0 || (index == 0 && hasChanges)) {
                    changeDescriptionParts.add('');
                }
                
                changeDescriptionParts.add(description);
            }
        }
        
        return renderCommentBody(changeDescriptionParts, null);
    }
    
    private String renderCommentBody(List<String> changeList, String body) {
        String fullBody = '';
        
        //add the body text
        if(!ADM_TextUtils.isBlank(body)) {
            fullBody += body;
            
            if(!changeList.isEmpty()) {
                fullBody += '\n';
            }
        }
        
        //add the change list messages
        for(String messageBody : changeList) {
            fullBody += messageBody + '\n';
        }
        
        return fullBody;
    }
}