mdapi-source/original-package/unpackaged/objects/Headcount__c.object
<CustomObject>
    <description>Prototype for T&amp;P Headcount Management functionality to be integrated into GUS</description>
    <fields>
        <fullName>Headcount_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of employee filling the position (lookup to User)</inlineHelpText>
        <label>Employee Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Headcounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hiring_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Hiring Manager for headcount</description>
        <label>Hiring Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Headcount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Open - New = New position added by Finance
Open - Backfill = Existing position available for Backfill
Offer - In Progress = Offer extended to candidate
Offer - Accepted = Offer accepted by candidate
Filled = Position filled by an employee</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open - New</fullName>
                    <default>true</default>
                    <label>Open - New</label>
                </value>
                <value>
                    <fullName>Open - Backfill</fullName>
                </value>
                <value>
                    <fullName>Offer In Progress</fullName>
                </value>
                <value>
                    <fullName>Offer Accepted</fullName>
                </value>
                <value>
                    <fullName>Filled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Position</label>
    <nameField>
        <displayFormat>H-{00000}</displayFormat>
        <label>Position #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Roster</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ADM_HeadCountController.cls
public with sharing class ADM_HeadCountController {

    public ADM_HeadCountController() {
    
    }

    public ADM_HeadCountController(ApexPages.StandardController stdController) {
    
    }

    public List<HeadCount__c> getOpenHeadcountForCurrentUser() {
       try {
           return [select id, Name, Headcount_Name__c from Headcount__c where Hiring_Manager__c =:UserInfo.getUserId() and Status__c in ('Open - New', 'Open - Backfill')];
       } catch(Exception e) {
           System.debug('Error returning Headcount:' + e);
           return new List<Headcount__c>();
       }   
    }



}