mdapi-source/original-package/unpackaged/objects/Locking_Record__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ToBe</fullName>
                </value>
                <value>
                    <fullName>Locked</fullName>
                </value>
                <value>
                    <fullName>Unlock Override</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>ADM_Scrum_Team__c</referenceTo>
        <relationshipLabel>Locking Records</relationshipLabel>
        <relationshipName>Locking_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Locking Record</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Locking Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locking Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LockingRecords.cls
public with sharing class LockingRecords {
	private String teamId;
	public List<Locking_Record__c> locks = new List<Locking_Record__c>();
	
	public String message { 
		get {
			if(locks.isEmpty()) {
				message = '';
			} else {
				String createdByName = locks[0].CreatedBy.Name;
				//createdByName = ADM_TextUtils.getUTF8EncodedValue(createdByName);
				message = 'Team has been locked out of main branch by ' + createdByName + '. ';	
			}
			return message;
		} 
		set; 
	}
	
	public Locking_Record__c lockRecord{
		get{
			if(locks.isEmpty()){
				lockRecord = null;
			}
			else{
				lockRecord = locks[0];
			}
			return lockRecord;
		}
		set;
	}
	
	public LockingRecords(String team) {
		this.teamId = team;
	}
	
	public List<Locking_Record__c> getLocks() {		
		locks = [Select l.Id, l.Name, l.Description__c, l.CreatedBy.Name, l.CreatedById From Locking_Record__c l Where l.Status__c = 'Locked' and l.Team__c =: this.teamId order by Id desc];
		return locks; 
	}
}