mdapi-source/original-package/unpackaged/objects/Partner_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Quarterly_Plan__c</fullName>
        <label>Quarterly Plan</label>
        <referenceTo>Quarterly_Plan__c</referenceTo>
        <relationshipLabel>Partner Plans</relationshipLabel>
        <relationshipName>Partner_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Partner Plan</label>
    <nameField>
        <displayFormat>PP-{0000}</displayFormat>
        <label>Partner Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapi-source/original-package/unpackaged/objects/Quarterly_Plan__c.object
<CustomObject>
    <label>Quarterly Plan</label>
    <nameField>
        <label>Quarterly Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quarterly Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PartnerPlanViewRedirect.cls
public class PartnerPlanViewRedirect 
{
    
    Private final Partner_Plan__c pp;
    Private id pp_QP_ID;
    public PartnerPlanViewRedirect(ApexPages.StandardController stdController) 
    {
		this.pp = (Partner_Plan__c)stdController.getRecord();
        Partner_plan__c pp = [select quarterly_plan__c from Partner_Plan__c where id=:pp.id limit 1];
        pp_QP_ID = pp.Quarterly_Plan__c;
  	}
	
    public pagereference redirectToQuarterlyPlan()
    {
    	PageReference pg = new PageReference ('/'+pp_QP_ID);
        pg.setRedirect(true);
		return pg;

    }
}